![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Fworkflows%2Fcontent_moderation&file=content_moderation.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Fworkflows%2Fcontent_moderation%2Fcontent_moderation.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/content_moderation/content_moderation.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Content Moderation — BigQuery AI Functions

An end-to-end content moderation pipeline that composes five AI functions:

1. **Generate** sample social media posts with `AI.GENERATE_TABLE`
2. **Flag** posts needing review with `AI.IF`
3. **Classify** flagged posts by violation type with `AI.CLASSIFY`
4. **Score** severity of flagged posts with `AI.SCORE`
5. **Summarize** moderation results with `AI.GENERATE` (and alternatively with `AI.AGG`)

**What this demonstrates:**
- Using `AI.IF` as a binary filter step — efficiently gate expensive downstream processing
- Composing filter → classify → score → summarize in one pipeline
- Each function adds value: `AI.IF` reduces volume, `AI.CLASSIFY` categorizes, `AI.SCORE` prioritizes
- Comparing manual aggregation (`STRING_AGG` + `AI.GENERATE`) vs purpose-built `AI.AGG`

**Functions used:** [`AI.GENERATE_TABLE`](../../functions/ai_generate_table/) | [`AI.IF`](../../functions/ai_if/) | [`AI.CLASSIFY`](../../functions/ai_classify/) | [`AI.SCORE`](../../functions/ai_score/) | [`AI.GENERATE`](../../functions/ai_generate/) | [`AI.AGG`](../../functions/ai_agg/)

**Prerequisites:** [Setup guide](../../setup/) | [Function reference](../../RESOURCES.md)

---
## Setup

Set your project and location, authenticate, and create shared resources.

> This workflow uses `AI.GENERATE_TABLE` (requires a connection and remote model) and `AI.IF`, `AI.CLASSIFY`, `AI.SCORE`, `AI.GENERATE` (no model needed). See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

In [5]:
import subprocess as _sp, json as _json

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant Vertex AI User role
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
_sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
         f'--member=serviceAccount:{sa}', '--role=roles/aiplatform.user', '--quiet'],
        capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

In [6]:
# Create remote Gemini model for AI.GENERATE_TABLE (idempotent)
client.query(f'''
CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`
  REMOTE WITH CONNECTION `{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}`
  OPTIONS (endpoint = \'gemini-2.5-flash\')
''').result()
print('Model gemini_flash ready')

Model gemini_flash ready

---
## Step 1 — Generate sample posts with AI.GENERATE_TABLE

Generate 20 social media posts from seed topics — a realistic mix of clean content and problematic posts. Each seed row describes a post category and topic; `AI.GENERATE_TABLE` generates a username and post text for each one.

In [7]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_mod_posts` AS
SELECT post_id, username, post_text
FROM AI.GENERATE_TABLE(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT
    post_id,
    CONCAT(
      'Generate one realistic social media post. Category: ', category,
      '. Topic: ', topic,
      '. Write 1-2 sentences. Create a believable username.'
    ) AS prompt
   FROM UNNEST([
     STRUCT(1 AS post_id, 'clean' AS category, 'positive product review of electronics' AS topic),
     STRUCT(2, 'clean', 'travel experience in another country'),
     STRUCT(3, 'clean', 'cooking recipe tip'),
     STRUCT(4, 'clean', 'tech discussion about a new phone'),
     STRUCT(5, 'clean', 'fitness motivation'),
     STRUCT(6, 'clean', 'book recommendation'),
     STRUCT(7, 'clean', 'pet appreciation post'),
     STRUCT(8, 'clean', 'hobby sharing about painting'),
     STRUCT(9, 'clean', 'local restaurant review'),
     STRUCT(10, 'clean', 'gardening update'),
     STRUCT(11, 'clean', 'music discovery'),
     STRUCT(12, 'clean', 'weekend hiking recap'),
     STRUCT(13, 'problematic', 'spam with fake URLs and too-good-to-be-true offers'),
     STRUCT(14, 'problematic', 'mild harassment targeting appearance'),
     STRUCT(15, 'problematic', 'obvious health misinformation about vaccines'),
     STRUCT(16, 'problematic', 'engagement bait clickbait'),
     STRUCT(17, 'problematic', 'spam promoting a get-rich-quick scheme'),
     STRUCT(18, 'problematic', 'personal attack and insult'),
     STRUCT(19, 'problematic', 'conspiracy theory misinformation'),
     STRUCT(20, 'problematic', 'phishing attempt disguised as urgent account warning')
   ])),
  STRUCT('username STRING, post_text STRING' AS output_schema)
)
'''
client.query(query).result()

posts = client.query(f'''
  SELECT post_id, username, post_text
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_posts`
  ORDER BY post_id
''').to_dataframe()
print(f'Generated {len(posts)} posts')
posts.head(10)

Generated 20 posts

,post_id,username,post_text
0,1,GadgetGeek_88,"Just received my new smart watch and I'm already in love! The battery life is fantastic and the fitness tracking features are incredibly accurate, highly recommend it!"
1,2,GlobetrotterGigi,Absolutely loved my recent trip to Italy! Exploring ancient ruins and enjoying delicious pasta was an unforgettable experience.
2,3,SpiceSavvy,Quick tip for amazing flavor: always toast your spices before adding them to your dish! It really brings out their essential oils and deepens the aroma. #cookinghacks #spicetips
3,4,GadgetGuruDave,Just got my hands on the new Pixel 8 Pro and the camera is absolutely incredible! Definitely a game-changer for mobile photography.
4,5,LiftLaughLove,"Don't wait for motivation, create it! Every workout is a step closer to the best version of yourself."
5,6,BookwormBetty,"Just finished 'Project Hail Mary' by Andy Weir and it was absolutely incredible! If you love sci-fi with humor and heart, you NEED to read this one."
6,7,HappyPawrent88,My furry companion brings so much joy and laughter into my life every single day! So thankful for all the unconditional love and wet nose boops.
7,8,Artful_Brush,Spent a relaxing afternoon painting this landscape! It's so calming to just let the colors flow. What are your favorite art mediums?
8,9,LocalEatsLover,"Just had an incredible meal at ""The Daily Grind"" down the street! Their avocado toast and coffee were both perfect, plus the atmosphere was super cozy. Definitely my new favorite local spot for breakfast!"
9,10,GardenLifeGuru,My snapdragons are blooming beautifully this week! So happy with how vibrant the colors turned out.

---
## Step 2 — Flag posts with AI.IF

`AI.IF` evaluates a natural language condition and returns TRUE or FALSE. Use it as a binary filter to identify posts needing review — this gates the more expensive downstream classification and scoring steps.

In [8]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_mod_flagged` AS
SELECT
  post_id,
  username,
  post_text,
  AI.IF(
    CONCAT(
      'This social media post contains problematic content such as spam, ',
      'harassment, hate speech, or misinformation: ',
      post_text
    )
  ) AS needs_review
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_posts`
'''
client.query(query).result()

flagged = client.query(f'''
  SELECT needs_review, COUNT(*) AS count
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_flagged`
  GROUP BY needs_review
''').to_dataframe()
print('AI.IF flagging results:')
for _, row in flagged.iterrows():
    label = 'Flagged for review' if row['needs_review'] else 'Clean'
    print(f'  {label}: {row["count"]} posts')

AI.IF flagging results:
  Clean: 14 posts
  Flagged for review: 6 posts

---
## Step 3 — Classify flagged posts with AI.CLASSIFY

`AI.CLASSIFY` categorizes each flagged post into a violation type. Only flagged posts are classified — `AI.IF` already filtered out the clean ones, saving API calls.

In [9]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_mod_classified` AS
SELECT
  post_id,
  username,
  post_text,
  AI.CLASSIFY(
    post_text,
    ['harassment', 'spam', 'hate_speech', 'misinformation']
  ) AS violation_type
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_flagged`
WHERE needs_review = TRUE
'''
client.query(query).result()

classified = client.query(f'''
  SELECT violation_type, COUNT(*) AS count
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_classified`
  GROUP BY violation_type
  ORDER BY count DESC
''').to_dataframe()
print('Violation type distribution:')
for _, row in classified.iterrows():
    print(f'  {row["violation_type"]}: {row["count"]}')

Violation type distribution:
  spam: 3
  misinformation: 2
  harassment: 1

---
## Step 4 — Score severity with AI.SCORE

`AI.SCORE` rates each flagged post on a 0–1 severity scale. Higher scores indicate more severe violations that need immediate attention.

In [10]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_mod_scored` AS
SELECT
  c.post_id,
  c.username,
  c.post_text,
  c.violation_type,
  AI.SCORE(
    CONCAT(
      'Rate the severity of this content violation. ',
      'Score 0 for borderline/mild issues, 1 for severe violations ',
      'requiring immediate action: ',
      c.post_text
    )
  ) AS severity_score
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_classified` c
'''
client.query(query).result()

scored = client.query(f'''
  SELECT post_id, username, violation_type,
    ROUND(severity_score, 2) AS severity_score, post_text
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_scored`
  ORDER BY severity_score DESC
''').to_dataframe()
print('Flagged posts ranked by severity:')
scored

Flagged posts ranked by severity:

,post_id,username,violation_type,severity_score,post_text
0,15,AwakeAndAware77,misinformation,1.0,"Don't fall for it, these 'vaccines' are literally reprogramming your cells and altering your natural DNA! They're trying to change us from within."
1,13,Wealth_Pro_Tips,spam,1.0,"Hey everyone, don't miss out on this amazing opportunity! Get a FREE iPhone 15 Pro and $1000 cash instantly just by clicking here: bit.ly/FreePhoneCashNow"
2,17,WealthBuilderElite,spam,1.0,"Unlock financial freedom with our exclusive new platform! Zero risk, maximum profit. DM me 'INFO' to get started today!"
3,20,SecurityAlert_345,spam,1.0,URGENT: Your account has suspicious activity. Click here immediately to verify your details and prevent account suspension: [malicious_link_here]
4,18,RealityCheck22,harassment,0.0,"Honestly, your last comment was as dumb as your profile picture. Maybe stick to things you actually understand, which seems to be nothing."
5,19,TruthSeeker88,misinformation,0.0,"They want you to believe everything is fine, but open your eyes! The elites are clearly behind the new 'health' mandates to control us."

### Step 4b — Action items

Show the highest-severity posts that need immediate attention (severity > 0.7).

In [11]:
query = f'''
SELECT post_id, username, violation_type,
  ROUND(severity_score, 2) AS severity_score, post_text
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_scored`
WHERE severity_score > 0.7
ORDER BY severity_score DESC
'''
urgent = client.query(query).to_dataframe()
print(f'{len(urgent)} posts need immediate attention:')
urgent

4 posts need immediate attention:

,post_id,username,violation_type,severity_score,post_text
0,15,AwakeAndAware77,misinformation,1.0,"Don't fall for it, these 'vaccines' are literally reprogramming your cells and altering your natural DNA! They're trying to change us from within."
1,13,Wealth_Pro_Tips,spam,1.0,"Hey everyone, don't miss out on this amazing opportunity! Get a FREE iPhone 15 Pro and $1000 cash instantly just by clicking here: bit.ly/FreePhoneCashNow"
2,17,WealthBuilderElite,spam,1.0,"Unlock financial freedom with our exclusive new platform! Zero risk, maximum profit. DM me 'INFO' to get started today!"
3,20,SecurityAlert_345,spam,1.0,URGENT: Your account has suspicious activity. Click here immediately to verify your details and prevent account suspension: [malicious_link_here]

---
## Step 5 — Executive summary with AI.GENERATE

Aggregate all pipeline results and generate an executive summary of the moderation run.

In [12]:
query = f'''
WITH stats AS (
  SELECT
    (SELECT COUNT(*) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_posts`) AS total_posts,
    (SELECT COUNTIF(needs_review) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_flagged`) AS flagged_count,
    (SELECT COUNTIF(NOT needs_review) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_flagged`) AS clean_count,
    (SELECT STRING_AGG(CONCAT(violation_type, ': ', CAST(cnt AS STRING)), ', ')
     FROM (SELECT violation_type, COUNT(*) AS cnt
           FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_classified`
           GROUP BY violation_type)) AS violation_breakdown,
    (SELECT ROUND(AVG(severity_score), 2) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_scored`) AS avg_severity,
    (SELECT COUNTIF(severity_score > 0.7) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_scored`) AS urgent_count
)
SELECT (AI.GENERATE(
  CONCAT(
    'Write a brief executive summary (2-3 paragraphs) of this content moderation pipeline run. ',
    'Total posts: ', CAST(total_posts AS STRING),
    '. Flagged for review: ', CAST(flagged_count AS STRING),
    '. Clean: ', CAST(clean_count AS STRING),
    '. Violation breakdown: ', IFNULL(violation_breakdown, 'none'),
    '. Average severity: ', CAST(IFNULL(avg_severity, 0) AS STRING),
    '. Posts needing immediate action (severity > 0.7): ', CAST(IFNULL(urgent_count, 0) AS STRING),
    '. End with a one-sentence takeaway.'
  )
)).result AS executive_summary
FROM stats
'''
df = client.query(query).to_dataframe()
print(df.iloc[0]['executive_summary'])

This content moderation pipeline run processed a total of 20 posts, with the majority, 14 posts (70%), identified as clean and compliant. The remaining 6 posts (30%) were flagged for further review due to detected policy violations.

A breakdown of the flagged content shows spam as the most frequent issue, accounting for 3 violations. Additionally, 2 posts were flagged for misinformation, and 1 instance of harassment was identified. The overall average severity across all flagged posts was 0.67, with a critical finding that 4 posts registered a severity score greater than 0.7, indicating an urgent need for immediate human intervention.

In summary, while the majority of content was clean, critical high-severity violations among flagged posts demand immediate human attention.

### Alternative — Summarize by violation type with AI.AGG

`AI.AGG` can summarize flagged posts per violation type directly — no manual `STRING_AGG` or stats CTEs needed. It automatically batches the data and returns one summary per group.

In [13]:
query = f'''
SELECT
  violation_type,
  AI.AGG(
    TO_JSON_STRING(STRUCT(username, post_text, ROUND(severity_score, 2) AS severity)),
    'Summarize these flagged posts: what patterns do you see, how severe are the violations, and what moderation action would you recommend?'
  ) AS violation_summary
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_mod_scored`
GROUP BY violation_type
'''
df_agg = client.query(query).to_dataframe()
for _, row in df_agg.iterrows():
    print(f'=== {row["violation_type"]} ===')
    print(row['violation_summary'])
    print()

=== harassment ===
The flagged posts show a pattern of personal attacks. The severity of these violations is low. I recommend issuing a warning.

=== misinformation ===
The flagged posts show a clear pattern of conspiracy theories, with both posts suggesting hidden agendas by "elites" to control people. One post specifically targets health mandates, while the other focuses on anti-vaccine misinformation, claiming vaccines alter DNA.

Regarding severity, one post is moderately severe (severity 0), warranting a warning, as it broadly discusses control through mandates. The other is more severe (severity 1) due to its specific, false claims about vaccines reprogramming cells and altering DNA, which constitutes health misinformation.

For moderation, I recommend a warning for the post about elites and health mandates, and removal for the post spreading misinformation about vaccines altering DNA.

=== spam ===
These flagged posts consistently exhibit patterns of phishing and scam attempts. They lure users with unrealistic promises like free iPhones, cash, or guaranteed profits, or create false urgency through account suspension warnings. All these tactics aim to trick users into clicking malicious links or divulging personal information.

The severity of these violations is uniformly high (severity 1) due to their deceptive nature and the potential for significant financial harm and account compromise.

For moderation, I recommend immediate removal of all these posts, permanent bans for the users involved, and blacklisting of any associated links.

---
## Cleanup

Drop tables created by this workflow. Shared resources (dataset, connection, models) are left for other notebooks.

In [14]:
for table in ['workflow_mod_posts', 'workflow_mod_flagged', 'workflow_mod_classified', 'workflow_mod_scored']:
    client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.{table}', not_found_ok=True)
    print(f'Dropped {table}')

Dropped workflow_mod_posts
Dropped workflow_mod_flagged
Dropped workflow_mod_classified
Dropped workflow_mod_scored

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [14]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')