![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ml%2Ffunctions%2Fencoding&file=encoding.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ml/functions/encoding/encoding.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ml/functions/encoding/encoding.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ml%2Ffunctions%2Fencoding%2Fencoding.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ml/functions/encoding/encoding.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ml/functions/encoding/encoding.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/functions/encoding/encoding.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/functions/encoding/encoding.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/functions/encoding/encoding.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/functions/encoding/encoding.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ml/functions/encoding/encoding.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ml/functions/encoding/encoding.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Encoding — BigQuery ML Model-Free Functions

Three categorical-encoding functions, all **analytic** (require `OVER()`): `ML.ONE_HOT_ENCODER` (scalar `STRING` → sparse one-hot/dummy vector), `ML.LABEL_ENCODER` (scalar `STRING` → ordinal `INT64`), and `ML.MULTI_HOT_ENCODER` (`ARRAY<STRING>` → sparse multi-hot vector). All three share the same `top_k`/`frequency_threshold` vocabulary-capping mechanism.

**When to use these:**
- `ML.ONE_HOT_ENCODER` — nominal categoricals for linear/logistic models that don't auto-encode the way you want.
- `ML.LABEL_ENCODER` — a compact ordinal integer, appropriate for tree models or where order genuinely doesn't matter to the algorithm.
- `ML.MULTI_HOT_ENCODER` — genuine array/multi-value columns (tags, multi-select fields) — not a substitute for splitting a string yourself.

**Data:** [`bigquery-public-data.ml_datasets.penguins`](https://console.cloud.google.com/marketplace/product/bigquery-public-datasets) — same dataset as [`functions/scalers/`](../scalers/) and [`functions/feature_engineering/`](../feature_engineering/).

**Featured in:** [`models/boosted_tree_regressor/`](../../models/boosted_tree_regressor/) (`ML.LABEL_ENCODER` inline in a `TRANSFORM` clause).

**References:** [Full reference](../../RESOURCES.md) | [`ML.ONE_HOT_ENCODER` docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-one-hot-encoder) | [`ML.LABEL_ENCODER` docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-label-encoder) | [`ML.MULTI_HOT_ENCODER` docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-multi-hot-encoder) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a shared dataset. No connection needed.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ml'  # Shared dataset across all bq-ml notebooks

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'bigframes')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ml ready

---
## Step 1 — `ML.ONE_HOT_ENCODER`: default vs. dummy encoding (`drop`), and `top_k` capping

`drop='none'` (default) keeps every category; `drop='most_frequent'` drops the single most frequent category (dummy encoding — avoids the linear-model collinearity trap [documented for `DUMMY_ENCODING`](../../RESOURCES.md) elsewhere in this project).

In [5]:
query = """
SELECT DISTINCT x,
  ML.ONE_HOT_ENCODER(x) OVER() AS onehot_default,
  ML.ONE_HOT_ENCODER(x, 'most_frequent') OVER() AS onehot_dummy
FROM UNNEST(['a','a','a','a','a','a', 'b','b','b','b','b','b','b', 'c','c','c','c','c','c']) AS x
ORDER BY x
"""
client.query(query).to_dataframe()

   x                onehot_default                  onehot_dummy
0  a  [{'index': 1, 'value': 1.0}]  [{'index': 1, 'value': 1.0}]
1  b  [{'index': 2, 'value': 1.0}]  [{'index': 2, 'value': 0.0}]
2  c  [{'index': 3, 'value': 1.0}]  [{'index': 3, 'value': 1.0}]

Note `onehot_dummy`: `'b'` is the most frequent category (7 occurrences), so `drop='most_frequent'` keeps its slot in the sparse struct but zeroes it out (`value: 0.0`) — this is the "baseline" category every other category's coefficient gets compared against, avoiding the one-hot/intercept collinearity trap.

Now `top_k` — cap the vocabulary to only the N most frequent categories, regardless of `frequency_threshold`. With `'a'`(10x), `'b'`(8x), `'c'`(6x), `'d'`(6x) — all well above the default `frequency_threshold=5`, so that's not what's at play here — `top_k=2` keeps only the 2 most frequent:

In [6]:
query = """
WITH data AS (
  SELECT x FROM UNNEST([
    'a','a','a','a','a','a','a','a','a','a',
    'b','b','b','b','b','b','b','b',
    'c','c','c','c','c','c',
    'd','d','d','d','d','d'
  ]) AS x
)
SELECT DISTINCT x,
  ML.ONE_HOT_ENCODER(x) OVER() AS no_topk_cap,
  ML.ONE_HOT_ENCODER(x, 'none', 2) OVER() AS topk2
FROM data
ORDER BY x
"""
client.query(query).to_dataframe()

   x                   no_topk_cap                         topk2
0  a  [{'index': 1, 'value': 1.0}]  [{'index': 1, 'value': 1.0}]
1  b  [{'index': 2, 'value': 1.0}]  [{'index': 2, 'value': 1.0}]
2  c  [{'index': 3, 'value': 1.0}]  [{'index': 0, 'value': 1.0}]
3  d  [{'index': 4, 'value': 1.0}]  [{'index': 0, 'value': 1.0}]

**Verified:** `'c'` and `'d'` both collapse to bucket `0` under `top_k=2`, even though neither is anywhere close to the `frequency_threshold=5` cutoff (6 occurrences each) — `top_k` and `frequency_threshold` are two independent caps, and either one alone can push a category into the shared unknown bucket.

---
## Step 2 — MAJOR GOTCHA (verified live): the default `frequency_threshold=5` silently drops rare categories, in ALL THREE encoders

RESOURCES.md already flags a documentation discrepancy: older repo notebooks cite `top_k=1,000,000`/`frequency_threshold=0` (no threshold at all); current docs specify `top_k=32,000`/`frequency_threshold=5`. This isn't just a docs footnote — it changes real output.

With `'a'` appearing 6 times, `'b'` appearing 7 times, and `'c'` appearing only **3** times (below the default threshold of 5):

In [7]:
query = """
SELECT DISTINCT x,
  ML.ONE_HOT_ENCODER(x) OVER() AS onehot_current_default_freq5,
  ML.ONE_HOT_ENCODER(x, 'none', 32000, 0) OVER() AS onehot_legacy_style_freq0,
  ML.LABEL_ENCODER(x) OVER() AS label_current_default_freq5,
  ML.LABEL_ENCODER(x, 32000, 0) OVER() AS label_legacy_style_freq0
FROM UNNEST(['a','a','a','a','a','a', 'b','b','b','b','b','b','b', 'c','c','c']) AS x
ORDER BY x
"""
client.query(query).to_dataframe()

,x,onehot_current_default_freq5,onehot_legacy_style_freq0,label_current_default_freq5,label_legacy_style_freq0
0,a,"[{'index': 1, 'value': 1.0}]","[{'index': 1, 'value': 1.0}]",1,1
1,b,"[{'index': 2, 'value': 1.0}]","[{'index': 2, 'value': 1.0}]",2,2
2,c,"[{'index': 0, 'value': 1.0}]","[{'index': 3, 'value': 1.0}]",0,3

**Verified:** under the current default, `'c'` (only 3 occurrences) collapses into bucket `0` for **both** `ML.ONE_HOT_ENCODER` and `ML.LABEL_ENCODER` — indistinguishable from `NULL`/unseen-at-predict. With `frequency_threshold=0` (the legacy behavior), `'c'` keeps its own index in both. On any real dataset with a rare-but-meaningful category (fewer than 5 total occurrences), **the current default silently discards it** unless you explicitly pass `frequency_threshold=0` or lower. This is easy to miss since it produces no error or warning — the category just quietly stops being distinguishable.

`ML.MULTI_HOT_ENCODER` shares the identical mechanism — same trap, on `ARRAY<STRING>` documents instead of scalar values. 6 tiny "documents," each containing `'common'` (appears in all 6, ≥5) plus one other word that appears in only 1 document:

In [8]:
query = """
WITH docs AS (
  SELECT * FROM UNNEST([
    STRUCT(1 AS id, ['common', 'apple'] AS arr),
    STRUCT(2 AS id, ['common', 'banana'] AS arr),
    STRUCT(3 AS id, ['common', 'cherry'] AS arr),
    STRUCT(4 AS id, ['common', 'date'] AS arr),
    STRUCT(5 AS id, ['common', 'elderberry'] AS arr),
    STRUCT(6 AS id, ['common', 'fig'] AS arr)
  ])
)
SELECT id, arr,
  ML.MULTI_HOT_ENCODER(arr) OVER() AS multihot_default_freq5,
  ML.MULTI_HOT_ENCODER(arr, 32000, 0) OVER() AS multihot_legacy_style_freq0
FROM docs
ORDER BY id
"""
client.query(query).to_dataframe()

,id,arr,multihot_default_freq5,multihot_legacy_style_freq0
0,1,"[common, apple]","[{'index': 1, 'value': 1.0}, {'index': 0, 'value': 1.0}]","[{'index': 4, 'value': 1.0}, {'index': 1, 'value': 1.0}]"
1,2,"[common, banana]","[{'index': 1, 'value': 1.0}, {'index': 0, 'value': 1.0}]","[{'index': 4, 'value': 1.0}, {'index': 2, 'value': 1.0}]"
2,3,"[common, cherry]","[{'index': 1, 'value': 1.0}, {'index': 0, 'value': 1.0}]","[{'index': 4, 'value': 1.0}, {'index': 3, 'value': 1.0}]"
3,4,"[common, date]","[{'index': 1, 'value': 1.0}, {'index': 0, 'value': 1.0}]","[{'index': 4, 'value': 1.0}, {'index': 5, 'value': 1.0}]"
4,5,"[common, elderberry]","[{'index': 1, 'value': 1.0}, {'index': 0, 'value': 1.0}]","[{'index': 4, 'value': 1.0}, {'index': 6, 'value': 1.0}]"
5,6,"[common, fig]","[{'index': 1, 'value': 1.0}, {'index': 0, 'value': 1.0}]","[{'index': 4, 'value': 1.0}, {'index': 7, 'value': 1.0}]"

**Verified: bucket `0` is genuinely overloaded** — `NULL` and a below-threshold category land on the exact same index, so a downstream model can't tell them apart. Add a `NULL` document to the mix above:

In [9]:
query = """
SELECT DISTINCT x, ML.ONE_HOT_ENCODER(x) OVER() AS onehot
FROM UNNEST([CAST(NULL AS STRING), 'a','a','a','a','a','a', 'b','b','b','b','b','b','b', 'c','c','c']) AS x
ORDER BY x IS NULL DESC, x
"""
client.query(query).to_dataframe()

      x                        onehot
0  None  [{'index': 0, 'value': 1.0}]
1     a  [{'index': 1, 'value': 1.0}]
2     b  [{'index': 2, 'value': 1.0}]
3     c  [{'index': 0, 'value': 1.0}]

---
## Step 3 — `ML.LABEL_ENCODER` and `ML.MULTI_HOT_ENCODER` on real data

`island` has plenty of rows per category (`Biscoe`/`Dream`/`Torgersen`), so none get dropped by the default threshold — unlike Step 2's tiny synthetic categories.

In [10]:
query = """
SELECT DISTINCT island,
  ML.ONE_HOT_ENCODER(island) OVER() AS island_onehot,
  ML.LABEL_ENCODER(island) OVER() AS island_label
FROM `bigquery-public-data.ml_datasets.penguins`
ORDER BY island
"""
client.query(query).to_dataframe()

      island                 island_onehot  island_label
0     Biscoe  [{'index': 1, 'value': 1.0}]             1
1      Dream  [{'index': 2, 'value': 1.0}]             2
2  Torgersen  [{'index': 3, 'value': 1.0}]             3

`ML.MULTI_HOT_ENCODER` on an `ARRAY<STRING>` column — one output feature per **unique element across all rows**, not per row:

In [11]:
query = """
SELECT arr, ML.MULTI_HOT_ENCODER(arr, 100, 0) OVER() AS multi_hot
FROM UNNEST([
  STRUCT(['tag_a', 'tag_b'] AS arr),
  STRUCT(['tag_b', 'tag_c'] AS arr),
  STRUCT(['tag_a'] AS arr)
])
"""
client.query(query).to_dataframe()

              arr                                                 multi_hot
0         [tag_a]                              [{'index': 1, 'value': 1.0}]
1  [tag_a, tag_b]  [{'index': 1, 'value': 1.0}, {'index': 2, 'value': 1.0}]
2  [tag_b, tag_c]  [{'index': 2, 'value': 1.0}, {'index': 3, 'value': 1.0}]

---
## Step 4 — Embedded in a real `CREATE MODEL TRANSFORM`

Both encoders' vocabularies (and the `top_k`/`frequency_threshold`/`drop` choices) travel with the model and auto-apply at `ML.PREDICT` — no separate encoding step needed at inference time.

In [12]:
query = """
CREATE OR REPLACE MODEL `{project}.{dataset}.encoding_downstream_logistic_regression`
TRANSFORM(
  species,
  ML.ONE_HOT_ENCODER(island) OVER() AS island_encoded,
  ML.LABEL_ENCODER(sex) OVER() AS sex_encoded
)
OPTIONS(model_type = 'LOGISTIC_REG', input_label_cols = ['species']) AS
SELECT species, island, sex
FROM `bigquery-public-data.ml_datasets.penguins`
""".format(project=PROJECT_ID, dataset=DATASET_ID)
client.query(query).result()
print('Model encoding_downstream_logistic_regression created')

query = f"SELECT * FROM ML.EVALUATE(MODEL `{PROJECT_ID}.{DATASET_ID}.encoding_downstream_logistic_regression`)"
client.query(query).to_dataframe()

Model encoding_downstream_logistic_regression created

   precision    recall  accuracy  f1_score  log_loss   roc_auc
0   0.762161  0.780702  0.709302  0.689151  0.557748  0.790519

`island`+`sex` alone are only modestly predictive of `species` (~0.71 accuracy) — that's expected and not the point here; the point is both encoders' fitted vocabularies are reused automatically, with no separate `ML.TRANSFORM` call needed.

---
## Examples — `%%bigquery` Magics

The same operations using IPython magic commands — write SQL directly in cells without Python string wrapping.

In [13]:
%%bigquery --project {PROJECT_ID}

SELECT DISTINCT island,
  ML.ONE_HOT_ENCODER(island) OVER() AS island_onehot,
  ML.LABEL_ENCODER(island) OVER() AS island_label
FROM `bigquery-public-data.ml_datasets.penguins`
ORDER BY island

Query is running:   0%|          |

Downloading:   0%|          |

      island                 island_onehot  island_label
0     Biscoe  [{'index': 1, 'value': 1.0}]             1
1      Dream  [{'index': 2, 'value': 1.0}]             2
2  Torgersen  [{'index': 3, 'value': 1.0}]             3

---
## Examples — BigFrames

`bigframes.ml.preprocessing.OneHotEncoder` and `LabelEncoder` map to `ML.ONE_HOT_ENCODER`/`ML.LABEL_ENCODER`. There is **no** direct `MultiHotEncoder` class.

In [14]:
import bigframes.pandas as bpd
from bigframes.ml.preprocessing import OneHotEncoder

bpd.close_session()  # Reset session to apply project/location settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

df = bpd.read_gbq("SELECT island FROM `bigquery-public-data.ml_datasets.penguins`")
encoder = OneHotEncoder()
encoder.fit(df[['island']])
encoder.transform(df[['island']]).peek()

             onehotencoded_island
251  [{'index': 1, 'value': 1.0}]
264  [{'index': 1, 'value': 1.0}]
223  [{'index': 1, 'value': 1.0}]
226  [{'index': 1, 'value': 1.0}]
210  [{'index': 1, 'value': 1.0}]

---
## Cleanup

Drop the model created in Step 4. The shared dataset is left for other notebooks.

In [15]:
client.query(f"DROP MODEL IF EXISTS `{PROJECT_ID}.{DATASET_ID}.encoding_downstream_logistic_regression`").result()
print('Dropped encoding_downstream_logistic_regression')

Dropped encoding_downstream_logistic_regression

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and everything in it.

In [16]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')