![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_generate_text&file=ai_generate_text.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_generate_text%2Fai_generate_text.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_generate_text/ai_generate_text.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.GENERATE_TEXT — BigQuery AI Functions

`AI.GENERATE_TEXT` is a table-valued function that generates text using a remote model. It supports Gemini, Claude, Llama, Mistral, and open models — making it the most flexible generation function.

**When to use it:**
- You need to use non-Gemini models (Claude, Llama, Mistral)
- You want table-valued output with all input columns preserved
- You need Google Search grounding with `ground_with_google_search`
- You have an existing `CREATE MODEL` workflow

**Alternatives:**
- [`AI.GENERATE`](../ai_generate/) — Scalar function, no model required, Gemini only
- [`AI.GENERATE_TABLE`](../ai_generate_table/) — TVF with structured output via output_schema
- [`ML.GENERATE_TEXT`](../ml_generate_text/) — Legacy predecessor with ml_generate_text_ column prefixes

**Multimodal:** Supports document, image, and video input via [ObjectRef](../../reference/unstructured-data-infrastructure.md#objectref-and-objectrefruntime-schema-reference). Pass a STRUCT prompt with `ObjectRef` fields to analyze unstructured data from Cloud Storage.

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-generate-text) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function requires a connection and a remote model. The cells below create them if they don't exist. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection
BUCKET = PROJECT_ID  # GCS bucket (same name as project)

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes', 'google-cloud-storage')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

In [5]:
import subprocess as _sp, json as _json

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant Vertex AI User role
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
for role in ['roles/aiplatform.user', 'roles/storage.objectViewer']:
    _sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
             f'--member=serviceAccount:{sa}', f'--role={role}', '--quiet'],
            capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

In [6]:
# Create remote Gemini model (idempotent)
client.query(f'''
CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`
  REMOTE WITH CONNECTION `{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}`
  OPTIONS (endpoint = \'gemini-2.5-flash\')
''').result()
print('Model gemini_flash ready')

Model gemini_flash ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

### 1. Simplest call — single prompt

The input query must have a `prompt` column. AI.GENERATE_TEXT returns all input columns plus `result`, `status`, and metadata columns.

In [7]:
query = f'''
SELECT result
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT 'What is BigQuery?' AS prompt)
)
'''
df = client.query(query).to_dataframe()
print(df.iloc[0]['result'])

**BigQuery is a fully managed, serverless data warehouse provided by Google Cloud.**

Think of it as a massive, super-fast, and incredibly scalable database designed specifically for analyzing vast amounts of data. It's built for analytics, not for typical transactional operations (like updating a single customer record in an online store).

Here's a breakdown of what that means and why it's so powerful:

**Key Characteristics and Features:**

1.  **Fully Managed and Serverless:**
    *   **Fully Managed:** You don't have to worry about managing servers, storage, or infrastructure. Google handles all the provisioning, scaling, patching, and maintenance. You just load your data and start querying.
    *   **Serverless:** You don't provision or manage any servers. BigQuery automatically scales computing resources up or down based on your query workload. You only pay for the data you store and the queries you run, not for idle compute resources.

2.  **Petabyte-Scale Analytics:**
    *   BigQuery can store and query extremely large datasets, from gigabytes to petabytes and even exabytes. It's designed to handle massive data volumes with ease.

3.  **High Performance (Massively Parallel Processing - MPP):**
    *   It uses a columnar storage format and a massively parallel processing (MPP) architecture. This means it can distribute queries across thousands of machines simultaneously, allowing it to execute complex analytical queries on huge datasets in seconds or even milliseconds.

4.  **SQL Interface:**
    *   You interact with BigQuery using standard SQL. If you know SQL, you can start querying BigQuery immediately. It supports a rich set of SQL functions and operations.

5.  **Cost-Effective:**
    *   You pay for the amount of data stored and the amount of data processed by your queries. There's a generous free tier, making it accessible for smaller projects. Its serverless nature means you avoid the costs of over-provisioning infrastructure.

6.  **Real-time Analytics:**
    *   While traditionally used for batch analytics, BigQuery also supports streaming data ingestion, allowing for near real-time analysis of continuously arriving data.

7.  **Data Integration:**
    *   Integrates seamlessly with other Google Cloud services (e.g., Cloud Storage, Dataflow, Dataproc, Looker Studio, AI Platform). It also has connectors for many third-party tools and applications.

8.  **Machine Learning Integration (BigQuery ML):**
    *   You can create and execute machine learning models (like linear regression, logistic regression, k-means clustering, etc.) directly within BigQuery using SQL. This allows data analysts to build ML models without needing to learn complex programming languages or frameworks.

9.  **Data Sharing and Collaboration:**
    *   Easy to share datasets and query results with other users or even publicly, with fine-grained access control.

10. **Geospatial Analysis (BigQuery GIS):**
    *   Includes built-in support for geospatial data types and functions, allowing you to perform location-based analysis directly in BigQuery.

**Common Use Cases:**

*   **Business Intelligence (BI) and Reporting:** Building dashboards and reports for business insights.
*   **Data Warehousing:** Consolidating data from various sources for analytical purposes.
*   **Ad-hoc Analysis:** Quickly exploring large datasets to answer specific business questions.
*   **Marketing Analytics:** Analyzing customer behavior, campaign performance, and website traffic.
*   **Financial Analysis:** Processing large financial datasets for risk assessment or market trends.
*   **IoT Analytics:** Analyzing data from connected devices.
*   **Machine Learning Feature Engineering:** Preparing and transforming data for ML models.

**In essence, BigQuery is a powerful tool for anyone who needs to quickly and efficiently analyze massive datasets without the overhead of managing complex infrastructure.** It democratizes big data analytics, making it accessible to a wider range of users, from data scientists and engineers to business analysts.

### 2. Processing multiple rows

Each row in the input gets its own model call. The prompt column is built with CONCAT.

In [8]:
query = f'''
SELECT prompt, result
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT CONCAT('What country is ', city, ' in? Answer in one word.') AS prompt, city
   FROM UNNEST(['Tokyo', 'Paris', 'Nairobi']) AS city)
)
'''
client.query(query).to_dataframe()

                                            prompt  result
0    What country is Tokyo in? Answer in one word.   Japan
1    What country is Paris in? Answer in one word.  France
2  What country is Nairobi in? Answer in one word.   Kenya

### 3. Controlling generation parameters

Pass generation parameters as a STRUCT. Parameters are named arguments, not JSON.

In [9]:
query = f'''
SELECT result
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT 'Write a haiku about cloud computing.' AS prompt),
  STRUCT(0.8 AS temperature, 100 AS max_output_tokens)
)
'''
df = client.query(query).to_dataframe()
print(df.iloc[0]['result'])

Servers in the sky,
Data flows, a digital stream,
Flexible, unbound.

### 4. Google Search grounding

Enable Google Search grounding with `ground_with_google_search`. The model will search the web for current information.

In [10]:
query = f'''
SELECT result
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT 'What is the current population of Tokyo?' AS prompt),
  STRUCT(TRUE AS ground_with_google_search)
)
'''
df = client.query(query).to_dataframe()
print(df.iloc[0]['result'])

The population of Tokyo varies depending on whether you are referring to the city proper, the Tokyo Metropolis (prefecture), or the Greater Tokyo Area.

Here's a breakdown:
*   **Tokyo Metropolis (prefecture):** As of October 1, 2025, the estimated population of Tokyo Metropolis is 14.273 million. Other estimates for 2026 place it at approximately 14 million.
*   **Tokyo City (23 special wards):** The 23 special wards, which are often considered the city of Tokyo, had an estimated population of 9.948 million as of October 1, 2025. Another source states around 9.73 million for the 23 wards.
*   **Greater Tokyo Area:** This larger metropolitan area, which includes Tokyo and surrounding prefectures, is estimated to have over 36 million people, with some estimates as high as 37 million people as of February 2026. The UN estimates the Tokyo urban agglomeration at 33.4 million, ranking it third worldwide.

### 5. Safety settings

Control content safety filtering with `safety_settings`.

In [11]:
query = f'''
SELECT result
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT 'Explain the science of fireworks.' AS prompt),
  STRUCT(
    [STRUCT('HARM_CATEGORY_DANGEROUS_CONTENT' AS category, 'BLOCK_ONLY_HIGH' AS threshold)] AS safety_settings
  )
)
'''
df = client.query(query).to_dataframe()
print(df.iloc[0]['result'])

The dazzling spectacle of fireworks is a fantastic demonstration of chemistry, physics, and engineering working in harmony. It's all about controlled explosions, carefully timed reactions, and the manipulation of light and sound.

Here's a breakdown of the science behind fireworks:

## The Core Components:

Every firework, from a simple firecracker to a massive aerial shell, contains a few key ingredients:

1.  **Fuel:** This provides the energy for the explosion. Common fuels include charcoal (carbon) and sulfur.
2.  **Oxidizer:** This provides the oxygen needed for the fuel to burn rapidly, even in a confined space. Potassium nitrate ($\text{KNO}_3$) is the most common oxidizer, often found in gunpowder.
3.  **Binder:** A substance like dextrin (a type of sugar) is used to hold the fuel and oxidizer together in a solid form, ensuring a consistent burn.
4.  **Colorants (Metal Salts):** These are the stars of the show, responsible for the vibrant colors. Different metal ions emit light at specific wavelengths when heated (incandescence and atomic emission).
5.  **Stabilizer:** Chemicals like potassium perchlorate help to stabilize the mixture and improve its shelf life.
6.  **Chlorine Donor:** Often, a compound like polyvinyl chloride (PVC) is added. When heated, it releases chlorine gas, which enhances the vibrancy and intensity of certain colors by forming metal chlorides.
7.  **Propellant/Lift Charge:** For aerial fireworks, black powder (a mixture of charcoal, sulfur, and potassium nitrate) is used to launch the shell into the air.
8.  **Burst Charge:** This is another small charge of black powder inside the shell, designed to ignite the "stars" and explode the shell at its peak altitude.
9.  **Fuses:** These are lengths of slow-burning material that ignite various parts of the firework in a specific sequence.

## The Chemistry of Color:

The brilliant colors of fireworks are achieved through two primary mechanisms:

1.  **Incandescence:** This is light produced by heat. As the metal particles in the stars burn, they get incredibly hot and glow. The color of incandescent light depends on the temperature of the burning material:
    *   **Red/Orange:** Cooler temperatures.
    *   **Yellow/White:** Hotter temperatures.
    *   Think of a blacksmith's forge – the metal glows red, then orange, then yellow, and finally white as it gets hotter.

2.  **Atomic Emission (Spectroscopy):** This is the more precise and vibrant color source. When specific metal atoms are heated to high temperatures, their electrons jump to higher energy levels. As these electrons fall back down to their original, lower energy levels, they emit light of very specific wavelengths, which we perceive as distinct colors. Each element has a unique "fingerprint" of emitted wavelengths.

Here's a table of common colorants and the colors they produce:

| Metal Salt / Element     | Color      |
| :----------------------- | :--------- |
| **Strontium salts**      | Red        |
| **Calcium salts**        | Orange     |
| **Sodium salts**         | Yellow     |
| **Barium salts**         | Green      |
| **Copper salts**         | Blue       |
| **Magnesium/Aluminum**   | White/Silver |
| **Copper + Strontium**   | Purple     |

**Why are some colors harder to achieve?**
Blue is particularly challenging. Copper compounds need a very specific temperature to emit blue light, and they can easily decompose into other colors or become too hot and emit white light. Purple is also difficult as it requires a precise mixture of red (strontium) and blue (copper) emitters.

## The Physics of the Display:

1.  **Lift-off:** For aerial shells, a lift charge (usually black powder) is ignited at the base of the shell. The rapid combustion produces a large volume of hot gas, creating pressure that propels the shell skyward. The shell is typically placed in a mortar tube for directional guidance.

2.  **Timing is Everything:** A time-delay fuse is ignited simultaneously with the lift charge. This fuse burns slowly as the shell ascends.

3.  **The Burst:** When the shell reaches its peak altitude, the time-delay fuse ignites the burst charge inside the shell. This explosion ruptures the shell casing and ignites the "stars."

4.  **Stars:** These are carefully crafted pellets containing the fuel, oxidizer, colorant, and binder. They are packed in specific arrangements within the shell to create different patterns (e.g., peony, chrysanthemum, willow). When the burst charge ignites them, they burn outwards, producing light and color.

5.  **Sound:** The characteristic "bang" of a firework comes from the rapid expansion of gases during the burst charge's explosion. This creates a shockwave that travels through the air as sound. Whistles are created by forcing gas through small holes in a specific way.

## Types of Fireworks:

*   **Aerial Shells:** The most common large-scale fireworks, launched from mortars. They contain stars arranged to create various patterns.
*   **Roman Candles:** Tubes that eject a series of stars or other effects at intervals.
*   **Fountains:** Ground-based fireworks that produce a shower of sparks upwards.
*   **Sparklers:** Wires coated with pyrotechnic composition that burn slowly, producing bright sparks.
*   **Firecrackers:** Small explosive devices primarily designed for sound.

## Safety:

Because fireworks involve controlled explosions and high temperatures, safety is paramount. The chemicals are reactive, and improper handling can lead to severe burns, injuries, or uncontrolled fires. This is why professional pyrotechnicians undergo extensive training and follow strict safety protocols.

In essence, fireworks are a beautiful and fleeting art form born from a precise understanding of chemical reactions and physical principles, all orchestrated to create a breathtaking sensory experience.

### 6. Inspecting response metadata

`AI.GENERATE_TEXT` returns additional columns beyond `result`: `full_response` (full JSON), `status`, `safety_attributes`, and token usage. These are useful for debugging, cost tracking, and safety auditing.

In [12]:
query = f'''
SELECT *
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT 'What is 2 + 2? Answer in one word.' AS prompt)
)
'''
df = client.query(query).to_dataframe()
print('Columns returned:', list(df.columns))
print(f'Result: {df.iloc[0]["result"]}')
print(f'Status: {df.iloc[0]["status"]}')

Columns returned: ['result', 'rai_result', 'grounding_result', 'statistics', 'full_response', 'status', 'prompt']
Result: Four
Status:

### 7. Processing table data at scale

Use a CTE or subquery to select specific rows, then pass to AI.GENERATE_TEXT. Materialize first when using LIMIT to avoid extra charges.

In [13]:
query = f'''
WITH reviews AS (
  SELECT *
  FROM UNNEST([
    STRUCT('r1' AS id, 'Amazing product, fast delivery!' AS review),
    STRUCT('r2', 'Terrible quality. Broke after one day.'),
    STRUCT('r3', 'Average product, nothing special.'),
    STRUCT('r4', 'Great value for the price!')
  ])
)
SELECT id, review, result AS sentiment
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT id, review,
   CONCAT('Classify this review as positive, negative, or neutral. Return only the label: ', review) AS prompt
   FROM reviews)
)
'''
client.query(query).to_dataframe()

   id                                  review sentiment
0  r3       Average product, nothing special.   Neutral
1  r2  Terrible quality. Broke after one day.  Negative
2  r1         Amazing product, fast delivery!  Positive
3  r4              Great value for the price!  Positive

---
## Examples — Multimodal with ObjectRef

`AI.GENERATE_TEXT` can analyze documents, images, and video stored in Cloud Storage. Build the reference with `OBJ.MAKE_REF` and pass it in a STRUCT prompt:

```
OBJ.MAKE_REF(uri, connection)   → ObjectRef — pass this straight to the function
```

The STRUCT replaces the STRING prompt. `OBJ.FETCH_METADATA` (content type and size) and `OBJ.GET_ACCESS_URL` (a signed `ObjectRefRuntime` URL) still have their uses — displaying an object, delegated access, an explicit TTL — but the AI functions take the `ObjectRef` itself. See the [ObjectRef reference](../../reference/unstructured-data-infrastructure.md#objectref-and-objectrefruntime-schema-reference) for details.

In [14]:
from google.cloud import storage as _storage
from pathlib import Path

# Upload invoice for the multimodal example
_gcs = _storage.Client(project=PROJECT_ID)
_bucket = _gcs.bucket(BUCKET)
_prefix = 'bq_ai_functions/ai_generate_text'

_data = Path('../../data/documents')
if not _data.exists():
    _data = Path('data/documents')

blob = _bucket.blob(f'{_prefix}/invoice_001.pdf')
if not blob.exists():
    blob.upload_from_filename(str(_data / 'invoices' / 'invoice_001.pdf'))
    print(f'Uploaded invoice_001.pdf → gs://{BUCKET}/{_prefix}/invoice_001.pdf')
else:
    print(f'Already exists: gs://{BUCKET}/{_prefix}/invoice_001.pdf')

Uploaded invoice_001.pdf → gs://statmike-mlops-349915/bq_ai_functions/ai_generate_text/invoice_001.pdf

### 8. Summarize a document

Pass a document via ObjectRef using a STRUCT prompt to analyze content from Cloud Storage.

In [15]:
query = f"""
SELECT result
FROM AI.GENERATE_TEXT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT STRUCT(
    'Summarize this document in 2-3 sentences.' AS prompt,
    [OBJ.MAKE_REF(
      'gs://{BUCKET}/bq_ai_functions/ai_generate_text/invoice_001.pdf',
      '{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}'
    )] AS object_refs
  ) AS prompt)
)
"""
df = client.query(query).to_dataframe()
print(df.iloc[0]['result'])

This invoice from Nexus Innovations Group to Global Reach Marketing LLC details services including website redesign, strategic consulting, and social media management. The total amount due for these services is $10,067.25, with a payment due date of August 14, 2024.

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### Basic call with `%%bigquery`

**Note:** `%%bigquery` magics cannot interpolate Python variables in the SQL body. Use `--project` on the magic line for project, but model/table references must be hardcoded or use `client.query()` instead.

Since AI.GENERATE_TEXT requires a `MODEL` reference with project/dataset, most examples are better run via `client.query()` with f-strings. Here we show one example with hardcoded references.

In [16]:
%%bigquery --project {PROJECT_ID}

SELECT result
FROM AI.GENERATE_TEXT(
  MODEL `statmike-mlops-349915.bq_ai_functions.gemini_flash`,
  (SELECT 'Write a haiku about SQL.' AS prompt),
  STRUCT(0.8 AS temperature)
)

Query is running:   0%|          |

Downloading:   0%|          |

                                                                         result
0  Data in a table,\nQueries fetch what you desire,\nKnowledge comes with ease.

### Capture results to a DataFrame

In [17]:
%%bigquery df_text --project {PROJECT_ID}

SELECT city, result AS country
FROM AI.GENERATE_TEXT(
  MODEL `statmike-mlops-349915.bq_ai_functions.gemini_flash`,
  (SELECT CONCAT('What country is ', city, ' in? One word.') AS prompt, city
   FROM UNNEST(['Tokyo', 'Paris', 'Nairobi']) AS city)
)

Query is running:   0%|          |

Downloading:   0%|          |

In [18]:
df_text

      city country
0    Paris  France
1    Tokyo   Japan
2  Nairobi   Kenya

---
## Examples — BigFrames

BigFrames wraps `AI.GENERATE_TEXT` via `bbq.ai.generate_text()`. It takes a model name string and a DataFrame.

**Key difference from SQL:** The function takes a model name and a DataFrame/Series with a `prompt` column.

In [19]:
import bigframes.pandas as bpd
import bigframes.bigquery as bbq

bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

### Basic generation

In [20]:
# Create input DataFrame with a 'prompt' column
df = bpd.DataFrame({
    'city': ['Tokyo', 'Paris', 'Nairobi'],
    'prompt': [
        'What country is Tokyo in? Answer in one word.',
        'What country is Paris in? Answer in one word.',
        'What country is Nairobi in? Answer in one word.',
    ]
})

# Use the model reference as a string
model_name = f'{PROJECT_ID}.{DATASET_ID}.gemini_flash'
result = bbq.ai.generate_text(model_name, df)

result[['city', 'result']].to_pandas()

      city  result
0    Tokyo   Japan
1  Nairobi   Kenya
2    Paris  France

---
## Cleanup

Remove GCS files uploaded for the multimodal examples. Shared resources (dataset, models, connection) are left for other notebooks.

In [21]:
# Delete GCS files uploaded for multimodal examples
from google.cloud import storage

gcs_client = storage.Client(project=PROJECT_ID)
bucket = gcs_client.bucket(BUCKET)
prefix = 'bq_ai_functions/ai_generate_text/'

blobs = list(bucket.list_blobs(prefix=prefix))
for blob in blobs:
    blob.delete()
    print(f'Deleted gs://{BUCKET}/{blob.name}')
if not blobs:
    print('No GCS files to clean up')

Deleted gs://statmike-mlops-349915/bq_ai_functions/ai_generate_text/invoice_001.pdf

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [22]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')