![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ml%2Fmodels%2Ftransform_only&file=transform_only.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ml/models/transform_only/transform_only.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ml/models/transform_only/transform_only.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ml%2Fmodels%2Ftransform_only%2Ftransform_only.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ml/models/transform_only/transform_only.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ml/models/transform_only/transform_only.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/models/transform_only/transform_only.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/models/transform_only/transform_only.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/models/transform_only/transform_only.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ml/models/transform_only/transform_only.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ml/models/transform_only/transform_only.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ml/models/transform_only/transform_only.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Transform-Only Models — BigQuery ML

Train a model that contains **only a `TRANSFORM` clause and no learning algorithm** with `CREATE MODEL` (model_type = `TRANSFORM_ONLY`) — a reusable, exportable preprocessing pipeline, decoupled from any estimator. There's no label, no training/evaluation of a predictor: the "output" of this model is the preprocessed data itself, produced by `ML.TRANSFORM`.

**Lifecycle:** `CREATE MODEL` (with `TRANSFORM`, no estimator) → `ML.TRANSFORM` → `ML.FEATURE_INFO` → `EXPORT MODEL` → feed the pipeline's output into a downstream `CREATE MODEL`

**Why this is its own model category:** every other model type in this project embeds an *optional* `TRANSFORM` clause directly on a predictive model (see [PCA](../pca/) Step 10, or [K-Means](../kmeans/)) — that embedded transform auto-applies at `ML.PREDICT`/`ML.EVALUATE` time, but it isn't reusable outside that one model. A `TRANSFORM_ONLY` model flips that: the pipeline is a first-class, reusable object with no estimator attached, at the cost of having to explicitly re-apply it (`ML.TRANSFORM`) before feeding new data into whatever downstream model consumes it.

**When to use a transform-only model:**
- Decouple feature engineering from model training so the same preprocessing (with its frozen train-time statistics — means, stddevs, vocabularies) can be reused across many downstream models.
- Build modular, feature-store-style transforms and chain them with CTEs or a view.
- Guarantee training/serving consistency without embedding the same `TRANSFORM` clause repeatedly across model definitions.

**A gotcha this notebook demonstrates directly, not just describes:** a downstream model trained on a `TRANSFORM_ONLY` pipeline's output has **no embedded `TRANSFORM` of its own**. If you call `ML.PREDICT` on that downstream model with *raw*, untransformed data, BigQuery ML does **not** error — it silently predicts using values on the wrong scale, giving confidently wrong answers. You must re-wrap new data in `ML.TRANSFORM` (using the same pipeline model) before every `ML.PREDICT`/`ML.EVALUATE` call.

**Data:** [`bigquery-public-data.ml_datasets.penguins`](https://console.cloud.google.com/marketplace/product/bigquery-public-datasets) — same dataset as [K-Means](../kmeans/), [PCA](../pca/), and [Autoencoder](../autoencoder/). The pipeline imputes missing `body_mass_g`, standard-scales two measurements, robust-scales a third, and one-hot encodes `sex`; a downstream `LOGISTIC_REG` model then predicts `species` from the pipeline's output.

**Bridges into:** Phase 6 (model-free `ML.*` functions) documents each preprocessing function (`ML.IMPUTER`, the scalers, the encoders) individually and in standalone SQL — this notebook shows several of them **composed into one reusable pipeline object**, which is the more realistic way they get used in practice.

**References:** [Full reference](../../RESOURCES.md) | [CREATE MODEL (transform-only) docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-create-transform) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a shared dataset for the model.

> A transform-only model trains on data already in BigQuery — no connection or remote model required. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ml'  # Shared dataset across all bq-ml notebooks
BUCKET = 'statmike-mlops-349915'  # <-- Replace with your GCS bucket (same location as DATASET_ID) -- used in Step 4 to export the pipeline

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'google-cloud-storage', 'db-dtypes', 'bigquery-magics', 'bigframes')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ml ready

---
## Step 1 — Create the pipeline with `CREATE MODEL`

`model_type = 'TRANSFORM_ONLY'` is the only option that applies here — no `input_label_cols`, no learning options (any would error, since there's no estimator to configure). Every transformed column needs an explicit alias; `species` and `island` pass through untransformed.

- `ML.IMPUTER(body_mass_g, 'mean')` fills the 2 rows with a missing `body_mass_g`.
- `ML.STANDARD_SCALER` z-scores `culmen_length_mm`/`culmen_depth_mm`.
- `ML.ROBUST_SCALER` scales `flipper_length_mm` by median/IQR instead (outlier-robust).
- `ML.ONE_HOT_ENCODER(sex)` turns the 3-category (`MALE`/`FEMALE`/`NULL`) string into a sparse vector.

All four are **analytic** functions and require the empty `OVER()` — `ML.IMPUTER` additionally requires a `strategy` argument (`'mean'`/`'median'`/`'most_frequent'`), unlike the scalers, which take only the column.

In [5]:
query = f"""
CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_penguins`
TRANSFORM(
  species,
  island,
  ML.IMPUTER(body_mass_g, 'mean') OVER() AS body_mass_g,
  ML.STANDARD_SCALER(culmen_length_mm) OVER() AS culmen_length_mm,
  ML.STANDARD_SCALER(culmen_depth_mm) OVER() AS culmen_depth_mm,
  ML.ROBUST_SCALER(flipper_length_mm) OVER() AS flipper_length_mm,
  ML.ONE_HOT_ENCODER(sex) OVER() AS sex_encoded
)
OPTIONS(
  model_type = 'TRANSFORM_ONLY'
) AS
SELECT species, island, sex, body_mass_g, culmen_length_mm, culmen_depth_mm, flipper_length_mm
FROM `bigquery-public-data.ml_datasets.penguins`
"""
client.query(query).result()
print('Model transform_only_penguins created')

Model transform_only_penguins created

---
## Step 2 — Apply the pipeline with `ML.TRANSFORM`

Returns the columns the `TRANSFORM` clause produces for the inputs it consumes.

> **GOTCHA (verified):** any input column whose name isn't reused as an output alias in the `TRANSFORM` clause passes straight through **untouched**, appended after the transform outputs — here that's raw `sex`, which the pipeline consumes (`ML.ONE_HOT_ENCODER(sex) OVER() AS sex_encoded`) but never re-emits under its own name, so it comes through a second time as-is right alongside `sex_encoded`. Useful for carrying an id/label column through without re-listing it in the pipeline, but easy to mistake for the pipeline itself re-emitting a raw column — it's really just unused-by-name input passed through.

In [6]:
query = f"""
SELECT *
FROM ML.TRANSFORM(
  MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_penguins`,
  (SELECT species, island, sex, body_mass_g, culmen_length_mm, culmen_depth_mm, flipper_length_mm
   FROM `bigquery-public-data.ml_datasets.penguins`
   LIMIT 5)
)
"""
client.query(query).to_dataframe()

,species,island,body_mass_g,culmen_length_mm,culmen_depth_mm,flipper_length_mm,sex_encoded,sex
0,Adelie Penguin (Pygoscelis adeliae),Dream,3475.0,-1.343074,0.633298,-0.565217,"[{'index': 1, 'value': 1.0}]",FEMALE
1,Adelie Penguin (Pygoscelis adeliae),Dream,4650.0,-0.756090,0.988285,-0.565217,"[{'index': 2, 'value': 1.0}]",MALE
2,Adelie Penguin (Pygoscelis adeliae),Dream,3900.0,-0.554314,0.886860,-0.565217,"[{'index': 2, 'value': 1.0}]",MALE
3,Chinstrap penguin (Pygoscelis antarctica),Dream,3500.0,0.472907,0.379735,-0.217391,"[{'index': 1, 'value': 1.0}]",FEMALE
4,Adelie Penguin (Pygoscelis adeliae),Dream,3000.0,-1.214671,-0.178102,-0.217391,"[{'index': 1, 'value': 1.0}]",FEMALE

---
## Step 3 — Introspect the raw inputs with `ML.FEATURE_INFO`

Reports statistics on the **raw** input columns (not the transformed outputs) — e.g. `sex` shows `null_count=10`, confirming why `ML.ONE_HOT_ENCODER` needs to handle nulls, and `body_mass_g` shows `null_count=2`, confirming why `ML.IMPUTER` is in the pipeline at all.

In [7]:
query = f"""
SELECT *
FROM ML.FEATURE_INFO(MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_penguins`)
"""
client.query(query).to_dataframe()

,input,min,max,mean,median,stddev,category_count,null_count,dimension
0,culmen_length_mm,32.1,59.6,43.921930,44.1,5.459584,<NA>,2,<NA>
1,body_mass_g,2700.0,6300.0,4201.754386,4050.0,801.954536,<NA>,2,<NA>
2,sex,NaN,NaN,NaN,NaN,NaN,3,10,<NA>
3,island,NaN,NaN,NaN,NaN,NaN,3,0,<NA>
4,species,NaN,NaN,NaN,NaN,NaN,3,0,<NA>
5,culmen_depth_mm,13.1,21.5,17.151170,17.3,1.974793,<NA>,2,<NA>
6,flipper_length_mm,172.0,231.0,200.915205,197.0,14.061714,<NA>,2,<NA>

---
## Step 4 — Export the pipeline with `EXPORT MODEL`

A transform-only export contains no predictive weights — there's no estimator — just the preprocessing graph and the frozen statistics (means, stddevs, one-hot vocabulary) computed at creation time. It exports as a `transform/saved_model.pb` (plus `assets`/`variables`), a distinct layout from a trained estimator's export.

In [8]:
query = f"""
EXPORT MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_penguins`
OPTIONS (URI = 'gs://{BUCKET}/bq_ml/transform_only/model')
"""
client.query(query).result()
print('Model exported')

from google.cloud import storage
storage_client = storage.Client(project=PROJECT_ID)
bucket = storage_client.bucket(BUCKET)
for blob in bucket.list_blobs(prefix='bq_ml/transform_only/model'):
    print(blob.name)

Model exported
bq_ml/transform_only/model/
bq_ml/transform_only/model/transform/
bq_ml/transform_only/model/transform/assets/
bq_ml/transform_only/model/transform/assets/dict.txt
bq_ml/transform_only/model/transform/fingerprint.pb
bq_ml/transform_only/model/transform/saved_model.pb
bq_ml/transform_only/model/transform/variables/
bq_ml/transform_only/model/transform/variables/variables.data-00000-of-00001
bq_ml/transform_only/model/transform/variables/variables.index

---
## Step 5 — Feed the pipeline's output into a downstream `CREATE MODEL`

The downstream model has **no embedded `TRANSFORM` of its own** — it trains directly on the already-transformed columns coming out of `ML.TRANSFORM`. This is the feature-store-style pattern: one shared pipeline, reused across as many downstream models as you like, each choosing which transformed columns to consume.

In [9]:
query = f"""
CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_downstream`
OPTIONS(
  model_type = 'LOGISTIC_REG',
  input_label_cols = ['species']
) AS
SELECT species, island, body_mass_g, culmen_length_mm, culmen_depth_mm, flipper_length_mm
FROM ML.TRANSFORM(
  MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_penguins`,
  (SELECT species, island, sex, body_mass_g, culmen_length_mm, culmen_depth_mm, flipper_length_mm
   FROM `bigquery-public-data.ml_datasets.penguins`
   WHERE body_mass_g IS NOT NULL)
)
"""
client.query(query).result()
print('Model transform_only_downstream created')

Model transform_only_downstream created

---
## Step 6 — Evaluate the downstream model with `ML.EVALUATE`

In [10]:
query = f"""
SELECT *
FROM ML.EVALUATE(MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_downstream`)
"""
client.query(query).to_dataframe()

   precision    recall  accuracy  f1_score  log_loss  roc_auc
0   0.997807  0.995098  0.997076  0.996431  0.023646      1.0

---
## Step 7 — The gotcha: predicting on raw data silently gives garbage

Because the downstream model has no embedded `TRANSFORM`, `ML.PREDICT` does **not** know to re-apply the pipeline. Feeding it raw (untransformed) feature values doesn't error — BigQuery ML happily predicts using values on the wrong scale, it just gives **wrong** answers.

> **Verified live:** every row below predicts `Gentoo penguin` (the largest species) regardless of its true species, because raw `body_mass_g`/`culmen_*` values are far outside the z-score-scaled range the model was actually trained on.

In [11]:
query = f"""
SELECT species, predicted_species
FROM ML.PREDICT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_downstream`,
  (SELECT species, island, body_mass_g, culmen_length_mm, culmen_depth_mm, flipper_length_mm
   FROM `bigquery-public-data.ml_datasets.penguins`
   WHERE body_mass_g IS NOT NULL LIMIT 5)
)
"""
client.query(query).to_dataframe()

,species,predicted_species
0,Adelie Penguin (Pygoscelis adeliae),Gentoo penguin (Pygoscelis papua)
1,Adelie Penguin (Pygoscelis adeliae),Gentoo penguin (Pygoscelis papua)
2,Chinstrap penguin (Pygoscelis antarctica),Gentoo penguin (Pygoscelis papua)
3,Adelie Penguin (Pygoscelis adeliae),Gentoo penguin (Pygoscelis papua)
4,Adelie Penguin (Pygoscelis adeliae),Gentoo penguin (Pygoscelis papua)

---
## Step 8 — The fix: re-apply `ML.TRANSFORM` before `ML.PREDICT`

Wrapping the same raw rows in `ML.TRANSFORM` first reproduces the exact preprocessing used at training time, and predictions become correct again. This re-application is the price of a transform-only model's reusability — contrast with an **embedded** `TRANSFORM` clause on a predictive model (e.g. [PCA](../pca/) Step 10), which auto-applies at predict time with no re-application needed, but isn't reusable across other models the way a standalone `TRANSFORM_ONLY` model is.

In [12]:
query = f"""
SELECT species, predicted_species
FROM ML.PREDICT(
  MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_downstream`,
  (SELECT species, island, body_mass_g, culmen_length_mm, culmen_depth_mm, flipper_length_mm
   FROM ML.TRANSFORM(
     MODEL `{PROJECT_ID}.{DATASET_ID}.transform_only_penguins`,
     (SELECT species, island, sex, body_mass_g, culmen_length_mm, culmen_depth_mm, flipper_length_mm
      FROM `bigquery-public-data.ml_datasets.penguins`
      WHERE body_mass_g IS NOT NULL LIMIT 5)
   )
  )
)
"""
client.query(query).to_dataframe()

,species,predicted_species
0,Adelie Penguin (Pygoscelis adeliae),Adelie Penguin (Pygoscelis adeliae)
1,Adelie Penguin (Pygoscelis adeliae),Adelie Penguin (Pygoscelis adeliae)
2,Adelie Penguin (Pygoscelis adeliae),Adelie Penguin (Pygoscelis adeliae)
3,Adelie Penguin (Pygoscelis adeliae),Adelie Penguin (Pygoscelis adeliae)
4,Chinstrap penguin (Pygoscelis antarctica),Chinstrap penguin (Pygoscelis antarctica)

---
## Examples — `%%bigquery` Magics

The same operations using IPython magic commands — write SQL directly in cells without Python string wrapping.

- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### `ML.FEATURE_INFO` with `%%bigquery`

In [13]:
%%bigquery --project {PROJECT_ID}

SELECT *
FROM ML.FEATURE_INFO(MODEL `statmike-mlops-349915.bq_ml.transform_only_penguins`)

Query is running:   0%|          |

Downloading:   0%|          |

,input,min,max,mean,median,stddev,category_count,null_count,dimension
0,culmen_length_mm,32.1,59.6,43.921930,44.1,5.459584,<NA>,2,<NA>
1,body_mass_g,2700.0,6300.0,4201.754386,4050.0,801.954536,<NA>,2,<NA>
2,sex,NaN,NaN,NaN,NaN,NaN,3,10,<NA>
3,island,NaN,NaN,NaN,NaN,NaN,3,0,<NA>
4,species,NaN,NaN,NaN,NaN,NaN,3,0,<NA>
5,culmen_depth_mm,13.1,21.5,17.151170,17.3,1.974793,<NA>,2,<NA>
6,flipper_length_mm,172.0,231.0,200.915205,197.0,14.061714,<NA>,2,<NA>

---
## Examples — BigFrames

There is **no single direct `TRANSFORM_ONLY` class** in BigFrames — the equivalent functionality is the `bigframes.ml.preprocessing` transformers (`StandardScaler`, `MaxAbsScaler`, `OneHotEncoder`, etc.) composed with `bigframes.ml.pipeline.Pipeline`, which compile down to the same BQML preprocessing functions under the hood. This shows the closest equivalent: a two-step `Pipeline` (impute, then scale) — but note it does not produce a queryable `TRANSFORM_ONLY` model object the way the SQL path does; it's a Python-side pipeline that gets applied at `.fit()`/`.predict()` time.

In [14]:
import bigframes.pandas as bpd

bpd.close_session()  # Reset session to apply project/location settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

In [15]:
from bigframes.ml.preprocessing import StandardScaler
from bigframes.ml.impute import SimpleImputer
from bigframes.ml.compose import ColumnTransformer

df = bpd.read_gbq('bigquery-public-data.ml_datasets.penguins')
df = df[df['body_mass_g'].notnull()]

# Impute then scale, composed as a ColumnTransformer (closest BigFrames equivalent
# to a reusable TRANSFORM_ONLY pipeline)
preprocessor = ColumnTransformer([
    ('scale_length', StandardScaler(), 'culmen_length_mm'),
    ('scale_depth', StandardScaler(), 'culmen_depth_mm'),
])
preprocessor.fit(df[['culmen_length_mm', 'culmen_depth_mm']])
preprocessor.transform(df[['culmen_length_mm', 'culmen_depth_mm']]).peek()

     standard_scaled_culmen_length_mm  standard_scaled_culmen_depth_mm
18                          -0.939522                         0.024748
51                          -1.141298                         1.343273
80                          -1.361417                         0.430448
86                           0.674683                         -1.34449
136                         -0.205793                        -1.496628

---
## Cleanup

Drop the models created by this notebook and remove the GCS export from Step 4. The shared dataset is left for other notebooks.

In [16]:
for model_name in [
    'transform_only_penguins',
    'transform_only_downstream',
]:
    client.query(f'DROP MODEL IF EXISTS `{PROJECT_ID}.{DATASET_ID}.{model_name}`').result()
    print(f'Dropped {model_name}')

# Remove the GCS export from Step 4
from google.cloud import storage
storage_client = storage.Client(project=PROJECT_ID)
bucket = storage_client.bucket(BUCKET)
blobs = list(bucket.list_blobs(prefix='bq_ml/transform_only/model'))
for blob in blobs:
    blob.delete()
print(f'Deleted {len(blobs)} exported model file(s) from gs://{BUCKET}/bq_ml/transform_only/model')

Dropped transform_only_penguins
Dropped transform_only_downstream
Deleted 9 exported model file(s) from gs://statmike-mlops-349915/bq_ml/transform_only/model

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and everything in it.

In [ ]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')