![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Fworkflows%2Fdocument_rag&file=document_rag.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Fworkflows%2Fdocument_rag%2Fdocument_rag.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/document_rag/document_rag.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Document RAG — BigQuery AI Functions

A complete document-based Retrieval-Augmented Generation (RAG) pipeline built entirely in BigQuery SQL:

1. **Parse** real documents with `AI.PARSE_DOCUMENT`
2. **Embed** document chunks with `AI.EMBED`
3. **Search** for relevant chunks with `VECTOR_SEARCH`
4. **Answer** questions with `AI.GENERATE`, grounded in document content

**What this demonstrates:**
- Building a document RAG pipeline entirely in BigQuery SQL — no external tools
- Parsing real PDFs into searchable chunks with `AI.PARSE_DOCUMENT`
- Asymmetric embedding pattern (RETRIEVAL_DOCUMENT / RETRIEVAL_QUERY)
- Composing parsed document chunks into grounded prompts
- Using ObjectRef (`OBJ.MAKE_REF`) as an alternative to object tables for document parsing
- Comparing RAG answers with and without retrieved context

**Functions used:** [`AI.PARSE_DOCUMENT`](../../functions/ai_parse_document/) | [`AI.EMBED`](../../functions/ai_embed/) | [`VECTOR_SEARCH`](../../functions/vector_search/) | [`AI.GENERATE`](../../functions/ai_generate/)

**Prerequisites:** [Setup guide](../../setup/) | [Function reference](../../RESOURCES.md)

---
## Setup

Set your project and location, authenticate, and create shared resources.

> This workflow requires: (1) a **Cloud resource connection** with Document AI and Storage roles, (2) a **Document AI Layout Parser processor**, and (3) an **object table** pointing to documents in Cloud Storage. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection
BUCKET = PROJECT_ID  # GCS bucket for document storage

### Environment

> **Already set up the project environment?** Skip to [Step 1](#step-1--parse-documents-with-aiparse_document).  
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? Run the cells below to install packages, authenticate, and create the shared dataset. See the [Setup Reference](../../setup/) for details.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes',
        'google-cloud-storage', 'google-cloud-documentai')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

In [5]:
import subprocess as _sp, json as _json

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant required roles
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
for role in ['roles/aiplatform.user', 'roles/storage.objectViewer', 'roles/documentai.apiUser']:
    _sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
             f'--member=serviceAccount:{sa}', f'--role={role}', '--quiet'],
            capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

In [6]:
from google.cloud import documentai_v1 as documentai

docai_client = documentai.DocumentProcessorServiceClient()
parent = docai_client.common_location_path(PROJECT_ID, 'us')

# Check for existing layout parser processor (idempotent)
PROCESSOR_DISPLAY_NAME = 'bq_ai_functions_layout_parser'
processor = None
for p in docai_client.list_processors(parent=parent):
    if p.display_name == PROCESSOR_DISPLAY_NAME:
        processor = p
        break

if processor is None:
    processor = docai_client.create_processor(
        parent=parent,
        processor=documentai.Processor(
            display_name=PROCESSOR_DISPLAY_NAME,
            type_='LAYOUT_PARSER_PROCESSOR',
        ),
    )

PROCESSOR_ID = processor.name
print(f'Layout Parser processor ready: {PROCESSOR_ID}')

Layout Parser processor ready: projects/1026793852137/locations/us/processors/54637c0f25399e5b

### Upload documents and create object table

Upload 20 sample invoices to Cloud Storage and create an object table to reference them from BigQuery.

In [7]:
from google.cloud import storage
from pathlib import Path
from tqdm import tqdm

gcs = storage.Client(project=PROJECT_ID)
bucket = gcs.bucket(BUCKET)
prefix = 'bq_ai_functions/document_rag'

data_dir = Path('../../data/documents/invoices')
if not data_dir.exists():
    data_dir = Path('data/documents/invoices')

files = sorted(data_dir.glob('*.pdf'))[:20]
uploaded, skipped = 0, 0
for f in tqdm(files, desc='Uploading'):
    blob = bucket.blob(f'{prefix}/{f.name}')
    if blob.exists():
        skipped += 1
    else:
        blob.upload_from_filename(str(f))
        uploaded += 1
print(f'Uploaded {uploaded} documents, skipped {skipped} (already exist)')
print(f'Location: gs://{BUCKET}/{prefix}/')

Uploading: 100%|██████████| 20/20 [00:02<00:00,  8.13it/s]

Uploaded 20 documents, skipped 0 (already exist)
Location: gs://statmike-mlops-349915/bq_ai_functions/document_rag/

In [8]:
client.query(f"""
CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_objects`
WITH CONNECTION `{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}`
OPTIONS (
  object_metadata = 'SIMPLE',
  uris = ['gs://{BUCKET}/{prefix}/*.pdf']
)
""").result()

df = client.query(f"""
  SELECT uri, content_type, size
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_objects`
  ORDER BY uri
""").to_dataframe()
print(f'Object table workflow_docrag_objects ready — {len(df)} documents')
df.head()

Object table workflow_docrag_objects ready — 20 documents

,uri,content_type,size
0,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_001.pdf,application/pdf,17240
1,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_002.pdf,application/pdf,16264
2,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_003.pdf,application/pdf,15007
3,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_004.pdf,application/pdf,21071
4,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_005.pdf,application/pdf,17012

---
## Step 1 — Parse documents with AI.PARSE_DOCUMENT

`AI.PARSE_DOCUMENT` reads documents from the object table, runs them through the Document AI Layout Parser, and returns text chunks. Each document becomes one or more chunks with `chunk_id`, `start_page`, `end_page`, and `content`. We persist the results to avoid re-parsing on every query.

In [9]:
query = f"""
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_chunks` AS
SELECT
  uri,
  chunk_id,
  start_page,
  end_page,
  content
FROM AI.PARSE_DOCUMENT(
  TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_objects`,
  endpoint => '{PROCESSOR_ID}'
)
"""
client.query(query).result()

stats = client.query(f"""
  SELECT COUNT(*) AS total_chunks, COUNT(DISTINCT uri) AS documents
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_chunks`
""").to_dataframe()
print(f'Parsed {stats.iloc[0]["documents"]} documents into {stats.iloc[0]["total_chunks"]} chunks')

Parsed 20 documents into 20 chunks

In [10]:
client.query(f"""
  SELECT uri, chunk_id, start_page, end_page, LEFT(content, 200) AS content_preview
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_chunks`
  ORDER BY uri, chunk_id
  LIMIT 5
""").to_dataframe()

,uri,chunk_id,start_page,end_page,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_001.pdf,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Marketing LLC Attn: Samantha Chen 789 Market Street,"
1,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_002.pdf,1,1,1,"# Harmony Event Solutions LLC\n\n123 Event Horizon Blvd Nashville, TN 37203(615) 555-0100 billing@harmonyevents.com INVOICE BILL TO Summit Conference Center Eleanor Vance 789 Mountain View Rd Knoxville,"
2,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_003.pdf,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 Austin, TX 78759 (512) 555-0123 billing@nexusinnovations.com INVOICE\n\n|-|\n| Invoice #: INV-2023-0110 |\n| Date: 2023-10-26 |\n| Due Date: 2023-11-"
3,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_004.pdf,1,1,1,"123 Creative Way Austin, TX 78701 (512) 555-1234 info@digitalascent.com INVOICE BILL TO GreenLeaf Organics Inc. Sarah Chen 456 Market St Dallas, TX 75201 Issued: 2024-06-15 Due: 2024-07-15 Terms: Net"
4,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_005.pdf,1,1,1,"Apex Digital Solutions LLC 789 Tech Drive | Innovation City, CA 90012 | (555) 789-0123 | billing@apexds.com INVOICE BILL TO Quantum Enterprises Inc. Attn: Eleanor Vance 101 Corporate Way Metropolis, N"

### Alternative: ObjectRef — skip the object table

`AI.PARSE_DOCUMENT` requires a `ref` column in its input. Object tables provide this automatically, but you can construct it inline using `OBJ.MAKE_REF` — no object table creation needed.

This approach uses `UNNEST` to create rows from GCS URIs, adds a `ref` column with `OBJ.MAKE_REF`, and passes the result directly to `AI.PARSE_DOCUMENT`. The output is identical to the object table approach above.

In [11]:
# ObjectRef alternative — parse documents without an object table
# Build URIs from the uploaded files
uris = [f'gs://{BUCKET}/{prefix}/invoice_{i:03d}.pdf' for i in range(1, 21)]
uris_sql = ', '.join(f"'{u}'" for u in uris)

query = f"""
SELECT
  uri,
  chunk_id,
  LEFT(content, 200) AS content_preview
FROM AI.PARSE_DOCUMENT(
  (SELECT
    uri,
    OBJ.MAKE_REF(uri, '{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}') AS ref
  FROM UNNEST([{uris_sql}]) AS uri),
  endpoint => '{PROCESSOR_ID}'
)
ORDER BY uri, chunk_id
LIMIT 5
"""
df = client.query(query).to_dataframe()
print(f'ObjectRef approach: parsed {df["uri"].nunique()} documents (showing first 5 chunks)')
df

ObjectRef approach: parsed 5 documents (showing first 5 chunks)

,uri,chunk_id,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_001.pdf,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Marketing LLC Attn: Samantha Chen 789 Market Street,"
1,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_002.pdf,1,"# Harmony Event Solutions LLC\n\n123 Event Horizon Blvd Nashville, TN 37203(615) 555-0100 billing@harmonyevents.com INVOICE BILL TO Summit Conference Center Eleanor Vance 789 Mountain View Rd Knoxville,"
2,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_003.pdf,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 Austin, TX 78759 (512) 555-0123 billing@nexusinnovations.com INVOICE\n\n|-|\n| Invoice #: INV-2023-0110 |\n| Date: 2023-10-26 |\n| Due Date: 2023-11-"
3,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_004.pdf,1,"123 Creative Way Austin, TX 78701 (512) 555-1234 info@digitalascent.com INVOICE BILL TO GreenLeaf Organics Inc. Sarah Chen 456 Market St Dallas, TX 75201 Issued: 2024-06-15 Due: 2024-07-15 Terms: Net"
4,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_005.pdf,1,"Apex Digital Solutions LLC 789 Tech Drive | Innovation City, CA 90012 | (555) 789-0123 | billing@apexds.com INVOICE BILL TO Quantum Enterprises Inc. Attn: Eleanor Vance 101 Corporate Way Metropolis, N"

---
## Step 2 — Embed chunks with AI.EMBED

Create embeddings for each document chunk using `text-embedding-005` with `RETRIEVAL_DOCUMENT` task type. This tells the embedding model that these are documents to be retrieved — queries will use the complementary `RETRIEVAL_QUERY` task type for asymmetric search.

In [12]:
query = f"""
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_embedded` AS
SELECT
  uri, chunk_id, start_page, end_page, content,
  (AI.EMBED(
    content => content,
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_DOCUMENT'
  )).result AS embedding
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_chunks`
"""
client.query(query).result()

verify = client.query(f"""
  SELECT COUNT(*) AS chunks, ARRAY_LENGTH(embedding) AS dims
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_embedded`
  GROUP BY dims
""").to_dataframe()
print(f'All {verify.iloc[0]["chunks"]} chunks embedded ({verify.iloc[0]["dims"]} dimensions)')

All 20 chunks embedded (768 dimensions)

---
## Step 3 — Retrieve and generate (RAG)

The core RAG pattern: embed the user question with `RETRIEVAL_QUERY`, find the most relevant document chunks with `VECTOR_SEARCH`, then pass them as context to `AI.GENERATE` to produce a grounded answer.

In [13]:
user_question = 'What is the total amount due on the invoice from Nexus Innovations Group?'

query = f"""
WITH retrieved AS (
  SELECT
    base.uri,
    base.chunk_id,
    base.content,
    distance
  FROM VECTOR_SEARCH(
    TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_embedded`,
    'embedding',
    query_value => (AI.EMBED(
      content => '{user_question}',
      endpoint => 'text-embedding-005',
      task_type => 'RETRIEVAL_QUERY'
    )).result,
    top_k => 3,
    distance_type => 'COSINE'
  )
),
context AS (
  SELECT STRING_AGG(
    CONCAT('--- Document: ', uri, ' (chunk ', CAST(chunk_id AS STRING), ') --- ', content),
    ' ||| '
  ) AS docs
  FROM retrieved
)
SELECT (AI.GENERATE(
  CONCAT(
    'You are a document analyst. Answer the user question based ONLY on the provided document excerpts. ',
    'Include specific details (amounts, dates, reference numbers) from the documents. ',
    'If the documents do not contain enough information, say so. ',
    'Document excerpts: ', c.docs,
    ' --- User question: {user_question}'
  )
)).result AS answer
FROM context c
"""
df = client.query(query).to_dataframe()
print(f'Question: {user_question}\n')
print(df.iloc[0]['answer'])

Question: What is the total amount due on the invoice from Nexus Innovations Group?

There are two invoices from Nexus Innovations Group in the provided documents.

1.  **Invoice #: INV-2023-0110** (issued to Quantum Solutions Inc.) has a **Total Due** of **$21217.00**.
2.  **Invoice #: INV-2024-0013** (issued to Global Reach Marketing LLC) has a **Total Due** of **$10067.25**.

The documents do not specify which invoice from Nexus Innovations Group the question refers to.

### View the retrieved chunks

See which document chunks were retrieved and used as context for the answer. Lower distance = higher relevance.

In [14]:
query = f"""
SELECT
  base.uri,
  base.chunk_id,
  LEFT(base.content, 200) AS content_preview,
  distance
FROM VECTOR_SEARCH(
  TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_embedded`,
  'embedding',
  query_value => (AI.EMBED(
    content => '{user_question}',
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_QUERY'
  )).result,
  top_k => 3,
  distance_type => 'COSINE'
)
"""
client.query(query).to_dataframe()

,uri,chunk_id,content_preview,distance
0,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_003.pdf,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 Austin, TX 78759 (512) 555-0123 billing@nexusinnovations.com INVOICE\n\n|-|\n| Invoice #: INV-2023-0110 |\n| Date: 2023-10-26 |\n| Due Date: 2023-11-",0.181489
1,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_001.pdf,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Marketing LLC Attn: Samantha Chen 789 Market Street,",0.195660
2,gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_018.pdf,1,"Quantum Innovations Group 456 Tech Lane | San Francisco, CA 94107 | (415) 555-0199 | billing@quantuminnovations.com INVOICE BILL TO Synergy Solutions Inc. Attn: Elara Vance 123 Business Parkway Oaklan",0.237207

### Batch RAG: answer multiple questions

Process multiple questions through the document RAG pipeline at once. Each question retrieves its own relevant chunks and gets a tailored answer.

In [15]:
query = f"""
WITH questions AS (
  SELECT question
  FROM UNNEST([
    'Which vendor has the highest total invoice amount?',
    'What are the payment terms on invoice INV-2024-0013?',
    'List all invoices due in November 2023.'
  ]) AS question
),
retrieved AS (
  SELECT
    query.question AS user_question,
    base.uri,
    base.content,
    distance
  FROM VECTOR_SEARCH(
    TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_embedded`,
    'embedding',
    (SELECT question,
       (AI.EMBED(content => question, endpoint => 'text-embedding-005',
                 task_type => 'RETRIEVAL_QUERY')).result AS embedding
     FROM questions),
    top_k => 3,
    distance_type => 'COSINE'
  )
),
context_per_question AS (
  SELECT
    user_question,
    STRING_AGG(
      CONCAT('--- ', uri, ' --- ', content),
      ' ||| '
    ) AS context
  FROM retrieved
  GROUP BY user_question
)
SELECT
  user_question,
  (AI.GENERATE(
    CONCAT(
      'Answer this question concisely based on the document excerpts below. ',
      'Include specific amounts, dates, and reference numbers. ',
      'Documents: ', context,
      ' --- Question: ', user_question
    )
  )).result AS answer
FROM context_per_question
"""
df = client.query(query).to_dataframe()
for _, row in df.iterrows():
    print(f'Q: {row["user_question"]}')
    print(f'A: {row["answer"]}\n')

Q: What are the payment terms on invoice INV-2024-0013?
A: The payment terms for invoice INV-2024-0013 are not found in the provided documents.

Q: Which vendor has the highest total invoice amount?
A: Quantum Innovations Corp. has the highest total invoice amount of $35690.00, for invoice INV-2023-0006 dated 2023-11-15.

Q: List all invoices due in November 2023.
A: The following invoices are due in November 2023:

*   **INV-2023-0016** is due on 2023-11-25 for a total of $15016.50.
*   **INV-2023-0034** is due on 2023-11-19 for a total of $13525.50.

---
## Step 4 — RAG vs direct generation

Compare the same question answered with and without retrieved document context. Without RAG, the model can only guess or hallucinate invoice details. With RAG, it grounds its answer in actual document content.

In [16]:
comparison_question = 'What is the total amount due on the invoice from Nexus Innovations Group?'

query = f"""
WITH no_rag AS (
  SELECT (AI.GENERATE(
    CONCAT(
      'Answer this question. If you do not have the information, say so. ',
      'Question: {comparison_question}'
    )
  )).result AS answer
),
rag_context AS (
  SELECT STRING_AGG(
    CONCAT('--- ', base.uri, ' --- ', base.content),
    ' ||| '
  ) AS docs
  FROM VECTOR_SEARCH(
    TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_docrag_embedded`,
    'embedding',
    query_value => (AI.EMBED(
      content => '{comparison_question}',
      endpoint => 'text-embedding-005',
      task_type => 'RETRIEVAL_QUERY'
    )).result,
    top_k => 3,
    distance_type => 'COSINE'
  )
),
with_rag AS (
  SELECT (AI.GENERATE(
    CONCAT(
      'Answer this question based ONLY on the provided documents. ',
      'Include specific amounts and reference numbers. ',
      'Documents: ', docs,
      ' --- Question: {comparison_question}'
    )
  )).result AS answer
  FROM rag_context
)
SELECT
  'Without RAG' AS method, answer FROM no_rag
UNION ALL
SELECT
  'With RAG' AS method, answer FROM with_rag
"""
df = client.query(query).to_dataframe()
for _, row in df.iterrows():
    print(f'=== {row["method"]} ===')
    print(f'{row["answer"]}\n')

=== Without RAG ===
I do not have access to specific invoice information, including the total amount due on an invoice from Nexus Innovations Group. This kind of detail would be confidential and specific to a particular transaction.

=== With RAG ===
Based on the provided documents, the total amounts due on invoices from Nexus Innovations Group are:

*   **$21217.00** for Invoice #: INV-2023-0110 (from gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_003.pdf)
*   **$10067.25** for Invoice #: INV-2024-0013 (from gs://statmike-mlops-349915/bq_ai_functions/document_rag/invoice_001.pdf)

The **Without RAG** answer is either a refusal ("I don't have that information") or a hallucinated amount. The **With RAG** answer references actual invoice data — amounts, dates, and reference numbers from the retrieved document chunks. This is the core value of RAG: grounding generation in retrieved evidence.

---
## Cleanup

Drop tables and GCS files created by this workflow. Shared resources (dataset, connection, processor) are left for other notebooks.

In [17]:
# Drop workflow-specific tables
for table in ['workflow_docrag_chunks', 'workflow_docrag_embedded', 'workflow_docrag_objects']:
    client.query(f'DROP TABLE IF EXISTS `{PROJECT_ID}.{DATASET_ID}.{table}`').result()
    print(f'Dropped {table}')

# Clean up GCS files
blobs = list(bucket.list_blobs(prefix=prefix))
for blob in blobs:
    blob.delete()
print(f'Deleted {len(blobs)} GCS files')

# Uncomment to delete the Document AI processor:
# docai_client.delete_processor(name=PROCESSOR_ID)
# print(f'Deleted processor {PROCESSOR_ID}')

Dropped workflow_docrag_chunks
Dropped workflow_docrag_embedded
Dropped workflow_docrag_objects
Deleted 20 GCS files

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [18]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')