![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_forecast&file=ai_forecast.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_forecast%2Fai_forecast.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.FORECAST — BigQuery AI Functions

`AI.FORECAST` is a table-valued function that forecasts future time series values using BigQuery ML's built-in TimesFM model. No model creation or training required.

**When to use it:**
- You want to forecast future values from historical time series data
- You need prediction intervals (confidence bounds) for forecasts
- You want to forecast multiple independent time series at once
- You need a zero-setup forecasting solution (no CREATE MODEL)
- You can specify a target date with `forecast_end_timestamp` instead of a numeric `horizon`
- You can control how much history the model sees with `context_window` (64–15,360 depending on model)

**Alternatives:**
- [`AI.DETECT_ANOMALIES`](../ai_detect_anomalies/) — Detect anomalies by comparing data against a forecast baseline
- [`AI.EVALUATE`](../ai_evaluate/) — Evaluate forecast accuracy against actual values

**Featured in:** [Time Series Intelligence](../../workflows/time_series_intelligence/)

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-forecast) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function doesn't require a connection or model — it uses end-user credentials automatically. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

### Setup: Create sample time series data

Generate synthetic daily sales data with realistic patterns using SQL.

In [5]:
# Create synthetic daily sales data with trend and weekly seasonality
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales` AS
WITH dates AS (
  SELECT date
  FROM UNNEST(GENERATE_DATE_ARRAY('2024-01-01', '2024-12-31')) AS date
)
SELECT
  date,
  -- Base sales + trend + weekly seasonality + noise
  GREATEST(0,
    1000
    + EXTRACT(DAYOFYEAR FROM date) * 2  -- upward trend
    + CASE EXTRACT(DAYOFWEEK FROM date)
        WHEN 1 THEN -200  -- Sunday dip
        WHEN 7 THEN 300   -- Saturday peak
        WHEN 6 THEN 200   -- Friday boost
        ELSE 0
      END
    + CAST(200 * (RAND() - 0.5) AS INT64)  -- random noise
  ) AS daily_sales
FROM dates
'''
client.query(query).result()

# Preview the data
df = client.query(f'SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales` ORDER BY date LIMIT 10').to_dataframe()
print(f'Rows: {client.query(f"SELECT COUNT(*) AS n FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`").to_dataframe().iloc[0]["n"]}')
df

Rows: 366

         date  daily_sales
0  2024-01-01         1068
1  2024-01-02          979
2  2024-01-03         1081
3  2024-01-04         1073
4  2024-01-05         1225
5  2024-01-06         1371
6  2024-01-07          853
7  2024-01-08          981
8  2024-01-09          983
9  2024-01-10          925

### 1. Basic forecast

`AI.FORECAST` requires `data_col` and `timestamp_col`. Default horizon is 10 time steps.

In [6]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date'
)
'''
client.query(query).to_dataframe()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1730.566162,0.95,1619.031513,1850.571145,
1,2025-01-02 00:00:00+00:00,1753.789307,0.95,1635.900648,1860.932624,
2,2025-01-03 00:00:00+00:00,1945.858643,0.95,1828.285865,2060.325828,
3,2025-01-04 00:00:00+00:00,2024.823608,0.95,1924.641414,2123.608421,
4,2025-01-05 00:00:00+00:00,1546.011597,0.95,1437.598038,1658.200596,
5,2025-01-06 00:00:00+00:00,1748.632812,0.95,1627.244833,1871.931014,
6,2025-01-07 00:00:00+00:00,1726.264648,0.95,1603.060167,1861.481917,
7,2025-01-08 00:00:00+00:00,1761.886963,0.95,1621.865038,1884.045974,
8,2025-01-09 00:00:00+00:00,1747.185059,0.95,1622.922419,1876.105999,
9,2025-01-10 00:00:00+00:00,1965.754150,0.95,1842.135776,2088.324446,

### 2. Custom horizon

Forecast more time steps into the future.

In [7]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 30
)
'''
client.query(query).to_dataframe()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1730.566162,0.95,1619.031513,1850.571145,
1,2025-01-02 00:00:00+00:00,1753.789307,0.95,1635.900648,1860.932624,
2,2025-01-03 00:00:00+00:00,1945.858643,0.95,1828.285865,2060.325828,
3,2025-01-04 00:00:00+00:00,2024.823608,0.95,1924.641414,2123.608421,
4,2025-01-05 00:00:00+00:00,1546.011597,0.95,1437.598038,1658.200596,
5,2025-01-06 00:00:00+00:00,1748.632812,0.95,1627.244833,1871.931014,
6,2025-01-07 00:00:00+00:00,1726.264648,0.95,1603.060167,1861.481917,
7,2025-01-08 00:00:00+00:00,1761.886963,0.95,1621.865038,1884.045974,
8,2025-01-09 00:00:00+00:00,1747.185059,0.95,1622.922419,1876.105999,
9,2025-01-10 00:00:00+00:00,1965.754150,0.95,1842.135776,2088.324446,
10,2025-01-11 00:00:00+00:00,2044.323242,0.95,1911.718905,2164.055655,
11,2025-01-12 00:00:00+00:00,1592.912964,0.95,1464.585132,1734.972611,
12,2025-01-13 00:00:00+00:00,1767.582153,0.95,1641.205613,1914.266688,
13,2025-01-14 00:00:00+00:00,1753.391357,0.95,1627.578438,1894.573752,
14,2025-01-15 00:00:00+00:00,1789.455322,0.95,1671.637983,1916.912615,
15,2025-01-16 00:00:00+00:00,1791.666748,0.95,1684.035421,1946.974888,
16,2025-01-17 00:00:00+00:00,1999.483521,0.95,1868.827664,2124.339276,
17,2025-01-18 00:00:00+00:00,2075.918457,0.95,1940.501442,2191.325251,
18,2025-01-19 00:00:00+00:00,1608.593994,0.95,1474.017073,1744.303377,
19,2025-01-20 00:00:00+00:00,1802.909668,0.95,1667.262267,1933.568321,
20,2025-01-21 00:00:00+00:00,1778.389893,0.95,1617.261494,1907.583582,
21,2025-01-22 00:00:00+00:00,1818.318848,0.95,1671.251971,1953.498777,
22,2025-01-23 00:00:00+00:00,1793.890015,0.95,1653.159226,1927.400374,
23,2025-01-24 00:00:00+00:00,2003.098999,0.95,1864.077362,2143.262622,
24,2025-01-25 00:00:00+00:00,2057.088867,0.95,1908.462372,2179.748957,
25,2025-01-26 00:00:00+00:00,1614.707520,0.95,1460.713868,1765.747543,
26,2025-01-27 00:00:00+00:00,1796.820801,0.95,1644.163663,1931.082954,
27,2025-01-28 00:00:00+00:00,1778.830078,0.95,1618.070205,1922.100422,
28,2025-01-29 00:00:00+00:00,1801.008301,0.95,1639.755192,1934.490832,
29,2025-01-30 00:00:00+00:00,1800.285156,0.95,1625.122482,1938.570491,

### 3. Include historical data

Set `output_historical_time_series => TRUE` to get historical + forecasted data in one result for comparison.

In [8]:
query = f'''
SELECT *
FROM AI.FORECAST(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`
   WHERE date >= '2024-11-01'),  -- last 2 months for context
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 14,
  output_historical_time_series => TRUE
)
ORDER BY time_series_timestamp
'''
df = client.query(query).to_dataframe()
print(f'Historical rows: {(df["time_series_type"] == "history").sum()}')
print(f'Forecast rows: {(df["time_series_type"] == "forecast").sum()}')
df.tail(20)

Historical rows: 61
Forecast rows: 14

,time_series_type,time_series_timestamp,time_series_data,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
55,history,2024-12-26 00:00:00+00:00,1634.000000,NaN,NaN,NaN,None
56,history,2024-12-27 00:00:00+00:00,2016.000000,NaN,NaN,NaN,None
57,history,2024-12-28 00:00:00+00:00,2029.000000,NaN,NaN,NaN,None
58,history,2024-12-29 00:00:00+00:00,1532.000000,NaN,NaN,NaN,None
59,history,2024-12-30 00:00:00+00:00,1798.000000,NaN,NaN,NaN,None
60,history,2024-12-31 00:00:00+00:00,1758.000000,NaN,NaN,NaN,None
61,forecast,2025-01-01 00:00:00+00:00,1745.802368,0.95,1599.106065,1877.123963,
62,forecast,2025-01-02 00:00:00+00:00,1769.411743,0.95,1619.460308,1895.465306,
63,forecast,2025-01-03 00:00:00+00:00,1960.573975,0.95,1863.744184,2072.625942,
64,forecast,2025-01-04 00:00:00+00:00,2009.072266,0.95,1925.678028,2089.214736,
65,forecast,2025-01-05 00:00:00+00:00,1600.233765,0.95,1439.855665,1786.607750,
66,forecast,2025-01-06 00:00:00+00:00,1753.342041,0.95,1622.203221,1910.318630,
67,forecast,2025-01-07 00:00:00+00:00,1751.580200,0.95,1615.866720,1912.146293,
68,forecast,2025-01-08 00:00:00+00:00,1730.805542,0.95,1587.020863,1893.718890,
69,forecast,2025-01-09 00:00:00+00:00,1768.433350,0.95,1624.195764,1933.293877,
70,forecast,2025-01-10 00:00:00+00:00,1963.004639,0.95,1858.897844,2080.629506,
71,forecast,2025-01-11 00:00:00+00:00,2014.352661,0.95,1915.524163,2121.385458,
72,forecast,2025-01-12 00:00:00+00:00,1625.102173,0.95,1445.574499,1826.901648,
73,forecast,2025-01-13 00:00:00+00:00,1758.451172,0.95,1608.976180,1926.201103,
74,forecast,2025-01-14 00:00:00+00:00,1745.751465,0.95,1594.587478,1910.174024,

### 4. Multi-series forecasting with id_cols

Forecast multiple independent time series at once by specifying `id_cols`.

In [9]:
# Create multi-series data
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_multi_series` AS
WITH dates AS (
  SELECT date
  FROM UNNEST(GENERATE_DATE_ARRAY('2024-01-01', '2024-12-31')) AS date
),
stores AS (
  SELECT * FROM UNNEST([
    STRUCT('downtown' AS store_id, 1500 AS base_sales),
    STRUCT('suburban', 800),
    STRUCT('airport', 2000)
  ])
)
SELECT
  s.store_id,
  d.date,
  GREATEST(0, s.base_sales + EXTRACT(DAYOFYEAR FROM d.date) * 1 + CAST(100 * (RAND() - 0.5) AS INT64)) AS daily_sales
FROM dates d CROSS JOIN stores s
'''
client.query(query).result()
print('Multi-series data created')

Multi-series data created

In [10]:
# Forecast each store independently
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_multi_series`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  id_cols => ['store_id'],
  horizon => 14
)
ORDER BY store_id, forecast_timestamp
'''
client.query(query).to_dataframe()

,store_id,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,airport,2025-01-01 00:00:00+00:00,2372.662842,0.95,2309.991987,2432.072964,
1,airport,2025-01-02 00:00:00+00:00,2378.297852,0.95,2319.652039,2440.593086,
2,airport,2025-01-03 00:00:00+00:00,2377.660889,0.95,2317.534251,2440.226823,
3,airport,2025-01-04 00:00:00+00:00,2373.740723,0.95,2316.353952,2435.670793,
4,airport,2025-01-05 00:00:00+00:00,2375.193115,0.95,2316.642888,2432.996206,
5,airport,2025-01-06 00:00:00+00:00,2373.683838,0.95,2314.120257,2436.245668,
6,airport,2025-01-07 00:00:00+00:00,2374.869629,0.95,2310.942342,2441.275790,
7,airport,2025-01-08 00:00:00+00:00,2368.316895,0.95,2302.237067,2428.311356,
8,airport,2025-01-09 00:00:00+00:00,2362.248047,0.95,2296.758166,2423.049387,
9,airport,2025-01-10 00:00:00+00:00,2377.264404,0.95,2313.114216,2440.580092,
10,airport,2025-01-11 00:00:00+00:00,2375.462891,0.95,2307.343660,2439.716885,
11,airport,2025-01-12 00:00:00+00:00,2392.566406,0.95,2321.736434,2454.528585,
12,airport,2025-01-13 00:00:00+00:00,2386.883057,0.95,2314.708166,2453.402721,
13,airport,2025-01-14 00:00:00+00:00,2379.514648,0.95,2309.606550,2448.291400,
14,downtown,2025-01-01 00:00:00+00:00,1879.440308,0.95,1818.722045,1949.140622,
15,downtown,2025-01-02 00:00:00+00:00,1885.717041,0.95,1823.010526,1958.374341,
16,downtown,2025-01-03 00:00:00+00:00,1875.991089,0.95,1811.961312,1946.391863,
17,downtown,2025-01-04 00:00:00+00:00,1872.447754,0.95,1811.544111,1941.387863,
18,downtown,2025-01-05 00:00:00+00:00,1873.626953,0.95,1808.909039,1937.349813,
19,downtown,2025-01-06 00:00:00+00:00,1871.965576,0.95,1809.499519,1936.598735,
20,downtown,2025-01-07 00:00:00+00:00,1881.656250,0.95,1817.158628,1949.754755,
21,downtown,2025-01-08 00:00:00+00:00,1881.762451,0.95,1813.375877,1941.956674,
22,downtown,2025-01-09 00:00:00+00:00,1892.604492,0.95,1825.789110,1954.575819,
23,downtown,2025-01-10 00:00:00+00:00,1888.725830,0.95,1825.259675,1950.008458,
24,downtown,2025-01-11 00:00:00+00:00,1894.459229,0.95,1831.897025,1953.610224,
25,downtown,2025-01-12 00:00:00+00:00,1891.534912,0.95,1825.475250,1949.638946,
26,downtown,2025-01-13 00:00:00+00:00,1885.354492,0.95,1817.784505,1947.135021,
27,downtown,2025-01-14 00:00:00+00:00,1876.634521,0.95,1809.144437,1942.184328,
28,suburban,2025-01-01 00:00:00+00:00,1175.815552,0.95,1120.532222,1227.895648,
29,suburban,2025-01-02 00:00:00+00:00,1183.446533,0.95,1129.103376,1238.044522,
30,suburban,2025-01-03 00:00:00+00:00,1176.831299,0.95,1123.140253,1230.767845,
31,suburban,2025-01-04 00:00:00+00:00,1179.024170,0.95,1126.901135,1236.169362,
32,suburban,2025-01-05 00:00:00+00:00,1181.783081,0.95,1126.033024,1238.123638,
33,suburban,2025-01-06 00:00:00+00:00,1191.062988,0.95,1133.080674,1252.684459,
34,suburban,2025-01-07 00:00:00+00:00,1195.940674,0.95,1130.413829,1260.915666,
35,suburban,2025-01-08 00:00:00+00:00,1196.124878,0.95,1129.088456,1260.761955,
36,suburban,2025-01-09 00:00:00+00:00,1191.865479,0.95,1125.712844,1257.790352,
37,suburban,2025-01-10 00:00:00+00:00,1187.778809,0.95,1122.053697,1254.503087,
38,suburban,2025-01-11 00:00:00+00:00,1184.727661,0.95,1115.842438,1251.225486,
39,suburban,2025-01-12 00:00:00+00:00,1189.811523,0.95,1119.831365,1254.018841,
40,suburban,2025-01-13 00:00:00+00:00,1192.992432,0.95,1122.851906,1258.551015,
41,suburban,2025-01-14 00:00:00+00:00,1190.172363,0.95,1123.845918,1257.387635,

### 5. Confidence level and TimesFM model version

Control prediction interval width and model version.

In [11]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 14,
  confidence_level => 0.99,
  model => 'TimesFM 2.0'
)
'''
client.query(query).to_dataframe()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1730.566162,0.99,1583.984786,1888.279443,
1,2025-01-02 00:00:00+00:00,1753.789307,0.99,1598.857346,1894.599494,
2,2025-01-03 00:00:00+00:00,1945.858643,0.99,1791.341821,2096.294025,
3,2025-01-04 00:00:00+00:00,2024.823608,0.99,1893.161887,2154.648858,
4,2025-01-05 00:00:00+00:00,1546.011597,0.99,1403.532029,1693.452935,
5,2025-01-06 00:00:00+00:00,1748.632812,0.99,1589.101965,1910.674116,
6,2025-01-07 00:00:00+00:00,1726.264648,0.99,1564.346513,1903.970262,
7,2025-01-08 00:00:00+00:00,1761.886963,0.99,1577.866960,1922.431117,
8,2025-01-09 00:00:00+00:00,1747.185059,0.99,1583.876268,1916.615895,
9,2025-01-10 00:00:00+00:00,1965.754150,0.99,1803.292067,2126.838824,
10,2025-01-11 00:00:00+00:00,2044.323242,0.99,1870.051603,2201.678306,
11,2025-01-12 00:00:00+00:00,1592.912964,0.99,1424.261605,1779.610987,
12,2025-01-13 00:00:00+00:00,1767.582153,0.99,1601.495226,1960.358309,
13,2025-01-14 00:00:00+00:00,1753.391357,0.99,1588.045154,1938.936475,

### 6. Forecast to a specific date

Use `forecast_end_timestamp` instead of `horizon` to forecast up to a target date. The horizon is calculated automatically from the data's frequency. Mutually exclusive with `horizon`.

In [12]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  forecast_end_timestamp => '2025-01-15'
)
'''
df = client.query(query).to_dataframe()
print(f'Forecasted {len(df)} days (through {df["forecast_timestamp"].max().strftime("%Y-%m-%d")})')
df

Forecasted 15 days (through 2025-01-15)

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1730.566162,0.95,1619.031513,1850.571145,
1,2025-01-02 00:00:00+00:00,1753.789307,0.95,1635.900648,1860.932624,
2,2025-01-03 00:00:00+00:00,1945.858643,0.95,1828.285865,2060.325828,
3,2025-01-04 00:00:00+00:00,2024.823608,0.95,1924.641414,2123.608421,
4,2025-01-05 00:00:00+00:00,1546.011597,0.95,1437.598038,1658.200596,
5,2025-01-06 00:00:00+00:00,1748.632812,0.95,1627.244833,1871.931014,
6,2025-01-07 00:00:00+00:00,1726.264648,0.95,1603.060167,1861.481917,
7,2025-01-08 00:00:00+00:00,1761.886963,0.95,1621.865038,1884.045974,
8,2025-01-09 00:00:00+00:00,1747.185059,0.95,1622.922419,1876.105999,
9,2025-01-10 00:00:00+00:00,1965.754150,0.95,1842.135776,2088.324446,
10,2025-01-11 00:00:00+00:00,2044.323242,0.95,1911.718905,2164.055655,
11,2025-01-12 00:00:00+00:00,1592.912964,0.95,1464.585132,1734.972611,
12,2025-01-13 00:00:00+00:00,1767.582153,0.95,1641.205613,1914.266688,
13,2025-01-14 00:00:00+00:00,1753.391357,0.95,1627.578438,1894.573752,
14,2025-01-15 00:00:00+00:00,1789.455322,0.95,1671.637983,1916.912615,

### 7. Setting the context window

The `context_window` controls how many historical time points the model uses to learn patterns. By default, the smallest window covering your data is auto-selected.

Supported values:
- **TimesFM 2.0:** 64, 128, 256, 512, 1024, 2048
- **TimesFM 2.5:** 64, 128, 256, 512, 1024, 2048, 4096, 8192, 15360

In [13]:
query = f'''
SELECT
  forecast_timestamp,
  ROUND(forecast_value, 0) AS forecast,
  ROUND(prediction_interval_lower_bound, 0) AS lower,
  ROUND(prediction_interval_upper_bound, 0) AS upper
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 7,
  context_window => 128
)
'''
client.query(query).to_dataframe()

         forecast_timestamp  forecast   lower   upper
0 2025-01-01 00:00:00+00:00    1783.0  1667.0  1897.0
1 2025-01-02 00:00:00+00:00    1776.0  1656.0  1887.0
2 2025-01-03 00:00:00+00:00    1965.0  1864.0  2079.0
3 2025-01-04 00:00:00+00:00    2045.0  1945.0  2141.0
4 2025-01-05 00:00:00+00:00    1623.0  1492.0  1773.0
5 2025-01-06 00:00:00+00:00    1750.0  1620.0  1896.0
6 2025-01-07 00:00:00+00:00    1753.0  1629.0  1910.0

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### Basic forecast with `%%bigquery`

In [14]:
%%bigquery --project {PROJECT_ID}

SELECT *
FROM AI.FORECAST(
  TABLE `statmike-mlops-349915.bq_ai_functions.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 7
)

Query is running:   0%|          |

Downloading:   0%|          |

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1730.566162,0.95,1619.031513,1850.571145,
1,2025-01-02 00:00:00+00:00,1753.789307,0.95,1635.900648,1860.932624,
2,2025-01-03 00:00:00+00:00,1945.858643,0.95,1828.285865,2060.325828,
3,2025-01-04 00:00:00+00:00,2024.823608,0.95,1924.641414,2123.608421,
4,2025-01-05 00:00:00+00:00,1546.011597,0.95,1437.598038,1658.200596,
5,2025-01-06 00:00:00+00:00,1748.632812,0.95,1627.244833,1871.931014,
6,2025-01-07 00:00:00+00:00,1726.264648,0.95,1603.060167,1861.481917,

---
## Examples — BigFrames

BigFrames wraps `AI.FORECAST` via `bbq.ai.forecast()`. No model object needed.

In [15]:
import bigframes.pandas as bpd
import bigframes.bigquery as bbq

bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

### Basic forecast

In [16]:
# Load the time series data
df = bpd.read_gbq(f'{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales')

# Forecast
forecast = bbq.ai.forecast(
    df,
    data_col='daily_sales',
    timestamp_col='date',
    horizon=14
)
forecast.to_pandas()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-14 00:00:00+00:00,1753.391357,0.95,1627.578438,1894.573752,
1,2025-01-03 00:00:00+00:00,1945.858643,0.95,1828.285865,2060.325828,
2,2025-01-08 00:00:00+00:00,1761.886963,0.95,1621.865038,1884.045974,
3,2025-01-10 00:00:00+00:00,1965.75415,0.95,1842.135776,2088.324446,
4,2025-01-02 00:00:00+00:00,1753.789307,0.95,1635.900648,1860.932624,
5,2025-01-09 00:00:00+00:00,1747.185059,0.95,1622.922419,1876.105999,
6,2025-01-05 00:00:00+00:00,1546.011597,0.95,1437.598038,1658.200596,
7,2025-01-04 00:00:00+00:00,2024.823608,0.95,1924.641414,2123.608421,
8,2025-01-06 00:00:00+00:00,1748.632812,0.95,1627.244833,1871.931014,
9,2025-01-13 00:00:00+00:00,1767.582153,0.95,1641.205613,1914.266688,
10,2025-01-01 00:00:00+00:00,1730.566162,0.95,1619.031513,1850.571145,
11,2025-01-11 00:00:00+00:00,2044.323242,0.95,1911.718905,2164.055655,
12,2025-01-07 00:00:00+00:00,1726.264648,0.95,1603.060167,1861.481917,
13,2025-01-12 00:00:00+00:00,1592.912964,0.95,1464.585132,1734.972611,

---
## Cleanup

Drop resources created by this notebook. Shared resources (dataset, models, connection) are left for other notebooks.

In [17]:
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales', not_found_ok=True)
print('Table ai_forecast_sales deleted')
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_forecast_multi_series', not_found_ok=True)
print('Table ai_forecast_multi_series deleted')

Table ai_forecast_sales deleted
Table ai_forecast_multi_series deleted

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [18]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')