![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fgcp-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_forecast&file=ai_forecast.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/gcp-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/gcp-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fgcp-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_forecast%2Fai_forecast.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/gcp-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/gcp-mlops/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/gcp-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/gcp-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/gcp-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/gcp-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/gcp-mlops/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/gcp-mlops/main/data%2Bai/bq-ai-functions/functions/ai_forecast/ai_forecast.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.FORECAST — BigQuery AI Functions

`AI.FORECAST` is a table-valued function that forecasts future time series values using BigQuery ML's built-in TimesFM model. No model creation or training required. Univariate forecasting is GA; multivariate forecasting and the TimesFM 3.0 model are Preview.

**When to use it:**
- You want to forecast future values from historical time series data
- You need prediction intervals (confidence bounds) for forecasts
- You want to forecast multiple independent time series at once
- You need a zero-setup forecasting solution (no CREATE MODEL)
- You can specify a target date with `forecast_end_timestamp` instead of a numeric `horizon`
- You can control how much history the model sees with `context_window` (64–15,360 on TimesFM 2.5; 64–2,048 on TimesFM 3.0)
- You have related series to forecast together, or covariates that should shape the forecast — TimesFM 3.0 (Preview) adds multivariate forecasting with `target_cols`, `past_covariate_cols` and `future_covariate_cols`

**Alternatives:**
- [`AI.DETECT_ANOMALIES`](../ai_detect_anomalies/) — Detect anomalies by comparing data against a forecast baseline
- [`AI.EVALUATE`](../ai_evaluate/) — Evaluate forecast accuracy against actual values
- [`ARIMA_PLUS`](../../../bq-ml/models/arima_plus/) — the trainable, in-BigQuery classical statistical alternative: custom holiday effects, hierarchical reconciliation across a real dimension hierarchy, decomposable and explainable components (`ML.EXPLAIN_FORECAST`), and forecast bounds — none of which the TimesFM functions expose. External regressors are no longer the dividing line: [`ARIMA_PLUS_XREG`](../../../bq-ml/models/arima_plus_xreg/) and TimesFM 3.0's covariates (section 9 below) both take them. Use `AI.FORECAST` for a fast, no-training baseline — with 3.0, a covariate-aware one; reach for `ARIMA_PLUS` when you need that level of control and explanation.
- [`ML.TREND` / `ML.SEASONALITY` / `ML.DETECT_CHANGE_POINTS`](../../../bq-ml/functions/time_series/) — model-free decomposition rather than forecasting: trend, seasonal components, and sustained structural change points, with no `CREATE MODEL` and no foundation model. Reach for these when the question is *what has this series been doing* rather than *what will it do next*.
- [`AI.CAUSAL_EFFECT`](../../../bq-ml/workflows/causal_effect/) — **the same forecasting idea aimed backwards.** It is not TimesFM: it wraps `ARIMA_PLUS`, and the sibling notebook reproduces its counterfactual bit-for-bit with a plain `CREATE MODEL ... ARIMA_PLUS`. Instead of forecasting past the end of the data, it forecasts past a point *inside* the data — the intervention date — and reports how far the observed values ran from that counterfactual. Reach for it when the question is *what would have happened without the change*, and for `AI.FORECAST` when the question is *what happens next*.

**Featured in:** [Time Series Intelligence](../../workflows/time_series_intelligence/)

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-forecast) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function doesn't require a connection or model — it uses end-user credentials automatically. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

### Setup: Create sample time series data

Generate synthetic daily sales data with realistic patterns using SQL.

In [5]:
# Create synthetic daily sales data with trend and weekly seasonality
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales` AS
WITH dates AS (
  SELECT date
  FROM UNNEST(GENERATE_DATE_ARRAY('2024-01-01', '2024-12-31')) AS date
)
SELECT
  date,
  -- Base sales + trend + weekly seasonality + noise
  GREATEST(0,
    1000
    + EXTRACT(DAYOFYEAR FROM date) * 2  -- upward trend
    + CASE EXTRACT(DAYOFWEEK FROM date)
        WHEN 1 THEN -200  -- Sunday dip
        WHEN 7 THEN 300   -- Saturday peak
        WHEN 6 THEN 200   -- Friday boost
        ELSE 0
      END
    + CAST(200 * (RAND() - 0.5) AS INT64)  -- random noise
  ) AS daily_sales
FROM dates
'''
client.query(query).result()

# Preview the data
df = client.query(f'SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales` ORDER BY date LIMIT 10').to_dataframe()
print(f'Rows: {client.query(f"SELECT COUNT(*) AS n FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`").to_dataframe().iloc[0]["n"]}')
df

Rows: 366

         date  daily_sales
0  2024-01-01         1028
1  2024-01-02         1014
2  2024-01-03         1054
3  2024-01-04          935
4  2024-01-05         1231
5  2024-01-06         1409
6  2024-01-07          779
7  2024-01-08         1101
8  2024-01-09         1062
9  2024-01-10         1050

### 1. Basic forecast

`AI.FORECAST` requires `data_col` and `timestamp_col`. Default horizon is 10 time steps.

In [6]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date'
)
'''
client.query(query).to_dataframe()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1767.150146,0.95,1637.488971,1902.589950,
1,2025-01-02 00:00:00+00:00,1737.037354,0.95,1604.912062,1878.188196,
2,2025-01-03 00:00:00+00:00,1970.917480,0.95,1827.087822,2093.408807,
3,2025-01-04 00:00:00+00:00,2035.346436,0.95,1905.369939,2156.289351,
4,2025-01-05 00:00:00+00:00,1518.659790,0.95,1380.067165,1643.081682,
5,2025-01-06 00:00:00+00:00,1745.525635,0.95,1621.220431,1861.631774,
6,2025-01-07 00:00:00+00:00,1748.203369,0.95,1620.273940,1856.405031,
7,2025-01-08 00:00:00+00:00,1759.301025,0.95,1630.555577,1876.333711,
8,2025-01-09 00:00:00+00:00,1738.738892,0.95,1617.911543,1852.598022,
9,2025-01-10 00:00:00+00:00,1974.989136,0.95,1859.134280,2086.227320,

### 2. Custom horizon

Forecast more time steps into the future.

In [7]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 30
)
'''
client.query(query).to_dataframe()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1764.908203,0.95,1642.657894,1896.012122,
1,2025-01-02 00:00:00+00:00,1736.368408,0.95,1608.546329,1873.812333,
2,2025-01-03 00:00:00+00:00,1969.156738,0.95,1826.067674,2087.921536,
3,2025-01-04 00:00:00+00:00,2036.044434,0.95,1910.480188,2155.789168,
4,2025-01-05 00:00:00+00:00,1523.827759,0.95,1386.842169,1645.103170,
5,2025-01-06 00:00:00+00:00,1747.624146,0.95,1623.921763,1862.683513,
6,2025-01-07 00:00:00+00:00,1744.736450,0.95,1618.115348,1850.601683,
7,2025-01-08 00:00:00+00:00,1757.612671,0.95,1628.933870,1874.046452,
8,2025-01-09 00:00:00+00:00,1744.158813,0.95,1626.559711,1855.787183,
9,2025-01-10 00:00:00+00:00,1966.289429,0.95,1850.202894,2076.411578,
10,2025-01-11 00:00:00+00:00,2050.304199,0.95,1925.029511,2155.562506,
11,2025-01-12 00:00:00+00:00,1539.989868,0.95,1417.304014,1670.328729,
12,2025-01-13 00:00:00+00:00,1774.837158,0.95,1645.192984,1880.613157,
13,2025-01-14 00:00:00+00:00,1760.783936,0.95,1645.528358,1866.579905,
14,2025-01-15 00:00:00+00:00,1774.244385,0.95,1653.729366,1882.362039,
15,2025-01-16 00:00:00+00:00,1751.243652,0.95,1622.407662,1879.127340,
16,2025-01-17 00:00:00+00:00,1972.249023,0.95,1856.410228,2080.614230,
17,2025-01-18 00:00:00+00:00,2052.822998,0.95,1929.785605,2176.304527,
18,2025-01-19 00:00:00+00:00,1539.658691,0.95,1416.840470,1658.088564,
19,2025-01-20 00:00:00+00:00,1775.108276,0.95,1641.391815,1873.398544,
20,2025-01-21 00:00:00+00:00,1756.679688,0.95,1655.444001,1871.177677,
21,2025-01-22 00:00:00+00:00,1777.018066,0.95,1668.058442,1879.601841,
22,2025-01-23 00:00:00+00:00,1772.345337,0.95,1643.470512,1877.996251,
23,2025-01-24 00:00:00+00:00,1991.727905,0.95,1878.348007,2107.929065,
24,2025-01-25 00:00:00+00:00,2067.301025,0.95,1949.291768,2180.059059,
25,2025-01-26 00:00:00+00:00,1557.010254,0.95,1425.660278,1667.113921,
26,2025-01-27 00:00:00+00:00,1780.172607,0.95,1665.141808,1877.291206,
27,2025-01-28 00:00:00+00:00,1775.440552,0.95,1670.847055,1874.604162,
28,2025-01-29 00:00:00+00:00,1800.029541,0.95,1679.896117,1907.636038,
29,2025-01-30 00:00:00+00:00,1775.816162,0.95,1649.209998,1886.978922,

### 3. Include historical data

Set `output_historical_time_series => TRUE` to get historical + forecasted data in one result for comparison.

In [8]:
query = f'''
SELECT *
FROM AI.FORECAST(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`
   WHERE date >= '2024-11-01'),  -- last 2 months for context
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 14,
  output_historical_time_series => TRUE
)
ORDER BY time_series_timestamp
'''
df = client.query(query).to_dataframe()
print(f'Historical rows: {(df["time_series_type"] == "history").sum()}')
print(f'Forecast rows: {(df["time_series_type"] == "forecast").sum()}')
df.tail(20)

Historical rows: 61
Forecast rows: 14

,time_series_type,time_series_timestamp,time_series_data,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
55,history,2024-12-26 00:00:00+00:00,1760.000000,NaN,NaN,NaN,None
56,history,2024-12-27 00:00:00+00:00,1903.000000,NaN,NaN,NaN,None
57,history,2024-12-28 00:00:00+00:00,2016.000000,NaN,NaN,NaN,None
58,history,2024-12-29 00:00:00+00:00,1494.000000,NaN,NaN,NaN,None
59,history,2024-12-30 00:00:00+00:00,1823.000000,NaN,NaN,NaN,None
60,history,2024-12-31 00:00:00+00:00,1819.000000,NaN,NaN,NaN,None
61,forecast,2025-01-01 00:00:00+00:00,1765.400024,0.95,1624.990524,1982.435112,
62,forecast,2025-01-02 00:00:00+00:00,1799.507080,0.95,1628.423407,2026.053493,
63,forecast,2025-01-03 00:00:00+00:00,1913.181152,0.95,1698.010910,2168.686036,
64,forecast,2025-01-04 00:00:00+00:00,2069.985596,0.95,1843.744051,2324.375200,
65,forecast,2025-01-05 00:00:00+00:00,1523.890015,0.95,1297.514623,1769.745434,
66,forecast,2025-01-06 00:00:00+00:00,1752.650269,0.95,1518.833946,1971.800192,
67,forecast,2025-01-07 00:00:00+00:00,1777.907471,0.95,1550.580329,2018.528848,
68,forecast,2025-01-08 00:00:00+00:00,1768.736328,0.95,1521.881547,1980.699408,
69,forecast,2025-01-09 00:00:00+00:00,1829.810425,0.95,1581.713216,2049.936741,
70,forecast,2025-01-10 00:00:00+00:00,1910.175781,0.95,1638.309523,2153.767580,
71,forecast,2025-01-11 00:00:00+00:00,2075.301758,0.95,1806.082031,2323.146375,
72,forecast,2025-01-12 00:00:00+00:00,1552.939209,0.95,1297.409862,1796.062041,
73,forecast,2025-01-13 00:00:00+00:00,1752.112061,0.95,1486.431789,1993.801495,
74,forecast,2025-01-14 00:00:00+00:00,1774.247314,0.95,1488.082255,2015.391790,

### 4. Multi-series forecasting with id_cols

Forecast multiple independent time series at once by specifying `id_cols`.

In [9]:
# Create multi-series data
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_multi_series` AS
WITH dates AS (
  SELECT date
  FROM UNNEST(GENERATE_DATE_ARRAY('2024-01-01', '2024-12-31')) AS date
),
stores AS (
  SELECT * FROM UNNEST([
    STRUCT('downtown' AS store_id, 1500 AS base_sales),
    STRUCT('suburban', 800),
    STRUCT('airport', 2000)
  ])
)
SELECT
  s.store_id,
  d.date,
  GREATEST(0, s.base_sales + EXTRACT(DAYOFYEAR FROM d.date) * 1 + CAST(100 * (RAND() - 0.5) AS INT64)) AS daily_sales
FROM dates d CROSS JOIN stores s
'''
client.query(query).result()
print('Multi-series data created')

Multi-series data created

In [10]:
# Forecast each store independently
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_multi_series`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  id_cols => ['store_id'],
  horizon => 14
)
ORDER BY store_id, forecast_timestamp
'''
client.query(query).to_dataframe()

,store_id,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,airport,2025-01-01 00:00:00+00:00,2365.902588,0.95,2305.631822,2423.030980,
1,airport,2025-01-02 00:00:00+00:00,2364.442871,0.95,2305.447577,2425.005619,
2,airport,2025-01-03 00:00:00+00:00,2365.255371,0.95,2304.367780,2428.374662,
3,airport,2025-01-04 00:00:00+00:00,2368.917236,0.95,2304.579982,2428.687671,
4,airport,2025-01-05 00:00:00+00:00,2374.789551,0.95,2309.577466,2436.302927,
5,airport,2025-01-06 00:00:00+00:00,2371.323486,0.95,2307.860688,2431.908264,
6,airport,2025-01-07 00:00:00+00:00,2373.277100,0.95,2306.640193,2430.315133,
7,airport,2025-01-08 00:00:00+00:00,2370.223633,0.95,2308.087831,2431.419636,
8,airport,2025-01-09 00:00:00+00:00,2369.674561,0.95,2309.925783,2429.936365,
9,airport,2025-01-10 00:00:00+00:00,2373.763672,0.95,2307.552794,2432.344889,
10,airport,2025-01-11 00:00:00+00:00,2374.780762,0.95,2314.383046,2432.749259,
11,airport,2025-01-12 00:00:00+00:00,2373.824463,0.95,2310.971020,2433.399244,
12,airport,2025-01-13 00:00:00+00:00,2376.754883,0.95,2312.239152,2435.942096,
13,airport,2025-01-14 00:00:00+00:00,2377.893555,0.95,2312.459682,2437.069568,
14,downtown,2025-01-01 00:00:00+00:00,1874.333618,0.95,1809.600205,1937.470643,
15,downtown,2025-01-02 00:00:00+00:00,1875.653809,0.95,1813.107287,1937.165129,
16,downtown,2025-01-03 00:00:00+00:00,1879.369995,0.95,1815.232876,1940.076123,
17,downtown,2025-01-04 00:00:00+00:00,1881.930908,0.95,1816.503009,1939.991443,
18,downtown,2025-01-05 00:00:00+00:00,1885.982544,0.95,1817.505427,1946.343665,
19,downtown,2025-01-06 00:00:00+00:00,1882.380127,0.95,1815.688895,1943.797544,
20,downtown,2025-01-07 00:00:00+00:00,1881.166504,0.95,1811.756120,1940.052213,
21,downtown,2025-01-08 00:00:00+00:00,1880.018066,0.95,1812.191196,1941.496718,
22,downtown,2025-01-09 00:00:00+00:00,1880.886963,0.95,1816.643615,1940.060176,
23,downtown,2025-01-10 00:00:00+00:00,1882.429565,0.95,1815.979905,1942.103853,
24,downtown,2025-01-11 00:00:00+00:00,1885.689087,0.95,1821.736791,1942.556110,
25,downtown,2025-01-12 00:00:00+00:00,1884.903809,0.95,1819.620778,1944.386178,
26,downtown,2025-01-13 00:00:00+00:00,1884.562988,0.95,1818.860464,1943.787540,
27,downtown,2025-01-14 00:00:00+00:00,1889.479736,0.95,1820.956698,1947.521789,
28,suburban,2025-01-01 00:00:00+00:00,1153.985107,0.95,1098.863266,1217.837717,
29,suburban,2025-01-02 00:00:00+00:00,1148.178589,0.95,1094.342297,1214.599307,
30,suburban,2025-01-03 00:00:00+00:00,1148.554932,0.95,1089.784599,1215.360796,
31,suburban,2025-01-04 00:00:00+00:00,1148.596191,0.95,1087.625898,1213.314106,
32,suburban,2025-01-05 00:00:00+00:00,1154.613281,0.95,1091.156643,1218.832921,
33,suburban,2025-01-06 00:00:00+00:00,1153.837158,0.95,1091.448017,1218.973818,
34,suburban,2025-01-07 00:00:00+00:00,1157.182983,0.95,1092.889602,1218.836749,
35,suburban,2025-01-08 00:00:00+00:00,1156.998169,0.95,1095.700046,1220.211172,
36,suburban,2025-01-09 00:00:00+00:00,1158.016113,0.95,1098.806497,1217.490643,
37,suburban,2025-01-10 00:00:00+00:00,1155.373657,0.95,1096.147797,1213.004807,
38,suburban,2025-01-11 00:00:00+00:00,1157.547729,0.95,1103.130456,1215.517535,
39,suburban,2025-01-12 00:00:00+00:00,1156.736572,0.95,1097.697031,1213.780953,
40,suburban,2025-01-13 00:00:00+00:00,1157.491211,0.95,1095.685478,1213.935940,
41,suburban,2025-01-14 00:00:00+00:00,1160.059082,0.95,1097.067119,1216.013376,

### 5. Confidence level and TimesFM model version

Control prediction interval width with `confidence_level`, and pin the model version with `model`.

**The default is TimesFM 2.5.** The other accepted value is `'TimesFM 3.0'` (Preview) — section 8 covers what it adds. Pin `model` whenever the numbers have to be reproducible: an unpinned call follows the default, and the default moves when Google advances it.

In [11]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 14,
  confidence_level => 0.99,
  model => 'TimesFM 2.5'
)
'''
client.query(query).to_dataframe()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1764.908203,0.99,1604.244063,1937.207959,
1,2025-01-02 00:00:00+00:00,1736.368408,0.99,1568.381720,1917.000344,
2,2025-01-03 00:00:00+00:00,1969.156738,0.99,1781.105831,2125.240140,
3,2025-01-04 00:00:00+00:00,2036.044434,0.99,1871.025043,2193.415691,
4,2025-01-05 00:00:00+00:00,1523.827759,0.99,1343.798177,1683.210666,
5,2025-01-06 00:00:00+00:00,1747.624146,0.99,1585.051657,1898.837787,
6,2025-01-07 00:00:00+00:00,1744.736450,0.99,1578.328114,1883.866950,
7,2025-01-08 00:00:00+00:00,1757.612671,0.99,1588.500060,1910.632598,
8,2025-01-09 00:00:00+00:00,1744.158813,0.99,1589.607395,1890.863358,
9,2025-01-10 00:00:00+00:00,1966.289429,0.99,1813.725861,2111.014465,
10,2025-01-11 00:00:00+00:00,2050.304199,0.99,1885.665350,2188.637063,
11,2025-01-12 00:00:00+00:00,1539.989868,0.99,1378.753324,1711.284168,
12,2025-01-13 00:00:00+00:00,1774.837158,0.99,1604.455833,1913.850385,
13,2025-01-14 00:00:00+00:00,1760.783936,0.99,1609.312430,1899.823407,

### 6. Forecast to a specific date

Use `forecast_end_timestamp` instead of `horizon` to forecast up to a target date. The horizon is calculated automatically from the data's frequency. Mutually exclusive with `horizon`.

In [12]:
query = f'''
SELECT *
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  forecast_end_timestamp => '2025-01-15'
)
'''
df = client.query(query).to_dataframe()
print(f'Forecasted {len(df)} days (through {df["forecast_timestamp"].max().strftime("%Y-%m-%d")})')
df

Forecasted 15 days (through 2025-01-15)

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1764.908203,0.95,1642.657894,1896.012122,
1,2025-01-02 00:00:00+00:00,1736.368408,0.95,1608.546329,1873.812333,
2,2025-01-03 00:00:00+00:00,1969.156738,0.95,1826.067674,2087.921536,
3,2025-01-04 00:00:00+00:00,2036.044434,0.95,1910.480188,2155.789168,
4,2025-01-05 00:00:00+00:00,1523.827759,0.95,1386.842169,1645.103170,
5,2025-01-06 00:00:00+00:00,1747.624146,0.95,1623.921763,1862.683513,
6,2025-01-07 00:00:00+00:00,1744.736450,0.95,1618.115348,1850.601683,
7,2025-01-08 00:00:00+00:00,1757.612671,0.95,1628.933870,1874.046452,
8,2025-01-09 00:00:00+00:00,1744.158813,0.95,1626.559711,1855.787183,
9,2025-01-10 00:00:00+00:00,1966.289429,0.95,1850.202894,2076.411578,
10,2025-01-11 00:00:00+00:00,2050.304199,0.95,1925.029511,2155.562506,
11,2025-01-12 00:00:00+00:00,1539.989868,0.95,1417.304014,1670.328729,
12,2025-01-13 00:00:00+00:00,1774.837158,0.95,1645.192984,1880.613157,
13,2025-01-14 00:00:00+00:00,1760.783936,0.95,1645.528358,1866.579905,
14,2025-01-15 00:00:00+00:00,1774.244385,0.95,1653.729366,1882.362039,

### 7. Setting the context window

The `context_window` controls how many of the most recent historical points the model sees. The two model versions handle it differently:

- **TimesFM 2.5** (default): 64, 128, 256, 512, 1024, 2048, 4096, 8192 or 15360. When unspecified, the smallest window covering your data is auto-selected. Any other value is rejected.
- **TimesFM 3.0**: a multiple of 32 from 64 to 2048. When unspecified, the **maximum** (2048) is used, and points older than that are ignored. A value above 2048 is rejected; a value that is not a multiple of 32 is accepted rather than rejected, so stay on the documented grid if you want to know what the model saw.

In [13]:
query = f'''
SELECT
  forecast_timestamp,
  ROUND(forecast_value, 0) AS forecast,
  ROUND(prediction_interval_lower_bound, 0) AS lower,
  ROUND(prediction_interval_upper_bound, 0) AS upper
FROM AI.FORECAST(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 7,
  context_window => 128
)
'''
client.query(query).to_dataframe()

         forecast_timestamp  forecast   lower   upper
0 2025-01-01 00:00:00+00:00    1772.0  1655.0  1906.0
1 2025-01-02 00:00:00+00:00    1740.0  1602.0  1889.0
2 2025-01-03 00:00:00+00:00    1991.0  1811.0  2152.0
3 2025-01-04 00:00:00+00:00    2076.0  1884.0  2247.0
4 2025-01-05 00:00:00+00:00    1537.0  1362.0  1686.0
5 2025-01-06 00:00:00+00:00    1772.0  1623.0  1916.0
6 2025-01-07 00:00:00+00:00    1791.0  1630.0  1922.0

### 8. TimesFM 3.0 (Preview): multivariate forecasting with `target_cols`

TimesFM 3.0 is selected with `model => 'TimesFM 3.0'`. On a single series it is a drop-in alternative to 2.5 with the same output columns, and a shorter reach: `horizon` is capped at 1,024 and the context window at 2,048 points.

What it adds is **multivariate forecasting**: pass `target_cols` (an array of column names) instead of `data_col`, and the model forecasts the series jointly. This syntax requires `model => 'TimesFM 3.0'` — with any other model, or with no `model` at all, the call fails with the generic `Invalid table-valued function AI.FORECAST`.

The output is restructured for multiple targets:
- the timestamp column **keeps its input name** (`date` here, not `forecast_timestamp`) and comes back as a `TIMESTAMP`
- each target becomes a `STRUCT<value, prediction_interval_lower_bound, prediction_interval_upper_bound>` under its own name
- `time_series_type` (`forecast`, or `history` when `output_historical_time_series => TRUE`), `confidence_level` and `ai_forecast_status` complete the row

`forecast_end_timestamp` is accepted in this form too, although the documented multivariate syntax lists only `horizon`.

First, a second table with two related daily series — sales and web visits — plus two columns that will serve as covariates in section 9. It covers 2024 as history and includes **14 future dates with the targets left NULL**; section 9 explains why.

In [14]:
# Two related daily series (sales, web visits) plus two covariates (promo flag, weekend flag).
# History: 2024. Future: 14 days with the targets NULL and the future covariates populated.
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales_mv` AS
WITH days AS (
  SELECT date,
    EXTRACT(DAYOFWEEK FROM date) AS dow,
    DATE_DIFF(date, DATE '2024-01-01', DAY) AS t
  FROM UNNEST(GENERATE_DATE_ARRAY('2024-01-01', '2025-01-14')) AS date
)
SELECT
  date,
  IF(date <= '2024-12-31', GREATEST(0,
    1000 + t * 2
    + CASE dow WHEN 1 THEN -200 WHEN 7 THEN 300 WHEN 6 THEN 200 ELSE 0 END
    + IF(MOD(t + 20, 30) < 3, 400, 0)            -- promotion lift
    + CAST(200 * (RAND() - 0.5) AS INT64)), NULL) AS daily_sales,
  IF(date <= '2024-12-31', GREATEST(0,
    5000 + t * 5
    + CASE dow WHEN 1 THEN -800 WHEN 7 THEN 1200 WHEN 6 THEN 800 ELSE 0 END
    + CAST(600 * (RAND() - 0.5) AS INT64)), NULL) AS web_visits,
  IF(MOD(t + 20, 30) < 3, 1, 0) AS promo_flag,   -- known in advance: the promotion calendar
  IF(dow IN (1, 7), 1, 0) AS is_weekend          -- known in advance: the calendar
FROM days
'''
client.query(query).result()

# The seam between history and future: targets stop, future covariates continue
df = client.query(f'''
SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales_mv`
WHERE date BETWEEN '2024-12-29' AND '2025-01-03' ORDER BY date''').to_dataframe()
df

         date  daily_sales  web_visits  promo_flag  is_weekend
0  2024-12-29         1506        5841           0           1
1  2024-12-30         1797        6597           0           0
2  2024-12-31         1708        6783           0           0
3  2025-01-01         <NA>        <NA>           0           0
4  2025-01-02         <NA>        <NA>           0           0
5  2025-01-03         <NA>        <NA>           0           0

Forecast both series jointly from the history rows. Each target comes back as its own `STRUCT`; the query below flattens the fields it wants.

In [15]:
query = f'''
SELECT
  date,
  ROUND(daily_sales.value) AS sales_forecast,
  ROUND(daily_sales.prediction_interval_lower_bound) AS sales_lower,
  ROUND(daily_sales.prediction_interval_upper_bound) AS sales_upper,
  ROUND(web_visits.value) AS visits_forecast,
  time_series_type,
  ai_forecast_status
FROM AI.FORECAST(
  (SELECT date, daily_sales, web_visits
   FROM `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales_mv`
   WHERE date <= '2024-12-31'),
  target_cols => ['daily_sales', 'web_visits'],
  timestamp_col => 'date',
  model => 'TimesFM 3.0',
  horizon => 7
)
ORDER BY date
'''
client.query(query).to_dataframe()

,date,sales_forecast,sales_lower,sales_upper,visits_forecast,time_series_type,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1753.0,1580.0,1927.0,6817.0,forecast,
1,2025-01-02 00:00:00+00:00,1753.0,1579.0,1938.0,6719.0,forecast,
2,2025-01-03 00:00:00+00:00,1938.0,1761.0,2120.0,7560.0,forecast,
3,2025-01-04 00:00:00+00:00,2107.0,1911.0,2320.0,8026.0,forecast,
4,2025-01-05 00:00:00+00:00,1821.0,1647.0,2022.0,5992.0,forecast,
5,2025-01-06 00:00:00+00:00,2074.0,1846.0,2335.0,6768.0,forecast,
6,2025-01-07 00:00:00+00:00,2027.0,1807.0,2268.0,6811.0,forecast,

### 9. Past and future covariates

Covariates are extra columns the model may use to shape the forecast. TimesFM 3.0 distinguishes two kinds by *when they are known*:

- **`past_covariate_cols`** — known only historically. Web visits influence sales, but tomorrow's visits are not known today: populated for history rows, NULL for the future rows.
- **`future_covariate_cols`** — known for the past *and* the future. The promotion calendar and the day of the week are fixed in advance: populated on every row, including the 14 future dates.

That is why the input table carries future rows with NULL targets: the future covariates have to be supplied for every timestamp you want forecast. Covariates require the `target_cols` form — `data_col` plus a covariate argument is rejected. Three things measured here that the syntax does not say:

- `horizon` is **capped by the future rows you supply** — ask for 30 with 14 future rows and you get 14, silently.
- Without `horizon`, the default of 10 applies even when more future rows are available.
- A past covariate alone, with no future rows at all, also works — it simply conditions the forecast on the history.

In [16]:
query = f'''
WITH forecast AS (
  SELECT
    date,
    ROUND(daily_sales.value) AS sales_forecast,
    ROUND(daily_sales.prediction_interval_lower_bound) AS lower,
    ROUND(daily_sales.prediction_interval_upper_bound) AS upper
  FROM AI.FORECAST(
    TABLE `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales_mv`,
    target_cols => ['daily_sales'],
    timestamp_col => 'date',
    model => 'TimesFM 3.0',
    horizon => 14,
    past_covariate_cols => ['web_visits'],
    future_covariate_cols => ['promo_flag', 'is_weekend']
  )
)
SELECT f.date, f.sales_forecast, f.lower, f.upper, c.promo_flag, c.is_weekend
FROM forecast f
JOIN `{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales_mv` c ON DATE(f.date) = c.date
ORDER BY f.date
'''
client.query(query).to_dataframe()

,date,sales_forecast,lower,upper,promo_flag,is_weekend
0,2025-01-01 00:00:00+00:00,1796.0,1639.0,1956.0,0,0
1,2025-01-02 00:00:00+00:00,1795.0,1621.0,1984.0,0,0
2,2025-01-03 00:00:00+00:00,1968.0,1790.0,2160.0,0,0
3,2025-01-04 00:00:00+00:00,2023.0,1832.0,2227.0,0,1
4,2025-01-05 00:00:00+00:00,1846.0,1647.0,2063.0,1,1
5,2025-01-06 00:00:00+00:00,2058.0,1819.0,2316.0,1,0
6,2025-01-07 00:00:00+00:00,2095.0,1792.0,2417.0,1,0
7,2025-01-08 00:00:00+00:00,1799.0,1587.0,2018.0,0,0
8,2025-01-09 00:00:00+00:00,1845.0,1634.0,2055.0,0,0
9,2025-01-10 00:00:00+00:00,2021.0,1824.0,2221.0,0,0
10,2025-01-11 00:00:00+00:00,2065.0,1874.0,2259.0,0,1
11,2025-01-12 00:00:00+00:00,1552.0,1357.0,1743.0,0,1
12,2025-01-13 00:00:00+00:00,1737.0,1547.0,1921.0,0,0
13,2025-01-14 00:00:00+00:00,1721.0,1533.0,1907.0,0,0

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### Basic forecast with `%%bigquery`

In [17]:
%%bigquery --project {PROJECT_ID}

SELECT *
FROM AI.FORECAST(
  TABLE `statmike-mlops-349915.bq_ai_functions.ai_forecast_sales`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  horizon => 7
)

Query is running:   0%|          |

Downloading:   0%|          |

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-01 00:00:00+00:00,1764.908203,0.95,1642.657894,1896.012122,
1,2025-01-02 00:00:00+00:00,1736.368408,0.95,1608.546329,1873.812333,
2,2025-01-03 00:00:00+00:00,1969.156738,0.95,1826.067674,2087.921536,
3,2025-01-04 00:00:00+00:00,2036.044434,0.95,1910.480188,2155.789168,
4,2025-01-05 00:00:00+00:00,1523.827759,0.95,1386.842169,1645.103170,
5,2025-01-06 00:00:00+00:00,1747.624146,0.95,1623.921763,1862.683513,
6,2025-01-07 00:00:00+00:00,1744.736450,0.95,1618.115348,1850.601683,

---
## Examples — BigFrames

BigFrames wraps `AI.FORECAST` via `bbq.ai.forecast()`. No model object needed. Pass `model` explicitly: the wrapper's own default is `'TimesFM 2.0'`, a version the SQL reference page no longer lists, so an unpinned wrapper call and an unpinned SQL call run different models.

In [18]:
import bigframes.pandas as bpd
import bigframes.bigquery as bbq

bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

### Basic forecast

In [19]:
# Load the time series data
df = bpd.read_gbq(f'{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales')

# Forecast
forecast = bbq.ai.forecast(
    df,
    data_col='daily_sales',
    timestamp_col='date',
    horizon=14,
    model='TimesFM 2.5'
)
forecast.to_pandas()

,forecast_timestamp,forecast_value,confidence_level,prediction_interval_lower_bound,prediction_interval_upper_bound,ai_forecast_status
0,2025-01-07 00:00:00+00:00,1744.73645,0.95,1618.115348,1850.601683,
1,2025-01-08 00:00:00+00:00,1757.612671,0.95,1628.93387,1874.046452,
2,2025-01-14 00:00:00+00:00,1760.783936,0.95,1645.528358,1866.579905,
3,2025-01-05 00:00:00+00:00,1523.827759,0.95,1386.842169,1645.10317,
4,2025-01-06 00:00:00+00:00,1747.624146,0.95,1623.921763,1862.683513,
5,2025-01-03 00:00:00+00:00,1969.156738,0.95,1826.067674,2087.921536,
6,2025-01-11 00:00:00+00:00,2050.304199,0.95,1925.029511,2155.562506,
7,2025-01-13 00:00:00+00:00,1774.837158,0.95,1645.192984,1880.613157,
8,2025-01-02 00:00:00+00:00,1736.368408,0.95,1608.546329,1873.812333,
9,2025-01-01 00:00:00+00:00,1764.908203,0.95,1642.657894,1896.012122,
10,2025-01-04 00:00:00+00:00,2036.044434,0.95,1910.480188,2155.789168,
11,2025-01-09 00:00:00+00:00,1744.158813,0.95,1626.559711,1855.787183,
12,2025-01-12 00:00:00+00:00,1539.989868,0.95,1417.304014,1670.328729,
13,2025-01-10 00:00:00+00:00,1966.289429,0.95,1850.202894,2076.411578,

---
## Cleanup

Drop resources created by this notebook. Shared resources (dataset, models, connection) are left for other notebooks.

In [20]:
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales', not_found_ok=True)
print('Table ai_forecast_sales deleted')
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_forecast_multi_series', not_found_ok=True)
print('Table ai_forecast_multi_series deleted')
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_forecast_sales_mv', not_found_ok=True)
print('Table ai_forecast_sales_mv deleted')

Table ai_forecast_sales deleted
Table ai_forecast_multi_series deleted

Table ai_forecast_sales_mv deleted

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [21]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')