![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FMLOps%2FServing%2FSQL+Inference&file=BQML+Remote+Model+on+Vertex+AI+Endpoint.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/SQL%20Inference/BQML%20Remote%20Model%20on%20Vertex%20AI%20Endpoint.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/SQL%20Inference/BQML%20Remote%20Model%20on%20Vertex%20AI%20Endpoint.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FMLOps%2FServing%2FSQL%2520Inference%2FBQML%2520Remote%2520Model%2520on%2520Vertex%2520AI%2520Endpoint.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/SQL%20Inference/BQML%20Remote%20Model%20on%20Vertex%20AI%20Endpoint.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/SQL%20Inference/BQML%20Remote%20Model%20on%20Vertex%20AI%20Endpoint.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/SQL%2520Inference/BQML%2520Remote%2520Model%2520on%2520Vertex%2520AI%2520Endpoint.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/SQL%2520Inference/BQML%2520Remote%2520Model%2520on%2520Vertex%2520AI%2520Endpoint.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/SQL%2520Inference/BQML%2520Remote%2520Model%2520on%2520Vertex%2520AI%2520Endpoint.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/SQL%2520Inference/BQML%2520Remote%2520Model%2520on%2520Vertex%2520AI%2520Endpoint.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/SQL%20Inference/BQML%20Remote%20Model%20on%20Vertex%20AI%20Endpoint.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/SQL%20Inference/BQML%20Remote%20Model%20on%20Vertex%20AI%20Endpoint.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# BQML Remote Model on Vertex AI Endpoint

Part of `vertex-ai-mlops/MLOps/Serving/Remote Models`

## Overview

This notebook shows how to deploy a sentiment analysis model to a **Vertex AI Endpoint** and then call it directly from SQL using **BigQuery ML Remote Models** with `ML.PREDICT()`. The result is a fully SQL-accessible inference pipeline — no Python required at scoring time.

## What You Will Learn

- **Cloud Resource Connection** — create and configure the BigQuery connection that authenticates to Vertex AI
- **CREATE MODEL REMOTE** — register a Vertex AI Endpoint as a BQML remote model with explicit INPUT / OUTPUT schema
- **ML.PREDICT()** — run single-row and multi-row predictions from pure SQL
- **Batch scoring patterns** — score entire tables, apply business logic, and persist results

## Prerequisites

- A Google Cloud project with billing enabled
- The following APIs enabled: BigQuery, BigQuery Connection, Vertex AI, Artifact Registry, Cloud Build
- Familiarity with BigQuery SQL basics

## What Are BQML Remote Models?

BigQuery ML remote models let BigQuery call **external prediction endpoints** during query execution. BigQuery sends rows to the endpoint via a Cloud Resource Connection and merges the returned predictions back into the query result set.

Key properties:
- Works with **any model framework** served behind a Vertex AI Endpoint (PyTorch, TensorFlow, scikit-learn, XGBoost, custom containers, etc.)
- Works with **any model size** — the model runs on the endpoint infrastructure, not inside BigQuery
- Supports `ML.PREDICT()` for inference and scheduled queries for automated batch scoring
- The connection's service account handles authentication — no keys or tokens in SQL

---
## Colab Setup

To run this notebook in Colab run the cells in this section. Otherwise, skip this section.

This cell will authenticate to GCP (follow prompts in the popup).

In [1]:
PROJECT_ID = 'statmike-mlops-349915' # replace with your project ID

In [2]:
try:
    import google.colab
    from google.colab import auth
    auth.authenticate_user()
    !gcloud config set project {PROJECT_ID}
except Exception:
    pass

---
## Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [README](readme.md) for uv setup details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [3]:
import subprocess, sys, shutil

def install(*packages):
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install(
    'google-cloud-aiplatform', 'google-cloud-storage',
    'google-cloud-artifact-registry', 'google-cloud-build',
    'google-cloud-bigquery', 'google-cloud-bigquery-connection',
    'transformers', 'torch', 'sentencepiece',
)

### API Enablement

In [4]:
!gcloud services enable bigquery.googleapis.com
!gcloud services enable bigqueryconnection.googleapis.com
!gcloud services enable aiplatform.googleapis.com
!gcloud services enable artifactregistry.googleapis.com
!gcloud services enable cloudbuild.googleapis.com

---
## Setup

inputs:

In [5]:
project = !gcloud config get-value project
PROJECT_ID = project[-1]
PROJECT_ID

'statmike-mlops-349915'

In [6]:
REGION = 'us-central1'
SERIES = 'mlops'
EXPERIMENT = 'bqml-remote-model'

GCS_BUCKET = PROJECT_ID
AR_REPO = 'mlops-serving'  # Artifact Registry Docker repo

BQ_DATASET = f'{SERIES}_{EXPERIMENT.replace("-", "_")}'
BQ_LOCATION = 'US'
ENDPOINT_DISPLAY_NAME = f'{SERIES}-{EXPERIMENT}'

In [7]:
project_number = !gcloud projects describe {PROJECT_ID} --format='value(projectNumber)'
PROJECT_NUMBER = project_number[0]
PROJECT_NUMBER

'1026793852137'

packages:

In [8]:
import json, os, time, tempfile, subprocess

from transformers import AutoModelForSequenceClassification, AutoTokenizer

import google.auth
from google.cloud import storage
from google.cloud import artifactregistry_v1
from google.cloud.devtools import cloudbuild_v1
from google.cloud import aiplatform
from google.cloud import bigquery
from google.cloud.bigquery_connection_v1 import ConnectionServiceClient, types

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/aiplatform/models.py:52: FutureWarning: Support for google-cloud-storage < 3.0.0 will be removed in a future version of google-cloud-aiplatform. Please upgrade to google-cloud-storage >= 3.0.0.
  from google.cloud.aiplatform.utils import gcs_utils

clients:

In [9]:
gcs = storage.Client(project = PROJECT_ID)
bucket = gcs.bucket(GCS_BUCKET)

cb = cloudbuild_v1.CloudBuildClient()

ar = artifactregistry_v1.ArtifactRegistryClient()

aiplatform.init(project = PROJECT_ID, location = REGION)

bq = bigquery.Client(project = PROJECT_ID, location = 'US')

conn_client = ConnectionServiceClient()

Parameters:

In [10]:
DIR = f"files/{EXPERIMENT}"
if not os.path.exists(DIR + '/source/app'):
    os.makedirs(DIR + '/source/app')

---
## Download HuggingFace Models

Download two sentiment analysis models from HuggingFace and upload them to GCS. Both models are fine-tuned on the [SST-2](https://huggingface.co/datasets/stanfordnlp/sst2) dataset for binary sentiment classification (POSITIVE/NEGATIVE).

- **v1 (DistilBERT):** Smaller, faster — good for initial deployment
- **v2 (BERT):** Larger, more accurate — uploaded to GCS for further experimentation

In [11]:
MODELS = {
    'v1': {
        'hub_name': 'distilbert-base-uncased-finetuned-sst-2-english',
        'display_name': 'distilbert-sst2',
    },
    'v2': {
        'hub_name': 'textattack/bert-base-uncased-SST-2',
        'display_name': 'bert-sst2',
    },
}

In [12]:
for version, info in MODELS.items():
    gcs_prefix = f'{SERIES}/{EXPERIMENT}/models/{version}'

    # check if already uploaded
    existing = list(bucket.list_blobs(prefix=gcs_prefix, max_results=1))
    if existing:
        print(f'{version} ({info["hub_name"]}) already in GCS at gs://{GCS_BUCKET}/{gcs_prefix}')
        continue

    print(f'Downloading {version}: {info["hub_name"]} ...')
    with tempfile.TemporaryDirectory() as tmpdir:
        model = AutoModelForSequenceClassification.from_pretrained(info['hub_name'])
        tokenizer = AutoTokenizer.from_pretrained(info['hub_name'])
        model.save_pretrained(tmpdir)
        tokenizer.save_pretrained(tmpdir)

        # upload to GCS
        for root, dirs, files in os.walk(tmpdir):
            for fname in files:
                local_path = os.path.join(root, fname)
                blob_name = f'{gcs_prefix}/{os.path.relpath(local_path, tmpdir)}'
                bucket.blob(blob_name).upload_from_filename(local_path)
        print(f'  Uploaded to gs://{GCS_BUCKET}/{gcs_prefix}')

    # store the GCS URI
    info['artifact_uri'] = f'gs://{GCS_BUCKET}/{gcs_prefix}'

# set artifact_uri for any that were already uploaded
for version, info in MODELS.items():
    if 'artifact_uri' not in info:
        info['artifact_uri'] = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/models/{version}'

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Downloading v1: distilbert-base-uncased-finetuned-sst-2-english ...

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 1239.61it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.74s/it]

  Uploaded to gs://statmike-mlops-349915/mlops/bqml-remote-model/models/v1
Downloading v2: textattack/bert-base-uncased-SST-2 ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15073.67it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.80s/it]

  Uploaded to gs://statmike-mlops-349915/mlops/bqml-remote-model/models/v2

In [13]:
for version, info in MODELS.items():
    blobs = list(bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/models/{version}'))
    print(f'{version} ({info["display_name"]}): {len(blobs)} files at {info["artifact_uri"]}')

v1 (distilbert-sst2): 4 files at gs://statmike-mlops-349915/mlops/bqml-remote-model/models/v1
v2 (bert-sst2): 4 files at gs://statmike-mlops-349915/mlops/bqml-remote-model/models/v2

---
## Build and Deploy Container

This section builds a lightweight **FastAPI** custom container for the sentiment model. The same container pattern is used throughout the MLOps/Serving/Online series.

The container:
1. Downloads the model from GCS at startup
2. Exposes `/health` and `/predict` routes expected by Vertex AI
3. Accepts `{"instances": [{"text": "..."}]}` and returns `{"predictions": [{"label": "...", "score": 0.99}]}`

In [14]:
%%writefile {DIR}/source/Dockerfile
FROM python:3.11-slim

COPY ./app /app
COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

ENV AIP_HEALTH_ROUTE=/health
ENV AIP_PREDICT_ROUTE=/predict
ENV AIP_HTTP_PORT=8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

Writing files/bqml-remote-model/source/Dockerfile

In [15]:
%%writefile {DIR}/source/app/main.py
import os, json, tempfile
from fastapi import FastAPI, Request
from google.cloud import storage
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import torch

app = FastAPI()

# ── Load model at startup ──────────────────────────────────────────
MODEL_DIR = tempfile.mkdtemp()
ARTIFACT_URI = os.environ.get('AIP_STORAGE_URI', '')

if ARTIFACT_URI:
    # Download from GCS
    client = storage.Client()
    prefix = ARTIFACT_URI.replace('gs://', '').split('/', 1)
    bucket = client.bucket(prefix[0])
    blobs = bucket.list_blobs(prefix=prefix[1] if len(prefix) > 1 else '')
    for blob in blobs:
        dest = os.path.join(
            MODEL_DIR,
            os.path.relpath(blob.name, prefix[1] if len(prefix) > 1 else ''),
        )
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        blob.download_to_filename(dest)

model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR)
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
model.eval()
LABELS = list(model.config.id2label.values())


# ── Routes ──────────────────────────────────────────────────────────
@app.get(os.environ.get('AIP_HEALTH_ROUTE', '/health'), status_code=200)
def health():
    return {}


@app.post(os.environ.get('AIP_PREDICT_ROUTE', '/predict'))
async def predict(request: Request):
    body = await request.json()
    instances = body['instances']

    texts = [inst['text'] if isinstance(inst, dict) else inst for inst in instances]

    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')
    with torch.no_grad():
        logits = model(**inputs).logits
    probs = torch.softmax(logits, dim=-1)
    scores, indices = probs.max(dim=-1)

    predictions = []
    for score, idx in zip(scores, indices):
        predictions.append({
            'label': LABELS[idx.item()],
            'score': round(score.item(), 6),
        })
    return {'predictions': predictions}

Writing files/bqml-remote-model/source/app/main.py

In [16]:
%%writefile {DIR}/source/requirements.txt
fastapi
uvicorn[standard]
google-cloud-storage
transformers
torch
sentencepiece

Writing files/bqml-remote-model/source/requirements.txt

In [17]:
IMAGE_NAME = f'{EXPERIMENT}'
IMAGE_URI = f'{REGION}-docker.pkg.dev/{PROJECT_ID}/{AR_REPO}/{IMAGE_NAME}'

# Ensure Artifact Registry repo exists
try:
    ar.get_repository(
        name=f'projects/{PROJECT_ID}/locations/{REGION}/repositories/{AR_REPO}'
    )
    print(f'AR repo already exists: {AR_REPO}')
except Exception:
    ar.create_repository(
        parent=f'projects/{PROJECT_ID}/locations/{REGION}',
        repository=artifactregistry_v1.Repository(
            format_=artifactregistry_v1.Repository.Format.DOCKER,
        ),
        repository_id=AR_REPO,
    )
    print(f'Created AR repo: {AR_REPO}')

# Upload source to GCS
import tarfile, io

buf = io.BytesIO()
with tarfile.open(fileobj=buf, mode='w:gz') as tar:
    tar.add(f'{DIR}/source', arcname='.')
buf.seek(0)

blob = bucket.blob(f'{SERIES}/{EXPERIMENT}/source.tar.gz')
blob.upload_from_file(buf, content_type='application/gzip')
print(f'Uploaded source to gs://{GCS_BUCKET}/{blob.name}')

# Build with Cloud Build
build = cloudbuild_v1.Build(
    source=cloudbuild_v1.Source(
        storage_source=cloudbuild_v1.StorageSource(
            bucket=GCS_BUCKET,
            object_=f'{SERIES}/{EXPERIMENT}/source.tar.gz',
        )
    ),
    images=[IMAGE_URI],
    steps=[
        cloudbuild_v1.BuildStep(
            name='gcr.io/cloud-builders/docker',
            args=['build', '-t', IMAGE_URI, '.'],
        ),
    ],
)

op = cb.create_build(project_id=PROJECT_ID, build=build)
print(f'Build started: {op.metadata.build.id}')
result = op.result()
print(f'Build finished: {result.status.name}')

AR repo already exists: mlops-serving
Uploaded source to gs://statmike-mlops-349915/mlops/bqml-remote-model/source.tar.gz
Build started: 65c8b8e0-4bfb-4400-9a98-9142c9ece225
Build finished: SUCCESS

In [18]:
# Upload model to Vertex AI Model Registry (v1 and v2)
for version, info in MODELS.items():
    model_display = f'{SERIES}-{EXPERIMENT}-{info["display_name"]}'
    model = aiplatform.Model.upload(
        display_name=model_display,
        serving_container_image_uri=IMAGE_URI,
        artifact_uri=info['artifact_uri'],
        serving_container_health_route='/health',
        serving_container_predict_route='/predict',
        serving_container_ports=[8080],
    )
    info['model_resource'] = model.resource_name
    print(f'Uploaded {version}: {model.display_name} -> {model.resource_name}')

# Create endpoint
endpoint = aiplatform.Endpoint.create(
    display_name=ENDPOINT_DISPLAY_NAME,
)
print(f'Created endpoint: {endpoint.display_name} -> {endpoint.resource_name}')

# Deploy v1 model
v1_model = aiplatform.Model(MODELS['v1']['model_resource'])
endpoint.deploy(
    model=v1_model,
    deployed_model_display_name=f'{EXPERIMENT}-v1',
    machine_type='n1-standard-4',
    min_replica_count=1,
    max_replica_count=1,
)
print(f'Deployed v1 model to endpoint')

Creating Model
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/4934395979714527232/operations/8912374185095856128
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/4934395979714527232/operations/8912374185095856128
Model created. Resource name: projects/1026793852137/locations/us-central1/models/4934395979714527232@1
To use this Model in another session:
model = aiplatform.Model('projects/1026793852137/locations/us-central1/models/4934395979714527232@1')
Uploaded v1: mlops-bqml-remote-model-distilbert-sst2 -> projects/1026793852137/locations/us-central1/models/4934395979714527232
Creating Model
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/876652715453710336/operations/8162947059603734528
Model created. Resource name: projects/1026793852137/locations/us-central1/models/876652715453710336@1
To use this Model in another session:
model = aiplatform.Model('projects/1026793852137/locations/us-central1/models/876652715453710336@1')
Uploaded v2: mlops-bqml-remote-model-bert-sst2 -> projects/1026793852137/locations/us-central1/models/876652715453710336
Creating Endpoint
Create Endpoint backing LRO: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616/operations/5854852250576355328
Endpoint created. Resource name: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
To use this Endpoint in another session:
endpoint = aiplatform.Endpoint('projects/1026793852137/locations/us-central1/endpoints/1368373556848623616')
Created endpoint: mlops-bqml-remote-model -> projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Deploying Model projects/1026793852137/locations/us-central1/models/4934395979714527232 to Endpoint : projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Deploy Endpoint model backing LRO: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616/operations/6684077531965947904
Endpoint model deployed. Resource name: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Deployed v1 model to endpoint

In [19]:
# Test the endpoint
test_instances = [{'text': t} for t in [
    'This movie is absolutely wonderful and I loved every minute of it!',
    'The food was terrible and the service was even worse.',
    'An average experience, nothing special but not bad either.',
]]

response = endpoint.predict(instances=test_instances)
for inst, pred in zip(test_instances, response.predictions):
    print(f'  "{inst["text"][:60]}"')
    print(f'    => {pred["label"]} (score: {pred["score"]})')
    print()

  "This movie is absolutely wonderful and I loved every minute "
    => POSITIVE (score: 0.999887)

  "The food was terrible and the service was even worse."
    => NEGATIVE (score: 0.999793)

  "An average experience, nothing special but not bad either."
    => POSITIVE (score: 0.859378)

---
## BigQuery Cloud Resource Connection

A **Cloud Resource Connection** is how BigQuery authenticates to external services like Vertex AI.

When you create a connection, BigQuery provisions a dedicated Google-managed service account. This service account is what actually calls the Vertex AI Endpoint on behalf of your SQL queries. You grant it the minimum permissions needed — in this case, `roles/aiplatform.user` so it can invoke predictions.

Key points:
- The connection is region-scoped (we use `US` to match BigQuery dataset location)
- The service account is automatically managed — no keys to rotate
- A single connection can be reused across multiple remote models

In [21]:
connection = types.Connection(
    cloud_resource=types.CloudResourceProperties(),
)

parent = f'projects/{PROJECT_ID}/locations/{BQ_LOCATION}'
connection_id = f'{SERIES}_{EXPERIMENT.replace("-", "_")}'

try:
    conn = conn_client.get_connection(name=f'{parent}/connections/{connection_id}')
    print(f'Connection already exists: {conn.name}')
except Exception:
    conn = conn_client.create_connection(
        parent=parent,
        connection_id=connection_id,
        connection=connection,
    )
    print(f'Created connection: {conn.name}')

CONNECTION_SA = conn.cloud_resource.service_account_id
print(f'Connection service account: {CONNECTION_SA}')

Created connection: projects/1026793852137/locations/us/connections/mlops_bqml_remote_model
Connection service account: bqcx-1026793852137-2ley@gcp-sa-bigquery-condel.iam.gserviceaccount.com

In [ ]:
!gcloud projects add-iam-policy-binding {PROJECT_ID} \
    --member=serviceAccount:{CONNECTION_SA} \
    --role=roles/aiplatform.user \
    --condition=None \
    --quiet

# IAM policy changes can take up to 60 seconds to propagate
import time
print('Waiting 60s for IAM propagation...')
time.sleep(60)
print('Done')

> **Note:** The 60-second wait above ensures the IAM binding has propagated before the next cell creates the remote model. If `CREATE MODEL` still fails with a permission error, re-run it after another minute.

---
## Register Remote Model in BigQuery

The `CREATE MODEL ... REMOTE WITH CONNECTION` statement registers a Vertex AI Endpoint as a BQML model. After this step, any BigQuery user with access to the model can run predictions with plain SQL.

The `INPUT` and `OUTPUT` clauses define the schema contract between BigQuery and the endpoint:
- **INPUT** — the columns BigQuery will send as the `instances` payload
- **OUTPUT** — the fields BigQuery expects in each element of the `predictions` response

In [25]:
# Create dataset if needed
dataset = bigquery.Dataset(f'{PROJECT_ID}.{BQ_DATASET}')
dataset.location = BQ_LOCATION
bq.create_dataset(dataset, exists_ok=True)
print(f'Dataset ready: {BQ_DATASET}')

ENDPOINT_RESOURCE = endpoint.resource_name
print(f'Endpoint resource: {ENDPOINT_RESOURCE}')

# Create remote model
create_model_sql = f"""
CREATE OR REPLACE MODEL `{BQ_DATASET}.sentiment_remote`
INPUT (text STRING)
OUTPUT (label STRING, score FLOAT64)
REMOTE WITH CONNECTION `{PROJECT_ID}.{BQ_LOCATION}.{connection_id}`
OPTIONS (
    endpoint = 'https://{REGION}-aiplatform.googleapis.com/v1/{ENDPOINT_RESOURCE}'
)
"""
print(create_model_sql)
bq.query(create_model_sql).result()
print('Remote model created')

Dataset ready: mlops_bqml_remote_model
Endpoint resource: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616

CREATE OR REPLACE MODEL `mlops_bqml_remote_model.sentiment_remote`
INPUT (text STRING)
OUTPUT (label STRING, score FLOAT64)
REMOTE WITH CONNECTION `statmike-mlops-349915.US.mlops_bqml_remote_model`
OPTIONS (
    endpoint = 'https://us-central1-aiplatform.googleapis.com/v1/projects/1026793852137/locations/us-central1/endpoints/1368373556848623616'
)

Remote model created

### INPUT / OUTPUT Schema Mapping

The schema you declare in `CREATE MODEL` must match what the endpoint expects and returns:

| Direction | BQML Declaration | Endpoint JSON |
|-----------|-----------------|---------------|
| INPUT | `text STRING` | `{"instances": [{"text": "..."}]}` |
| OUTPUT | `label STRING, score FLOAT64` | `{"predictions": [{"label": "POSITIVE", "score": 0.99}]}` |

BigQuery automatically wraps each row's input columns into an element of the `instances` array and unpacks each element of `predictions` back into output columns.

---
## Run Predictions with ML.PREDICT()

`ML.PREDICT()` is the SQL function that sends rows to the remote model and returns predictions. It works like any other table-valued function — you can wrap it in `SELECT`, `JOIN`, `WHERE`, `GROUP BY`, etc.

In [30]:
query = f"""
SELECT *
FROM ML.PREDICT(
    MODEL `{BQ_DATASET}.sentiment_remote`,
    (SELECT 'This movie is absolutely wonderful!' AS text)
)
"""
bq.query(query).result().to_dataframe()

      label     score remote_model_status                                 text
0  POSITIVE  0.999877                None  This movie is absolutely wonderful!

In [31]:
query = f"""
SELECT *
FROM ML.PREDICT(
    MODEL `{BQ_DATASET}.sentiment_remote`,
    (
        SELECT text
        FROM UNNEST([
            'This movie is absolutely wonderful!',
            'The food was terrible and the service was even worse.',
            'An average experience, nothing special but not bad either.',
            'I can\\'t believe how great this product is — highly recommend!',
            'Worst purchase I have ever made. Total waste of money.'
        ]) AS text
    )
)
"""
bq.query(query).result().to_dataframe()

,label,score,remote_model_status,text
0,POSITIVE,0.999877,None,This movie is absolutely wonderful!
1,NEGATIVE,0.999793,None,The food was terrible and the service was even...
2,POSITIVE,0.859377,None,"An average experience, nothing special but not..."
3,POSITIVE,0.999843,None,I can't believe how great this product is — hi...
4,NEGATIVE,0.999794,None,Worst purchase I have ever made. Total waste o...

In [32]:
# Create a test table with review text
create_table_sql = f"""
CREATE OR REPLACE TABLE `{BQ_DATASET}.reviews` AS
SELECT *
FROM UNNEST([
    STRUCT('rev-001' AS review_id, 'electronics' AS category, 'Absolutely love this phone, best purchase ever!' AS text),
    STRUCT('rev-002', 'electronics', 'Screen broke after one week. Very disappointed.'),
    STRUCT('rev-003', 'food', 'The chocolate cake was divine, will order again.'),
    STRUCT('rev-004', 'food', 'Arrived stale and the packaging was damaged.'),
    STRUCT('rev-005', 'travel', 'Beautiful hotel with stunning ocean views.'),
    STRUCT('rev-006', 'travel', 'Flight was delayed 6 hours with no communication.'),
    STRUCT('rev-007', 'electronics', 'Does exactly what it says. Good value for the price.'),
    STRUCT('rev-008', 'food', 'Tastes okay but nothing special for the price.'),
    STRUCT('rev-009', 'travel', 'Friendly staff but the room was a bit small.'),
    STRUCT('rev-010', 'electronics', 'Returned it immediately. Completely unusable.')
])
"""
bq.query(create_table_sql).result()
print(f'Created table {BQ_DATASET}.reviews with 10 rows')

Created table mlops_bqml_remote_model.reviews with 10 rows

In [33]:
# Score the reviews table and add business logic
score_sql = f"""
CREATE OR REPLACE TABLE `{BQ_DATASET}.scored_reviews` AS
SELECT
    r.review_id,
    r.category,
    r.text,
    p.label AS sentiment,
    p.score AS confidence,
    CASE
        WHEN p.label = 'NEGATIVE' AND p.score > 0.95 THEN 'URGENT'
        WHEN p.label = 'NEGATIVE' THEN 'REVIEW'
        ELSE 'OK'
    END AS action
FROM ML.PREDICT(
    MODEL `{BQ_DATASET}.sentiment_remote`,
    (SELECT review_id, category, text FROM `{BQ_DATASET}.reviews`)
) p
JOIN `{BQ_DATASET}.reviews` r USING (review_id, category, text)
ORDER BY p.score DESC
"""
bq.query(score_sql).result()

# Display results
bq.query(f'SELECT * FROM `{BQ_DATASET}.scored_reviews` ORDER BY action, confidence DESC').result().to_dataframe()

,review_id,category,text,sentiment,confidence,action
0,rev-005,travel,Beautiful hotel with stunning ocean views.,POSITIVE,0.999873,OK
1,rev-001,electronics,"Absolutely love this phone, best purchase ever!",POSITIVE,0.999858,OK
2,rev-007,electronics,Does exactly what it says. Good value for the ...,POSITIVE,0.999783,OK
3,rev-003,food,"The chocolate cake was divine, will order again.",POSITIVE,0.999450,OK
4,rev-004,food,Arrived stale and the packaging was damaged.,NEGATIVE,0.999811,URGENT
5,rev-002,electronics,Screen broke after one week. Very disappointed.,NEGATIVE,0.999681,URGENT
6,rev-006,travel,Flight was delayed 6 hours with no communication.,NEGATIVE,0.999147,URGENT
7,rev-010,electronics,Returned it immediately. Completely unusable.,NEGATIVE,0.996556,URGENT
8,rev-009,travel,Friendly staff but the room was a bit small.,NEGATIVE,0.995244,URGENT
9,rev-008,food,Tastes okay but nothing special for the price.,NEGATIVE,0.962117,URGENT

### Remote Model vs Model Import (ONNX)

| Aspect | Remote Model (this notebook) | BQML Model Import (ONNX) |
|--------|------------------------------|--------------------------|
| **Where model runs** | Vertex AI Endpoint (your infrastructure) | Inside BigQuery (Google-managed) |
| **Model size** | Any size | < 250 MB (ONNX limit) |
| **Framework** | Any (PyTorch, TF, custom) | Must export to ONNX |
| **Latency** | Network round-trip to endpoint | In-process, very fast |
| **Cost** | Endpoint compute + BQ query | BQ query only (on-demand slots) |
| **Best for** | Large models, GPU inference, existing endpoints | Small models, high-throughput batch scoring |

---
## Cleanup

Remove the resources created in this notebook to avoid ongoing charges.

In [34]:
# Drop remote model
bq.query(f'DROP MODEL IF EXISTS `{BQ_DATASET}.sentiment_remote`').result()
print('Dropped remote model')

# Drop test tables
bq.query(f'DROP TABLE IF EXISTS `{BQ_DATASET}.reviews`').result()
bq.query(f'DROP TABLE IF EXISTS `{BQ_DATASET}.scored_reviews`').result()
print('Dropped test tables')

# Drop dataset (only if empty)
bq.delete_dataset(f'{PROJECT_ID}.{BQ_DATASET}', delete_contents=True, not_found_ok=True)
print(f'Deleted dataset {BQ_DATASET}')

Dropped remote model
Dropped test tables
Deleted dataset mlops_bqml_remote_model

In [35]:
# Undeploy all models and delete endpoint
endpoints = aiplatform.Endpoint.list(filter=f'display_name="{ENDPOINT_DISPLAY_NAME}"')
for ep in endpoints:
    ep.undeploy_all()
    ep.delete()
    print(f'Deleted endpoint: {ep.display_name}')

Undeploying Endpoint model: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Undeploy Endpoint model backing LRO: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616/operations/8672064923729133568
Endpoint model undeployed. Resource name: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Deleting Endpoint : projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Endpoint deleted. . Resource name: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Deleting Endpoint resource: projects/1026793852137/locations/us-central1/endpoints/1368373556848623616
Delete Endpoint backing LRO: projects/1026793852137/locations/us-central1/operations/7794988896298729472
Endpoint resource projects/1026793852137/locations/us-central1/endpoints/1368373556848623616 deleted.
Deleted endpoint: mlops-bqml-remote-model

In [36]:
# Delete models from Vertex AI Model Registry
for version, info in MODELS.items():
    if 'model_resource' in info:
        m = aiplatform.Model(info['model_resource'])
        m.delete()
        print(f'Deleted model: {info["display_name"]}')

Deleting Model : projects/1026793852137/locations/us-central1/models/4934395979714527232
Model deleted. . Resource name: projects/1026793852137/locations/us-central1/models/4934395979714527232
Deleting Model resource: projects/1026793852137/locations/us-central1/models/4934395979714527232
Delete Model backing LRO: projects/1026793852137/locations/us-central1/models/4934395979714527232/operations/3340928864829308928
Model resource projects/1026793852137/locations/us-central1/models/4934395979714527232 deleted.
Deleted model: distilbert-sst2
Deleting Model : projects/1026793852137/locations/us-central1/models/876652715453710336
Model deleted. . Resource name: projects/1026793852137/locations/us-central1/models/876652715453710336
Deleting Model resource: projects/1026793852137/locations/us-central1/models/876652715453710336
Delete Model backing LRO: projects/1026793852137/locations/us-central1/models/876652715453710336/operations/313384015329492992
Model resource projects/1026793852137/locations/us-central1/models/876652715453710336 deleted.
Deleted model: bert-sst2

### Remove GCS Artifacts (Optional)

Uncomment to remove the model artifacts and source files from GCS.

In [37]:
# # Remove model artifacts and source files from GCS
# for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/'):
#     blob.delete()
# print(f'Removed gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/')

In [38]:
# Delete the BigQuery connection
parent = f'projects/{PROJECT_ID}/locations/{BQ_LOCATION}'
connection_id = f'{SERIES}_{EXPERIMENT.replace("-", "_")}'
try:
    conn_client.delete_connection(name=f'{parent}/connections/{connection_id}')
    print(f'Deleted connection: {connection_id}')
except Exception as e:
    print(f'Connection delete skipped: {e}')

Deleted connection: mlops_bqml_remote_model