![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_generate_int&file=ai_generate_int.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_generate_int%2Fai_generate_int.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_generate_int/ai_generate_int.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.GENERATE_INT — BigQuery AI Functions

`AI.GENERATE_INT` is a scalar function that returns a STRUCT containing an INT64 value per row. Use it for integer estimation, counting, and classification with numeric labels.

**When to use it:**
- You need integer outputs (counts, labels, ratings on integer scale)
- You want full control over model and parameters
- You need response metadata (full_response, status)

**Alternatives:**
- [`AI.GENERATE_DOUBLE`](../ai_generate_double/) — FLOAT64 output for continuous numeric values
- [`AI.GENERATE_BOOL`](../ai_generate_bool/) — BOOL output for true/false questions
- [`AI.GENERATE`](../ai_generate/) — Full control with output_schema for any structured output

**Multimodal:** Supports document, image, and video input via [ObjectRef](../../reference/unstructured-data-infrastructure.md#objectref-and-objectrefruntime-schema-reference). Pass a STRUCT prompt with `ObjectRef` fields to extract integer values from unstructured data.

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-generate-int) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function doesn't require a connection or model for SQL usage — it uses end-user credentials automatically. BigFrames requires a connection, so we reference the shared one here. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection (used by BigFrames)
BUCKET = PROJECT_ID  # GCS bucket (same name as project)

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes', 'google-cloud-storage')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

### 1. Numeric fact retrieval

`AI.GENERATE_INT` returns a STRUCT with `result` (INT64), `full_response` (JSON), and `status` (STRING).

In [5]:
query = """
SELECT
  country,
  (AI.GENERATE_INT(
    CONCAT('How many states or provinces does ', country, ' have? Return just the number.')
  )).result AS num_divisions
FROM UNNEST(['United States', 'Canada', 'Brazil', 'India', 'Australia']) AS country
"""
client.query(query).to_dataframe()

         country  num_divisions
0         Brazil             26
1  United States             50
2          India             28
3         Canada             10
4      Australia              8

### 2. Integer scoring

Rate items on an integer scale.

In [6]:
query = """
SELECT
  review,
  (AI.GENERATE_INT(
    CONCAT('Rate this product review on a scale of 1 to 5 stars: ', review)
  )).result AS stars
FROM UNNEST([
  'Best purchase I have made this year!',
  'Complete waste of money.',
  'Decent product, does what it says.',
  'Exceeded my expectations in every way!',
  'Not great, not terrible.'
]) AS review
ORDER BY stars DESC
"""
client.query(query).to_dataframe()

                                   review  stars
0    Best purchase I have made this year!      5
1  Exceeded my expectations in every way!      5
2                Not great, not terrible.      3
3      Decent product, does what it says.      3
4                Complete waste of money.      1

### 3. Counting and estimation

In [7]:
query = """
SELECT
  sentence,
  (AI.GENERATE_INT(
    CONCAT('How many words are in this sentence? Just the number: ', sentence)
  )).result AS word_count
FROM UNNEST([
  'The quick brown fox jumps over the lazy dog.',
  'Hello world.',
  'BigQuery is a fully managed enterprise data warehouse.'
]) AS sentence
"""
client.query(query).to_dataframe()

                                                 sentence  word_count
0            The quick brown fox jumps over the lazy dog.           9
1  BigQuery is a fully managed enterprise data warehouse.           8
2                                            Hello world.           2

### 4. With endpoint

In [8]:
query = """
SELECT
  element,
  (AI.GENERATE_INT(
    CONCAT('What is the atomic number of ', element, '?'),
    endpoint => 'gemini-2.5-flash'
  )).result AS atomic_number
FROM UNNEST(['Hydrogen', 'Carbon', 'Oxygen', 'Iron', 'Gold']) AS element
"""
client.query(query).to_dataframe()

    element  atomic_number
0    Oxygen              8
1    Carbon              6
2      Gold             79
3  Hydrogen              1
4      Iron             26

---
## Examples — Multimodal with ObjectRef

`AI.GENERATE_INT` can analyze documents, images, and video stored in Cloud Storage. Build the reference with `OBJ.MAKE_REF` and pass it in a STRUCT prompt:

```
OBJ.MAKE_REF(uri, connection)   → ObjectRef — pass this straight to the function
```

The STRUCT replaces the STRING prompt. `OBJ.FETCH_METADATA` (content type and size) and `OBJ.GET_ACCESS_URL` (a signed `ObjectRefRuntime` URL) still have their uses — displaying an object, delegated access, an explicit TTL — but the AI functions take the `ObjectRef` itself. See the [ObjectRef reference](../../reference/unstructured-data-infrastructure.md#objectref-and-objectrefruntime-schema-reference) for details.

In [9]:
import subprocess as _sp, json as _json
from google.cloud import storage as _storage
from pathlib import Path

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant required roles
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
for role in ['roles/aiplatform.user', 'roles/storage.objectViewer']:
    _sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
             f'--member=serviceAccount:{sa}', f'--role={role}', '--quiet'],
            capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

# Upload invoice for the multimodal example
_gcs = _storage.Client(project=PROJECT_ID)
_bucket = _gcs.bucket(BUCKET)
_prefix = 'bq_ai_functions/ai_generate_int'

_data = Path('../../data/documents')
if not _data.exists():
    _data = Path('data/documents')

blob = _bucket.blob(f'{_prefix}/invoice_001.pdf')
if not blob.exists():
    blob.upload_from_filename(str(_data / 'invoices' / 'invoice_001.pdf'))
    print(f'Uploaded invoice_001.pdf → gs://{BUCKET}/{_prefix}/invoice_001.pdf')
else:
    print(f'Already exists: gs://{BUCKET}/{_prefix}/invoice_001.pdf')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

Uploaded invoice_001.pdf → gs://statmike-mlops-349915/bq_ai_functions/ai_generate_int/invoice_001.pdf

### 5. Count items in a document

Pass a document via ObjectRef in a STRUCT prompt to extract an integer value.

In [10]:
query = f"""
SELECT
  (AI.GENERATE_INT(
    STRUCT(
      'How many line items are on this invoice?' AS prompt,
      [OBJ.MAKE_REF(
        'gs://{BUCKET}/bq_ai_functions/ai_generate_int/invoice_001.pdf',
        '{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}'
      )] AS object_refs
    )
  )).result AS line_item_count
"""
client.query(query).to_dataframe()

   line_item_count
0                3

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### AI.GENERATE_INT with `%%bigquery`

In [11]:
%%bigquery --project {PROJECT_ID}

SELECT
  country,
  (AI.GENERATE_INT(
    CONCAT('How many official languages does ', country, ' have?')
  )).result AS num_languages
FROM UNNEST(['Switzerland', 'Canada', 'India', 'Japan']) AS country

Query is running:   0%|          |

Downloading:   0%|          |

       country  num_languages
0       Canada              2
1  Switzerland              4
2        Japan              1
3        India             22

---
## Examples — BigFrames

BigFrames wraps `AI.GENERATE_INT` via `bbq.ai.generate_int()`. Returns a Series of structs.

In [12]:
import bigframes.pandas as bpd
import bigframes.bigquery as bbq

bpd.close_session()  # Reset session to apply connection settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION
bpd.options.bigquery.bq_connection = f'{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}'

### Integer estimation

In [13]:
df = bpd.DataFrame({'element': ['Hydrogen', 'Carbon', 'Oxygen', 'Iron', 'Gold']})

df['response'] = bbq.ai.generate_int(('What is the atomic number of ', df['element'], '?'))
df['atomic_number'] = df['response'].struct.field('result')
df[['element', 'atomic_number']].to_pandas()

    element  atomic_number
0  Hydrogen              1
1    Carbon              6
2    Oxygen              8
3      Iron             26
4      Gold             79

---
## Cleanup

Remove GCS files uploaded for the multimodal examples. Shared resources (dataset, models, connection) are left for other notebooks.

In [14]:
# Delete GCS files uploaded for multimodal examples
from google.cloud import storage

gcs_client = storage.Client(project=PROJECT_ID)
bucket = gcs_client.bucket(BUCKET)
prefix = 'bq_ai_functions/ai_generate_int/'

blobs = list(bucket.list_blobs(prefix=prefix))
for blob in blobs:
    blob.delete()
    print(f'Deleted gs://{BUCKET}/{blob.name}')
if not blobs:
    print('No GCS files to clean up')

Deleted gs://statmike-mlops-349915/bq_ai_functions/ai_generate_int/invoice_001.pdf

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [15]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')