![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_count_tokens&file=ai_count_tokens.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_count_tokens%2Fai_count_tokens.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_count_tokens/ai_count_tokens.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.COUNT_TOKENS — BigQuery AI Functions

`AI.COUNT_TOKENS` is a **utility scalar function** that estimates the number of **input tokens** in a text prompt. Token counting happens inside BigQuery and **incurs no Vertex AI charges** — so you can use it freely to size prompts and estimate cost *before* calling the paid generative functions.

**When to use it:**
- Estimate the cost of an `AI.GENERATE` / `AI.GENERATE_TABLE` job before running it
- Check prompts against a model's input token limit
- Compare prompt sizes across rows, templates, or models

**Alternatives / companions:**
- [`AI.GENERATE`](../ai_generate/) — the generation function whose default model this uses when no `endpoint` is given
- Actual per-query token usage (input + thinking + output) appears in the **Job information** tab of the Query results pane

**Note:** `AI.COUNT_TOKENS` counts **input** tokens only — not thinking or output tokens.

**Text only (Preview):** the input must be a `STRING` — multimodal/ObjectRef prompts are not accepted (verified 2026-07-17), so `full_response` always reports `modality: "TEXT"`. This is a Preview function; multimodal support should be re-evaluated at GA.

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-count-tokens) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, and authenticate.

> `AI.COUNT_TOKENS` needs no connection and no model — it uses your end-user credentials and counts tokens inside BigQuery. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'bigframes')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

---
## Examples — SQL

Progressive examples from simplest to most advanced. `AI.COUNT_TOKENS(INPUT [, endpoint => ENDPOINT])` returns a `STRUCT<result INT64, full_response JSON>`.

### 1. Simplest call — count tokens in a literal string

`.result` is the integer token count. Token count isn't the same as word count.

In [5]:
query = """
SELECT AI.COUNT_TOKENS("Token count isn't always equal to word count.").result AS num_tokens
"""
client.query(query).to_dataframe()

   num_tokens
0          11

### 2. Understand the full output — `result` + `full_response`

`AI.COUNT_TOKENS` returns a `STRUCT` with two fields. Use `.*` to see both, and use `JSON_*` extractors to pull apart `full_response`:

- **`result`** (INT64) — the total input token count
- **`full_response`** (JSON) — `totalTokens` plus a `promptTokensDetails` array giving the token count per input `modality` (always `TEXT` for this text-only function)

In [6]:
query = """
SELECT
  ct.result AS num_tokens,
  ct.full_response AS full_response,
  INT64(ct.full_response.totalTokens) AS total_tokens,
  STRING(ct.full_response.promptTokensDetails[0].modality) AS modality,
  INT64(ct.full_response.promptTokensDetails[0].tokenCount) AS modality_token_count
FROM (
  SELECT AI.COUNT_TOKENS('Summarize the quarterly earnings report.') AS ct
)
"""
client.query(query).to_dataframe()

,num_tokens,full_response,total_tokens,modality,modality_token_count
0,7,"{""promptTokensDetails"":[{""modality"":""TEXT"",""tokenCount"":7}],""totalTokens"":7}",7,TEXT,7

### 3. Count tokens over a table column

Apply it per row to real text — here, public IMDB movie reviews.

In [7]:
query = """
SELECT
  review,
  AI.COUNT_TOKENS(review).result AS num_tokens
FROM `bigquery-public-data.imdb.reviews`
LIMIT 5
"""
client.query(query).to_dataframe()

,review,num_tokens
0,"Ik know it is impossible to keep all details of a book in a movie. But this movie has changed nearly everything without any reason. Furthermore many changes have made the story illogical. A few examples: 1) in the movie ""Paul Renauld"" really meets Poriot before he dies (in the book Poirot only gets a letter), telling him he is afraid to be killed. This is completely stupid because if Renaulds plan would have succeeded, Poirot would have known that the dead man would not have been Renauld.(Poirot was in the morgue when Mrs Renauld identified the victim). 2) The movie has ""combined"" two persons into one! ""Cinderella"" has been removed by the movie. The girl Hastings falls in love with and the ex-girlfriend of Jack Renauld are one person in the movie! Why for god's sake? 3)Hastings finds the victims cause he is such a bad golf player. Totally unfunny and stupid. 4) The movie tells secrets much too early (for example at the very beginning). So you know things you shouldn't know. 5) The murderer gets shot at the end by a person who doesn't exists in the book. Perhaps because the person (""cinderella"") who stops the murderer does not exists in the movie. 6)The book is very complex. The movie takes only about 90 minutes. Sure it is difficult to include all the necessary details but it is impossible if you include stupid things which were not in the book and have no meaning (e.g. bicycle race).",324
1,"""The Racketeer"" stars Carol (deprived of the ""e"" that usually appeared at the end of her first name) Lombard as a woman thrown out of society because she left her husband for a concert violinist (Roland Drew) who has since become a down-and-out alcoholic, and torn between her love for him and the interest of New York crime kingpin Robert Armstrong (top-billed). It's virtually a compendium of what was wrong with the earliest talkies: stiff direction, immobile cameras, stagy acting and ridiculously slow-paced delivery of lines. At the time the sound crews were telling the directors to have their actors speak every line s-l-o-w-l-y and not to start speaking their own line until after the previous actor had finished theirs. Done about five years later, this could have been an interesting movie, but director Howard Higgin faithfully follows his sound recorder's dictates and systematically undercuts the talents we know Lombard and Armstrong had from watching their later movies. ""The Racketeer"" was made in 1929, a year that despite the transition problems from silent to sound nonetheless gave us some legitimate masterpieces — Vidor's ""Hallelujah!,"" Mamoulian's ""Applause,"" Wyler's ""Hell's Heroes,"" Capra's ""Ladies of Leisure"" — all from directors with strong enough wills to tell the soundboard dictators to get stuffed and let their actors talk and act naturalistically. Too bad Howard Higgin wasn't that strong; as it is, watching a naturally rapid-paced actor like Armstrong slog through the part in the ridiculous way he's been told to speak, one can't help but wonder where that 50-foot gorilla is when Armstrong needs him.",365
2,"This one and the one prior ""Toulon's Revenge"" and the next one seem to be completely different from the first two movies where the puppets were not so nice. It is basically choose your series, the first two go together and paint the puppets as killers, while the next three are a series of them being the good guys. This one plays out to much like some cheesy television series episode to be as good as part three was and I never really had the urge to try and watch part five of the series. Basically, a kid gets the puppets while some strange dark lord or something sends his evil puppets out to kill, this dark lord looks like some sort of enemy from one of those live action Japanese shows like Ultraman. The movie is over before you know it though so it has to get credit for not inflicting you with a very painful to watch movie. Just to many plot holes and things in it for it to be considered an okay movie. You do get to see the guy who played Toulon in the last movie though then you have a very anti-climatic battle and wham the movie is over before it really begins.",230
3,"Unless you're interested in seeing 2 hours worth of scenic mountain footage featuring hysterical characters, lots of histrionics and cheap 70s gore (not much of it either), I would advise to avoid this movie. It is long winded, overlong and has a rather annoying amateurish feel to it. Masterpiece? No, an average thriller, shot in an average fashion, in a gorgeous Italian landscape. I'm a huge fan of slow paced 1970 movies, when there is a plot to delight and entertain you. In this case, it didn't work out for me. The plot is trite, interlaced with superficial and stereotypical characters, backed by hilarious angry mobs and your typical Italian widow dressed all in black, sobbing.If you are not acquainted and familiar with the Italy country side, the movie might be worth seeing as the scenery itself is spectacular and rather breathtaking. This movie isn't however, nothing out of the ordinary, there are much better Italian horror flicks than this. Not much else than a yawn fest. 5/10",223
4,"Yes, thats that i felt after i completed watching this movie. The acting is below-average and the special effects are horrible. In fact, the worst i have ever seen. It is a very low budget movie. There is no way this movie will can scare you, it has no creepy or scary moments. Mr. bone eater was more of a funny creature for me. It could have been much better but oh well they didn't had a big budget. The movie fails to convince you that you are watching a horror movie, lol. I would name this movie The Time Eater (waster). I am sure you would have a lot of better movies/etc to watch. Still watch it if: 1. you have nothing else to watch. 2. you get to watch it for free. Not worth renting at all.",170

### 4. Specify a model endpoint

`endpoint` selects which model's tokenizer rules to use. If omitted, the default model used by `AI.GENERATE` is used.

In [8]:
query = """
SELECT
  review,
  AI.COUNT_TOKENS(review, endpoint => 'gemini-2.5-pro').result AS num_tokens
FROM `bigquery-public-data.imdb.reviews`
LIMIT 5
"""
client.query(query).to_dataframe()

,review,num_tokens
0,"Ik know it is impossible to keep all details of a book in a movie. But this movie has changed nearly everything without any reason. Furthermore many changes have made the story illogical. A few examples: 1) in the movie ""Paul Renauld"" really meets Poriot before he dies (in the book Poirot only gets a letter), telling him he is afraid to be killed. This is completely stupid because if Renaulds plan would have succeeded, Poirot would have known that the dead man would not have been Renauld.(Poirot was in the morgue when Mrs Renauld identified the victim). 2) The movie has ""combined"" two persons into one! ""Cinderella"" has been removed by the movie. The girl Hastings falls in love with and the ex-girlfriend of Jack Renauld are one person in the movie! Why for god's sake? 3)Hastings finds the victims cause he is such a bad golf player. Totally unfunny and stupid. 4) The movie tells secrets much too early (for example at the very beginning). So you know things you shouldn't know. 5) The murderer gets shot at the end by a person who doesn't exists in the book. Perhaps because the person (""cinderella"") who stops the murderer does not exists in the movie. 6)The book is very complex. The movie takes only about 90 minutes. Sure it is difficult to include all the necessary details but it is impossible if you include stupid things which were not in the book and have no meaning (e.g. bicycle race).",324
1,"""The Racketeer"" stars Carol (deprived of the ""e"" that usually appeared at the end of her first name) Lombard as a woman thrown out of society because she left her husband for a concert violinist (Roland Drew) who has since become a down-and-out alcoholic, and torn between her love for him and the interest of New York crime kingpin Robert Armstrong (top-billed). It's virtually a compendium of what was wrong with the earliest talkies: stiff direction, immobile cameras, stagy acting and ridiculously slow-paced delivery of lines. At the time the sound crews were telling the directors to have their actors speak every line s-l-o-w-l-y and not to start speaking their own line until after the previous actor had finished theirs. Done about five years later, this could have been an interesting movie, but director Howard Higgin faithfully follows his sound recorder's dictates and systematically undercuts the talents we know Lombard and Armstrong had from watching their later movies. ""The Racketeer"" was made in 1929, a year that despite the transition problems from silent to sound nonetheless gave us some legitimate masterpieces — Vidor's ""Hallelujah!,"" Mamoulian's ""Applause,"" Wyler's ""Hell's Heroes,"" Capra's ""Ladies of Leisure"" — all from directors with strong enough wills to tell the soundboard dictators to get stuffed and let their actors talk and act naturalistically. Too bad Howard Higgin wasn't that strong; as it is, watching a naturally rapid-paced actor like Armstrong slog through the part in the ridiculous way he's been told to speak, one can't help but wonder where that 50-foot gorilla is when Armstrong needs him.",365
2,"This one and the one prior ""Toulon's Revenge"" and the next one seem to be completely different from the first two movies where the puppets were not so nice. It is basically choose your series, the first two go together and paint the puppets as killers, while the next three are a series of them being the good guys. This one plays out to much like some cheesy television series episode to be as good as part three was and I never really had the urge to try and watch part five of the series. Basically, a kid gets the puppets while some strange dark lord or something sends his evil puppets out to kill, this dark lord looks like some sort of enemy from one of those live action Japanese shows like Ultraman. The movie is over before you know it though so it has to get credit for not inflicting you with a very painful to watch movie. Just to many plot holes and things in it for it to be considered an okay movie. You do get to see the guy who played Toulon in the last movie though then you have a very anti-climatic battle and wham the movie is over before it really begins.",230
3,"Unless you're interested in seeing 2 hours worth of scenic mountain footage featuring hysterical characters, lots of histrionics and cheap 70s gore (not much of it either), I would advise to avoid this movie. It is long winded, overlong and has a rather annoying amateurish feel to it. Masterpiece? No, an average thriller, shot in an average fashion, in a gorgeous Italian landscape. I'm a huge fan of slow paced 1970 movies, when there is a plot to delight and entertain you. In this case, it didn't work out for me. The plot is trite, interlaced with superficial and stereotypical characters, backed by hilarious angry mobs and your typical Italian widow dressed all in black, sobbing.If you are not acquainted and familiar with the Italy country side, the movie might be worth seeing as the scenery itself is spectacular and rather breathtaking. This movie isn't however, nothing out of the ordinary, there are much better Italian horror flicks than this. Not much else than a yawn fest. 5/10",223
4,"Yes, thats that i felt after i completed watching this movie. The acting is below-average and the special effects are horrible. In fact, the worst i have ever seen. It is a very low budget movie. There is no way this movie will can scare you, it has no creepy or scary moments. Mr. bone eater was more of a funny creature for me. It could have been much better but oh well they didn't had a big budget. The movie fails to convince you that you are watching a horror movie, lol. I would name this movie The Time Eater (waster). I am sure you would have a lot of better movies/etc to watch. Still watch it if: 1. you have nothing else to watch. 2. you get to watch it for free. Not worth renting at all.",170

### 5. Estimate cost/size before a batch AI job

Because counting is free, aggregate token counts across a column to size a workload *before* running the paid generation functions over it.

In [9]:
query = """
WITH counts AS (
  SELECT AI.COUNT_TOKENS(review).result AS tokens
  FROM `bigquery-public-data.imdb.reviews`
  LIMIT 100
)
SELECT
  COUNT(*) AS num_documents,
  SUM(tokens) AS total_input_tokens,
  ROUND(AVG(tokens), 1) AS avg_tokens_per_doc,
  MAX(tokens) AS max_tokens
FROM counts
"""
client.query(query).to_dataframe()

   num_documents  total_input_tokens  avg_tokens_per_doc  max_tokens
0            100               29848               298.5        1199

---
## Examples — `%%bigquery` Magics

The same call using IPython magics — SQL directly in the cell.

### Count tokens with `%%bigquery`

In [10]:
%%bigquery --project {PROJECT_ID}

SELECT
  review,
  AI.COUNT_TOKENS(review).result AS num_tokens
FROM `bigquery-public-data.imdb.reviews`
LIMIT 5

Query is running:   0%|          |

Downloading:   0%|          |

,review,num_tokens
0,"This tale of the upper-classes getting their come-uppance and wallowing in their high-class misery is like a contemporary Mid-Sommerish version of an old Joan Crawford movie in which she suffered in mink. Here, people behave in a frightfully civilized manner in the face of adversity. A well-heeled London solicitor, (Tom Wilkinson), discovers that not only is his wife having an affair with the local gentry but that she has also killed their housekeeper's husband in a hit-and-run accident. He throws up, but otherwise his stiff-upper-lip hardly quavers.Written and directed by Julian Fellowes, who won an Oscar for writing ""Gosford Park"", (this is his directorial debut), from a novel by Nigel Balchin, it's quite comical although I am not sure how much of the comedy is intended. It's like a throw-back to British films of the forties where characters all behaved like characters in books or plays rather than like people might in real life. However, it's not all bad. Wilkinson is terrific, even if you never believe in him as a person while Emily Watson, (the adulterous wife), and Rupert Everett, (the highly amoral high-class totty), are both very good at covering the cracks in the material. Tony Pierce-Roberts' cinematography ensures that no matter how hard it is on the ear it's always good on the eye.",294
1,"Where on earth do I start with the mess that is Darkhunters? Firstly the script is one of the worst to ever find its way onto a cinema or TV screen and can only be described as a poorly judged Stephen King rip-off. At one point the supposedly fearsome darkhunter Jack claims that Carol, the girl who is helping the man he is pursuing, is as annoying as ""a gherkin in a burger"". I would be laughing if I was making it up-BUT I'M NOT! Just as ludicrous is how Carol originally came to have the power to see how people die. A cat gave it to her when she was holding it during an auto accident she had as a kid. WHAT????????Secondly, for a horror movie, it has no sense of tension or threat whatsoever. This may not be helped by the fact that all the action happens during stark, broad daylight. Not very atmospheric at all.Thirdly the acting is truly awful, Pinion proves again that he needs to be speaking in his native tongue to be even remotely believable. Jeff Fahey is obviously on auto-pilot but how can blame him as he runs through a woe-ful Humphry Bogart impersonation as Barlow (Marlowe-Barlow? We get the joke it just isn't funny). Credit should go to Susan Paterno, an actress I was not aware of, she does her best with the awful part she has and puts the other, more experienced actors to shame.At no point is it even explained how the HUMAN character can understand what Van Husen's character is saying to her. She obviously has some sort of degree in screwy alien languages.On the plus side one moment is well done, the car crash involving Susan. The sfx are throughly believable and if it weren't for the hilarious storyline reason for this to occur it would have been applauded.All I can say about darkhunters is that British horror will never recover from its interminable slump if movies like this continue to be made and shown. Avoid this movie like the plague, although the plague would be a lot more scary.Darkhunters 0/5p.s. the insinuations in other reviews that the film remains too intelligent for some are honestly hilarious. It is a weak defence when some claim ""you didn't like it because you didn't understand it"". The letters after my name make a fool of you not me.",491
2,"First of all, I really can't understand how some people ""enjoyed"" this movie. It's the worst thing I have ever seen. Even the actors seem to be bored...and I think that says it all!However, I have to give my applause to the opening credits creators - that team seems to have a really good future. That's why I recommend the big studios to watch ONLY the opening credits, and one or two special effects sequences (if they're watched outside this movie, it almost looks like a good movie).Better luck (or judgment) next time for the producers of this, this... this ""thing!"".",132
3,"My wife spotted this film on the aisle at a local video store. From the cover it looked like a science-fiction film, but upon turning it over my wife saw Rebecca St. James was in the film, realized it was a Christian movie, and suggested we watch it. We are conservative evangelicals but we also know that ""Christian"" films have a poor reputation in the mainstream. Nevertheless, we decided to give it a screening.To be fair, there were a few things I liked about the film. The musical score - much of which was orchestrated - was quite good. The cinematography was also pretty good considering it was a lower-budget movie.Unfortunately, any virtue in this film's production work was lost on a regrettable script. The film begins with an interesting premise - UFO abductions - but by midway through the feature the storyline veers wildly into an evangelistic crusade spearheaded by the movie's two main characters... which then veers wildly into a treatise on the Rapture. At least the Frank Peretti-inspired ""The Visitation"" (which was itself a deeply flawed film) had an endgame that tied together the movie's premise. ""Unidentified"" ends nowhere even close to where it started, which is a huge letdown.As for the acting? The supporting acting ranges from decent to awful. (Rebecca St. James plays a bit part and is passable.) For their part, a few of the main characters are manned capably enough. Sadly, their talents are wasted on characters so one-dimensional in their personalities so as to be unbelievable. The ""protagonists"" are anything but; you know it's bad when two Christian viewers find the most vocal Christian character in the film to be the most annoying.A final note on the evangelistic tone of this movie, which will be of more interest to Christian than non-Christian readers. In a word, it is embarrassing. Other Christian films like Carmen's ""The Champion"" and Peretti's ""The Hangman's Curse"" have managed to communicate a genuinely uncompromising portrait of the Christian faith without sounding preachy or oppressive. This film, by contrast, is a sledgehammer that feels so heavy-handed and lacking in tact that a non-Christian would have a hard time taking it seriously.I do believe that the filmmaker's heart is in the right place, and I applaud efforts to create good Christian film. Unfortunately, this is not one of them. If your church is looking for a screening of a good Christian film, consider ""Mercy Streets,"" the aforementioned ""The Champion,"" or (if you're Pentecostal) Robert Duvall's provocative ""The Apostle."" As for ""Unidentified?"" Rent it if you must, but screen it before you show it to a non-Christian or a larger audience.",574
4,"This movie should have come with a disclaimer that it was akin to the Left Behind series. I did not know it would be a Bible-thumping movie. I expected it to truly be a movie about UFOs and alien abduction for entertainment's sake. As previous reviewer comments, it would be fine to show at a church, but not at a public theater, at least not without the consumer's prior knowledge of what the premise of the movie is about. I felt deceived out of my $$ spent for this movie, as nothing in the summary refers to its religious overtones. If you go to church, it'll probably be shown there for free some time. Other than the cover-up of its true subject matter, the movie was fine as far as acting and script were concerned. But I have to say I walked out an hour into the movie when I saw what direction it was headed and that I was not going to be entertained, but preached to.",197

---
## Examples — BigFrames

There is no native BigFrames API for `AI.COUNT_TOKENS` yet. Use `session.read_gbq_query()` to run the SQL and return a BigFrames DataFrame.

In [11]:
import bigframes.pandas as bpd

bpd.close_session()  # Reset session to apply project/location settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

In [12]:
query = f"""
SELECT
  review,
  AI.COUNT_TOKENS(review).result AS num_tokens
FROM `bigquery-public-data.imdb.reviews`
LIMIT 5
"""
bpd.read_gbq_query(query)

                                              review  num_tokens
0  This tale of the upper-classes getting their c...         294
1  Where on earth do I start with the mess that i...         491
2  First of all, I really can't understand how so...         132
3  My wife spotted this film on the aisle at a lo...         574
4  This movie should have come with a disclaimer ...         197

[5 rows x 2 columns]

---
## Cleanup

This notebook creates no tables, models, or GCS objects — `AI.COUNT_TOKENS` is a read-only scalar function — so there is nothing to clean up.