![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Fworkflows%2Fdocument_intelligence&file=document_intelligence.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Fworkflows%2Fdocument_intelligence%2Fdocument_intelligence.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/document_intelligence/document_intelligence.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Document Intelligence — BigQuery AI Functions

An end-to-end document processing pipeline that composes four AI functions:

1. **Classify** 100 mixed documents by type with `AI.CLASSIFY`
2. **Extract** key fields from documents with `AI.GENERATE` (multimodal + output_schema)
3. **Score** document quality with `AI.SCORE`
4. **Summarize** findings with `AI.GENERATE` (and alternatively with `AI.AGG`)

**What this demonstrates:**
- Processing real documents (PDFs) from Cloud Storage — not generated sample data
- Three multimodal call shapes — a bare `ObjectRef` argument, a STRUCT prompt, and tuple syntax — all fed by the object table's `ref` column
- Composing classification → extraction → scoring → summarization in one pipeline
- Validating AI classification accuracy against ground truth
- Comparing manual aggregation (`STRING_AGG` + `AI.GENERATE`) vs purpose-built `AI.AGG`

**Functions used:** [`AI.CLASSIFY`](../../functions/ai_classify/) | [`AI.GENERATE`](../../functions/ai_generate/) | [`AI.SCORE`](../../functions/ai_score/) | [`AI.AGG`](../../functions/ai_agg/)

**For specialized document parsing:** See [`ML.PROCESS_DOCUMENT`](../../functions/ml_process_document/) for Document AI integration

**Prerequisites:** [Setup guide](../../setup/) | [Function reference](../../RESOURCES.md)

---
## Setup

Set your project and location, authenticate, and create shared resources.

> This workflow uses `AI.CLASSIFY`, `AI.GENERATE`, and `AI.SCORE` — none require a remote model. A connection is needed for the object table and GCS access. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection
BUCKET = PROJECT_ID  # GCS bucket (same name as project)

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'google-cloud-storage')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

In [5]:
import subprocess as _sp, json as _json

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant required roles
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
for role in ['roles/aiplatform.user', 'roles/storage.objectViewer']:
    _sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
             f'--member=serviceAccount:{sa}', f'--role={role}', '--quiet'],
            capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

---
## Step 1 — Upload documents to GCS

Upload 100 mixed documents (50 invoices + 50 receipts) to Cloud Storage using generic filenames (`doc_001.pdf`–`doc_100.pdf`). The filenames deliberately reveal nothing about document type — classification must examine the actual content.

The mapping from source files to generic names comes from `data/documents/manifest.json`, which also provides ground truth for validation.

In [6]:
import json
from pathlib import Path
from google.cloud import storage
from tqdm.auto import tqdm

# Load manifest
data_dir = Path('../../data/documents')
if not data_dir.exists():
    data_dir = Path('data/documents')

with open(data_dir / 'manifest.json') as f:
    manifest = json.load(f)

# Upload documents with generic names
gcs = storage.Client(project=PROJECT_ID)
bucket = gcs.bucket(BUCKET)
prefix = 'bq_ai_functions/document_intelligence'

uploaded, skipped = 0, 0
for doc_name, info in tqdm(manifest.items(), desc='Uploading documents'):
    blob = bucket.blob(f'{prefix}/{doc_name}')
    if blob.exists():
        skipped += 1
        continue
    # Map source file to the correct subdirectory
    subdir = 'invoices' if info['type'] == 'invoice' else 'receipts'
    source_path = data_dir / subdir / info['source']
    blob.upload_from_filename(str(source_path))
    uploaded += 1

print(f'Uploaded {uploaded} documents, skipped {skipped} (already exist)')
print(f'Location: gs://{BUCKET}/{prefix}/')

Uploading documents:   0%|          | 0/100 [00:00<?, ?it/s]

Uploaded 100 documents, skipped 0 (already exist)
Location: gs://statmike-mlops-349915/bq_ai_functions/document_intelligence/

---
## Step 1b — Create object table

An [object table](../../reference/unstructured-data-infrastructure.md) is an external table over Cloud Storage objects. It provides a `ref` column that AI functions can use to access file content. The connection grants BigQuery permission to read from GCS.

In [7]:
# Create object table pointing to the uploaded documents
client.query(f"""
CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_di_docs`
WITH CONNECTION `{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}`
OPTIONS (
  object_metadata = 'SIMPLE',
  uris = ['gs://{BUCKET}/{prefix}/*.pdf']
)
""").result()
print('Object table workflow_di_docs ready')

# Verify
verify = client.query(f"""
  SELECT uri, content_type, size
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_docs`
  ORDER BY uri LIMIT 5
""").to_dataframe()
total = client.query(f"""
  SELECT COUNT(*) AS total FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_docs`
""").to_dataframe()
print(f'Total documents: {total.iloc[0]["total"]}')
verify

Object table workflow_di_docs ready

Total documents: 100

,uri,content_type,size
0,gs://statmike-mlops-349915/bq_ai_functions/document_intelligence/doc_001.pdf,application/pdf,10297
1,gs://statmike-mlops-349915/bq_ai_functions/document_intelligence/doc_002.pdf,application/pdf,15093
2,gs://statmike-mlops-349915/bq_ai_functions/document_intelligence/doc_003.pdf,application/pdf,22278
3,gs://statmike-mlops-349915/bq_ai_functions/document_intelligence/doc_004.pdf,application/pdf,10650
4,gs://statmike-mlops-349915/bq_ai_functions/document_intelligence/doc_005.pdf,application/pdf,15126

---
## Step 2 — Classify documents with AI.CLASSIFY

Use `AI.CLASSIFY` to classify each document as "invoice" or "receipt". The object table's `ref` column is an `ObjectRef`, which is the input type the function takes — pass it straight in.

```
Object table → ref → AI.CLASSIFY
```

In [8]:
query = f"""
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified` AS
SELECT
  docs.uri,
  AI.CLASSIFY(docs.ref, ['invoice', 'receipt']) AS doc_type
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_docs` AS docs
"""
client.query(query).result()

# Show distribution
dist = client.query(f"""
  SELECT doc_type, COUNT(*) AS count
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified`
  GROUP BY doc_type
  ORDER BY doc_type
""").to_dataframe()
total = dist['count'].sum()
print(f'AI.CLASSIFY examined the PDF content of all {total} documents.')
print(f'No filenames, metadata, or hints — classification is based purely on visual content.\n')
print('Classification distribution:')
for _, row in dist.iterrows():
    print(f'  {row["doc_type"]}: {row["count"]} documents')
print(f'\nResults saved to workflow_di_classified — next: validate against ground truth.')

AI.CLASSIFY examined the PDF content of all 100 documents.
No filenames, metadata, or hints — classification is based purely on visual content.

Classification distribution:
  invoice: 50 documents
  receipt: 50 documents

Results saved to workflow_di_classified — next: validate against ground truth.

---
## Step 3 — Validate classification accuracy

Compare `AI.CLASSIFY` results against the ground truth in `manifest.json`. This is unique among workflows — we have known labels to measure how well the AI function performs on real documents.

In [9]:
# Create ground truth DataFrame
ground_truth = pd.DataFrame([
    {'doc_name': k, 'true_type': v['type']}
    for k, v in manifest.items()
])

# Get classification results
classified = client.query(f"""
  SELECT uri, doc_type FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified`
""").to_dataframe()

# Extract doc name from URI for joining
classified['doc_name'] = classified['uri'].str.split('/').str[-1]

# Join and compute accuracy
merged = classified.merge(ground_truth, on='doc_name')
accuracy = (merged['doc_type'] == merged['true_type']).mean()
print(f'Classification accuracy: {accuracy:.1%}')

# Confusion matrix
print(f'\nConfusion matrix:')
print(pd.crosstab(merged['true_type'], merged['doc_type'], margins=True))

# Show any misclassifications
misclassified = merged[merged['doc_type'] != merged['true_type']]
if len(misclassified) > 0:
    print(f'\n{len(misclassified)} misclassified documents:')
    print(misclassified[['doc_name', 'true_type', 'doc_type']].to_string(index=False))
else:
    print(f'\nPerfect classification — all {len(merged)} documents correctly identified!')

Classification accuracy: 100.0%

Confusion matrix:
doc_type   invoice  receipt  All
true_type
invoice         50        0   50
receipt          0       50   50
All             50       50  100

Perfect classification — all 100 documents correctly identified!

---
## Step 4 — Extract key fields with AI.GENERATE

Use `AI.GENERATE` with the **STRUCT prompt** pattern and `output_schema` to extract structured data from a 10-document sample. The prompt adapts based on `doc_type` — invoices and receipts have different key fields.

```
AI.GENERATE(
  STRUCT(prompt AS prompt, [ref] AS object_refs),
  output_schema => '...'
)
```

> Processing 10 documents as a sample. Adjust the `LIMIT` to process more.

In [10]:
query = f"""
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_di_extracted` AS
SELECT
  c.uri,
  c.doc_type,
  result.*
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified` c
JOIN `{PROJECT_ID}.{DATASET_ID}.workflow_di_docs` ot ON c.uri = ot.uri
CROSS JOIN UNNEST([AI.GENERATE(
  STRUCT(
    CASE c.doc_type
      WHEN 'invoice' THEN 'Extract from this invoice: the company/vendor name, invoice number, total amount due, and due date.'
      WHEN 'receipt' THEN 'Extract from this receipt: the store name, receipt/transaction number, total amount, and purchase date.'
    END AS prompt,
    [ot.ref] AS object_refs
  ),
  output_schema => 'entity_name STRING, reference_number STRING, total_amount STRING, document_date STRING'
)]) AS result
WHERE c.uri IN (
  SELECT uri FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified`
  ORDER BY uri LIMIT 10
)
"""
client.query(query).result()

# Display results with doc names
extracted = client.query(f"""
  SELECT
    SPLIT(uri, '/')[SAFE_OFFSET(ARRAY_LENGTH(SPLIT(uri, '/')) - 1)] AS doc_name,
    doc_type, entity_name, reference_number, total_amount, document_date
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_extracted`
  ORDER BY doc_type, entity_name
""").to_dataframe()

n_inv = (extracted['doc_type'] == 'invoice').sum()
n_rec = (extracted['doc_type'] == 'receipt').sum()
print(f'Extracted structured fields from {len(extracted)} documents ({n_inv} invoices, {n_rec} receipts).')
print(f'The CASE expression in the prompt adapts extraction instructions to each document type.\n')
extracted

Extracted structured fields from 10 documents (5 invoices, 5 receipts).
The CASE expression in the prompt adapts extraction instructions to each document type.

,doc_name,doc_type,entity_name,reference_number,total_amount,document_date
0,doc_008.pdf,invoice,Horizon Digital Solutions,INV-2023-0019,17428.25,2023-11-20
1,doc_003.pdf,invoice,Innovate Media Group,INV-2024-0037,8660.00,None
2,doc_006.pdf,invoice,Nexus Innovations Group,INV-2024-0013,10067.25,2024-08-14
3,doc_005.pdf,invoice,Quantum Innovations Inc.,INV-2024-0004,12178.13,2024-04-14
4,doc_010.pdf,invoice,Starlight Solutions Group LLC,INV-2023-0026,19403.75,None
5,doc_001.pdf,receipt,GADGET GURU HUB,7890,55.42,08/15/2023
6,doc_009.pdf,receipt,GADGET GURU HUB,None,82.66,07/22/2023
7,doc_007.pdf,receipt,Gadget Galaxy,5678,68.68,05/20/2024
8,doc_004.pdf,receipt,Tech Haven Electronics,8765,86.03,05/15/2024
9,doc_002.pdf,receipt,Tech Haven Electronics,4321,71.36,10/26/2023

### Step 4b — Validate extraction against ground truth

Compare extracted values against `manifest.json` key fields to see how accurately the model reads these documents.

In [11]:
# Get extraction results with doc names
extraction_results = client.query(f"""
  SELECT uri, doc_type, entity_name, reference_number, total_amount, document_date
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_extracted`
""").to_dataframe()
extraction_results['doc_name'] = extraction_results['uri'].str.split('/').str[-1]

# Build comparison table
rows = []
for _, row in extraction_results.iterrows():
    doc = row['doc_name']
    truth = manifest[doc]['key_fields']
    doc_type = manifest[doc]['type']

    if doc_type == 'invoice':
        expected_name = truth.get('company', '')
        expected_total = truth.get('total_due', '')
        expected_date = truth.get('due_date', '')
    else:
        expected_name = truth.get('store_name', '')
        expected_total = truth.get('total', '')
        expected_date = truth.get('date', '')

    # Name match: case-insensitive containment
    name_match = (expected_name.lower() in row['entity_name'].lower()
                  or row['entity_name'].lower() in expected_name.lower())

    # Total match: compare as floats to avoid "8660.00" vs "8660.0" false negatives
    try:
        extracted_val = float(''.join(c for c in (row['total_amount'] or '') if c.isdigit() or c == '.'))
        total_match = extracted_val == float(expected_total)
    except (ValueError, TypeError):
        total_match = False

    rows.append({
        'doc': doc, 'type': row['doc_type'],
        'entity_name': f'{"✓" if name_match else "✗"} {row["entity_name"]}',
        'expected_name': expected_name,
        'total': f'{"✓" if total_match else "✗"} {row["total_amount"]}',
        'expected_total': str(expected_total),
        'name_ok': name_match, 'total_ok': total_match,
    })

comparison = pd.DataFrame(rows)

# Summary
name_acc = comparison['name_ok'].mean()
total_acc = comparison['total_ok'].mean()
print(f'Extraction accuracy across {len(comparison)} documents:')
print(f'  Entity name:  {comparison["name_ok"].sum()}/{len(comparison)} correct ({name_acc:.0%})')
print(f'  Total amount: {comparison["total_ok"].sum()}/{len(comparison)} correct ({total_acc:.0%})')

# Show the comparison
print()
comparison[['doc', 'type', 'entity_name', 'expected_name', 'total', 'expected_total']]

Extraction accuracy across 10 documents:
  Entity name:  10/10 correct (100%)
  Total amount: 10/10 correct (100%)

,doc,type,entity_name,expected_name,total,expected_total
0,doc_003.pdf,invoice,✓ Innovate Media Group,Innovate Media Group,✓ 8660.00,8660.0
1,doc_010.pdf,invoice,✓ Starlight Solutions Group LLC,Starlight Solutions Group LLC,✓ 19403.75,19403.75
2,doc_006.pdf,invoice,✓ Nexus Innovations Group,Nexus Innovations Group,✓ 10067.25,10067.25
3,doc_005.pdf,invoice,✓ Quantum Innovations Inc.,Quantum Innovations Inc.,✓ 12178.13,12178.13
4,doc_008.pdf,invoice,✓ Horizon Digital Solutions,Horizon Digital Solutions,✓ 17428.25,17428.25
5,doc_004.pdf,receipt,✓ Tech Haven Electronics,Tech Haven Electronics,✓ 86.03,86.03
6,doc_002.pdf,receipt,✓ Tech Haven Electronics,Tech Haven Electronics,✓ 71.36,71.36
7,doc_007.pdf,receipt,✓ Gadget Galaxy,Gadget Galaxy,✓ 68.68,68.68
8,doc_001.pdf,receipt,✓ GADGET GURU HUB,Gadget Guru Hub,✓ 55.42,55.42
9,doc_009.pdf,receipt,✓ GADGET GURU HUB,Gadget Guru Hub,✓ 82.66,82.66

---
## Step 5 — Score document quality with AI.SCORE

Use `AI.SCORE` with the **tuple syntax** to rate each document's completeness for accounting purposes — whether it contains all necessary details (amounts, dates, vendor info, reference numbers) to be processed without follow-up. This criterion produces more varied scores than visual quality alone, since receipts and invoices have different levels of structured detail.

```sql
AI.SCORE(('scoring criteria', ref))
```

In [12]:
query = f"""
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_di_scored` AS
SELECT
  c.uri,
  c.doc_type,
  AI.SCORE(
    ('Rate whether this document contains all information needed for accounting: clear line items, tax breakdown, payment terms, vendor contact details, and reference numbers. Score 0 for missing most details, 1 for fully complete.',
     ot.ref)
  ) AS quality_score
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified` c
JOIN `{PROJECT_ID}.{DATASET_ID}.workflow_di_docs` ot ON c.uri = ot.uri
WHERE c.uri IN (
  SELECT uri FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified`
  ORDER BY uri LIMIT 10
)
"""
client.query(query).result()
print('Scoring complete')

# Show scores by type
scored = client.query(f"""
  SELECT doc_type, ROUND(AVG(quality_score), 2) AS avg_score,
         ROUND(MIN(quality_score), 2) AS min_score,
         ROUND(MAX(quality_score), 2) AS max_score,
         COUNT(*) AS count
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_scored`
  GROUP BY doc_type
""").to_dataframe()
print(f'\nAccounting completeness scores by document type:')
print(scored.to_string(index=False))

# Individual scores with doc names
all_scores = client.query(f"""
  SELECT
    SPLIT(uri, '/')[SAFE_OFFSET(ARRAY_LENGTH(SPLIT(uri, '/')) - 1)] AS doc_name,
    doc_type,
    quality_score
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_scored`
  ORDER BY quality_score DESC
""").to_dataframe()
print(f'\nIndividual document scores:')
all_scores

Scoring complete

Accounting completeness scores by document type:
doc_type  avg_score  min_score  max_score  count
 receipt        0.0        0.0        0.0      5
 invoice        1.0        1.0        1.0      5

Individual document scores:

      doc_name doc_type  quality_score
0  doc_006.pdf  invoice            1.0
1  doc_010.pdf  invoice            1.0
2  doc_003.pdf  invoice            1.0
3  doc_008.pdf  invoice            1.0
4  doc_005.pdf  invoice            1.0
5  doc_009.pdf  receipt            0.0
6  doc_001.pdf  receipt            0.0
7  doc_007.pdf  receipt            0.0
8  doc_002.pdf  receipt            0.0
9  doc_004.pdf  receipt            0.0

---
## Step 6 — Executive summary with AI.GENERATE

Aggregate all pipeline results — classification counts, extraction details, quality scores — into a single prompt and generate an executive summary. This final step composes the outputs of `AI.CLASSIFY`, `AI.GENERATE` (extraction), and `AI.SCORE` into one narrative, demonstrating how AI functions chain together in SQL.

In [13]:
query = f"""
WITH stats AS (
  SELECT
    (SELECT COUNT(*) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified`) AS total_docs,
    (SELECT COUNTIF(doc_type = 'invoice') FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified`) AS invoice_count,
    (SELECT COUNTIF(doc_type = 'receipt') FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_classified`) AS receipt_count,
    (SELECT ROUND(AVG(quality_score), 2) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_scored`) AS avg_quality,
    (SELECT ROUND(MIN(quality_score), 2) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_scored`) AS min_quality,
    (SELECT ROUND(MAX(quality_score), 2) FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_scored`) AS max_quality,
    (SELECT STRING_AGG(
        CONCAT(entity_name, ' (', reference_number, '): $', total_amount, ' due ', document_date),
        '; ')
     FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_extracted` WHERE doc_type = 'invoice') AS invoice_details,
    (SELECT STRING_AGG(
        CONCAT(entity_name, ': $', total_amount, ' on ', document_date),
        '; ')
     FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_extracted` WHERE doc_type = 'receipt') AS receipt_details
)
SELECT (AI.GENERATE(
  CONCAT(
    'You are a document processing analyst. Write a brief executive summary (3-4 paragraphs) of this automated document processing pipeline run. ',
    'Include a section on each phase: classification, extraction, and quality assessment.\\n\\n',
    'CLASSIFICATION: ', CAST(total_docs AS STRING), ' documents processed. ',
    CAST(invoice_count AS STRING), ' classified as invoices, ',
    CAST(receipt_count AS STRING), ' as receipts. Classification was validated against ground truth with 100%% accuracy.\\n\\n',
    'EXTRACTION (10-document sample):\\n',
    'Invoices: ', IFNULL(invoice_details, 'none'), '\\n',
    'Receipts: ', IFNULL(receipt_details, 'none'), '\\n\\n',
    'QUALITY ASSESSMENT (10-document sample, 0-1 scale for accounting completeness): ',
    'avg=', CAST(avg_quality AS STRING),
    ', min=', CAST(min_quality AS STRING),
    ', max=', CAST(max_quality AS STRING), '\\n\\n',
    'End with a one-sentence takeaway on the pipeline.'
  )
)).result AS executive_summary
FROM stats
"""
df = client.query(query).to_dataframe()
print(df.iloc[0]['executive_summary'])

## Executive Summary: Automated Document Processing Pipeline Run

This report summarizes a recent automated document processing pipeline run involving 100 documents, encompassing classification, extraction, and quality assessment phases. The pipeline demonstrated high accuracy in document classification but revealed opportunities for improvement in the completeness of extracted financial data, particularly for receipts.

**Classification:** The classification phase successfully processed all 100 documents. The system accurately identified 50 documents as invoices and 50 as receipts, achieving a perfect 100% accuracy against the ground truth. This indicates a robust and reliable classification model for these document types, requiring no manual intervention for categorization.

**Extraction:** A 10-document sample provided insight into the extraction capabilities. For invoices, key fields such as vendor name, invoice number, amount due, and due date were accurately extracted from the provided examples. Similarly, for receipts, merchant name, amount, and date were successfully identified. However, the qualitative data suggests that while core data points are captured, the comprehensiveness of extracted financial details, especially across receipts, might be inconsistent.

**Quality Assessment:** The quality assessment, based on a 10-document sample and an accounting completeness scale (0-1), yielded an average score of 0.5, with a range from 0 to 1. This indicates significant variability in the completeness of extracted information relevant for accounting purposes. A minimum score of 0 suggests that some documents may be missing crucial financial details, while a maximum score of 1 confirms that some documents are fully extracted for accounting needs. This variability highlights a potential area for enhancement in the extraction logic or model.

**Overall Takeaway:** While the document classification is highly accurate, the pipeline's extraction phase requires further refinement to ensure consistently complete accounting-relevant data, particularly for receipts.

### Alternative — Summarize by document type with AI.AGG

`AI.AGG` can summarize extraction and quality results per document type directly, without manually concatenating data into a single prompt.

In [14]:
query = f"""
SELECT
  e.doc_type,
  AI.AGG(
    TO_JSON_STRING(STRUCT(e.entity_name, e.reference_number, e.total_amount, e.document_date, s.quality_score)),
    'Summarize these documents: what vendors/stores appear, what are the typical amounts, and how complete is the data quality?'
  ) AS doc_type_summary
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_di_extracted` e
JOIN `{PROJECT_ID}.{DATASET_ID}.workflow_di_scored` s ON e.uri = s.uri
GROUP BY e.doc_type
"""
df_agg = client.query(query).to_dataframe()
for _, row in df_agg.iterrows():
    print(f'=== {row["doc_type"]} ===')
    print(row["doc_type_summary"])
    print()

=== invoice ===
Based on the provided data, here is the summary analysis:

### Vendors/Stores Identified
The dataset includes five distinct entities, all appearing to be professional or digital service providers:
*   Innovate Media Group
*   Starlight Solutions Group LLC
*   Nexus Innovations Group
*   Quantum Innovations Inc.
*   Horizon Digital Solutions

### Typical Amounts
The transaction amounts are relatively high, ranging from approximately **$8,660 to $19,404**. The average transaction value across these five entries is approximately **$13,567.48**.

### Data Quality Assessment
The overall data quality is **poor to moderate**, characterized by the following issues:
*   **Missing Information:** The `document_date` field is missing for 40% of the records (Innovate Media Group and Starlight Solutions Group LLC).
*   **Consistency:** While the `entity_name` and `total_amount` fields are populated for all entries, the lack of temporal data for a significant portion of the records limits the ability to perform trend analysis or aging reports.
*   **Quality Score:** Every record is assigned a `quality_score` of 1, which, depending on the scale used, suggests these records may have been flagged for review or represent the lowest tier of data integrity.

=== receipt ===
Based on the provided data, here is the summary analysis:

### Vendors/Stores
There are three distinct entities identified in the documents:
*   **Tech Haven Electronics** (2 entries)
*   **Gadget Galaxy** (1 entry)
*   **GADGET GURU HUB** (2 entries)

### Typical Amounts
The transaction amounts range from a minimum of **$55.42** to a maximum of **$86.03**. The average transaction amount across all five documents is approximately **$72.83**.

### Data Quality
The data quality is **poor**.
*   **Quality Score:** Every entry has a `quality_score` of 0, indicating significant issues with the extraction or source reliability.
*   **Missing Information:** There is at least one instance where the `reference_number` is null (GADGET GURU HUB), suggesting incomplete documentation or extraction failures.
*   **Consistency:** While the entity names are recognizable, the variation in naming (e.g., "GADGET GURU HUB") suggests a lack of standardized vendor naming conventions.

---
## Cleanup

Drop tables created by this workflow and delete GCS files. Shared resources (dataset, connection) are left for other notebooks.

In [15]:
# Drop workflow tables
for table in ['workflow_di_classified', 'workflow_di_extracted', 'workflow_di_scored']:
    client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.{table}', not_found_ok=True)
    print(f'Dropped {table}')

# Drop the object table
client.query(f'DROP EXTERNAL TABLE IF EXISTS `{PROJECT_ID}.{DATASET_ID}.workflow_di_docs`').result()
print('Dropped workflow_di_docs')

# Delete GCS files
from google.cloud import storage

gcs = storage.Client(project=PROJECT_ID)
bucket = gcs.bucket(BUCKET)
blobs = list(bucket.list_blobs(prefix='bq_ai_functions/document_intelligence/'))
for blob in blobs:
    blob.delete()
print(f'Cleaned up {len(blobs)} GCS files and workflow tables')

Dropped workflow_di_classified

Dropped workflow_di_extracted
Dropped workflow_di_scored

Dropped workflow_di_docs

Cleaned up 100 GCS files and workflow tables

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [16]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')