![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FMLOps%2FServing%2FBatch&file=Batch%20Inference%20With%20Dataproc.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FMLOps%2FServing%2FBatch%2FBatch%2520Inference%2520With%2520Dataproc.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b>
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataproc.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataproc.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a>
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataproc.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a>
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataproc.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b>
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a>
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a>
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Batch Inference With Dataproc

Run batch inference using [PySpark](https://spark.apache.org/docs/latest/api/python/) on [Dataproc Serverless](https://cloud.google.com/dataproc-serverless/docs/overview). Models load directly into Spark executors — no container build, no endpoint. Dataproc auto-provisions resources, runs the job, and tears down.

This notebook demonstrates:

- Pandas UDF for HuggingFace model inference with per-executor model caching
- BigQuery I/O via the built-in Spark BigQuery connector
- Submitting batch jobs with the `BatchControllerClient` Python SDK
- Multi-model inference with separate batch jobs
- Orchestrating Dataproc jobs with Vertex AI Pipelines (KFP)

**How it works:** A PySpark script defines a Pandas UDF that loads a HuggingFace model from GCS once per executor, then processes text in batches. Dataproc Serverless runtime 2.2 ships with torch and transformers pre-installed — no custom container or dependency installation needed.

**Story arc:**
1. Write a PySpark inference script with a Pandas UDF
2. Submit to Dataproc Serverless and verify results
3. Compare two models (DistilBERT vs BERT) via separate batch jobs
4. Orchestrate the workflow as a KFP pipeline

**Models:**
- v1: [`distilbert-base-uncased-finetuned-sst-2-english`](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english) (67M params) — returns `POSITIVE`/`NEGATIVE`
- v2: [`textattack/bert-base-uncased-SST-2`](https://huggingface.co/textattack/bert-base-uncased-SST-2) (110M params) — returns `LABEL_0`/`LABEL_1`

---
## Colab Setup

To run this notebook in Colab run the cells in this section. Otherwise, skip this section.

This cell will authenticate to GCP (follow prompts in the popup).

In [1]:
PROJECT_ID = 'statmike-mlops-349915' # replace with your project ID

In [2]:
try:
    import google.colab
    from google.colab import auth
    auth.authenticate_user()
    !gcloud config set project {PROJECT_ID}
except Exception:
    pass

---
## Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [README](../readme.md) for uv setup details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [3]:
import subprocess, sys, shutil

def install(*packages):
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install(
    'google-cloud-aiplatform', 'google-cloud-storage',
    'google-cloud-bigquery', 'google-cloud-pipeline-components',
    'google-cloud-dataproc',
    'transformers', 'torch', 'sentencepiece',
    'kfp', 'pandas', 'db-dtypes',
)

### API Enablement

In [4]:
!gcloud services enable aiplatform.googleapis.com
!gcloud services enable dataproc.googleapis.com

---
## Setup

inputs:

In [5]:
project = !gcloud config get-value project
PROJECT_ID = project[-1]
PROJECT_ID

'statmike-mlops-349915'

In [6]:
REGION = 'us-central1'
SERIES = 'mlops'
EXPERIMENT = 'dataproc-batch'

GCS_BUCKET = PROJECT_ID
BQ_DATASET = f'{SERIES}_{EXPERIMENT}'.replace('-', '_')

In [7]:
project_number = !gcloud projects describe {PROJECT_ID} --format='value(projectNumber)'
PROJECT_NUMBER = project_number[0]
PROJECT_NUMBER

'1026793852137'

packages:

In [8]:
import json, os, time, tempfile
from datetime import datetime

from google.cloud import storage
from google.cloud import bigquery
from google.cloud import aiplatform
from google.cloud import dataproc_v1
import pandas as pd

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/aiplatform/models.py:52: FutureWarning: Support for google-cloud-storage < 3.0.0 will be removed in a future version of google-cloud-aiplatform. Please upgrade to google-cloud-storage >= 3.0.0.
  from google.cloud.aiplatform.utils import gcs_utils

clients:

In [9]:
gcs = storage.Client(project = PROJECT_ID)
bucket = gcs.bucket(GCS_BUCKET)

bq_client = bigquery.Client(project = PROJECT_ID)

aiplatform.init(project = PROJECT_ID, location = REGION)

# Dataproc Serverless requires a regional endpoint
dataproc_client = dataproc_v1.BatchControllerClient(
    client_options={'api_endpoint': f'{REGION}-dataproc.googleapis.com:443'}
)

parameters:

In [10]:
DIR = f'files/dataproc'
os.makedirs(DIR, exist_ok=True)

In [11]:
# Test sentences used throughout the notebook
SENTENCES = [
    "This movie is absolutely wonderful and I loved every minute of it!",
    "The food was terrible and the service was even worse.",
    "An average experience, nothing special but not bad either.",
    "I cannot believe how amazing this product is, truly life-changing.",
    "Disappointing quality for the price. Would not recommend.",
    "The weather today is mild and partly cloudy.",
    "I had the worst customer service experience of my life yesterday.",
    "What a fantastic performance by the entire cast!",
    "The instructions were confusing and the product broke on day one.",
    "Pretty good overall, with some room for improvement.",
]

### Network Configuration

Dataproc Serverless requires [Private Google Access](https://cloud.google.com/vpc/docs/configure-private-google-access) on the subnet to reach Google APIs (BigQuery, GCS). The cell below checks and enables it on the default subnet.

In [12]:
status = !gcloud compute networks subnets describe default --region={REGION} --format="get(privateIpGoogleAccess)"
if status[0] == 'False':
    !gcloud compute networks subnets update default --region={REGION} --enable-private-ip-google-access
    status = !gcloud compute networks subnets describe default --region={REGION} --format="get(privateIpGoogleAccess)"
print(f'Private Google Access enabled: {status[0]}')

Private Google Access enabled: True

---
## Download HuggingFace Models

Download two sentiment analysis models from HuggingFace and upload them to GCS. Dataproc executors will download these model files at job startup — no container build or Model Registry upload needed.

- **v1 (DistilBERT):** Smaller, faster — primary model
- **v2 (BERT):** Larger — second model for multi-model comparison

In [13]:
MODELS = {
    'v1': {
        'hub_name': 'distilbert-base-uncased-finetuned-sst-2-english',
        'display_name': 'distilbert-sst2',
    },
    'v2': {
        'hub_name': 'textattack/bert-base-uncased-SST-2',
        'display_name': 'bert-sst2',
    },
}

In [14]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

for version, info in MODELS.items():
    gcs_prefix = f'{SERIES}/{EXPERIMENT}/models/{version}'

    # check if already uploaded
    existing = list(bucket.list_blobs(prefix=gcs_prefix, max_results=1))
    if existing:
        print(f'{version} ({info["hub_name"]}) already in GCS at gs://{GCS_BUCKET}/{gcs_prefix}')
        continue

    print(f'Downloading {version}: {info["hub_name"]} ...')
    with tempfile.TemporaryDirectory() as tmpdir:
        model = AutoModelForSequenceClassification.from_pretrained(info['hub_name'])
        tokenizer = AutoTokenizer.from_pretrained(info['hub_name'])
        model.save_pretrained(tmpdir)
        tokenizer.save_pretrained(tmpdir)

        for root, dirs, files in os.walk(tmpdir):
            for fname in files:
                local_path = os.path.join(root, fname)
                blob_name = f'{gcs_prefix}/{os.path.relpath(local_path, tmpdir)}'
                bucket.blob(blob_name).upload_from_filename(local_path)
        print(f'  Uploaded to gs://{GCS_BUCKET}/{gcs_prefix}')

    info['artifact_uri'] = f'gs://{GCS_BUCKET}/{gcs_prefix}'

# set artifact_uri for any that were already uploaded
for version, info in MODELS.items():
    if 'artifact_uri' not in info:
        info['artifact_uri'] = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/models/{version}'

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading v1: distilbert-base-uncased-finetuned-sst-2-english ...

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2296.36it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.58s/it]

  Uploaded to gs://statmike-mlops-349915/mlops/dataproc-batch/models/v1
Downloading v2: textattack/bert-base-uncased-SST-2 ...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12298.22it/s]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it]

  Uploaded to gs://statmike-mlops-349915/mlops/dataproc-batch/models/v2

In [15]:
for version, info in MODELS.items():
    blobs = list(bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/models/{version}'))
    print(f'{version} ({info["display_name"]}): {len(blobs)} files at {info["artifact_uri"]}')

v1 (distilbert-sst2): 4 files at gs://statmike-mlops-349915/mlops/dataproc-batch/models/v1
v2 (bert-sst2): 4 files at gs://statmike-mlops-349915/mlops/dataproc-batch/models/v2

---
## Create BigQuery Input Data

Create the same input table used across the batch inference series. The `category` and `created_date` columns exist for post-processing enrichment — the model only uses `text`.

In [16]:
# Create BQ dataset
dataset_ref = bigquery.Dataset(f'{PROJECT_ID}.{BQ_DATASET}')
dataset_ref.location = REGION
try:
    bq_client.get_dataset(dataset_ref)
    print(f'Dataset {BQ_DATASET} already exists')
except Exception:
    bq_client.create_dataset(dataset_ref)
    print(f'Created dataset {BQ_DATASET}')

# Create input table
BQ_TABLE = 'input_data'
schema = [
    bigquery.SchemaField('id', 'INTEGER'),
    bigquery.SchemaField('text', 'STRING'),
    bigquery.SchemaField('category', 'STRING'),
    bigquery.SchemaField('created_date', 'DATE'),
]

categories = ['entertainment', 'dining', 'general', 'product', 'product',
              'weather', 'service', 'entertainment', 'product', 'general']
rows = [
    {'id': i + 1, 'text': text, 'category': categories[i], 'created_date': '2026-04-18'}
    for i, text in enumerate(SENTENCES)
]

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition='WRITE_TRUNCATE',
)
bq_client.load_table_from_json(
    rows, f'{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}', job_config=job_config
).result()
print(f'Loaded {len(rows)} rows into {BQ_TABLE} (WRITE_TRUNCATE)')

bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}` ORDER BY id LIMIT 3').to_dataframe()

Created dataset mlops_dataproc_batch
Loaded 10 rows into input_data (WRITE_TRUNCATE)

,id,text,category,created_date
0,1,This movie is absolutely wonderful and I loved...,entertainment,2026-04-18
1,2,The food was terrible and the service was even...,dining,2026-04-18
2,3,"An average experience, nothing special but not...",general,2026-04-18

---
## Run on Dataproc Serverless

Deploy a PySpark batch job to [Dataproc Serverless](https://cloud.google.com/dataproc-serverless/docs/overview) for cloud-scale inference. The key features:

- **Serverless:** No cluster to manage — Dataproc provisions executors, runs the job, and tears down
- **Runtime 2.2:** Ships with torch, transformers, and other ML libs pre-installed — no custom container needed
- **BigQuery connector:** Built-in `spark.read.format('bigquery')` for direct BQ I/O
- **Autoscaling:** Dataproc adjusts executor count based on workload

The PySpark script uses a **Pandas UDF** pattern for inference:

```python
@pandas_udf(schema)
def sentiment_udf(texts: pd.Series) -> pd.DataFrame:
    pipe = get_model(model_uri)  # cached per executor
    results = pipe(texts.tolist(), batch_size=32)
    return pd.DataFrame(results)
```

Each executor loads the model from GCS once (cached in a module-level dict), then reuses it across all UDF calls. This avoids the per-row model loading overhead of a naive UDF.

In [21]:
%%writefile {DIR}/inference.py
"""Standalone PySpark script for sentiment batch inference on Dataproc Serverless."""
import argparse
import os
import tempfile

from pyspark.sql import SparkSession
from pyspark.sql.functions import pandas_udf, col, lit, round as spark_round
from pyspark.sql.types import StructType, StructField, StringType, FloatType
import pandas as pd

# Module-level model cache — persists across UDF calls within the same executor
_model_cache = {}


def get_model(model_gcs_uri):
    """Load model from GCS, caching after first load per executor."""
    if model_gcs_uri not in _model_cache:
        from transformers import pipeline as hf_pipeline
        from google.cloud import storage

        client = storage.Client()
        parts = model_gcs_uri.replace('gs://', '').split('/', 1)
        bkt = client.bucket(parts[0])
        prefix = parts[1]
        model_dir = tempfile.mkdtemp()
        for blob in bkt.list_blobs(prefix=prefix):
            rel = blob.name[len(prefix):].lstrip('/')
            if rel:
                local = os.path.join(model_dir, rel)
                os.makedirs(os.path.dirname(local), exist_ok=True)
                blob.download_to_filename(local)
        # Load tokenizer explicitly — DistilBERT doesn't accept token_type_ids
        # but some transformers versions (e.g. runtime 2.2) generate them
        from transformers import AutoTokenizer
        tokenizer = AutoTokenizer.from_pretrained(model_dir)
        if 'token_type_ids' in tokenizer.model_input_names:
            tokenizer.model_input_names.remove('token_type_ids')
        _model_cache[model_gcs_uri] = hf_pipeline(
            'sentiment-analysis', model=model_dir, tokenizer=tokenizer
        )
    return _model_cache[model_gcs_uri]


def run():
    parser = argparse.ArgumentParser()
    parser.add_argument('--project', required=True)
    parser.add_argument('--bq_dataset', required=True)
    parser.add_argument('--source_table', required=True)
    parser.add_argument('--output_table', required=True)
    parser.add_argument('--model_gcs_uri', required=True)
    parser.add_argument('--model_name', default='distilbert')
    parser.add_argument('--temp_bucket', required=True)
    args = parser.parse_args()

    spark = SparkSession.builder.appName('batch-inference').getOrCreate()
    spark.conf.set('temporaryGcsBucket', args.temp_bucket)

    # Read from BigQuery
    df = spark.read.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.source_table}') \
        .load() \
        .select('id', 'text', 'category')

    # Define sentiment UDF with struct return type
    model_uri = args.model_gcs_uri

    schema = StructType([
        StructField('label', StringType()),
        StructField('score', FloatType()),
    ])

    @pandas_udf(schema)
    def sentiment_udf(texts: pd.Series) -> pd.DataFrame:
        pipe = get_model(model_uri)
        results = pipe(texts.tolist(), batch_size=32)
        return pd.DataFrame(results)

    # Apply inference and format output
    result_df = df.withColumn('prediction', sentiment_udf(col('text')))
    output_df = result_df.select(
        col('id'),
        col('text'),
        col('prediction.label').alias('label'),
        spark_round(col('prediction.score'), 6).alias('score'),
        lit(args.model_name).alias('model'),
    )

    # Write to BigQuery
    output_df.write.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.output_table}') \
        .mode('overwrite') \
        .save()

    print(f'Results written to {args.project}.{args.bq_dataset}.{args.output_table}')


if __name__ == '__main__':
    run()

Overwriting files/dataproc/inference.py

In [22]:
# Upload PySpark script to GCS
bucket.blob(f'{SERIES}/{EXPERIMENT}/dataproc/inference.py').upload_from_filename(
    f'{DIR}/inference.py'
)
script_gcs_path = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataproc/inference.py'
print(f'Script uploaded: {script_gcs_path}')

Script uploaded: gs://statmike-mlops-349915/mlops/dataproc-batch/dataproc/inference.py

In [23]:
# Submit Dataproc Serverless batch job
BQ_OUTPUT_TABLE = 'dataproc_predictions'
batch_id = f'sentiment-batch-{datetime.now().strftime("%Y%m%d-%H%M%S")}'

batch = dataproc_v1.Batch(
    pyspark_batch=dataproc_v1.PySparkBatch(
        main_python_file_uri=script_gcs_path,
        args=[
            '--project', PROJECT_ID,
            '--bq_dataset', BQ_DATASET,
            '--source_table', BQ_TABLE,
            '--output_table', BQ_OUTPUT_TABLE,
            '--model_gcs_uri', MODELS['v1']['artifact_uri'],
            '--model_name', 'distilbert',
            '--temp_bucket', GCS_BUCKET,
        ],
    ),
    runtime_config=dataproc_v1.RuntimeConfig(version='2.2'),
)

print(f'Submitting Dataproc batch job: {batch_id}')
operation = dataproc_client.create_batch(
    request={
        'parent': f'projects/{PROJECT_ID}/locations/{REGION}',
        'batch': batch,
        'batch_id': batch_id,
    }
)
print(f'Job submitted. Console: https://console.cloud.google.com/dataproc/batches/{REGION}/{batch_id}?project={PROJECT_ID}')

Submitting Dataproc batch job: sentiment-batch-20260421-210955
Job submitted. Console: https://console.cloud.google.com/dataproc/batches/us-central1/sentiment-batch-20260421-210955?project=statmike-mlops-349915

In [24]:
# Wait for job completion (blocks until SUCCEEDED/FAILED/CANCELLED)
response = operation.result()
print(f'Batch state: {dataproc_v1.Batch.State(response.state).name}')

Batch state: SUCCEEDED

In [25]:
# Read predictions from BigQuery
df_results = bq_client.query(f'''
    SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_OUTPUT_TABLE}`
    ORDER BY id
''').to_dataframe()

print(f'Dataproc predictions ({len(df_results)} rows):')
print()
df_results

Dataproc predictions (10 rows):

,id,text,label,score,model
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",POSITIVE,0.859377,distilbert
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,NEGATIVE,0.999791,distilbert
7,8,What a fantastic performance by the entire cast!,POSITIVE,0.999882,distilbert
8,9,The instructions were confusing and the produc...,NEGATIVE,0.998770,distilbert
9,10,"Pretty good overall, with some room for improv...",POSITIVE,0.999488,distilbert

### Inference Patterns

| Pattern | Model Loading | Best For |
|---------|-------------|----------|
| **Pandas UDF** (shown above) | Once per executor (cached in module dict) | Structured DataFrames, SQL-friendly output |
| **`mapPartitions`** | Once per partition (explicit) | Full control over model lifecycle, RDD-based |
| **Naive UDF** | Every row (slow!) | Never use for ML inference |

The **Pandas UDF** pattern is preferred because:
- Processes data in Arrow-optimized batches (not row-by-row)
- Returns structured types (struct with `label` + `score`)
- Integrates with DataFrame operations (`withColumn`, `select`)
- Model caching via module-level dict avoids repeated downloads

**`mapPartitions` alternative** (lower-level):

```python
def predict_partition(iterator):
    pipe = get_model(model_uri)  # loaded once per partition
    for row in iterator:
        result = pipe(row.text)[0]
        yield (row.id, row.text, result['label'], result['score'], 'distilbert')

results_rdd = df.rdd.mapPartitions(predict_partition)
output_df = spark.createDataFrame(results_rdd, schema=['id', 'text', 'label', 'score', 'model'])
```

---
## Multi-Model Inference

Run both DistilBERT and BERT on the same data via separate Dataproc Serverless batch jobs. Each job writes to a different output table, then we compare results.

Unlike Dataflow (which can branch within a single pipeline), Dataproc Serverless runs one PySpark script per batch job. Sequential jobs are the simplest pattern — each job is independent and uses the same script with different `--model_gcs_uri` and `--output_table` args.

In [26]:
# Submit batch job for v2 (BERT) model
BQ_OUTPUT_TABLE_V2 = 'dataproc_predictions_v2'
batch_id_v2 = f'sentiment-batch-v2-{datetime.now().strftime("%Y%m%d-%H%M%S")}'

batch_v2 = dataproc_v1.Batch(
    pyspark_batch=dataproc_v1.PySparkBatch(
        main_python_file_uri=script_gcs_path,
        args=[
            '--project', PROJECT_ID,
            '--bq_dataset', BQ_DATASET,
            '--source_table', BQ_TABLE,
            '--output_table', BQ_OUTPUT_TABLE_V2,
            '--model_gcs_uri', MODELS['v2']['artifact_uri'],
            '--model_name', 'bert',
            '--temp_bucket', GCS_BUCKET,
        ],
    ),
    runtime_config=dataproc_v1.RuntimeConfig(version='2.2'),
)

print(f'Submitting v2 batch job: {batch_id_v2}')
operation_v2 = dataproc_client.create_batch(
    request={
        'parent': f'projects/{PROJECT_ID}/locations/{REGION}',
        'batch': batch_v2,
        'batch_id': batch_id_v2,
    }
)
print(f'Job submitted. Console: https://console.cloud.google.com/dataproc/batches/{REGION}/{batch_id_v2}?project={PROJECT_ID}')

Submitting v2 batch job: sentiment-batch-v2-20260421-211302
Job submitted. Console: https://console.cloud.google.com/dataproc/batches/us-central1/sentiment-batch-v2-20260421-211302?project=statmike-mlops-349915

In [27]:
# Wait for v2 job
response_v2 = operation_v2.result()
print(f'Batch state: {dataproc_v1.Batch.State(response_v2.state).name}')

Batch state: SUCCEEDED

In [28]:
# Compare predictions from both models
v1_df = bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_OUTPUT_TABLE}` ORDER BY id').to_dataframe()
v2_df = bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_OUTPUT_TABLE_V2}` ORDER BY id').to_dataframe()

print('Model Comparison \u2014 Same Sentences, Different Models')
print('=' * 70)
print()

for _, (r1, r2) in enumerate(zip(v1_df.itertuples(), v2_df.itertuples())):
    print(f'  "{r1.text[:65]}..."')
    print(f'    DistilBERT: {r1.label:>10} (score: {r1.score:.6f})')
    print(f'    BERT:       {r2.label:>10} (score: {r2.score:.6f})')
    print()

Model Comparison — Same Sentences, Different Models
======================================================================

  "This movie is absolutely wonderful and I loved every minute of it..."
    DistilBERT:   POSITIVE (score: 0.999887)
    BERT:          LABEL_1 (score: 0.999614)

  "The food was terrible and the service was even worse...."
    DistilBERT:   NEGATIVE (score: 0.999793)
    BERT:          LABEL_0 (score: 0.999059)

  "An average experience, nothing special but not bad either...."
    DistilBERT:   POSITIVE (score: 0.859377)
    BERT:          LABEL_1 (score: 0.898916)

  "I cannot believe how amazing this product is, truly life-changing..."
    DistilBERT:   POSITIVE (score: 0.999858)
    BERT:          LABEL_1 (score: 0.999475)

  "Disappointing quality for the price. Would not recommend...."
    DistilBERT:   NEGATIVE (score: 0.999712)
    BERT:          LABEL_0 (score: 0.997783)

  "The weather today is mild and partly cloudy...."
    DistilBERT:   NEGATIVE (score: 0.964102)
    BERT:          LABEL_0 (score: 0.818888)

  "I had the worst customer service experience of my life yesterday...."
    DistilBERT:   NEGATIVE (score: 0.999791)
    BERT:          LABEL_0 (score: 0.998323)

  "What a fantastic performance by the entire cast!..."
    DistilBERT:   POSITIVE (score: 0.999882)
    BERT:          LABEL_1 (score: 0.999615)

  "The instructions were confusing and the product broke on day one...."
    DistilBERT:   NEGATIVE (score: 0.998770)
    BERT:          LABEL_0 (score: 0.997837)

  "Pretty good overall, with some room for improvement...."
    DistilBERT:   POSITIVE (score: 0.999488)
    BERT:          LABEL_1 (score: 0.997235)

---
## Orchestrate with KFP Pipeline

For production, wrap the Dataproc job in a [KFP pipeline](https://www.kubeflow.org/docs/components/pipelines/) on Vertex AI Pipelines. This adds scheduling, parameterization, and lineage tracking.

The approach: the PySpark script is already uploaded to GCS. The KFP pipeline uses the pre-built `DataprocPySparkBatchOp` to submit and monitor the job.

### Define KFP Pipeline

Uses the pre-built [`DataprocPySparkBatchOp`](https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-2.22.0/api/v1/dataproc.html) from `google-cloud-pipeline-components`. This component:

- Submits a Dataproc Serverless batch job
- Tracks the job via `gcp_resources` — Vertex AI Pipelines natively monitors the batch lifecycle (no active polling container)
- Supports runtime version, Spark properties, custom containers, and all batch parameters

In [29]:
from kfp import dsl, compiler
from google_cloud_pipeline_components.v1.dataproc import DataprocPySparkBatchOp

@dsl.pipeline(
    name='dataproc-batch-inference',
    description='Run sentiment batch inference via Dataproc Serverless',
)
def dataproc_inference_pipeline(
    project: str,
    region: str,
    script_gcs_path: str,
    model_gcs_uri: str,
    model_name: str,
    bq_dataset: str,
    source_table: str,
    output_table: str = 'pipeline_predictions',
    temp_bucket: str = '',
):
    DataprocPySparkBatchOp(
        project=project,
        location=region,
        main_python_file_uri=script_gcs_path,
        runtime_config_version='2.2',
        runtime_config_properties={
            'spark.executor.instances': '2',
            'spark.driver.memory': '4g',
            'spark.executor.memory': '4g',
        },
        args=[
            '--project', project,
            '--bq_dataset', bq_dataset,
            '--source_table', source_table,
            '--output_table', output_table,
            '--model_gcs_uri', model_gcs_uri,
            '--model_name', model_name,
            '--temp_bucket', temp_bucket,
        ],
    )

print('KFP pipeline defined: dataproc_inference_pipeline (using DataprocPySparkBatchOp)')

KFP pipeline defined: dataproc_inference_pipeline (using DataprocPySparkBatchOp)

In [30]:
# Compile and submit
pipeline_json = f'{DIR}/dataproc_inference_pipeline.json'
compiler.Compiler().compile(
    pipeline_func=dataproc_inference_pipeline,
    package_path=pipeline_json,
)
print(f'Pipeline compiled to {pipeline_json}')

pipeline_job = aiplatform.PipelineJob(
    display_name=f'{SERIES}-{EXPERIMENT}-pipeline',
    template_path=pipeline_json,
    parameter_values={
        'project': PROJECT_ID,
        'region': REGION,
        'script_gcs_path': f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataproc/inference.py',
        'model_gcs_uri': MODELS['v1']['artifact_uri'],
        'model_name': 'distilbert',
        'bq_dataset': BQ_DATASET,
        'source_table': BQ_TABLE,
        'output_table': 'pipeline_predictions',
        'temp_bucket': GCS_BUCKET,
    },
    labels={'series': SERIES, 'experiment': EXPERIMENT},
    enable_caching=False,
)

print('Submitting pipeline ...')
pipeline_job.submit()
print(f'Pipeline job: {pipeline_job.resource_name}')

Pipeline compiled to files/dataproc/dataproc_inference_pipeline.json
Submitting pipeline ...
Creating PipelineJob
PipelineJob created. Resource name: projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755
To use this PipelineJob in another session:
pipeline_job = aiplatform.PipelineJob.get('projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755')
View Pipeline Job:
https://console.cloud.google.com/vertex-ai/locations/us-central1/pipelines/runs/dataproc-batch-inference-20260421211755?project=1026793852137
Pipeline job: projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755

In [31]:
# Wait for pipeline completion
pipeline_job.wait()
print(f'Pipeline state: {pipeline_job.state.name}')

PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755 current state:
3
PipelineJob run completed. Resource name: projects/1026793852137/locations/us-central1/pipelineJobs/dataproc-batch-inference-20260421211755
Pipeline state: PIPELINE_STATE_SUCCEEDED

In [32]:
# Read KFP pipeline output
kfp_table = f'{PROJECT_ID}.{BQ_DATASET}.pipeline_predictions'
try:
    kfp_results = bq_client.query(f'SELECT * FROM `{kfp_table}` ORDER BY id').to_dataframe()
    print(f'Pipeline results ({len(kfp_results)} rows):')
except Exception as e:
    kfp_results = None
    print(f'Could not read results table: {e}')

kfp_results

Pipeline results (10 rows):

,id,text,label,score,model
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",POSITIVE,0.859377,distilbert
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,NEGATIVE,0.999791,distilbert
7,8,What a fantastic performance by the entire cast!,POSITIVE,0.999882,distilbert
8,9,The instructions were confusing and the produc...,NEGATIVE,0.998770,distilbert
9,10,"Pretty good overall, with some room for improv...",POSITIVE,0.999488,distilbert

### Pipeline Parameterization

Change any of these at submission time without recompiling:

| Parameter | Purpose |
|-----------|----------|
| `model_gcs_uri` | Point to a different model in GCS |
| `model_name` | Label for the model in output |
| `source_table` | Score a different dataset |
| `output_table` | Write to a different output table |
| `temp_bucket` | GCS bucket for BigQuery connector temp files |

**Scheduling:** Use Vertex AI Pipeline schedules or Airflow (see [Orchestrating Batch Inference With Airflow](./Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb)) to run this pipeline on a recurring basis.

---
## Configuration Reference

### Dataproc Serverless

Dataproc Serverless auto-provisions resources per job. Key configuration via Spark properties:

| Property | Description | Default |
|----------|-------------|----------|
| `spark.executor.instances` | Number of executors | 2 |
| `spark.executor.memory` | Memory per executor | 1g |
| `spark.executor.cores` | Cores per executor | 2 |
| `spark.driver.memory` | Driver memory | 1g |
| `spark.dynamicAllocation.enabled` | Enable autoscaling | true |

### Runtime Versions

| Version | Key ML Libraries |
|---------|------------------|
| **2.2** | torch, transformers, tokenizers, accelerate, xgboost |
| 2.1 | Standard Spark + BigQuery connector |
| 1.x | Legacy — no ML libs pre-installed |

Use runtime 2.2+ for ML workloads to avoid dependency installation.

### Custom Containers

For full control over the environment (pinned versions, additional native libraries):

```python
batch.runtime_config = dataproc_v1.RuntimeConfig(
    container_image='us-central1-docker.pkg.dev/project/repo/image:tag',
)
```

The container must NOT include Spark (it's mounted at runtime). See [custom container docs](https://cloud.google.com/dataproc-serverless/docs/guides/custom-containers).

### GPU Support

Dataproc supports GPU via RAPIDS accelerator — not demonstrated here as our small models don't benefit from GPU acceleration.

### Three-Way Comparison

| Aspect | Vertex AI Batch | Dataflow RunInference | Dataproc PySpark |
|--------|:-:|:-:|:-:|
| **Processing model** | Container per worker | Beam pipeline | Spark DataFrame |
| **Pre/post processing** | KFP pipeline steps | Beam DoFns | Spark UDFs / transforms |
| **Model loading** | Container startup | ModelHandler | Pandas UDF + cache |
| **Autoscaling** | No (fixed workers) | Yes (within bounds) | Yes (dynamic allocation) |
| **Data ecosystem** | GCS, BQ | GCS, BQ, Pub/Sub | GCS, BQ, Hive, Delta |
| **Multi-model** | Separate jobs | Single pipeline branches | Separate jobs |
| **Serverless** | Yes | Yes | Yes |
| **ML libs pre-installed** | No (container) | No (requirements) | Yes (runtime 2.2) |
| **Best for** | Simple managed predict | Complex processing | Spark-native teams |

---
## Cleanup

Remove all resources created by this notebook.

### Delete BigQuery Dataset

In [33]:
bq_client.delete_dataset(
    f'{PROJECT_ID}.{BQ_DATASET}',
    delete_contents=True,
    not_found_ok=True,
)
print(f'Deleted BQ dataset {BQ_DATASET}')

Deleted BQ dataset mlops_dataproc_batch

### Remove GCS Artifacts (Optional)

Uncomment to remove the model artifacts and pipeline files from GCS.

In [ ]:
# # Remove all GCS artifacts for this experiment
# for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/'):
#     blob.delete()
# print(f'Removed gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/')