![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FMLOps%2FServing%2FBatch&file=Batch+Inference+With+Dataflow.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataflow.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataflow.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FMLOps%2FServing%2FBatch%2FBatch%2520Inference%2520With%2520Dataflow.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataflow.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataflow.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b>
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataflow.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataflow.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a>
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataflow.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a>
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Batch%2520Inference%2520With%2520Dataflow.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b>
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a>
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a>
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataflow.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Batch%20Inference%20With%20Dataflow.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Batch Inference With Dataflow

Run batch inference using [Apache Beam](https://beam.apache.org/) on [Dataflow](https://cloud.google.com/dataflow). Models load directly into Dataflow workers — no container build, no endpoint. Pre/post processing are native Beam pipeline stages that scale independently.

This notebook demonstrates:

- Custom `ModelHandler` for HuggingFace models stored in GCS
- Pre/post processing as Beam `DoFn` stages
- Dynamic batching with `BatchElements`
- Local testing with `DirectRunner` before deploying to Dataflow
- Multi-model inference with separate pipeline branches
- Orchestrating Dataflow jobs with Vertex AI Pipelines (KFP)

**How it works:** Apache Beam's `RunInference` transform manages model loading, batching, and inference. Each Dataflow worker downloads the model from GCS once at startup, then processes elements in batches. Dataflow autoscales workers based on data volume.

**Story arc:**
1. Build a custom `ModelHandler` that loads HuggingFace models from GCS
2. Test the pipeline locally with `DirectRunner`
3. Run on Dataflow with `DataflowRunner`
4. Compare two models (DistilBERT vs BERT) in a multi-model pipeline
5. Orchestrate the workflow as a KFP pipeline

**Models:**
- v1: [`distilbert-base-uncased-finetuned-sst-2-english`](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english) (67M params) — returns `POSITIVE`/`NEGATIVE`
- v2: [`textattack/bert-base-uncased-SST-2`](https://huggingface.co/textattack/bert-base-uncased-SST-2) (110M params) — returns `LABEL_0`/`LABEL_1`

---
## Colab Setup

To run this notebook in Colab run the cells in this section. Otherwise, skip this section.

This cell will authenticate to GCP (follow prompts in the popup).

In [1]:
PROJECT_ID = 'statmike-mlops-349915' # replace with your project ID

In [2]:
try:
    import google.colab
    from google.colab import auth
    auth.authenticate_user()
    !gcloud config set project {PROJECT_ID}
except Exception:
    pass

---
## Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [README](../readme.md) for uv setup details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [3]:
import subprocess, sys, shutil

def install(*packages):
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install(
    'google-cloud-aiplatform', 'google-cloud-storage',
    'google-cloud-bigquery', 'google-cloud-pipeline-components',
    'apache-beam[gcp]',
    'transformers', 'torch', 'sentencepiece',
    'kfp', 'pandas', 'db-dtypes',
)

### API Enablement

In [4]:
!gcloud services enable aiplatform.googleapis.com
!gcloud services enable dataflow.googleapis.com

---
## Setup

inputs:

In [5]:
project = !gcloud config get-value project
PROJECT_ID = project[-1]
PROJECT_ID

'statmike-mlops-349915'

In [6]:
REGION = 'us-central1'
SERIES = 'mlops'
EXPERIMENT = 'dataflow-batch'

GCS_BUCKET = PROJECT_ID
BQ_DATASET = f'{SERIES}_{EXPERIMENT}'.replace('-', '_')

In [7]:
project_number = !gcloud projects describe {PROJECT_ID} --format='value(projectNumber)'
PROJECT_NUMBER = project_number[0]
PROJECT_NUMBER

'1026793852137'

packages:

In [8]:
import json, os, time, tempfile

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
from apache_beam.ml.inference.base import ModelHandler, PredictionResult, RunInference

from google.cloud import storage
from google.cloud import bigquery
from google.cloud import aiplatform
import pandas as pd

WARNING:root:crcmod package not found. This package is required if python-snappy or google-crc32c are not installed. To ensure crcmod is installed, install the tfrecord extra: pip install apache-beam[tfrecord]
/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/aiplatform/models.py:52: FutureWarning: Support for google-cloud-storage < 3.0.0 will be removed in a future version of google-cloud-aiplatform. Please upgrade to google-cloud-storage >= 3.0.0.
  from google.cloud.aiplatform.utils import gcs_utils

clients:

In [9]:
gcs = storage.Client(project = PROJECT_ID)
bucket = gcs.bucket(GCS_BUCKET)

bq_client = bigquery.Client(project = PROJECT_ID)

aiplatform.init(project = PROJECT_ID, location = REGION)

parameters:

In [10]:
DIR = f'files/dataflow'
os.makedirs(DIR, exist_ok=True)

In [11]:
# Test sentences used throughout the notebook
SENTENCES = [
    "This movie is absolutely wonderful and I loved every minute of it!",
    "The food was terrible and the service was even worse.",
    "An average experience, nothing special but not bad either.",
    "I cannot believe how amazing this product is, truly life-changing.",
    "Disappointing quality for the price. Would not recommend.",
    "The weather today is mild and partly cloudy.",
    "I had the worst customer service experience of my life yesterday.",
    "What a fantastic performance by the entire cast!",
    "The instructions were confusing and the product broke on day one.",
    "Pretty good overall, with some room for improvement.",
]

---
## Download HuggingFace Models

Download two sentiment analysis models from HuggingFace and upload them to GCS. Dataflow workers will download these model files at pipeline startup — no container build or Model Registry upload needed.

- **v1 (DistilBERT):** Smaller, faster — primary model
- **v2 (BERT):** Larger — second model for multi-model comparison

In [12]:
MODELS = {
    'v1': {
        'hub_name': 'distilbert-base-uncased-finetuned-sst-2-english',
        'display_name': 'distilbert-sst2',
    },
    'v2': {
        'hub_name': 'textattack/bert-base-uncased-SST-2',
        'display_name': 'bert-sst2',
    },
}

In [13]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

for version, info in MODELS.items():
    gcs_prefix = f'{SERIES}/{EXPERIMENT}/models/{version}'

    # check if already uploaded
    existing = list(bucket.list_blobs(prefix=gcs_prefix, max_results=1))
    if existing:
        print(f'{version} ({info["hub_name"]}) already in GCS at gs://{GCS_BUCKET}/{gcs_prefix}')
        continue

    print(f'Downloading {version}: {info["hub_name"]} ...')
    with tempfile.TemporaryDirectory() as tmpdir:
        model = AutoModelForSequenceClassification.from_pretrained(info['hub_name'])
        tokenizer = AutoTokenizer.from_pretrained(info['hub_name'])
        model.save_pretrained(tmpdir)
        tokenizer.save_pretrained(tmpdir)

        for root, dirs, files in os.walk(tmpdir):
            for fname in files:
                local_path = os.path.join(root, fname)
                blob_name = f'{gcs_prefix}/{os.path.relpath(local_path, tmpdir)}'
                bucket.blob(blob_name).upload_from_filename(local_path)
        print(f'  Uploaded to gs://{GCS_BUCKET}/{gcs_prefix}')

    info['artifact_uri'] = f'gs://{GCS_BUCKET}/{gcs_prefix}'

# set artifact_uri for any that were already uploaded
for version, info in MODELS.items():
    if 'artifact_uri' not in info:
        info['artifact_uri'] = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/models/{version}'

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

v1 (distilbert-base-uncased-finetuned-sst-2-english) already in GCS at gs://statmike-mlops-349915/mlops/dataflow-batch/models/v1
v2 (textattack/bert-base-uncased-SST-2) already in GCS at gs://statmike-mlops-349915/mlops/dataflow-batch/models/v2

In [14]:
for version, info in MODELS.items():
    blobs = list(bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/models/{version}'))
    print(f'{version} ({info["display_name"]}): {len(blobs)} files at {info["artifact_uri"]}')

v1 (distilbert-sst2): 4 files at gs://statmike-mlops-349915/mlops/dataflow-batch/models/v1
v2 (bert-sst2): 4 files at gs://statmike-mlops-349915/mlops/dataflow-batch/models/v2

---
## Create BigQuery Input Data

Create the same input table used across the batch inference series. The `category` and `created_date` columns exist for post-processing enrichment — the model only uses `text`.

In [15]:
# Create BQ dataset
dataset_ref = bigquery.Dataset(f'{PROJECT_ID}.{BQ_DATASET}')
dataset_ref.location = REGION
try:
    bq_client.get_dataset(dataset_ref)
    print(f'Dataset {BQ_DATASET} already exists')
except Exception:
    bq_client.create_dataset(dataset_ref)
    print(f'Created dataset {BQ_DATASET}')

# Create input table
BQ_TABLE = 'input_data'
schema = [
    bigquery.SchemaField('id', 'INTEGER'),
    bigquery.SchemaField('text', 'STRING'),
    bigquery.SchemaField('category', 'STRING'),
    bigquery.SchemaField('created_date', 'DATE'),
]

categories = ['entertainment', 'dining', 'general', 'product', 'product',
              'weather', 'service', 'entertainment', 'product', 'general']
rows = [
    {'id': i + 1, 'text': text, 'category': categories[i], 'created_date': '2026-04-18'}
    for i, text in enumerate(SENTENCES)
]

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition='WRITE_TRUNCATE',
)
bq_client.load_table_from_json(
    rows, f'{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}', job_config=job_config
).result()
print(f'Loaded {len(rows)} rows into {BQ_TABLE} (WRITE_TRUNCATE)')

bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}` ORDER BY id LIMIT 3').to_dataframe()

Dataset mlops_dataflow_batch already exists
Loaded 10 rows into input_data (WRITE_TRUNCATE)

,id,text,category,created_date
0,1,This movie is absolutely wonderful and I loved...,entertainment,2026-04-18
1,2,The food was terrible and the service was even...,dining,2026-04-18
2,3,"An average experience, nothing special but not...",general,2026-04-18

---
## Custom ModelHandler

Apache Beam's `RunInference` transform uses a `ModelHandler` to manage model loading and inference. The handler is instantiated once per worker — the model downloads from GCS at worker startup, then serves all elements routed to that worker.

Our handler wraps HuggingFace's `pipeline()` API, which handles tokenization and inference internally. Input elements are dicts with at least a `text` field; the handler extracts text, runs batch inference, and returns `PredictionResult` objects that carry both the original element and the model output.

In [16]:
class SentimentModelHandler(ModelHandler):
    """ModelHandler that loads a HuggingFace sentiment model from GCS."""

    def __init__(self, model_gcs_uri):
        self._model_gcs_uri = model_gcs_uri
        self._model_name = model_gcs_uri.split('/')[-1]  # 'v1' or 'v2'

    def load_model(self):
        """Download model from GCS and load with HuggingFace pipeline.
        Called once per worker at startup."""
        from transformers import pipeline as hf_pipeline
        from google.cloud import storage as gcs_lib

        client = gcs_lib.Client()
        parts = self._model_gcs_uri.replace('gs://', '').split('/', 1)
        bkt = client.bucket(parts[0])
        prefix = parts[1]

        model_dir = tempfile.mkdtemp()
        for blob in bkt.list_blobs(prefix=prefix):
            rel = blob.name[len(prefix):].lstrip('/')
            if rel:
                local = os.path.join(model_dir, rel)
                os.makedirs(os.path.dirname(local), exist_ok=True)
                blob.download_to_filename(local)

        return hf_pipeline('sentiment-analysis', model=model_dir, tokenizer=model_dir)

    def run_inference(self, batch, model, inference_args=None):
        """Run sentiment analysis on a batch of elements.

        Args:
            batch: List of dicts, each with at least a 'text' field.
            model: The HuggingFace pipeline loaded by load_model().

        Returns:
            List of PredictionResult with the original element and prediction dict.
        """
        texts = [element['text'] for element in batch]
        results = model(texts)
        return [
            PredictionResult(example=element, inference=result)
            for element, result in zip(batch, results)
        ]

    def batch_elements_kwargs(self):
        """Configure dynamic batching bounds for RunInference."""
        return {'min_batch_size': 1, 'max_batch_size': 32}

print('SentimentModelHandler defined')

SentimentModelHandler defined

### Pre/Post Processing DoFns

Pre- and post-processing run as separate Beam stages that scale independently from inference:

- **`PreprocessFn`** — Clean text, validate, pass metadata through
- **`PostprocessFn`** — Extract prediction fields, format for BigQuery output

In [17]:
class PreprocessFn(beam.DoFn):
    """Clean and validate text before inference."""
    def process(self, row):
        text = row.get('text', '')
        if isinstance(text, str):
            text = text.strip()
        if text:
            yield {
                'id': row.get('id', 0),
                'text': text,
                'category': row.get('category', ''),
            }


class PostprocessFn(beam.DoFn):
    """Format PredictionResult for BigQuery output."""
    def __init__(self, model_name=''):
        self._model_name = model_name

    def process(self, prediction_result):
        element = prediction_result.example
        result = prediction_result.inference
        yield {
            'id': element['id'],
            'text': element['text'],
            'label': result['label'],
            'score': round(result['score'], 6),
            'model': self._model_name,
        }

print('DoFns defined: PreprocessFn, PostprocessFn')

DoFns defined: PreprocessFn, PostprocessFn

---
## Test with DirectRunner

Run the pipeline locally to verify the model handler and DoFns work before deploying to Dataflow. `DirectRunner` executes everything in-process — no cloud resources needed.

In [18]:
# Build model handler for DistilBERT (v1)
v1_handler = SentimentModelHandler(MODELS['v1']['artifact_uri'])

# Run locally with DirectRunner — write results to a temp file
DIRECT_OUTPUT = '/tmp/beam_direct_results'

with beam.Pipeline(options=PipelineOptions()) as p:
    (
        p
        | 'CreateInput' >> beam.Create([
            {'id': i + 1, 'text': s, 'category': c}
            for i, (s, c) in enumerate(zip(SENTENCES, categories))
        ])
        | 'Preprocess' >> beam.ParDo(PreprocessFn())
        | 'Infer' >> RunInference(model_handler=v1_handler)
        | 'Postprocess' >> beam.ParDo(PostprocessFn('distilbert'))
        | 'ToJson' >> beam.Map(json.dumps)
        | 'Write' >> beam.io.WriteToText(
            DIRECT_OUTPUT, file_name_suffix='.jsonl', shard_name_template='',
        )
    )

# Read results back
direct_results = [json.loads(line) for line in open(f'{DIRECT_OUTPUT}.jsonl') if line.strip()]
print(f'DirectRunner results ({len(direct_results)} sentences):')

WARNING:apache_beam.runners.interactive.interactive_environment:Dependencies required for Interactive Beam PCollection visualization are not available, please use: `pip install apache-beam[interactive]` to install necessary dependencies to enable all data visualization features.

WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['--f=/home/user/.local/share/jupyter/runtime/kernel-v3d35caa5b8403de158be0d1a215b8534e1be104ef.json']
WARNING:apache_beam.options.pipeline_options:Unparseable argument: --f=/home/user/.local/share/jupyter/runtime/kernel-v3d35caa5b8403de158be0d1a215b8534e1be104ef.json
WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['--f=/home/user/.local/share/jupyter/runtime/kernel-v3d35caa5b8403de158be0d1a215b8534e1be104ef.json']
WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['--f=/home/user/.local/share/jupyter/runtime/kernel-v3d35caa5b8403de158be0d1a215b8534e1be104ef.json']
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2266.36it/s]
WARNING:apache_beam.io.filebasedsink:Deleting 1 existing files in target path matching:

DirectRunner results (10 sentences):

In [19]:
for r in sorted(direct_results, key=lambda x: x['id']):
    print(f'  [{r["id"]:>2}] {r["label"]:>10} ({r["score"]:.4f})  "{r["text"][:55]}..."')

  [ 1]   POSITIVE (0.9999)  "This movie is absolutely wonderful and I loved every mi..."
  [ 2]   NEGATIVE (0.9998)  "The food was terrible and the service was even worse...."
  [ 3]   POSITIVE (0.8594)  "An average experience, nothing special but not bad eith..."
  [ 4]   POSITIVE (0.9999)  "I cannot believe how amazing this product is, truly lif..."
  [ 5]   NEGATIVE (0.9997)  "Disappointing quality for the price. Would not recommen..."
  [ 6]   NEGATIVE (0.9641)  "The weather today is mild and partly cloudy...."
  [ 7]   NEGATIVE (0.9998)  "I had the worst customer service experience of my life ..."
  [ 8]   POSITIVE (0.9999)  "What a fantastic performance by the entire cast!..."
  [ 9]   NEGATIVE (0.9988)  "The instructions were confusing and the product broke o..."
  [10]   POSITIVE (0.9995)  "Pretty good overall, with some room for improvement...."

---
## Run on Dataflow

Deploy the same pipeline to [Dataflow](https://cloud.google.com/dataflow) for cloud-scale execution. The key differences from DirectRunner:

- **Workers:** Dataflow provisions VMs, installs dependencies, downloads the model
- **I/O:** Reads from BigQuery, writes results to BigQuery
- **Autoscaling:** Dataflow adjusts worker count based on data volume
- **Startup time:** Workers need ~5 minutes to provision and install `torch` + `transformers`

> **Production tip:** For faster startup, use a [custom container](https://cloud.google.com/dataflow/docs/guides/using-custom-containers) with dependencies pre-installed instead of `--requirements_file`.

In [20]:
%%writefile {DIR}/requirements.txt
transformers
torch
sentencepiece
google-cloud-storage

Overwriting files/dataflow/requirements.txt

In [21]:
# Upload requirements to GCS for Dataflow workers
bucket.blob(f'{SERIES}/{EXPERIMENT}/dataflow/requirements.txt').upload_from_filename(
    f'{DIR}/requirements.txt'
)
requirements_gcs = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataflow/requirements.txt'
print(f'Requirements uploaded: {requirements_gcs}')

Requirements uploaded: gs://statmike-mlops-349915/mlops/dataflow-batch/dataflow/requirements.txt

In [22]:
from datetime import datetime

# Output table for Dataflow results
BQ_OUTPUT_TABLE = 'dataflow_predictions'

options = PipelineOptions([
    f'--project={PROJECT_ID}',
    f'--region={REGION}',
    '--runner=DataflowRunner',
    f'--temp_location=gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataflow/temp',
    f'--staging_location=gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataflow/staging',
    f'--requirements_file={DIR}/requirements.txt',
    f'--job_name=sentiment-batch-{datetime.now().strftime("%Y%m%d-%H%M%S")}',
    '--save_main_session',
    '--machine_type=n1-standard-4',
    '--num_workers=2',
    '--max_num_workers=4',
])

v1_handler = SentimentModelHandler(MODELS['v1']['artifact_uri'])

BQ_SCHEMA = 'id:INTEGER,text:STRING,label:STRING,score:FLOAT64,model:STRING'

print('Building and submitting Dataflow pipeline ...')

p = beam.Pipeline(options=options)
(
    p
    | 'ReadBQ' >> beam.io.ReadFromBigQuery(
        query=f'SELECT id, text, category FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}` ORDER BY id',
        use_standard_sql=True,
    )
    | 'Preprocess' >> beam.ParDo(PreprocessFn())
    | 'Infer' >> RunInference(model_handler=v1_handler)
    | 'Postprocess' >> beam.ParDo(PostprocessFn('distilbert'))
    | 'WriteBQ' >> beam.io.WriteToBigQuery(
        table=f'{PROJECT_ID}:{BQ_DATASET}.{BQ_OUTPUT_TABLE}',
        schema=BQ_SCHEMA,
        write_disposition=beam.io.BigQueryDisposition.WRITE_TRUNCATE,
        create_disposition=beam.io.BigQueryDisposition.CREATE_IF_NEEDED,
    )
)

pipeline_result = p.run()
print(f'Dataflow job submitted: {pipeline_result.job_id()}')
print(f'Console: https://console.cloud.google.com/dataflow/jobs/{REGION}/{pipeline_result.job_id()}?project={PROJECT_ID}')

Building and submitting Dataflow pipeline ...

WARNING:apache_beam.options.pipeline_options:Bucket gs://statmike-mlops-349915/mlops/dataflow-batch/dataflow/temp used as temp_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.

WARNING:apache_beam.transforms.core:Using yield and return in the process method of <class 'apache_beam.io.gcp.bigquery_file_loads.WriteRecordsToFile'> can lead to unexpected behavior, see:https://github.com/apache/beam/issues/22969.
WARNING:apache_beam.transforms.core:Using yield and return in the process method of <class 'apache_beam.io.gcp.bigquery_file_loads.PartitionFiles'> can lead to unexpected behavior, see:https://github.com/apache/beam/issues/22969.
WARNING:apache_beam.transforms.core:Using yield and return in the process method of <class 'apache_beam.io.gcp.bigquery_file_loads.WriteRecordsToFile'> can lead to unexpected behavior, see:https://github.com/apache/beam/issues/22969.
WARNING:apache_beam.transforms.core:Using yield and return in the process method of <class 'apache_beam.io.gcp.bigquery_file_loads.PartitionFiles'> can lead to unexpected behavior, see:https://github.com/apache/beam/issues/22969.

Dataflow job submitted: 2026-04-21_08_49_46-15830313519308978898
Console: https://console.cloud.google.com/dataflow/jobs/us-central1/2026-04-21_08_49_46-15830313519308978898?project=statmike-mlops-349915

In [23]:
# Wait for job completion
print(f'Waiting for Dataflow job {pipeline_result.job_id()} ...')
pipeline_result.wait_until_finish()
print(f'Job state: {pipeline_result.state}')

Waiting for Dataflow job 2026-04-21_08_49_46-15830313519308978898 ...
Job state: DONE

In [24]:
# Read predictions from BigQuery
df_results = bq_client.query(f'''
    SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_OUTPUT_TABLE}`
    ORDER BY id
''').to_dataframe()

print(f'Dataflow predictions ({len(df_results)} rows):')
print()
df_results

Dataflow predictions (10 rows):

,id,text,label,score,model
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",POSITIVE,0.859379,distilbert
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,NEGATIVE,0.999791,distilbert
7,8,What a fantastic performance by the entire cast!,POSITIVE,0.999882,distilbert
8,9,The instructions were confusing and the produc...,NEGATIVE,0.998770,distilbert
9,10,"Pretty good overall, with some room for improv...",POSITIVE,0.999488,distilbert

---
## Pre/Post Processing Patterns

The pipeline above uses separate `DoFn` stages for pre- and post-processing. Apache Beam's `RunInference` also supports **inline** pre/post processing via `with_preprocess_fn()` and `with_postprocess_fn()`. Here's how the two approaches compare:

### Inline Functions (Alternative)

```python
def preprocess(element):
    return {**element, 'text': element['text'].strip()}

def postprocess(result):
    return {
        'id': result.example['id'],
        'label': result.inference['label'],
        'score': result.inference['score'],
    }

# Attach directly to RunInference
(
    p
    | ReadFromBigQuery(...)
    | RunInference(handler)
        .with_preprocess_fn(preprocess)
        .with_postprocess_fn(postprocess)
    | WriteToBigQuery(...)
)
```

### When to Use Each

| Approach | Scaling | Complexity | Best For |
|----------|---------|------------|----------|
| **Separate DoFns** | Each stage scales independently | More pipeline stages | Complex transforms, filtering, fan-out |
| **Inline functions** | Co-located with inference | Fewer stages, simpler | Lightweight transforms (field extraction, renaming) |

For production pipelines with non-trivial pre/post processing (SQL joins, external lookups, validation with dead-letter output), separate DoFns are the standard pattern. Inline functions work well for simple field mapping.

### Dynamic Batching

`RunInference` automatically batches elements before calling `run_inference()`. The `batch_elements_kwargs()` method on the handler controls batching bounds:

```python
def batch_elements_kwargs(self):
    return {'min_batch_size': 1, 'max_batch_size': 32}
```

Beam's `BatchElements` transform measures per-element processing time and adjusts batch size within these bounds to maximize throughput. Unlike Vertex AI Batch Prediction's fixed `batchSize` parameter, this adapts at runtime.

| Setting | Effect |
|---------|--------|
| `min_batch_size=1` | Don't wait for a full batch — process immediately if available |
| `max_batch_size=32` | Cap batch size to avoid OOM in the model |
| `max_batch_duration_secs` | Optional timeout — flush partial batches after N seconds |

**Rule of thumb:** Set `max_batch_size` based on your model's memory footprint. For transformer models, 16-32 is typical. Beam handles the rest.

---
## Multi-Model Inference

Run both DistilBERT and BERT on the same data in a single pipeline. Each model gets its own `RunInference` stage with a separate handler. Results are flattened into a single output with a `model` column identifying which model produced each prediction.

This pattern enables model comparison, A/B analysis, and ensemble scoring — all in one pipeline execution.

In [25]:
# Multi-model pipeline with DirectRunner
v1_handler = SentimentModelHandler(MODELS['v1']['artifact_uri'])
v2_handler = SentimentModelHandler(MODELS['v2']['artifact_uri'])

MULTI_OUTPUT = '/tmp/beam_multi_results'

input_data = [
    {'id': i + 1, 'text': s, 'category': c}
    for i, (s, c) in enumerate(zip(SENTENCES, categories))
]

with beam.Pipeline(options=PipelineOptions()) as p:
    preprocessed = (
        p
        | 'Create' >> beam.Create(input_data)
        | 'Preprocess' >> beam.ParDo(PreprocessFn())
    )

    # Branch 1: DistilBERT
    distilbert = (
        preprocessed
        | 'InferV1' >> RunInference(model_handler=v1_handler)
        | 'PostV1' >> beam.ParDo(PostprocessFn('distilbert'))
    )

    # Branch 2: BERT
    bert = (
        preprocessed
        | 'InferV2' >> RunInference(model_handler=v2_handler)
        | 'PostV2' >> beam.ParDo(PostprocessFn('bert'))
    )

    # Merge and write results
    merged = (distilbert, bert) | 'Flatten' >> beam.Flatten()
    (
        merged
        | 'ToJson' >> beam.Map(json.dumps)
        | 'Write' >> beam.io.WriteToText(
            MULTI_OUTPUT, file_name_suffix='.jsonl', shard_name_template='',
        )
    )

# Read results back
multi_results = [json.loads(line) for line in open(f'{MULTI_OUTPUT}.jsonl') if line.strip()]
print(f'Multi-model results: {len(multi_results)} predictions ({len(multi_results)//2} per model)')

WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['--f=/home/user/.local/share/jupyter/runtime/kernel-v3d35caa5b8403de158be0d1a215b8534e1be104ef.json']
WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['--f=/home/user/.local/share/jupyter/runtime/kernel-v3d35caa5b8403de158be0d1a215b8534e1be104ef.json']
WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['--f=/home/user/.local/share/jupyter/runtime/kernel-v3d35caa5b8403de158be0d1a215b8534e1be104ef.json']
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2533.50it/s]
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 2665.81it/s]
WARNING:apache_beam.io.filebasedsink:Deleting 1 existing files in target path matching:

Multi-model results: 20 predictions (10 per model)

In [26]:
# Display side-by-side comparison
print('Model Comparison — Same Sentences, Different Models')
print('=' * 70)
print()

# Group by sentence ID
by_id = {}
for r in multi_results:
    by_id.setdefault(r['id'], {})[r['model']] = r

for sid in sorted(by_id.keys()):
    preds = by_id[sid]
    text = list(preds.values())[0]['text']
    print(f'  "{text[:65]}..."')
    if 'distilbert' in preds:
        d = preds['distilbert']
        print(f'    DistilBERT: {d["label"]:>10} (score: {d["score"]:.6f})')
    if 'bert' in preds:
        b = preds['bert']
        print(f'    BERT:       {b["label"]:>10} (score: {b["score"]:.6f})')
    print()

Model Comparison — Same Sentences, Different Models
======================================================================

  "This movie is absolutely wonderful and I loved every minute of it..."
    DistilBERT:   POSITIVE (score: 0.999887)
    BERT:          LABEL_1 (score: 0.999614)

  "The food was terrible and the service was even worse...."
    DistilBERT:   NEGATIVE (score: 0.999793)
    BERT:          LABEL_0 (score: 0.999059)

  "An average experience, nothing special but not bad either...."
    DistilBERT:   POSITIVE (score: 0.859379)
    BERT:          LABEL_1 (score: 0.898916)

  "I cannot believe how amazing this product is, truly life-changing..."
    DistilBERT:   POSITIVE (score: 0.999858)
    BERT:          LABEL_1 (score: 0.999475)

  "Disappointing quality for the price. Would not recommend...."
    DistilBERT:   NEGATIVE (score: 0.999712)
    BERT:          LABEL_0 (score: 0.997783)

  "The weather today is mild and partly cloudy...."
    DistilBERT:   NEGATIVE (score: 0.964102)
    BERT:          LABEL_0 (score: 0.818888)

  "I had the worst customer service experience of my life yesterday...."
    DistilBERT:   NEGATIVE (score: 0.999791)
    BERT:          LABEL_0 (score: 0.998323)

  "What a fantastic performance by the entire cast!..."
    DistilBERT:   POSITIVE (score: 0.999882)
    BERT:          LABEL_1 (score: 0.999615)

  "The instructions were confusing and the product broke on day one...."
    DistilBERT:   NEGATIVE (score: 0.998770)
    BERT:          LABEL_0 (score: 0.997837)

  "Pretty good overall, with some room for improvement...."
    DistilBERT:   POSITIVE (score: 0.999488)
    BERT:          LABEL_1 (score: 0.997235)

### Multi-Model Patterns

| Pattern | How It Works | Best For |
|---------|-------------|----------|
| **Separate branches** (shown above) | Fan out from shared input, each branch has its own handler | Different model architectures, clear separation |
| **KeyedModelHandler** | Route elements to handlers by key in a single `RunInference` step | Same architecture, different weights (A/B testing) |
| **Sequential pipelines** | Run the full pipeline twice with different handlers | Simplest, but reads input data twice |

The **separate branches** pattern is most flexible — each branch can have its own pre/post processing, and the pipeline graph is easy to reason about. `KeyedModelHandler` (available in Beam 2.50+) is more efficient when you have many models of the same type:

```python
from apache_beam.ml.inference.base import KeyedModelHandler, KeyModelMapping

keyed_handler = KeyedModelHandler([
    KeyModelMapping(keys=['distilbert'], handler=v1_handler),
    KeyModelMapping(keys=['bert'], handler=v2_handler),
])
```

---
## Orchestrate with KFP Pipeline

For production, wrap the Dataflow job in a [KFP pipeline](https://www.kubeflow.org/docs/components/pipelines/) on Vertex AI Pipelines. This adds scheduling, parameterization, and lineage tracking.

The approach: write the Beam pipeline as a standalone Python script, upload it to GCS, then launch it from a KFP component using the Dataflow API.

### Standalone Pipeline Script

The `%%writefile` cell below creates a self-contained Beam pipeline script that can run independently or be launched by KFP. All parameters are passed via command-line arguments.

In [57]:
%%writefile {DIR}/pipeline.py
"""Standalone Beam pipeline for sentiment batch inference."""
import subprocess, sys

# Fix package incompatibilities in the DataflowPythonJobOp launcher container
# (gcr.io/ml-pipeline/google-cloud-pipeline-components:2.22.0).
# The container has numpy/pandas ABI mismatches and broken apitools imports.
# Reinstall beam (with all deps) and pandas to get a consistent package set.
subprocess.check_call([
    sys.executable, '-m', 'pip', 'install', '-q',
    '--force-reinstall', 'apache-beam[gcp]', 'pandas',
])

import argparse, json, logging, os, tempfile

logging.basicConfig(level=logging.INFO)

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
from apache_beam.ml.inference.base import ModelHandler, PredictionResult, RunInference


class SentimentModelHandler(ModelHandler):
    def __init__(self, model_gcs_uri):
        self._model_gcs_uri = model_gcs_uri

    def load_model(self):
        from transformers import pipeline as hf_pipeline
        from google.cloud import storage
        client = storage.Client()
        parts = self._model_gcs_uri.replace('gs://', '').split('/', 1)
        bkt = client.bucket(parts[0])
        prefix = parts[1]
        model_dir = tempfile.mkdtemp()
        for blob in bkt.list_blobs(prefix=prefix):
            rel = blob.name[len(prefix):].lstrip('/')
            if rel:
                local = os.path.join(model_dir, rel)
                os.makedirs(os.path.dirname(local), exist_ok=True)
                blob.download_to_filename(local)
        return hf_pipeline('sentiment-analysis', model=model_dir, tokenizer=model_dir)

    def run_inference(self, batch, model, inference_args=None):
        texts = [e['text'] for e in batch]
        results = model(texts)
        return [PredictionResult(example=e, inference=r) for e, r in zip(batch, results)]

    def batch_elements_kwargs(self):
        return {'min_batch_size': 1, 'max_batch_size': 32}


class PreprocessFn(beam.DoFn):
    def process(self, row):
        text = row.get('text', '')
        if isinstance(text, str):
            text = text.strip()
        if text:
            yield {'id': row.get('id', 0), 'text': text, 'category': row.get('category', '')}


class PostprocessFn(beam.DoFn):
    def process(self, prediction_result):
        element = prediction_result.example
        result = prediction_result.inference
        yield {
            'id': element['id'],
            'text': element['text'],
            'label': result['label'],
            'score': round(result['score'], 6),
            'model': 'distilbert',
        }


def run(argv=None):
    parser = argparse.ArgumentParser()
    # Note: --project is NOT declared here because DataflowPythonJobOp
    # auto-injects --project into the command. Declaring it here would
    # consume it via parse_known_args, preventing Beam from seeing it.
    parser.add_argument('--bq_dataset', required=True)
    parser.add_argument('--source_table', required=True)
    parser.add_argument('--output_table', required=True)
    parser.add_argument('--model_gcs_uri', required=True)
    known_args, pipeline_args = parser.parse_known_args(argv)

    # Get project from Beam pipeline options (auto-injected by the component)
    options = PipelineOptions(pipeline_args)
    project = options.get_all_options()['project']

    handler = SentimentModelHandler(known_args.model_gcs_uri)
    schema = 'id:INTEGER,text:STRING,label:STRING,score:FLOAT64,model:STRING'

    with beam.Pipeline(options=options) as p:
        (
            p
            | 'Read' >> beam.io.ReadFromBigQuery(
                query=f'SELECT id, text, category FROM `{project}.{known_args.bq_dataset}.{known_args.source_table}`',
                use_standard_sql=True,
            )
            | 'Preprocess' >> beam.ParDo(PreprocessFn())
            | 'Infer' >> RunInference(model_handler=handler)
            | 'Postprocess' >> beam.ParDo(PostprocessFn())
            | 'Write' >> beam.io.WriteToBigQuery(
                table=f'{project}:{known_args.bq_dataset}.{known_args.output_table}',
                schema=schema,
                write_disposition=beam.io.BigQueryDisposition.WRITE_TRUNCATE,
                create_disposition=beam.io.BigQueryDisposition.CREATE_IF_NEEDED,
            )
        )


if __name__ == '__main__':
    run()

Overwriting files/dataflow/pipeline.py

In [58]:
# Upload pipeline script and requirements to GCS
for f in ['pipeline.py', 'requirements.txt']:
    bucket.blob(f'{SERIES}/{EXPERIMENT}/dataflow/{f}').upload_from_filename(f'{DIR}/{f}')
    print(f'Uploaded: gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataflow/{f}')

Uploaded: gs://statmike-mlops-349915/mlops/dataflow-batch/dataflow/pipeline.py
Uploaded: gs://statmike-mlops-349915/mlops/dataflow-batch/dataflow/requirements.txt

### Define KFP Pipeline

Uses the pre-built [`DataflowPythonJobOp`](https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-2.22.0/api/v1/dataflow.html) from `google-cloud-pipeline-components`. This component:

- Downloads the Python script and requirements from GCS
- Submits the Dataflow job
- Tracks the job via `gcp_resources` — Vertex AI Pipelines natively monitors the Dataflow job lifecycle (no active polling container)
- Automatically passes `--runner`, `--project`, `--region`, and `--temp_location` to the script
- Auto-stages GCS paths for `--requirements_file` to a local path before launching

In [59]:
from kfp import dsl, compiler
from google_cloud_pipeline_components.v1.dataflow import DataflowPythonJobOp

@dsl.pipeline(
    name='dataflow-batch-inference',
    description='Run sentiment batch inference via Dataflow',
)
def dataflow_inference_pipeline(
    project: str,
    region: str,
    pipeline_gcs_path: str,
    requirements_gcs_path: str,
    model_gcs_uri: str,
    bq_dataset: str,
    source_table: str,
    output_table: str = 'pipeline_predictions',
    temp_location: str = '',
    staging_location: str = '',
    machine_type: str = 'n1-standard-4',
    num_workers: str = '2',
    max_workers: str = '4',
):
    # DataflowPythonJobOp automatically adds: --runner, --project, --region, --temp_location
    # It also auto-stages GCS paths for: --requirements_file, --setup_file
    # pipeline.py self-fixes the launcher container's numpy/pandas ABI mismatch.
    DataflowPythonJobOp(
        project=project,
        location=region,
        python_module_path=pipeline_gcs_path,
        temp_location=temp_location,
        args=[
            '--bq_dataset', bq_dataset,
            '--source_table', source_table,
            '--output_table', output_table,
            '--model_gcs_uri', model_gcs_uri,
            '--requirements_file', requirements_gcs_path,
            '--staging_location', staging_location,
            '--machine_type', machine_type,
            '--num_workers', num_workers,
            '--max_num_workers', max_workers,
            '--save_main_session',
        ],
    )

print('KFP pipeline defined: dataflow_inference_pipeline (using DataflowPythonJobOp)')

KFP pipeline defined: dataflow_inference_pipeline (using DataflowPythonJobOp)

In [60]:
# Compile and submit
pipeline_json = f'{DIR}/dataflow_inference_pipeline.json'
compiler.Compiler().compile(
    pipeline_func=dataflow_inference_pipeline,
    package_path=pipeline_json,
)
print(f'Pipeline compiled to {pipeline_json}')

pipeline_job = aiplatform.PipelineJob(
    display_name=f'{SERIES}-{EXPERIMENT}-pipeline',
    template_path=pipeline_json,
    parameter_values={
        'project': PROJECT_ID,
        'region': REGION,
        'pipeline_gcs_path': f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataflow/pipeline.py',
        'requirements_gcs_path': f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/dataflow/requirements.txt',
        'model_gcs_uri': MODELS['v1']['artifact_uri'],
        'bq_dataset': BQ_DATASET,
        'source_table': BQ_TABLE,
        'output_table': 'pipeline_predictions',
        'temp_location': f'gs://{GCS_BUCKET}/dataflow/temp',
        'staging_location': f'gs://{GCS_BUCKET}/dataflow/staging',
        'machine_type': 'n1-standard-4',
        'num_workers': '2',
        'max_workers': '4',
    },
    labels={'series': SERIES, 'experiment': EXPERIMENT},
    enable_caching=False,
)

print('Submitting pipeline ...')
pipeline_job.submit()
print(f'Pipeline job: {pipeline_job.resource_name}')

Pipeline compiled to files/dataflow/dataflow_inference_pipeline.json
Submitting pipeline ...
Pipeline job: projects/1026793852137/locations/us-central1/pipelineJobs/dataflow-batch-inference-20260421193714

In [61]:
# Wait for pipeline completion
pipeline_job.wait()
print(f'Pipeline state: {pipeline_job.state.name}')

Pipeline state: PIPELINE_STATE_SUCCEEDED

In [62]:
# Read KFP pipeline output
kfp_table = f'{PROJECT_ID}.{BQ_DATASET}.pipeline_predictions'
try:
    kfp_results = bq_client.query(f'SELECT * FROM `{kfp_table}` ORDER BY id').to_dataframe()
    print(f'Pipeline results ({len(kfp_results)} rows):')
except Exception as e:
    kfp_results = None
    print(f'Could not read results table: {e}')

kfp_results

Pipeline results (10 rows):

,id,text,label,score,model
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",POSITIVE,0.859379,distilbert
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,NEGATIVE,0.999791,distilbert
7,8,What a fantastic performance by the entire cast!,POSITIVE,0.999882,distilbert
8,9,The instructions were confusing and the produc...,NEGATIVE,0.998770,distilbert
9,10,"Pretty good overall, with some room for improv...",POSITIVE,0.999488,distilbert

### Pipeline Parameterization

Change any of these at submission time without recompiling:

| Parameter | Purpose |
|-----------|---------|
| `model_gcs_uri` | Point to a different model in GCS |
| `source_table` | Score a different dataset |
| `machine_type` | Scale worker resources up/down |
| `num_workers` / `max_workers` | Control parallelism and autoscaling |
| `output_table` | Write to a different output table |

**Scheduling:** Use Vertex AI Pipeline schedules or Airflow (see [Orchestrating Batch Inference With Airflow](./Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb)) to run this pipeline on a recurring basis.

---
## Configuration Reference

### Autoscaling

Dataflow autoscales workers between `num_workers` and `max_num_workers` based on backlog. This is a key advantage over Vertex AI Batch Prediction, which uses a fixed worker count.

| Parameter | Description | Default |
|-----------|-------------|---------|
| `num_workers` | Initial worker count | 1 |
| `max_num_workers` | Maximum workers (autoscaling ceiling) | 1000 |
| `machine_type` | Machine type per worker | `n1-standard-1` |
| `disk_size_gb` | Disk size per worker | 250 |

### Custom Containers

For production, pre-install large dependencies (torch, transformers) in a custom Docker image:

```python
options = PipelineOptions([
    '--sdk_container_image=us-central1-docker.pkg.dev/my-project/my-repo/beam-pytorch:latest',
    # No --requirements_file needed — deps are in the container
])
```

This reduces worker startup from ~5 minutes (installing torch) to ~30 seconds.

### GPU Support

Dataflow supports GPU workers via Runner v2:

```python
options = PipelineOptions([
    '--experiments=use_runner_v2',
    '--sdk_container_image=my-gpu-container',
    '--dataflow_service_options=worker_accelerator=type:nvidia-tesla-t4;count:1;install-nvidia-driver',
])
```

Not demonstrated here — our small sentiment models don't benefit from GPU acceleration.

### Comparison: Dataflow vs Vertex AI Batch Prediction

| Aspect | Dataflow RunInference | Vertex AI Batch Prediction |
|--------|:-:|:-:|
| **Pre/post processing** | Native pipeline stages | KFP pipeline steps |
| **Multi-model** | Single pipeline (branches) | Separate jobs |
| **Model loading** | Direct (ModelHandler) | Container-based |
| **Autoscaling** | Yes (within bounds) | No (fixed workers) |
| **Custom logic** | Full Beam SDK | Limited to container |
| **Dynamic batching** | BatchElements (auto-tuned) | Fixed batchSize |
| **Exactly-once** | Supported | At-least-once |
| **Best for** | Complex processing pipelines | Simple managed batch predict |

---
## Cleanup

Remove all resources created by this notebook.

### Delete BigQuery Dataset

In [63]:
bq_client.delete_dataset(
    f'{PROJECT_ID}.{BQ_DATASET}',
    delete_contents=True,
    not_found_ok=True,
)
print(f'Deleted BQ dataset {BQ_DATASET}')

Deleted BQ dataset mlops_dataflow_batch

### Remove GCS Artifacts (Optional)

Uncomment to remove the model artifacts, pipeline files, and Dataflow staging from GCS.

In [ ]:
# # Remove all GCS artifacts for this experiment
# for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/'):
#     blob.delete()
# print(f'Removed gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/')