![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FMLOps%2FServing%2FBatch&file=Orchestrating+Batch+Inference+With+Airflow.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FMLOps%2FServing%2FBatch%2FOrchestrating%2520Batch%2520Inference%2520With%2520Airflow.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Orchestrating%2520Batch%2520Inference%2520With%2520Airflow.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Orchestrating%2520Batch%2520Inference%2520With%2520Airflow.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Orchestrating%2520Batch%2520Inference%2520With%2520Airflow.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Orchestrating%2520Batch%2520Inference%2520With%2520Airflow.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Orchestrating Batch Inference With Airflow

Orchestrate batch inference workflows using [Cloud Composer](https://cloud.google.com/composer/docs/concepts/overview) (managed [Apache Airflow](https://airflow.apache.org/)). Airflow adds what standalone batch jobs lack: scheduling, data dependencies, monitoring, alerting, and backfill.

This notebook demonstrates four orchestration patterns:

1. **Airflow → Dataproc** — `DataprocCreateBatchOperator` launches a PySpark Serverless job directly
2. **Airflow → Dataflow** — `BeamRunPythonPipelineOperator` launches a Beam pipeline on Dataflow
3. **Airflow → KFP Pipeline** — `RunPipelineJobOperator` triggers a Vertex AI Pipeline that runs inference
4. **Airflow → Vertex AI Batch** — `CreateBatchPredictionJobOperator` for managed batch prediction

**Where Airflow fits:** KFP (Notebooks 1-3) handles the *how* — ML pipeline logic, artifact tracking, model lineage. Airflow handles the *when* — scheduling, data dependencies, cross-system coordination, backfill. In production, Airflow is the scheduler that decides when to kick off the ML pipeline.

**Prerequisites:** This notebook is fully self-contained — it builds the prediction container and registers the model for Pattern 4 inline.

---
## Colab Setup

To run this notebook in Colab run the cells in this section. Otherwise, skip this section.

This cell will authenticate to GCP (follow prompts in the popup).

In [1]:
PROJECT_ID = 'statmike-mlops-349915' # replace with your project ID

In [2]:
try:
    import google.colab
    from google.colab import auth
    auth.authenticate_user()
    !gcloud config set project {PROJECT_ID}
except Exception:
    pass

---
## Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [README](../readme.md) for uv setup details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [3]:
import subprocess, sys, shutil

def install(*packages):
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install(
    'google-cloud-aiplatform', 'google-cloud-storage',
    'google-cloud-bigquery', 'google-cloud-pipeline-components',
    'google-cloud-dataproc', 'google-cloud-orchestration-airflow',
    'google-cloud-build', 'google-cloud-artifact-registry',
    'transformers', 'torch', 'sentencepiece',
    'kfp', 'pandas', 'db-dtypes',
)

### API Enablement

In [4]:
!gcloud services enable aiplatform.googleapis.com
!gcloud services enable dataproc.googleapis.com
!gcloud services enable dataflow.googleapis.com
!gcloud services enable composer.googleapis.com
!gcloud services enable cloudbuild.googleapis.com
!gcloud services enable artifactregistry.googleapis.com

---
## Setup

inputs:

In [5]:
project = !gcloud config get-value project
PROJECT_ID = project[-1]
PROJECT_ID

'statmike-mlops-349915'

In [6]:
REGION = 'us-central1'
SERIES = 'mlops'
EXPERIMENT = 'airflow-batch'

GCS_BUCKET = PROJECT_ID
BQ_DATASET = f'{SERIES}_{EXPERIMENT}'.replace('-', '_')
AR_REPO = f"{SERIES}-docker"

In [7]:
project_number = !gcloud projects describe {PROJECT_ID} --format='value(projectNumber)'
PROJECT_NUMBER = project_number[0]
PROJECT_NUMBER

'1026793852137'

packages:

In [8]:
import json, os, time, tempfile
from datetime import datetime

from google.cloud import storage
from google.cloud import bigquery
from google.cloud import aiplatform
from google.cloud import dataproc_v1
from google.cloud.orchestration.airflow import service_v1
from google.cloud.devtools import cloudbuild_v1
from google.cloud import artifactregistry_v1
import pandas as pd

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/aiplatform/models.py:52: FutureWarning: Support for google-cloud-storage < 3.0.0 will be removed in a future version of google-cloud-aiplatform. Please upgrade to google-cloud-storage >= 3.0.0.
  from google.cloud.aiplatform.utils import gcs_utils

clients:

In [9]:
gcs = storage.Client(project = PROJECT_ID)
bucket = gcs.bucket(GCS_BUCKET)

bq_client = bigquery.Client(project = PROJECT_ID)

aiplatform.init(project = PROJECT_ID, location = REGION)

# Composer SDK client — manages Cloud Composer environments
composer_client = service_v1.EnvironmentsClient()

# Cloud Build + Artifact Registry (for Vertex AI Batch container)
cb = cloudbuild_v1.CloudBuildClient()
ar = artifactregistry_v1.ArtifactRegistryClient()

parameters:

In [10]:
DIR = f'files/airflow'
os.makedirs(DIR, exist_ok=True)

In [11]:
# Test sentences used throughout the notebook
SENTENCES = [
    "This movie is absolutely wonderful and I loved every minute of it!",
    "The food was terrible and the service was even worse.",
    "An average experience, nothing special but not bad either.",
    "I cannot believe how amazing this product is, truly life-changing.",
    "Disappointing quality for the price. Would not recommend.",
    "The weather today is mild and partly cloudy.",
    "I had the worst customer service experience of my entire life.",
    "A masterpiece of storytelling with brilliant performances throughout.",
    "Not worth the hype. The product broke after just two days.",
    "It works as expected, does the job without any issues.",
]

---
## Download HuggingFace Models

Download two sentiment analysis models from HuggingFace and upload them to GCS. Dataproc workers, Dataflow workers, and the Vertex AI Batch Prediction container all download these model files at job startup.

- **v1 (DistilBERT):** Smaller, faster — primary model
- **v2 (BERT):** Larger — second model for multi-model comparison

In [12]:
MODELS = {
    'v1': {
        'hub_name': 'distilbert-base-uncased-finetuned-sst-2-english',
        'display_name': 'distilbert-sst2',
    },
    'v2': {
        'hub_name': 'textattack/bert-base-uncased-SST-2',
        'display_name': 'bert-sst2',
    },
}

In [13]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

for version, info in MODELS.items():
    gcs_prefix = f'{SERIES}/{EXPERIMENT}/models/{version}'

    # check if already uploaded
    existing = list(bucket.list_blobs(prefix=gcs_prefix, max_results=1))
    if existing:
        print(f'{version} ({info["hub_name"]}) already in GCS at gs://{GCS_BUCKET}/{gcs_prefix}')
        continue

    print(f'Downloading {version}: {info["hub_name"]} ...')
    with tempfile.TemporaryDirectory() as tmpdir:
        model = AutoModelForSequenceClassification.from_pretrained(info['hub_name'])
        tokenizer = AutoTokenizer.from_pretrained(info['hub_name'])
        model.save_pretrained(tmpdir)
        tokenizer.save_pretrained(tmpdir)

        for root, dirs, files in os.walk(tmpdir):
            for fname in files:
                local_path = os.path.join(root, fname)
                blob_name = f'{gcs_prefix}/{os.path.relpath(local_path, tmpdir)}'
                bucket.blob(blob_name).upload_from_filename(local_path)
        print(f'  Uploaded to gs://{GCS_BUCKET}/{gcs_prefix}')

    info['artifact_uri'] = f'gs://{GCS_BUCKET}/{gcs_prefix}'

# set artifact_uri for any that were already uploaded
for version, info in MODELS.items():
    if 'artifact_uri' not in info:
        info['artifact_uri'] = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/models/{version}'

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

v1 (distilbert-base-uncased-finetuned-sst-2-english) already in GCS at gs://statmike-mlops-349915/mlops/airflow-batch/models/v1
v2 (textattack/bert-base-uncased-SST-2) already in GCS at gs://statmike-mlops-349915/mlops/airflow-batch/models/v2

In [14]:
for version, info in MODELS.items():
    blobs = list(bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/models/{version}'))
    print(f'{version} ({info["display_name"]}): {len(blobs)} files at {info["artifact_uri"]}')

v1 (distilbert-sst2): 4 files at gs://statmike-mlops-349915/mlops/airflow-batch/models/v1
v2 (bert-sst2): 4 files at gs://statmike-mlops-349915/mlops/airflow-batch/models/v2

---
## Create BigQuery Input Data

Create the same input table used across the batch inference series. The `category` and `created_date` columns exist for post-processing enrichment — the model only uses `text`.

In [15]:
# Create BQ dataset
dataset_ref = bigquery.Dataset(f'{PROJECT_ID}.{BQ_DATASET}')
dataset_ref.location = REGION
try:
    bq_client.get_dataset(dataset_ref)
    print(f'Dataset {BQ_DATASET} already exists')
except Exception:
    bq_client.create_dataset(dataset_ref)
    print(f'Created dataset {BQ_DATASET}')

# Create input table
BQ_TABLE = 'input_data'
schema = [
    bigquery.SchemaField('id', 'INTEGER'),
    bigquery.SchemaField('text', 'STRING'),
    bigquery.SchemaField('category', 'STRING'),
    bigquery.SchemaField('created_date', 'DATE'),
]

categories = ['entertainment', 'dining', 'general', 'product', 'product',
              'weather', 'service', 'entertainment', 'product', 'general']
rows = [
    {'id': i + 1, 'text': text, 'category': categories[i], 'created_date': '2026-04-18'}
    for i, text in enumerate(SENTENCES)
]

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition='WRITE_TRUNCATE',
)
bq_client.load_table_from_json(
    rows, f'{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}', job_config=job_config
).result()
print(f'Loaded {len(rows)} rows into {BQ_TABLE} (WRITE_TRUNCATE)')

bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}` ORDER BY id LIMIT 3').to_dataframe()

Dataset mlops_airflow_batch already exists
Loaded 10 rows into input_data (WRITE_TRUNCATE)

,id,text,category,created_date
0,1,This movie is absolutely wonderful and I loved...,entertainment,2026-04-18
1,2,The food was terrible and the service was even...,dining,2026-04-18
2,3,"An average experience, nothing special but not...",general,2026-04-18

---
## Cloud Composer Environment

[Cloud Composer](https://cloud.google.com/composer/docs/concepts/overview) is managed Apache Airflow. It handles the Airflow webserver, scheduler, workers, metadata database, and GCS bucket for DAGs.

> **First run:** Creating a Composer environment takes **~25 minutes**. The cell below checks for an existing environment first and reuses it if found. Subsequent runs skip creation entirely.

In [16]:
COMPOSER_ENV = f'{SERIES}-{EXPERIMENT}'
print(f'Composer environment name: {COMPOSER_ENV}')

Composer environment name: mlops-airflow-batch

In [17]:
# Grant the Composer v2 Service Agent Extension role (required for environment creation)
# This is idempotent — safe to run multiple times
!gcloud projects add-iam-policy-binding {PROJECT_ID} \
    --member=serviceAccount:service-{PROJECT_NUMBER}@cloudcomposer-accounts.iam.gserviceaccount.com \
    --role=roles/composer.ServiceAgentV2Ext \
    --condition=None \
    --quiet > /dev/null 2>&1
print('Composer Service Agent role granted')

Composer Service Agent role granted

In [18]:
# Check for existing environment, create if not found
env_path = f'projects/{PROJECT_ID}/locations/{REGION}/environments/{COMPOSER_ENV}'

try:
    env = composer_client.get_environment(name=env_path)
    print(f'Found existing environment: {COMPOSER_ENV} (state: {env.state.name})')
except Exception:
    print(f'Creating Composer 2 environment: {COMPOSER_ENV} (this takes ~25 minutes) ...')
    env_config = service_v1.Environment(
        name=env_path,
        config=service_v1.EnvironmentConfig(
            software_config=service_v1.SoftwareConfig(
                image_version='composer-2-airflow-2',
            ),
            node_config=service_v1.NodeConfig(
                service_account=f'{PROJECT_NUMBER}-compute@developer.gserviceaccount.com',
            ),
            environment_size=service_v1.EnvironmentConfig.EnvironmentSize.ENVIRONMENT_SIZE_SMALL,
        ),
    )
    operation = composer_client.create_environment(
        parent=f'projects/{PROJECT_ID}/locations/{REGION}',
        environment=env_config,
    )
    env = operation.result(timeout=2400)  # blocks until RUNNING (~25 min)
    print(f'Environment created: {COMPOSER_ENV} (state: {env.state.name})')

Found existing environment: mlops-airflow-batch (state: RUNNING)

In [19]:
# Extract environment details
AIRFLOW_URI = env.config.airflow_uri
DAG_GCS_PREFIX = env.config.dag_gcs_prefix

print(f'Airflow UI:   {AIRFLOW_URI}')
print(f'DAGs bucket:  {DAG_GCS_PREFIX}')

# Parse the DAGs GCS bucket and prefix for file uploads
dag_bucket_name = DAG_GCS_PREFIX.replace('gs://', '').split('/')[0]
dag_prefix = '/'.join(DAG_GCS_PREFIX.replace('gs://', '').split('/')[1:])
dag_bucket = gcs.bucket(dag_bucket_name)
print(f'DAG uploads:  gs://{dag_bucket_name}/{dag_prefix}/')

Airflow UI:   https://a259bb476a794f3f97cfc1cdc1167ce4-dot-us-central1.composer.googleusercontent.com
DAGs bucket:  gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags
DAG uploads:  gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/

### Environment Sizing

| Size | Workers | Scheduler | Database | Best For |
|------|---------|-----------|----------|----------|
| Small | 1-3 | 0.5 vCPU | db-f1-micro | Dev/test, light workloads |
| Medium | 2-6 | 2 vCPU | db-custom-2 | Production, moderate DAGs |
| Large | 3-12 | 4 vCPU | db-custom-4 | High-throughput, many DAGs |

We use **Small** for this demo. The operators launch work on external services (Dataproc, Dataflow, Vertex AI) — Composer workers just submit and monitor, so they need minimal resources.

---
## Why Airflow for Batch ML

KFP (Notebooks 1-3) handles **how** to run inference — pipeline logic, artifact tracking, model lineage. Airflow handles **when** and **what around it**:

**Scheduling:** Cron-based or event-driven triggers. Run inference daily at 2 AM, or when new data lands.

**Data Dependencies:** `BigQueryCheckOperator` waits for today's partition to exist before starting inference — no wasted compute on missing data.

**Backfill:** Missed a day? `airflow dags backfill --start-date 2026-04-15 --end-date 2026-04-17` reruns the DAG for each missing date. KFP has no native equivalent.

**Cross-System Coordination:** Airflow DAGs can combine BQ checks, ML inference, Slack notifications, and downstream ETL in one workflow.

**Monitoring & Alerting:** Built-in retry, SLA tracking, failure callbacks. Page the on-call when inference fails or misses its deadline.

### Production Flow

```
Data Landing (scheduled/event)
    |
    v
Data Validation (Airflow: BigQueryCheckOperator)
    |
    v
ML Inference (Airflow triggers: Dataproc / Dataflow / Vertex AI / KFP)
    |
    v
Result Validation (Airflow: BigQueryCheckOperator on output)
    |
    v
Downstream Systems (Airflow: BQ transforms, notifications, exports)
```

This notebook demonstrates the "ML Inference" step — Airflow triggering batch inference on four different compute platforms.

---
## Shared Infrastructure

Container builds for the Dataflow SDK container (DAG 2) and the Vertex AI prediction container (DAG 4) both require Artifact Registry.

In [20]:
# Create or retrieve Artifact Registry repo
docker_repo = None
for repo in ar.list_repositories(parent=f'projects/{PROJECT_ID}/locations/{REGION}'):
    if AR_REPO == repo.name.split('/')[-1]:
        docker_repo = repo
        print(f'Retrieved existing repo: {docker_repo.name}')

if not docker_repo:
    operation = ar.create_repository(
        request=artifactregistry_v1.CreateRepositoryRequest(
            parent=f'projects/{PROJECT_ID}/locations/{REGION}',
            repository_id=AR_REPO,
            repository=artifactregistry_v1.Repository(
                description=f'Docker images for the {SERIES} series.',
                name=AR_REPO,
                format_=artifactregistry_v1.Repository.Format.DOCKER,
                labels={'series': SERIES},
            ),
        )
    )
    print('Creating Artifact Registry repo ...')
    docker_repo = operation.result()
    print(f'Created: {docker_repo.name}')

REPOSITORY = f"{REGION}-docker.pkg.dev/{PROJECT_ID}/{docker_repo.name.split('/')[-1]}"
print(f'Repository: {REPOSITORY}')

Retrieved existing repo: projects/statmike-mlops-349915/locations/us-central1/repositories/mlops-docker
Repository: us-central1-docker.pkg.dev/statmike-mlops-349915/mlops-docker

---
## Prepare Inference Scripts

The Dataproc and Dataflow DAGs launch standalone Python scripts. These are the same proven scripts from [Notebook 2 (Dataflow)](./Batch%20Inference%20With%20Dataflow.ipynb) and [Notebook 3 (Dataproc)](./Batch%20Inference%20With%20Dataproc.ipynb) — copied here so this notebook is self-contained.

In [21]:
%%writefile {DIR}/inference.py
"""Standalone PySpark script for sentiment batch inference on Dataproc Serverless."""
import argparse
import os
import tempfile

from pyspark.sql import SparkSession
from pyspark.sql.functions import pandas_udf, col, lit, round as spark_round
from pyspark.sql.types import StructType, StructField, StringType, FloatType
import pandas as pd

# Module-level model cache — persists across UDF calls within the same executor
_model_cache = {}


def get_model(model_gcs_uri):
    """Load model from GCS, caching after first load per executor."""
    if model_gcs_uri not in _model_cache:
        from transformers import pipeline as hf_pipeline
        from google.cloud import storage

        client = storage.Client()
        parts = model_gcs_uri.replace('gs://', '').split('/', 1)
        bkt = client.bucket(parts[0])
        prefix = parts[1]
        model_dir = tempfile.mkdtemp()
        for blob in bkt.list_blobs(prefix=prefix):
            rel = blob.name[len(prefix):].lstrip('/')
            if rel:
                local = os.path.join(model_dir, rel)
                os.makedirs(os.path.dirname(local), exist_ok=True)
                blob.download_to_filename(local)
        # Load tokenizer explicitly — DistilBERT doesn't accept token_type_ids
        # but some transformers versions (e.g. runtime 2.2) generate them
        from transformers import AutoTokenizer
        tokenizer = AutoTokenizer.from_pretrained(model_dir)
        if 'token_type_ids' in tokenizer.model_input_names:
            tokenizer.model_input_names.remove('token_type_ids')
        _model_cache[model_gcs_uri] = hf_pipeline(
            'sentiment-analysis', model=model_dir, tokenizer=tokenizer
        )
    return _model_cache[model_gcs_uri]


def run():
    parser = argparse.ArgumentParser()
    parser.add_argument('--project', required=True)
    parser.add_argument('--bq_dataset', required=True)
    parser.add_argument('--source_table', required=True)
    parser.add_argument('--output_table', required=True)
    parser.add_argument('--model_gcs_uri', required=True)
    parser.add_argument('--model_name', default='distilbert')
    parser.add_argument('--temp_bucket', required=True)
    args = parser.parse_args()

    spark = SparkSession.builder.appName('batch-inference').getOrCreate()
    spark.conf.set('temporaryGcsBucket', args.temp_bucket)

    # Read from BigQuery
    df = spark.read.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.source_table}') \
        .load() \
        .select('id', 'text', 'category')

    # Define sentiment UDF with struct return type
    model_uri = args.model_gcs_uri

    schema = StructType([
        StructField('label', StringType()),
        StructField('score', FloatType()),
    ])

    @pandas_udf(schema)
    def sentiment_udf(texts: pd.Series) -> pd.DataFrame:
        pipe = get_model(model_uri)
        results = pipe(texts.tolist(), batch_size=32)
        return pd.DataFrame(results)

    # Apply inference and format output
    result_df = df.withColumn('prediction', sentiment_udf(col('text')))
    output_df = result_df.select(
        col('id'),
        col('text'),
        col('prediction.label').alias('label'),
        spark_round(col('prediction.score'), 6).alias('score'),
        lit(args.model_name).alias('model'),
    )

    # Write to BigQuery
    output_df.write.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.output_table}') \
        .mode('overwrite') \
        .save()

    print(f'Results written to {args.project}.{args.bq_dataset}.{args.output_table}')


if __name__ == '__main__':
    run()

Overwriting files/airflow/inference.py

In [22]:
%%writefile {DIR}/pipeline.py
"""Standalone Beam pipeline for sentiment batch inference."""
import argparse, json, logging, os, tempfile

logging.basicConfig(level=logging.INFO)

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions, SetupOptions
from apache_beam.ml.inference.base import ModelHandler, PredictionResult, RunInference


class SentimentModelHandler(ModelHandler):
    def __init__(self, model_gcs_uri):
        self._model_gcs_uri = model_gcs_uri

    def load_model(self):
        from transformers import pipeline as hf_pipeline
        from google.cloud import storage
        client = storage.Client()
        parts = self._model_gcs_uri.replace('gs://', '').split('/', 1)
        bkt = client.bucket(parts[0])
        prefix = parts[1]
        model_dir = tempfile.mkdtemp()
        for blob in bkt.list_blobs(prefix=prefix):
            rel = blob.name[len(prefix):].lstrip('/')
            if rel:
                local = os.path.join(model_dir, rel)
                os.makedirs(os.path.dirname(local), exist_ok=True)
                blob.download_to_filename(local)
        return hf_pipeline('sentiment-analysis', model=model_dir, tokenizer=model_dir)

    def run_inference(self, batch, model, inference_args=None):
        texts = [e['text'] for e in batch]
        results = model(texts)
        return [PredictionResult(example=e, inference=r) for e, r in zip(batch, results)]

    def batch_elements_kwargs(self):
        return {'min_batch_size': 1, 'max_batch_size': 32}


class PreprocessFn(beam.DoFn):
    def process(self, row):
        text = row.get('text', '')
        if isinstance(text, str):
            text = text.strip()
        if text:
            yield {'id': row.get('id', 0), 'text': text, 'category': row.get('category', '')}


class PostprocessFn(beam.DoFn):
    def process(self, prediction_result):
        element = prediction_result.example
        result = prediction_result.inference
        yield {
            'id': element['id'],
            'text': element['text'],
            'label': result['label'],
            'score': round(result['score'], 6),
            'model': 'distilbert',
        }


def run(argv=None):
    parser = argparse.ArgumentParser()
    # Note: --project is NOT declared here because DataflowPythonJobOp
    # auto-injects --project into the command. Declaring it here would
    # consume it via parse_known_args, preventing Beam from seeing it.
    parser.add_argument('--bq_dataset', required=True)
    parser.add_argument('--source_table', required=True)
    parser.add_argument('--output_table', required=True)
    parser.add_argument('--model_gcs_uri', required=True)
    known_args, pipeline_args = parser.parse_known_args(argv)

    # Get project from Beam pipeline options (auto-injected by the component)
    options = PipelineOptions(pipeline_args)
    options.view_as(SetupOptions).save_main_session = True
    project = options.get_all_options()['project']

    handler = SentimentModelHandler(known_args.model_gcs_uri)
    schema = 'id:INTEGER,text:STRING,label:STRING,score:FLOAT64,model:STRING'

    with beam.Pipeline(options=options) as p:
        (
            p
            | 'Read' >> beam.io.ReadFromBigQuery(
                query=f'SELECT id, text, category FROM `{project}.{known_args.bq_dataset}.{known_args.source_table}`',
                use_standard_sql=True,
            )
            | 'Preprocess' >> beam.ParDo(PreprocessFn())
            | 'Infer' >> RunInference(model_handler=handler)
            | 'Postprocess' >> beam.ParDo(PostprocessFn())
            | 'Write' >> beam.io.WriteToBigQuery(
                table=f'{project}:{known_args.bq_dataset}.{known_args.output_table}',
                schema=schema,
                write_disposition=beam.io.BigQueryDisposition.WRITE_TRUNCATE,
                create_disposition=beam.io.BigQueryDisposition.CREATE_IF_NEEDED,
            )
        )


if __name__ == '__main__':
    run()

Overwriting files/airflow/pipeline.py

In [23]:
%%writefile {DIR}/requirements.txt
transformers
torch
sentencepiece
google-cloud-storage

Overwriting files/airflow/requirements.txt

In [24]:
# Upload inference scripts and requirements to GCS
for f in ['inference.py', 'pipeline.py', 'requirements.txt']:
    blob_path = f'{SERIES}/{EXPERIMENT}/airflow/{f}'
    bucket.blob(blob_path).upload_from_filename(f'{DIR}/{f}')
    print(f'Uploaded: gs://{GCS_BUCKET}/{blob_path}')

Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/airflow/inference.py
Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/airflow/pipeline.py
Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/airflow/requirements.txt

In [25]:
# Compile a KFP pipeline for the Airflow → KFP pattern
# This reuses the DataprocPySparkBatchOp pattern from Notebook 3
from kfp import dsl, compiler
from google_cloud_pipeline_components.v1.dataproc import DataprocPySparkBatchOp

@dsl.pipeline(
    name='airflow-dataproc-inference',
    description='Dataproc batch inference triggered by Airflow',
)
def airflow_inference_pipeline(
    project: str,
    region: str,
    script_gcs_path: str,
    model_gcs_uri: str,
    model_name: str,
    bq_dataset: str,
    source_table: str,
    output_table: str = 'kfp_predictions',
    temp_bucket: str = '',
):
    task = DataprocPySparkBatchOp(
        project=project,
        location=region,
        main_python_file_uri=script_gcs_path,
        runtime_config_version='2.2',
        runtime_config_properties={
            'spark.executor.instances': '2',
            'spark.driver.memory': '4g',
            'spark.executor.memory': '4g',
        },
        args=[
            '--project', project,
            '--bq_dataset', bq_dataset,
            '--source_table', source_table,
            '--output_table', output_table,
            '--model_gcs_uri', model_gcs_uri,
            '--model_name', model_name,
            '--temp_bucket', temp_bucket,
        ],
    )
    task.set_caching_options(False)

# Compile and upload
pipeline_json = f'{DIR}/airflow_inference_pipeline.json'
compiler.Compiler().compile(
    pipeline_func=airflow_inference_pipeline,
    package_path=pipeline_json,
)
print(f'Pipeline compiled to {pipeline_json}')

# Upload template to GCS
blob_path = f'{SERIES}/{EXPERIMENT}/airflow/airflow_inference_pipeline.json'
bucket.blob(blob_path).upload_from_filename(pipeline_json)
PIPELINE_TEMPLATE_GCS = f'gs://{GCS_BUCKET}/{blob_path}'
print(f'Pipeline template: {PIPELINE_TEMPLATE_GCS}')

Pipeline compiled to files/airflow/airflow_inference_pipeline.json
Pipeline template: gs://statmike-mlops-349915/mlops/airflow-batch/airflow/airflow_inference_pipeline.json

In [26]:
import time

def wait_for_dag_parsed(dag_id, timeout=300, poll_interval=15):
    """Wait until Airflow has parsed and registered the DAG."""
    print(f'Waiting for Airflow to parse DAG: {dag_id} ...')
    start = time.time()
    while time.time() - start < timeout:
        result = !gcloud composer environments run {COMPOSER_ENV} \
            --location {REGION} \
            dags list -- -o plain 2>/dev/null
        if dag_id in '\n'.join(result):
            print(f'DAG {dag_id} registered ({int(time.time() - start)}s)')
            return True
        time.sleep(poll_interval)
    raise TimeoutError(f'DAG {dag_id} not parsed after {timeout}s — check Airflow import errors')

def trigger_dag(dag_id, max_retries=3, retry_delay=20):
    """Trigger a DAG, retrying on scheduler-to-webserver sync delays."""
    for attempt in range(max_retries):
        result = !gcloud composer environments run {COMPOSER_ENV} \
            --location {REGION} \
            dags trigger -- {dag_id} 2>&1
        output = '\n'.join(result)
        if 'not found' not in output.lower():
            print(f'DAG {dag_id} triggered')
            return True
        if attempt < max_retries - 1:
            print(f'DAG {dag_id}: not ready (sync delay), retrying in {retry_delay}s ...')
            time.sleep(retry_delay)
    raise RuntimeError(f'Failed to trigger DAG {dag_id} after {max_retries} attempts')

def wait_for_dag(dag_id, timeout=1800, poll_interval=30):
    """Poll DAG run status until success or failure (checks latest run only)."""
    start = time.time()
    while time.time() - start < timeout:
        result = !gcloud composer environments run {COMPOSER_ENV} \
            --location {REGION} \
            dags list-runs -- -d {dag_id} -o table 2>/dev/null
        output = '\n'.join(result)
        if 'no data found' in output.lower():
            print(f'DAG {dag_id}: no run found — trigger may have failed')
            return 'not_triggered'
        # Check only the FIRST data row (latest run) — skip headers/separators
        for line in result:
            stripped = line.strip()
            if not stripped or stripped.startswith('=') or stripped.startswith('dag_id') or stripped.startswith('conf') or stripped.startswith('['):
                continue
            lower = stripped.lower()
            if '| success' in lower:
                print(f'DAG {dag_id}: SUCCESS ({int(time.time() - start)}s)')
                return 'success'
            elif '| failed' in lower:
                print(f'DAG {dag_id}: FAILED ({int(time.time() - start)}s)')
                return 'failed'
            elif '| running' in lower or '| queued' in lower:
                break  # still in progress, continue polling
            break  # unknown format, continue polling
        print(f'DAG {dag_id}: running ({int(time.time() - start)}s elapsed) ...')
        time.sleep(poll_interval)
    print(f'DAG {dag_id}: TIMEOUT after {timeout}s')
    return 'timeout'

print('Helper functions defined: wait_for_dag_parsed(), trigger_dag(), wait_for_dag()')

Helper functions defined: wait_for_dag_parsed(), trigger_dag(), wait_for_dag()

---
## DAG 1: Airflow → Dataproc

The simplest pattern. Airflow launches a Dataproc Serverless batch job directly using [`DataprocCreateBatchOperator`](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/dataproc.html). The operator submits the PySpark script and waits for completion.

> **Production tip:** Add `deferrable=True` to release the Airflow worker slot while waiting for long-running jobs. This requires a Medium+ Composer environment with a dedicated triggerer process.

In [27]:
# Write DAG file with project-specific values injected
dag_dataproc = f'''"""DAG: Batch inference via Dataproc Serverless."""
from datetime import datetime
from airflow import models
from airflow.providers.google.cloud.operators.dataproc import DataprocCreateBatchOperator

PROJECT_ID = '{PROJECT_ID}'
REGION = '{REGION}'
SCRIPT_GCS = 'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/airflow/inference.py'
MODEL_GCS = '{MODELS["v1"]["artifact_uri"]}'
BQ_DATASET = '{BQ_DATASET}'
SOURCE_TABLE = '{BQ_TABLE}'
OUTPUT_TABLE = 'dataproc_predictions'

with models.DAG(
    'batch_inference_dataproc',
    schedule_interval=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=['batch-inference', 'dataproc'],
) as dag:

    run_inference = DataprocCreateBatchOperator(
        task_id='run_dataproc_inference',
        region=REGION,
        project_id=PROJECT_ID,
        batch={{
            'pyspark_batch': {{
                'main_python_file_uri': SCRIPT_GCS,
                'args': [
                    '--project', PROJECT_ID,
                    '--bq_dataset', BQ_DATASET,
                    '--source_table', SOURCE_TABLE,
                    '--output_table', OUTPUT_TABLE,
                    '--model_gcs_uri', MODEL_GCS,
                    '--model_name', 'distilbert',
                    '--temp_bucket', PROJECT_ID,
                ],
            }},
            'runtime_config': {{'version': '2.2'}},
        }},
        batch_id='airflow-dp-' + '{{{{ ts_nodash | lower }}}}',
    )
'''

with open(f'{DIR}/dag_dataproc.py', 'w') as f:
    f.write(dag_dataproc)
print(f'Written: {DIR}/dag_dataproc.py')

Written: files/airflow/dag_dataproc.py

In [28]:
# Upload DAG to Composer's DAGs bucket
dag_blob = dag_bucket.blob(f'{dag_prefix}/dag_dataproc.py')
dag_blob.upload_from_filename(f'{DIR}/dag_dataproc.py')
print(f'Uploaded DAG to: gs://{dag_bucket_name}/{dag_prefix}/dag_dataproc.py')
print(f'\nAirflow will parse the DAG within ~60 seconds.')
print(f'Airflow UI: {AIRFLOW_URI}')

Uploaded DAG to: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_dataproc.py

Airflow will parse the DAG within ~60 seconds.
Airflow UI: https://a259bb476a794f3f97cfc1cdc1167ce4-dot-us-central1.composer.googleusercontent.com

In [29]:
wait_for_dag_parsed('batch_inference_dataproc')
trigger_dag('batch_inference_dataproc')

Waiting for Airflow to parse DAG: batch_inference_dataproc ...
DAG batch_inference_dataproc registered (67s)
DAG batch_inference_dataproc triggered

True

In [30]:
status = wait_for_dag('batch_inference_dataproc')

DAG batch_inference_dataproc: running (51s elapsed) ...
DAG batch_inference_dataproc: SUCCESS (137s)

In [31]:
# Read Dataproc DAG results from BigQuery
dataproc_table = f'{PROJECT_ID}.{BQ_DATASET}.dataproc_predictions'
try:
    df = bq_client.query(f'SELECT * FROM `{dataproc_table}` ORDER BY id').to_dataframe()
    print(f'Dataproc results ({len(df)} rows):')
    display(df)
except Exception as e:
    print(f'Results not available: {e}')

Dataproc results (10 rows):

,id,text,label,score,model
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",POSITIVE,0.859377,distilbert
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,NEGATIVE,0.999799,distilbert
7,8,A masterpiece of storytelling with brilliant p...,POSITIVE,0.999886,distilbert
8,9,Not worth the hype. The product broke after ju...,NEGATIVE,0.999780,distilbert
9,10,"It works as expected, does the job without any...",POSITIVE,0.999659,distilbert

---
## DAG 2: Airflow → Dataflow

Uses [`BeamRunPythonPipelineOperator`](https://airflow.apache.org/docs/apache-airflow-providers-apache-beam/stable/operators.html) with `DataflowRunner`. This is the modern replacement for the deprecated `DataflowCreatePythonJobOperator` (removed in 2026 provider releases).

The operator uploads the Python pipeline script, creates a Dataflow job, and monitors it to completion.

> **Why a custom SDK container?** When a Beam pipeline has heavy dependencies (PyTorch \~2 GB), Dataflow downloads them via pip on the Airflow worker *before* submitting the job. On Composer SMALL environments, this blocks the worker long enough to trigger Airflow's zombie task detection — the scheduler kills the task thinking it's stuck. Building a [custom SDK container](https://cloud.google.com/dataflow/docs/guides/using-custom-containers) with dependencies pre-installed bypasses the local pip download entirely.

### Build Dataflow SDK Container

The SDK container is used by Dataflow *workers* — it must be based on the official `apache/beam_python3.x_sdk` image with the same Beam version installed in the Composer environment.

In [32]:
# Get the Beam version installed in the Composer environment
result = !gcloud composer environments describe {COMPOSER_ENV} \
    --location {REGION} \
    --format="value(config.softwareConfig.imageVersion)"

IMAGE_VERSION = result[0].strip()
print(f'Composer image: {IMAGE_VERSION}')

# Get package list from the environment
pkg_result = !gcloud composer environments list-packages {COMPOSER_ENV} \
    --location {REGION} 2>/dev/null

BEAM_VERSION = None
for line in pkg_result:
    if line.strip().startswith('apache-beam') or line.strip().startswith('apache_beam'):
        parts = line.strip().split()
        if len(parts) >= 2:
            BEAM_VERSION = parts[1].strip()
            break

if not BEAM_VERSION:
    raise RuntimeError(f'Could not determine Beam version. Package list output: {pkg_result}')
print(f'Beam SDK version in Composer: {BEAM_VERSION}')

Composer image: composer-2.16.11-airflow-2.11.1
Beam SDK version in Composer: 2.72.0

In [33]:
# Build custom SDK container with ML dependencies pre-installed
SDK_IMAGE = f'{REPOSITORY}/beam-ml-sdk'

dockerfile_content = f"""FROM apache/beam_python3.11_sdk:{BEAM_VERSION}
RUN pip install --no-cache-dir transformers torch sentencepiece google-cloud-storage
"""

# Write Dockerfile to GCS for Cloud Build
bucket.blob(f'{SERIES}/{EXPERIMENT}/beam-sdk/Dockerfile').upload_from_string(dockerfile_content)

build = cloudbuild_v1.Build(steps=[])

# Step 1: retrieve Dockerfile from GCS
build.steps.append({
    'name': 'gcr.io/cloud-builders/gsutil',
    'args': ['cp', f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/beam-sdk/Dockerfile', '/workspace/Dockerfile'],
})

# Step 2: docker build
build.steps.append({
    'name': 'gcr.io/cloud-builders/docker',
    'args': ['build', '-t', SDK_IMAGE, '/workspace'],
})

build.images = [SDK_IMAGE]

print(f'Building Beam SDK container ({BEAM_VERSION} + ML deps) with Cloud Build ...')
print('This takes ~5-8 minutes (downloading torch into the container)')
operation = cb.create_build(project_id=PROJECT_ID, build=build)
build_response = operation.result()
print(f'Build status: {build_response.status.name}')
SDK_CONTAINER_IMAGE = SDK_IMAGE
print(f'SDK container: {SDK_CONTAINER_IMAGE}')

Building Beam SDK container (2.72.0 + ML deps) with Cloud Build ...
This takes ~5-8 minutes (downloading torch into the container)

Build status: SUCCESS
SDK container: us-central1-docker.pkg.dev/statmike-mlops-349915/mlops-docker/beam-ml-sdk

In [34]:
dag_dataflow = f'''"""DAG: Batch inference via Dataflow (Beam RunInference)."""
from datetime import datetime
from airflow import models
from airflow.providers.apache.beam.operators.beam import BeamRunPythonPipelineOperator
from airflow.providers.google.cloud.operators.dataflow import DataflowConfiguration

PROJECT_ID = '{PROJECT_ID}'
REGION = '{REGION}'
PIPELINE_GCS = 'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/airflow/pipeline.py'
MODEL_GCS = '{MODELS["v1"]["artifact_uri"]}'
BQ_DATASET = '{BQ_DATASET}'
SOURCE_TABLE = '{BQ_TABLE}'
OUTPUT_TABLE = 'dataflow_predictions'
GCS_BUCKET = '{GCS_BUCKET}'
SDK_CONTAINER = '{SDK_CONTAINER_IMAGE}'

with models.DAG(
    'batch_inference_dataflow',
    schedule_interval=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=['batch-inference', 'dataflow'],
) as dag:

    run_inference = BeamRunPythonPipelineOperator(
        task_id='run_dataflow_inference',
        runner='DataflowRunner',
        py_file=PIPELINE_GCS,
        pipeline_options={{
            'bq_dataset': BQ_DATASET,
            'source_table': SOURCE_TABLE,
            'output_table': OUTPUT_TABLE,
            'model_gcs_uri': MODEL_GCS,
            'sdk_container_image': SDK_CONTAINER,
            'temp_location': f'gs://{{GCS_BUCKET}}/dataflow/temp',
            'staging_location': f'gs://{{GCS_BUCKET}}/dataflow/staging',
            'project': PROJECT_ID,
            'region': REGION,
            'machine_type': 'n1-standard-4',
            'num_workers': '2',
            'max_num_workers': '4',
        }},
        dataflow_config=DataflowConfiguration(
            project_id=PROJECT_ID,
            location=REGION,
            job_name='airflow-dataflow-inference',
            wait_until_finished=True,
        ),
    )
'''

with open(f'{DIR}/dag_dataflow.py', 'w') as f:
    f.write(dag_dataflow)
print(f'Written: {DIR}/dag_dataflow.py')

Written: files/airflow/dag_dataflow.py

In [35]:
dag_blob = dag_bucket.blob(f'{dag_prefix}/dag_dataflow.py')
dag_blob.upload_from_filename(f'{DIR}/dag_dataflow.py')
print(f'Uploaded DAG to: gs://{dag_bucket_name}/{dag_prefix}/dag_dataflow.py')
print(f'Airflow will parse the DAG within ~60 seconds.')

Uploaded DAG to: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_dataflow.py
Airflow will parse the DAG within ~60 seconds.

In [36]:
wait_for_dag_parsed('batch_inference_dataflow')
trigger_dag('batch_inference_dataflow')

Waiting for Airflow to parse DAG: batch_inference_dataflow ...
DAG batch_inference_dataflow registered (126s)
DAG batch_inference_dataflow triggered

True

In [37]:
status = wait_for_dag('batch_inference_dataflow')

DAG batch_inference_dataflow: running (63s elapsed) ...
DAG batch_inference_dataflow: running (154s elapsed) ...
DAG batch_inference_dataflow: running (243s elapsed) ...
DAG batch_inference_dataflow: running (326s elapsed) ...
DAG batch_inference_dataflow: SUCCESS (448s)

In [38]:
# Read Dataflow DAG results from BigQuery
dataflow_table = f'{PROJECT_ID}.{BQ_DATASET}.dataflow_predictions'
try:
    df = bq_client.query(f'SELECT * FROM `{dataflow_table}` ORDER BY id').to_dataframe()
    print(f'Dataflow results ({len(df)} rows):')
    display(df)
except Exception as e:
    print(f'Results not available: {e}')

Dataflow results (10 rows):

,id,text,label,score,model
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",POSITIVE,0.859379,distilbert
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,NEGATIVE,0.999799,distilbert
7,8,A masterpiece of storytelling with brilliant p...,POSITIVE,0.999886,distilbert
8,9,Not worth the hype. The product broke after ju...,NEGATIVE,0.999780,distilbert
9,10,"It works as expected, does the job without any...",POSITIVE,0.999659,distilbert

---
## DAG 3: Airflow → KFP Pipeline

The cleanest separation of concerns: Airflow handles *when* (scheduling, data dependencies), KFP handles *how* (ML pipeline logic, artifact tracking, lineage).

[`RunPipelineJobOperator`](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/vertex_ai.html) triggers a compiled KFP pipeline stored in GCS. The pipeline we compiled earlier uses `DataprocPySparkBatchOp` — so this is Airflow → KFP → Dataproc, a three-layer orchestration.

**When to use this pattern:**
- Team already uses KFP for ML pipeline management
- Need artifact lineage and experiment tracking (KFP provides this, Airflow doesn't)
- ML pipeline has multiple steps (preprocess → inference → postprocess) that benefit from KFP's DAG visualization

In [39]:
dag_kfp = f'''"""DAG: Batch inference via Vertex AI Pipelines (KFP)."""
from datetime import datetime
from airflow import models
from airflow.providers.google.cloud.operators.vertex_ai.pipeline_job import RunPipelineJobOperator

PROJECT_ID = '{PROJECT_ID}'
REGION = '{REGION}'
PIPELINE_TEMPLATE = '{PIPELINE_TEMPLATE_GCS}'
SCRIPT_GCS = 'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/airflow/inference.py'
MODEL_GCS = '{MODELS["v1"]["artifact_uri"]}'
BQ_DATASET = '{BQ_DATASET}'
SOURCE_TABLE = '{BQ_TABLE}'

with models.DAG(
    'batch_inference_kfp',
    schedule_interval=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=['batch-inference', 'kfp'],
) as dag:

    run_pipeline = RunPipelineJobOperator(
        task_id='run_kfp_pipeline',
        project_id=PROJECT_ID,
        region=REGION,
        display_name='airflow-kfp-inference',
        template_path=PIPELINE_TEMPLATE,
        parameter_values={{
            'project': PROJECT_ID,
            'region': REGION,
            'script_gcs_path': SCRIPT_GCS,
            'model_gcs_uri': MODEL_GCS,
            'model_name': 'distilbert',
            'bq_dataset': BQ_DATASET,
            'source_table': SOURCE_TABLE,
            'output_table': 'kfp_predictions',
            'temp_bucket': PROJECT_ID,
        }},
    )
'''

with open(f'{DIR}/dag_kfp.py', 'w') as f:
    f.write(dag_kfp)
print(f'Written: {DIR}/dag_kfp.py')

Written: files/airflow/dag_kfp.py

In [40]:
dag_blob = dag_bucket.blob(f'{dag_prefix}/dag_kfp.py')
dag_blob.upload_from_filename(f'{DIR}/dag_kfp.py')
print(f'Uploaded DAG to: gs://{dag_bucket_name}/{dag_prefix}/dag_kfp.py')
print(f'Airflow will parse the DAG within ~60 seconds.')

Uploaded DAG to: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_kfp.py
Airflow will parse the DAG within ~60 seconds.

In [41]:
wait_for_dag_parsed('batch_inference_kfp')
trigger_dag('batch_inference_kfp')

Waiting for Airflow to parse DAG: batch_inference_kfp ...
DAG batch_inference_kfp registered (98s)
DAG batch_inference_kfp triggered

True

In [42]:
status = wait_for_dag('batch_inference_kfp', timeout=2400)

DAG batch_inference_kfp: running (51s elapsed) ...
DAG batch_inference_kfp: running (142s elapsed) ...
DAG batch_inference_kfp: running (224s elapsed) ...
DAG batch_inference_kfp: running (316s elapsed) ...
DAG batch_inference_kfp: running (380s elapsed) ...
DAG batch_inference_kfp: SUCCESS (461s)

In [43]:
# Read KFP DAG results from BigQuery
kfp_table = f'{PROJECT_ID}.{BQ_DATASET}.kfp_predictions'
try:
    df = bq_client.query(f'SELECT * FROM `{kfp_table}` ORDER BY id').to_dataframe()
    print(f'KFP pipeline results ({len(df)} rows):')
    display(df)
except Exception as e:
    print(f'Results not available: {e}')

KFP pipeline results (10 rows):

,id,text,label,score,model
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",POSITIVE,0.859377,distilbert
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,NEGATIVE,0.999799,distilbert
7,8,A masterpiece of storytelling with brilliant p...,POSITIVE,0.999886,distilbert
8,9,Not worth the hype. The product broke after ju...,NEGATIVE,0.999780,distilbert
9,10,"It works as expected, does the job without any...",POSITIVE,0.999659,distilbert

### Airflow → KFP vs Direct

| Aspect | Airflow → KFP | Airflow Direct |
|--------|:-:|:-:|
| ML artifact lineage | KFP tracks artifacts, models, metrics | No tracking |
| Pipeline visualization | KFP DAG + Airflow DAG | Airflow DAG only |
| Multi-step ML logic | KFP handles preprocess → infer → postprocess | Gets complex in a single DAG |
| Overhead | Two orchestrators | One orchestrator |
| Best for | ML-first teams with existing KFP pipelines | Simple batch jobs, Airflow-native teams |

---
## DAG 4: Airflow → Vertex AI Batch Prediction

This pattern uses [`CreateBatchPredictionJobOperator`](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/vertex_ai.html) to launch a Vertex AI Batch Prediction job directly from Airflow.

Unlike patterns 1-3 which use standalone inference scripts, Vertex AI Batch Prediction requires:
1. A **serving container** in Artifact Registry that hosts the model as an API
2. A **model registered** in the Vertex AI Model Registry pointing to the container and model artifacts

We build both below, then deploy the DAG.

### Build Prediction Container

The prediction container is a FastAPI app that Vertex AI scales horizontally for batch inference. Each replica downloads model files from GCS (via `AIP_STORAGE_URI`), loads the HuggingFace model, and serves predictions on the `/predict` endpoint.

> For the full walkthrough of this container pattern, see [Notebook 1 (Vertex AI Batch Prediction)](./Vertex%20AI%20Batch%20Prediction.ipynb).

In [44]:
# Create container source directory
os.makedirs(f'{DIR}/source/app', exist_ok=True)

In [45]:
%%writefile {DIR}/source/Dockerfile
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

# Vertex AI probes AIP_HTTP_PORT (default 8080); tiangolo image binds to PORT
ENV PORT 8080
# Single worker — batch prediction only needs one, and faster startup
ENV WEB_CONCURRENCY 1

COPY ./app /app
COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

Overwriting files/airflow/source/Dockerfile

In [46]:
%%writefile {DIR}/source/requirements.txt
google-cloud-storage
transformers
torch
sentencepiece

Overwriting files/airflow/source/requirements.txt

In [47]:
%%writefile {DIR}/source/app/__init__.py
# Vertex AI serving container

Overwriting files/airflow/source/app/__init__.py

In [48]:
%%writefile {DIR}/source/app/main.py
import os
from fastapi import FastAPI, Request
from transformers import pipeline
from google.cloud import storage

app = FastAPI()

# Download model from GCS at startup (AIP_STORAGE_URI set by Vertex AI)
gcs = storage.Client()
storage_uri = os.environ['AIP_STORAGE_URI']
parts = storage_uri.replace('gs://', '').split('/', 1)
bucket = gcs.bucket(parts[0])
prefix = parts[1] if len(parts) > 1 else ''

model_dir = '/tmp/model'
os.makedirs(model_dir, exist_ok=True)
for blob in bucket.list_blobs(prefix=prefix):
    rel = blob.name[len(prefix):].lstrip('/')
    if rel:
        local = os.path.join(model_dir, rel)
        os.makedirs(os.path.dirname(local), exist_ok=True)
        blob.download_to_filename(local)

classifier = pipeline('sentiment-analysis', model=model_dir, tokenizer=model_dir)


@app.get(os.environ['AIP_HEALTH_ROUTE'], status_code=200)
def health():
    return {}


@app.post(os.environ['AIP_PREDICT_ROUTE'])
async def predict(request: Request):
    body = await request.json()
    instances = body['instances']

    texts = []
    for inst in instances:
        if isinstance(inst, str):
            texts.append(inst)
        elif isinstance(inst, dict):
            texts.append(inst.get('text', str(inst)))
        else:
            texts.append(str(inst))

    results = classifier(texts)
    predictions = [
        {'label': r['label'], 'score': round(r['score'], 6)}
        for r in results
    ]
    return {'predictions': predictions}

Overwriting files/airflow/source/app/main.py

In [49]:
%%writefile {DIR}/source/app/prestart.sh
#!/bin/bash
echo "prestart: container ready"

Overwriting files/airflow/source/app/prestart.sh

In [50]:
# Artifact Registry repo already created in the Shared Infrastructure section
print(f'Using Artifact Registry repo: {REPOSITORY}')

Using Artifact Registry repo: us-central1-docker.pkg.dev/statmike-mlops-349915/mlops-docker

In [51]:
# Upload source files to GCS for Cloud Build
source_dir = f'{DIR}/source'
gcs_prefix = f'{SERIES}/{EXPERIMENT}/source'
for root, dirs, source_files in os.walk(source_dir):
    for fname in source_files:
        local_path = os.path.join(root, fname)
        rel_path = os.path.relpath(local_path, source_dir)
        blob_path = f'{gcs_prefix}/{rel_path}'
        bucket.blob(blob_path).upload_from_filename(local_path)
        print(f'Uploaded: gs://{GCS_BUCKET}/{blob_path}')

Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/source/Dockerfile
Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/source/requirements.txt
Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/source/app/__init__.py
Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/source/app/prestart.sh
Uploaded: gs://statmike-mlops-349915/mlops/airflow-batch/source/app/main.py

In [52]:
# Build container with Cloud Build
build = cloudbuild_v1.Build(steps=[])

# Step 1: retrieve source from GCS
build.steps.append({
    'name': 'gcr.io/cloud-builders/gsutil',
    'args': ['cp', '-r', f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/source/*', '/workspace'],
})

# Step 2: docker build
build.steps.append({
    'name': 'gcr.io/cloud-builders/docker',
    'args': ['build', '-t', f'{REPOSITORY}/{EXPERIMENT}', '/workspace'],
})

build.images = [f'{REPOSITORY}/{EXPERIMENT}']

print('Building container with Cloud Build (~3-5 minutes) ...')
operation = cb.create_build(project_id=PROJECT_ID, build=build)
build_response = operation.result()
IMAGE_URI = build_response.images[0]
print(f'Build status: {build_response.status.name}')
print(f'Image: {IMAGE_URI}')

Building container with Cloud Build (~3-5 minutes) ...

Build status: SUCCESS
Image: us-central1-docker.pkg.dev/statmike-mlops-349915/mlops-docker/airflow-batch

### Register Model

Upload the model to the Vertex AI Model Registry, linking it to the container image and the GCS model artifacts.

In [53]:
# Register model — delete and re-create to pick up any container changes
existing_models = aiplatform.Model.list(
    filter=f'display_name="{EXPERIMENT}-distilbert"',
)
for m in existing_models:
    m.delete()
    print(f'Deleted existing model: {m.resource_name}')

vertex_model = aiplatform.Model.upload(
    display_name=f'{EXPERIMENT}-distilbert',
    serving_container_image_uri=IMAGE_URI,
    artifact_uri=MODELS['v1']['artifact_uri'],
    serving_container_predict_route='/predict',
    serving_container_health_route='/health',
    serving_container_environment_variables={'TIMEOUT': '600'},
    labels={'series': SERIES, 'experiment': EXPERIMENT},
)
MODEL_RESOURCE = vertex_model.resource_name
print(f'Model registered: {MODEL_RESOURCE}')

Deleting Model : projects/1026793852137/locations/us-central1/models/2262987344497868800
Model deleted. . Resource name: projects/1026793852137/locations/us-central1/models/2262987344497868800
Deleting Model resource: projects/1026793852137/locations/us-central1/models/2262987344497868800
Delete Model backing LRO: projects/1026793852137/locations/us-central1/models/2262987344497868800/operations/3305223118070480896
Model resource projects/1026793852137/locations/us-central1/models/2262987344497868800 deleted.
Deleted existing model: projects/1026793852137/locations/us-central1/models/2262987344497868800
Creating Model
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/5809783157284667392/operations/1129421548097110016

Model created. Resource name: projects/1026793852137/locations/us-central1/models/5809783157284667392@1
To use this Model in another session:
model = aiplatform.Model('projects/1026793852137/locations/us-central1/models/5809783157284667392@1')
Model registered: projects/1026793852137/locations/us-central1/models/5809783157284667392
To use this Model in another session:
model = aiplatform.Model('projects/1026793852137/locations/us-central1/models/5809783157284667392@1')
Model registered: projects/1026793852137/locations/us-central1/models/5809783157284667392

### Deploy and Trigger the DAG

In [54]:
# Write DAG file with project-specific values injected
dag_vertex = f'''"""DAG: Batch inference via Vertex AI Batch Prediction."""
from datetime import datetime
from airflow import models
from airflow.providers.google.cloud.operators.vertex_ai.batch_prediction_job import (
    CreateBatchPredictionJobOperator,
)

PROJECT_ID = '{PROJECT_ID}'
REGION = '{REGION}'
MODEL_RESOURCE = '{MODEL_RESOURCE}'
BQ_DATASET = '{BQ_DATASET}'
SOURCE_TABLE = '{BQ_TABLE}'

with models.DAG(
    'batch_inference_vertex_batch',
    schedule_interval=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=['batch-inference', 'vertex-ai'],
) as dag:

    batch_predict = CreateBatchPredictionJobOperator(
        task_id='run_vertex_batch',
        project_id=PROJECT_ID,
        region=REGION,
        model_name=MODEL_RESOURCE,
        job_display_name='airflow-vertex-batch',
        bigquery_source=f'bq://{{PROJECT_ID}}.{{BQ_DATASET}}.{{SOURCE_TABLE}}',
        bigquery_destination_prefix=f'bq://{{PROJECT_ID}}.{{BQ_DATASET}}',
        machine_type='n1-standard-4',
        starting_replica_count=1,
        max_replica_count=1,
    )
'''

with open(f'{DIR}/dag_vertex_batch.py', 'w') as f:
    f.write(dag_vertex)
print(f'Written: {DIR}/dag_vertex_batch.py')

Written: files/airflow/dag_vertex_batch.py

In [55]:
dag_blob = dag_bucket.blob(f'{dag_prefix}/dag_vertex_batch.py')
dag_blob.upload_from_filename(f'{DIR}/dag_vertex_batch.py')
print(f'Uploaded DAG to: gs://{dag_bucket_name}/{dag_prefix}/dag_vertex_batch.py')
print(f'Airflow will parse the DAG within ~60 seconds.')

Uploaded DAG to: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_vertex_batch.py
Airflow will parse the DAG within ~60 seconds.

In [56]:
wait_for_dag_parsed('batch_inference_vertex_batch')
trigger_dag('batch_inference_vertex_batch')

Waiting for Airflow to parse DAG: batch_inference_vertex_batch ...
DAG batch_inference_vertex_batch registered (92s)
DAG batch_inference_vertex_batch triggered

True

In [57]:
status = wait_for_dag('batch_inference_vertex_batch', timeout=3600)

DAG batch_inference_vertex_batch: running (58s elapsed) ...
DAG batch_inference_vertex_batch: running (139s elapsed) ...
DAG batch_inference_vertex_batch: running (228s elapsed) ...
DAG batch_inference_vertex_batch: running (319s elapsed) ...
DAG batch_inference_vertex_batch: running (403s elapsed) ...
DAG batch_inference_vertex_batch: running (468s elapsed) ...
DAG batch_inference_vertex_batch: running (537s elapsed) ...
DAG batch_inference_vertex_batch: running (617s elapsed) ...
DAG batch_inference_vertex_batch: running (698s elapsed) ...
DAG batch_inference_vertex_batch: running (778s elapsed) ...
DAG batch_inference_vertex_batch: running (848s elapsed) ...
DAG batch_inference_vertex_batch: running (936s elapsed) ...
DAG batch_inference_vertex_batch: running (1017s elapsed) ...
DAG batch_inference_vertex_batch: running (1080s elapsed) ...
DAG batch_inference_vertex_batch: running (1160s elapsed) ...
DAG batch_inference_vertex_batch: SUCCESS (1249s)

In [58]:
# Read Vertex AI Batch Prediction results
# Vertex AI creates output tables with auto-generated names in the destination dataset
vertex_tables = list(bq_client.list_tables(f'{PROJECT_ID}.{BQ_DATASET}'))
prediction_tables = [t for t in vertex_tables if t.table_id.startswith('prediction')]

if prediction_tables:
    latest = sorted(prediction_tables, key=lambda t: t.table_id)[-1]
    print(f'Vertex AI prediction table: {latest.table_id}')
    df = bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{latest.table_id}` LIMIT 10').to_dataframe()
    print(f'Vertex AI Batch results ({len(df)} rows):')
    display(df)
else:
    print('No prediction tables found — check Airflow UI for job status')

Vertex AI prediction table: predictions_2026_04_24T18_46_40_317Z_666
Vertex AI Batch results (10 rows):

,id,text,category,created_date,prediction
0,2,The food was terrible and the service was even...,dining,2026-04-18,"{""label"": ""NEGATIVE"", ""score"": 0.999767}"
1,1,This movie is absolutely wonderful and I loved...,entertainment,2026-04-18,"{""label"": ""POSITIVE"", ""score"": 0.999876}"
2,8,A masterpiece of storytelling with brilliant p...,entertainment,2026-04-18,"{""label"": ""POSITIVE"", ""score"": 0.999875}"
3,3,"An average experience, nothing special but not...",general,2026-04-18,"{""label"": ""POSITIVE"", ""score"": 0.947852}"
4,10,"It works as expected, does the job without any...",general,2026-04-18,"{""label"": ""POSITIVE"", ""score"": 0.99937}"
5,4,"I cannot believe how amazing this product is, ...",product,2026-04-18,"{""label"": ""POSITIVE"", ""score"": 0.999791}"
6,5,Disappointing quality for the price. Would not...,product,2026-04-18,"{""label"": ""NEGATIVE"", ""score"": 0.999585}"
7,9,Not worth the hype. The product broke after ju...,product,2026-04-18,"{""label"": ""NEGATIVE"", ""score"": 0.999645}"
8,7,I had the worst customer service experience of...,service,2026-04-18,"{""label"": ""NEGATIVE"", ""score"": 0.999785}"
9,6,The weather today is mild and partly cloudy.,weather,2026-04-18,"{""label"": ""NEGATIVE"", ""score"": 0.990854}"

### When to Use Vertex AI Batch Prediction via Airflow

| Use Case | Recommendation |
|----------|---------------|
| Model already in Model Registry | Vertex AI Batch — simplest path |
| Need `instanceConfig` (`keyField`, `includedFields`) | Vertex AI Batch — only option |
| Custom pre/post processing | Dataproc or Dataflow — more flexible |
| Team uses KFP for ML | Airflow → KFP — leverages existing pipelines |
| Simple batch scoring | Dataproc — fewest moving parts |

---
## Production Patterns

The DAGs above demonstrate the mechanics. In production, Airflow adds scheduling, retry, backfill, and multi-model coordination.

### Scheduling & Catchup

```python
with models.DAG(
    'daily_inference',
    schedule_interval='0 2 * * *',    # Run daily at 2 AM
    start_date=datetime(2026, 4, 1),
    catchup=False,                     # Don't backfill past dates on first deploy
    max_active_runs=1,                 # One run at a time
) as dag:
    ...
```

- `schedule_interval` accepts cron expressions or Airflow presets (`@daily`, `@hourly`)
- `catchup=False` prevents Airflow from creating runs for every missed interval since `start_date`
- `max_active_runs=1` prevents overlapping inference jobs that could compete for compute resources

### Backfill — Airflow's Killer Feature for Batch ML

Missed a day? A model was wrong and you need to re-score last week?

```bash
# Re-run inference for April 15-17
gcloud composer environments run my-env --location us-central1 \
    dags backfill -- -s 2026-04-15 -e 2026-04-17 daily_inference
```

Airflow creates one DAG run per date, each with its own execution date. The DAG code uses `{{ ds }}` (execution date template) to:
- Read the correct input partition: `WHERE date = '{{ ds }}'`
- Write to the correct output partition: `output_{{ ds_nodash }}`
- Ensure idempotency: re-running the same date overwrites previous results

KFP has no native equivalent. Without Airflow, backfill means writing custom scripts to loop over dates and submit jobs manually.

### Multi-Model with TaskGroups

Run both models in parallel, then compare results:

```python
from airflow.utils.task_group import TaskGroup

with TaskGroup('model_inference') as inference:
    distilbert = DataprocCreateBatchOperator(
        task_id='distilbert_inference',
        batch={...},  # model_gcs_uri → v1
    )
    bert = DataprocCreateBatchOperator(
        task_id='bert_inference',
        batch={...},  # model_gcs_uri → v2
    )

compare = BigQueryInsertJobOperator(
    task_id='compare_models',
    configuration={'query': {'query': '''
        SELECT a.id, a.text, a.label AS distilbert, b.label AS bert
        FROM predictions_v1 a JOIN predictions_v2 b USING (id)
    '''}},
)

inference >> compare
```

TaskGroups are visual only — they group tasks in the Airflow UI but don't change execution behavior. Both models run in parallel because there's no dependency between them.

### Retry & Alerting

```python
default_args = {
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
    'on_failure_callback': alert_on_failure,  # Slack, email, PagerDuty
    'sla': timedelta(hours=2),                # Alert if job exceeds 2 hours
}
```

- **Retries**: Batch jobs fail sometimes — quota limits, transient network errors, preemptible worker loss. 2 retries with 5-minute delays handles most transient failures.
- **SLA**: `sla` flags tasks that exceed a time limit. Critical for ML pipelines with downstream consumers waiting for fresh predictions.
- **Callbacks**: `on_failure_callback` fires when a task fails all retries. Send to Slack, PagerDuty, or Cloud Monitoring.

### Idempotent DAGs

DAGs should be idempotent: running the same date twice produces the same result without duplicating data.

**Pattern:** Write to date-partitioned BigQuery tables, overwrite partition on re-run:

```python
output_table = f'predictions_{ds_nodash}'  # predictions_20260418

# In the inference script:
df.write.format('bigquery') \
    .option('table', f'{project}.{dataset}.{output_table}') \
    .mode('overwrite') \
    .save()
```

**Anti-pattern:** Append-only writes that duplicate data on retry. If a job fails halfway and retries, the append includes both the partial and complete results.

### Decision Framework

| Need | Airflow → KFP | Airflow Direct (Dataproc/Dataflow) |
|------|:-:|:-:|
| ML artifact lineage | Yes (KFP tracks) | No |
| Multi-step ML pipeline | KFP handles it | Gets complex in DAG |
| Team already has KFP | Leverage existing pipelines | Unnecessary layer |
| Simple batch predict | Extra overhead | Clean and simple |
| Backfill | Both | Both |
| Cross-system deps | Both (Airflow handles) | Both |
| Monitoring | Airflow UI + KFP UI | Airflow UI only |

### Series Comparison

| Notebook | Orchestration | Scheduling | Best For |
|----------|:---:|:---:|:---:|
| 1. Vertex AI Batch | KFP | Manual / cron | Managed prediction with Model Registry |
| 2. Dataflow | KFP | Manual / cron | Complex Beam pipelines, autoscaling |
| 3. Dataproc | KFP | Manual / cron | PySpark ecosystem, large-scale data |
| 4. Airflow (this) | Airflow (+KFP) | Airflow DAG | Enterprise scheduling, data dependencies, backfill |

---
## Cleanup

### Remove DAGs from Composer

In [59]:
# Remove DAGs from Composer's GCS bucket
for dag_file in ['dag_dataproc.py', 'dag_dataflow.py', 'dag_kfp.py', 'dag_vertex_batch.py']:
    blob = dag_bucket.blob(f'{dag_prefix}/{dag_file}')
    try:
        blob.delete()
        print(f'Deleted: gs://{dag_bucket_name}/{dag_prefix}/{dag_file}')
    except Exception:
        print(f'Not found: {dag_file} (already deleted)')
print('\nAirflow will remove the DAGs from its UI within ~60 seconds.')

Deleted: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_dataproc.py
Deleted: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_dataflow.py
Deleted: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_kfp.py
Deleted: gs://us-central1-mlops-airflow-b-e8584ef9-bucket/dags/dag_vertex_batch.py

Airflow will remove the DAGs from its UI within ~60 seconds.

### Delete Models from Registry

In [60]:
# Delete models registered for this experiment
models = aiplatform.Model.list(
    filter=f'labels.experiment="{EXPERIMENT}"',
)
for m in models:
    m.delete()
    print(f'Deleted model: {m.display_name}')
if not models:
    print('No models found to delete')

Deleting Model : projects/1026793852137/locations/us-central1/models/5809783157284667392
Model deleted. . Resource name: projects/1026793852137/locations/us-central1/models/5809783157284667392
Deleting Model resource: projects/1026793852137/locations/us-central1/models/5809783157284667392
Delete Model backing LRO: projects/1026793852137/locations/us-central1/models/5809783157284667392/operations/1089733576380907520
Model resource projects/1026793852137/locations/us-central1/models/5809783157284667392 deleted.
Deleted model: airflow-batch-distilbert

### Delete BigQuery Dataset

In [61]:
bq_client.delete_dataset(
    f'{PROJECT_ID}.{BQ_DATASET}',
    delete_contents=True,
    not_found_ok=True,
)
print(f'Deleted BQ dataset {BQ_DATASET}')

Deleted BQ dataset mlops_airflow_batch

### Remove GCS Artifacts (Optional)

Uncomment to remove the model artifacts, pipeline files, and inference scripts from GCS.

In [62]:
# # Remove all GCS artifacts for this experiment
# for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/'):
#     blob.delete()
# print(f'Removed gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/')

### Composer Environment (Optional)

Composer environments take ~25 minutes to create and cost ~$0.35/hour while running. **Don't delete if you plan to reuse it.** Uncomment below to delete:

In [63]:
# # Delete Composer environment (~5 minutes)
# composer_client.delete_environment(
#     name=f'projects/{PROJECT_ID}/locations/{REGION}/environments/{COMPOSER_ENV}'
# ).result()
# print(f'Deleted Composer environment: {COMPOSER_ENV}')