![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FMLOps%2FServing%2FBatch&file=Vertex+AI+Batch+Prediction.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Vertex%20AI%20Batch%20Prediction.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Vertex%20AI%20Batch%20Prediction.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FMLOps%2FServing%2FBatch%2FVertex%2520AI%2520Batch%2520Prediction.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Vertex%20AI%20Batch%20Prediction.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Vertex%20AI%20Batch%20Prediction.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Vertex%2520AI%2520Batch%2520Prediction.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Vertex%2520AI%2520Batch%2520Prediction.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Vertex%2520AI%2520Batch%2520Prediction.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/MLOps/Serving/Batch/Vertex%2520AI%2520Batch%2520Prediction.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Vertex%20AI%20Batch%20Prediction.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/MLOps/Serving/Batch/Vertex%20AI%20Batch%20Prediction.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Vertex AI Batch Prediction

Run batch inference on large datasets using [Vertex AI Batch Prediction](https://cloud.google.com/vertex-ai/docs/predictions/get-batch-predictions). This notebook demonstrates:

- Batch prediction from GCS (JSONL) and BigQuery inputs
- Column control with `instanceConfig`: `includedFields`, `excludedFields`
- Tuning worker count and batch size for optimal throughput
- Multi-model batch prediction for comparison and validation
- Orchestrating batch workflows with Vertex AI Pipelines (KFP)

**Why batch?** When you need predictions for thousands or millions of records and don't need real-time responses, batch prediction is more cost-effective than online endpoints. No persistent infrastructure, no idle compute, and native integration with BigQuery for warehouse-scale scoring.

**Container portability:** The same FastAPI container used in the [online serving notebooks](../readme.md) works for batch prediction. Vertex AI manages the workers, distributes input data, collects results, and shuts down. No endpoint needed.

**Story arc:**
1. Build container and register models
2. Batch prediction from GCS (JSONL) with DistilBERT
3. Batch prediction from BigQuery with BERT + `instanceConfig` column control
4. Compare DistilBERT vs BERT results (multi-model)
5. Orchestrate the full workflow as a KFP pipeline

**Models:**
- v1: [`distilbert-base-uncased-finetuned-sst-2-english`](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english) (67M params) — returns `POSITIVE`/`NEGATIVE`
- v2: [`textattack/bert-base-uncased-SST-2`](https://huggingface.co/textattack/bert-base-uncased-SST-2) (110M params) — returns `LABEL_0`/`LABEL_1`

---
## Colab Setup

To run this notebook in Colab run the cells in this section. Otherwise, skip this section.

This cell will authenticate to GCP (follow prompts in the popup).

In [1]:
PROJECT_ID = 'statmike-mlops-349915' # replace with your project ID

In [2]:
try:
    import google.colab
    from google.colab import auth
    auth.authenticate_user()
    !gcloud config set project {PROJECT_ID}
except Exception:
    pass

---
## Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [README](../readme.md) for uv setup details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [3]:
import subprocess, sys, shutil

def install(*packages):
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install(
    'google-cloud-aiplatform', 'google-cloud-storage',
    'google-cloud-artifact-registry', 'google-cloud-build',
    'google-cloud-bigquery', 'google-cloud-pipeline-components',
    'transformers', 'torch', 'sentencepiece',
    'kfp', 'pandas', 'db-dtypes',
)

### API Enablement

In [4]:
!gcloud services enable aiplatform.googleapis.com
!gcloud services enable artifactregistry.googleapis.com
!gcloud services enable cloudbuild.googleapis.com

---
## Setup

inputs:

In [5]:
project = !gcloud config get-value project
PROJECT_ID = project[-1]
PROJECT_ID

'statmike-mlops-349915'

In [6]:
REGION = 'us-central1'
SERIES = 'mlops'
EXPERIMENT = 'vertex-batch'

GCS_BUCKET = PROJECT_ID
AR_REPO = 'mlops-serving'
BQ_DATASET = f'{SERIES}_{EXPERIMENT}'.replace('-', '_')

In [7]:
project_number = !gcloud projects describe {PROJECT_ID} --format='value(projectNumber)'
PROJECT_NUMBER = project_number[0]
PROJECT_NUMBER

'1026793852137'

packages:

In [8]:
import json, os, time, tempfile, subprocess

from transformers import AutoModelForSequenceClassification, AutoTokenizer

import google.auth
from google.cloud import storage
from google.cloud import artifactregistry_v1
from google.cloud.devtools import cloudbuild_v1
from google.cloud import aiplatform
from google.cloud import aiplatform_v1
from google.cloud import bigquery
import pandas as pd

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

clients:

In [9]:
gcs = storage.Client(project = PROJECT_ID)
bucket = gcs.bucket(GCS_BUCKET)

cb = cloudbuild_v1.CloudBuildClient()

ar = artifactregistry_v1.ArtifactRegistryClient()

aiplatform.init(project = PROJECT_ID, location = REGION)

bq_client = bigquery.Client(project = PROJECT_ID)

jobs_client = aiplatform_v1.JobServiceClient(
    client_options = {'api_endpoint': f'{REGION}-aiplatform.googleapis.com'}
)

parameters:

In [10]:
DIR = f'files/vertex-batch'
if not os.path.exists(DIR + '/source/app'):
    os.makedirs(DIR + '/source/app')

In [11]:
# Test sentences used throughout the notebook
SENTENCES = [
    "This movie is absolutely wonderful and I loved every minute of it!",
    "The food was terrible and the service was even worse.",
    "An average experience, nothing special but not bad either.",
    "I cannot believe how amazing this product is, truly life-changing.",
    "Disappointing quality for the price. Would not recommend.",
    "The weather today is mild and partly cloudy.",
    "I had the worst customer service experience of my life yesterday.",
    "What a fantastic performance by the entire cast!",
    "The instructions were confusing and the product broke on day one.",
    "Pretty good overall, with some room for improvement.",
]

---
## Download HuggingFace Models

Download two sentiment analysis models from HuggingFace and upload them to GCS. Both models are fine-tuned on the [SST-2](https://huggingface.co/datasets/stanfordnlp/sst2) dataset for binary sentiment classification.

- **v1 (DistilBERT):** Smaller, faster — used for GCS batch prediction
- **v2 (BERT):** Larger, more accurate — used for BQ batch prediction with `instanceConfig`

In [12]:
MODELS = {
    'v1': {
        'hub_name': 'distilbert-base-uncased-finetuned-sst-2-english',
        'display_name': 'distilbert-sst2',
    },
    'v2': {
        'hub_name': 'textattack/bert-base-uncased-SST-2',
        'display_name': 'bert-sst2',
    },
}

In [13]:
for version, info in MODELS.items():
    gcs_prefix = f'{SERIES}/{EXPERIMENT}/models/{version}'

    # check if already uploaded
    existing = list(bucket.list_blobs(prefix=gcs_prefix, max_results=1))
    if existing:
        print(f'{version} ({info["hub_name"]}) already in GCS at gs://{GCS_BUCKET}/{gcs_prefix}')
        continue

    print(f'Downloading {version}: {info["hub_name"]} ...')
    with tempfile.TemporaryDirectory() as tmpdir:
        model = AutoModelForSequenceClassification.from_pretrained(info['hub_name'])
        tokenizer = AutoTokenizer.from_pretrained(info['hub_name'])
        model.save_pretrained(tmpdir)
        tokenizer.save_pretrained(tmpdir)

        for root, dirs, files in os.walk(tmpdir):
            for fname in files:
                local_path = os.path.join(root, fname)
                blob_name = f'{gcs_prefix}/{os.path.relpath(local_path, tmpdir)}'
                bucket.blob(blob_name).upload_from_filename(local_path)
        print(f'  Uploaded to gs://{GCS_BUCKET}/{gcs_prefix}')

    info['artifact_uri'] = f'gs://{GCS_BUCKET}/{gcs_prefix}'

# set artifact_uri for any that were already uploaded
for version, info in MODELS.items():
    if 'artifact_uri' not in info:
        info['artifact_uri'] = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/models/{version}'

v1 (distilbert-base-uncased-finetuned-sst-2-english) already in GCS at gs://statmike-mlops-349915/mlops/vertex-batch/models/v1
v2 (textattack/bert-base-uncased-SST-2) already in GCS at gs://statmike-mlops-349915/mlops/vertex-batch/models/v2

In [14]:
for version, info in MODELS.items():
    blobs = list(bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/models/{version}'))
    print(f'{version} ({info["display_name"]}): {len(blobs)} files at {info["artifact_uri"]}')

v1 (distilbert-sst2): 4 files at gs://statmike-mlops-349915/mlops/vertex-batch/models/v1
v2 (bert-sst2): 4 files at gs://statmike-mlops-349915/mlops/vertex-batch/models/v2

---
## Build Custom Prediction Container

Build a custom container with [FastAPI](https://fastapi.tiangolo.com/) that serves predictions for both online and batch use cases. The container handles two input formats:

- **Plain strings** — from GCS JSONL batch input (each line is a quoted string)
- **JSON objects** — from BigQuery batch input or when using `instanceConfig` (each row becomes a dict)

```
|__ Dockerfile
|__ requirements.txt
|__ app
    |__ __init__.py
    |__ main.py
    |__ prestart.sh
```

### Setup Artifact Registry

In [15]:
docker_repo = None
for repo in ar.list_repositories(parent=f'projects/{PROJECT_ID}/locations/{REGION}'):
    if AR_REPO == repo.name.split('/')[-1]:
        docker_repo = repo
        print(f'Retrieved existing repo: {docker_repo.name}')

if not docker_repo:
    operation = ar.create_repository(
        request=artifactregistry_v1.CreateRepositoryRequest(
            parent=f'projects/{PROJECT_ID}/locations/{REGION}',
            repository_id=AR_REPO,
            repository=artifactregistry_v1.Repository(
                description=f'Docker images for the {SERIES} series.',
                name=AR_REPO,
                format_=artifactregistry_v1.Repository.Format.DOCKER,
                labels={'series': SERIES},
            ),
        )
    )
    print('Creating Repository ...')
    docker_repo = operation.result()
    print(f'Completed creating repo: {docker_repo.name}')

Retrieved existing repo: projects/statmike-mlops-349915/locations/us-central1/repositories/mlops-serving

In [16]:
REPOSITORY = f"{REGION}-docker.pkg.dev/{PROJECT_ID}/{docker_repo.name.split('/')[-1]}"
REPOSITORY

'us-central1-docker.pkg.dev/statmike-mlops-349915/mlops-serving'

### Create Application Files

In [17]:
%%writefile {DIR}/source/Dockerfile
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

COPY ./app /app
COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

Overwriting files/vertex-batch/source/Dockerfile

In [18]:
%%writefile {DIR}/source/requirements.txt
google-cloud-storage
transformers
torch
sentencepiece

Overwriting files/vertex-batch/source/requirements.txt

In [19]:
%%writefile {DIR}/source/app/__init__.py
# init file

Overwriting files/vertex-batch/source/app/__init__.py

In [20]:
%%writefile {DIR}/source/app/main.py
import os
from fastapi import FastAPI, Request
from transformers import pipeline
from google.cloud import storage

app = FastAPI()

# Download model files from GCS (set by AIP_STORAGE_URI)
gcs = storage.Client()
storage_uri = os.environ['AIP_STORAGE_URI']
parts = storage_uri.replace('gs://', '').split('/', 1)
bucket = gcs.bucket(parts[0])
prefix = parts[1] if len(parts) > 1 else ''

model_dir = '/tmp/model'
os.makedirs(model_dir, exist_ok=True)
for blob in bucket.list_blobs(prefix=prefix):
    rel = blob.name[len(prefix):].lstrip('/')
    if rel:
        local = os.path.join(model_dir, rel)
        os.makedirs(os.path.dirname(local), exist_ok=True)
        blob.download_to_filename(local)

# Load the sentiment analysis pipeline
classifier = pipeline('sentiment-analysis', model=model_dir, tokenizer=model_dir)


@app.get(os.environ['AIP_HEALTH_ROUTE'], status_code=200)
def health():
    return {}


@app.post(os.environ['AIP_PREDICT_ROUTE'])
async def predict(request: Request):
    body = await request.json()
    instances = body['instances']

    # Handle both plain strings (GCS JSONL) and objects (BQ / instanceConfig)
    texts = []
    for inst in instances:
        if isinstance(inst, str):
            texts.append(inst)
        elif isinstance(inst, dict):
            # instanceConfig sends filtered objects — extract the text field
            texts.append(inst.get('text', str(inst)))
        else:
            texts.append(str(inst))

    results = classifier(texts)
    return {
        'predictions': [
            {'label': r['label'], 'score': round(r['score'], 6)}
            for r in results
        ]
    }

Overwriting files/vertex-batch/source/app/main.py

In [21]:
%%writefile {DIR}/source/app/prestart.sh
#!/bin/bash
export PORT=$AIP_HTTP_PORT
# Single worker — each container loads a large model at startup.
# Vertex AI scales by adding replicas, not gunicorn workers.
export WEB_CONCURRENCY=1

Overwriting files/vertex-batch/source/app/prestart.sh

### Upload Source to GCS

In [22]:
source_files = [
    'Dockerfile',
    'requirements.txt',
    'app/__init__.py',
    'app/main.py',
    'app/prestart.sh',
]
for f in source_files:
    bucket.blob(f'{SERIES}/{EXPERIMENT}/source/{f}').upload_from_filename(f'{DIR}/source/{f}')

print('Source files uploaded to GCS:')
for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/source'):
    print(f'  gs://{bucket.name}/{blob.name}')

Source files uploaded to GCS:
  gs://statmike-mlops-349915/mlops/vertex-batch/source/Dockerfile
  gs://statmike-mlops-349915/mlops/vertex-batch/source/app/__init__.py
  gs://statmike-mlops-349915/mlops/vertex-batch/source/app/main.py
  gs://statmike-mlops-349915/mlops/vertex-batch/source/app/prestart.sh
  gs://statmike-mlops-349915/mlops/vertex-batch/source/requirements.txt

### Build Container with Cloud Build

In [23]:
build = cloudbuild_v1.Build(steps=[])

# Step 1: retrieve source from GCS
build.steps.append({
    'name': 'gcr.io/cloud-builders/gsutil',
    'args': ['cp', '-r', f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/source/*', '/workspace'],
})

# Step 2: docker build
build.steps.append({
    'name': 'gcr.io/cloud-builders/docker',
    'args': ['build', '-t', f'{REPOSITORY}/{EXPERIMENT}', '/workspace'],
})

# Push the image
build.images = [f'{REPOSITORY}/{EXPERIMENT}']

print('Starting Cloud Build ...')
operation = cb.create_build(project_id=PROJECT_ID, build=build)
build_response = operation.result()
print(f'Build status: {build_response.status.name}')
print(f'Image: {build_response.artifacts.images[0]}')

Starting Cloud Build ...
Build status: SUCCESS
Image: us-central1-docker.pkg.dev/statmike-mlops-349915/mlops-serving/vertex-batch

In [24]:
IMAGE_URI = build_response.artifacts.images[0]
IMAGE_URI

'us-central1-docker.pkg.dev/statmike-mlops-349915/mlops-serving/vertex-batch'

---
## Upload Models to Vertex AI Model Registry

Upload both models using the same container image but different `artifact_uri` values. Unlike online serving, batch prediction does **not** require creating an endpoint — the batch job spins up workers with the container, runs inference, and shuts down.

In [25]:
vertex_model_v1 = aiplatform.Model.upload(
    display_name=f'{EXPERIMENT}-distilbert',
    serving_container_image_uri=IMAGE_URI,
    artifact_uri=MODELS['v1']['artifact_uri'],
    serving_container_predict_route='/predict',
    serving_container_health_route='/health',
    labels={'series': SERIES, 'experiment': EXPERIMENT, 'version': 'v1'},
)
print(f'v1 model: {vertex_model_v1.resource_name}')

Creating Model
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/3971258978154840064/operations/5575554925363986432
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/3971258978154840064/operations/5575554925363986432
Model created. Resource name: projects/1026793852137/locations/us-central1/models/3971258978154840064@1
To use this Model in another session:
model = aiplatform.Model('projects/1026793852137/locations/us-central1/models/3971258978154840064@1')
v1 model: projects/1026793852137/locations/us-central1/models/3971258978154840064

In [26]:
vertex_model_v2 = aiplatform.Model.upload(
    display_name=f'{EXPERIMENT}-bert',
    serving_container_image_uri=IMAGE_URI,
    artifact_uri=MODELS['v2']['artifact_uri'],
    serving_container_predict_route='/predict',
    serving_container_health_route='/health',
    labels={'series': SERIES, 'experiment': EXPERIMENT, 'version': 'v2'},
)
print(f'v2 model: {vertex_model_v2.resource_name}')

Creating Model
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/5598747293495853056/operations/3897119639238344704
Create Model backing LRO: projects/1026793852137/locations/us-central1/models/5598747293495853056/operations/3897119639238344704
Model created. Resource name: projects/1026793852137/locations/us-central1/models/5598747293495853056@1
To use this Model in another session:
model = aiplatform.Model('projects/1026793852137/locations/us-central1/models/5598747293495853056@1')
v2 model: projects/1026793852137/locations/us-central1/models/5598747293495853056

---
## Batch Prediction from GCS (JSONL)

Run batch prediction using JSONL input from GCS. Each line in the input file is a JSON string — the model receives these as plain text instances.

This uses the high-level `model.batch_predict()` SDK which blocks until the job completes. We configure the worker count and machine type to control throughput and cost.

In [27]:
# Create JSONL input file — each line is a JSON-encoded string
jsonl_content = '\n'.join(json.dumps(s) for s in SENTENCES)
jsonl_blob = bucket.blob(f'{SERIES}/{EXPERIMENT}/batch/input/sentences.jsonl')
jsonl_blob.upload_from_string(jsonl_content)

jsonl_gcs_uri = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/batch/input/sentences.jsonl'
print(f'Input file: {jsonl_gcs_uri}')
print(f'Sentences: {len(SENTENCES)}')
print()
print('Preview:')
for line in jsonl_content.split('\n')[:3]:
    print(f'  {line}')

Input file: gs://statmike-mlops-349915/mlops/vertex-batch/batch/input/sentences.jsonl
Sentences: 10

Preview:
  "This movie is absolutely wonderful and I loved every minute of it!"
  "The food was terrible and the service was even worse."
  "An average experience, nothing special but not bad either."

In [28]:
print('Submitting batch prediction job (DistilBERT, GCS JSONL) ...')
print(f'  Workers: 2 x n1-standard-4')
print()

batch_job_gcs = vertex_model_v1.batch_predict(
    job_display_name=f'{SERIES}-{EXPERIMENT}-gcs-distilbert',
    gcs_source=[jsonl_gcs_uri],
    gcs_destination_prefix=f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/batch/output/gcs',
    instances_format='jsonl',
    machine_type='n1-standard-4',
    starting_replica_count=2,
    max_replica_count=2,
)

print(f'Job completed: {batch_job_gcs.resource_name}')
print(f'Duration: {batch_job_gcs.end_time - batch_job_gcs.start_time}')

Submitting batch prediction job (DistilBERT, GCS JSONL) ...
  Workers: 2 x n1-standard-4

Creating BatchPredictionJob
BatchPredictionJob created. Resource name: projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648
To use this BatchPredictionJob in another session:
bpj = aiplatform.BatchPredictionJob('projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648')
View Batch Prediction Job:
https://console.cloud.google.com/ai/platform/locations/us-central1/batch-predictions/2825831590184091648?project=1026793852137
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
3
BatchPredictionJob projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648 current state:
4
BatchPredictionJob run completed. Resource name: projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648
Job completed: projects/1026793852137/locations/us-central1/batchPredictionJobs/2825831590184091648
Duration: 0:16:14.358708

In [29]:
# Read predictions from GCS output
output_dir = batch_job_gcs.output_info.gcs_output_directory
prefix = output_dir.replace(f'gs://{GCS_BUCKET}/', '')

gcs_results = []
for blob in bucket.list_blobs(prefix=prefix):
    # Vertex AI writes output files named like prediction.results-00000-of-00001 (JSONL format, no .jsonl extension)
    if 'prediction' in blob.name.split('/')[-1]:
        for line in blob.download_as_text().strip().split('\n'):
            if line:
                gcs_results.append(json.loads(line))

print(f'DistilBERT predictions ({len(gcs_results)} sentences):')
print()
for r in gcs_results:
    text = r['instance'] if isinstance(r['instance'], str) else str(r['instance'])
    pred = r['prediction']
    print(f'  "{text[:60]}..."')
    print(f'    => {pred["label"]} (score: {pred["score"]:.6f})')
    print()

DistilBERT predictions (10 sentences):

  "This movie is absolutely wonderful and I loved every minute ..."
    => POSITIVE (score: 0.999887)

  "The food was terrible and the service was even worse...."
    => NEGATIVE (score: 0.999793)

  "An average experience, nothing special but not bad either...."
    => POSITIVE (score: 0.859379)

  "I cannot believe how amazing this product is, truly life-cha..."
    => POSITIVE (score: 0.999858)

  "Disappointing quality for the price. Would not recommend...."
    => NEGATIVE (score: 0.999712)

  "The weather today is mild and partly cloudy...."
    => NEGATIVE (score: 0.964102)

  "I had the worst customer service experience of my life yeste..."
    => NEGATIVE (score: 0.999791)

  "What a fantastic performance by the entire cast!..."
    => POSITIVE (score: 0.999882)

  "The instructions were confusing and the product broke on day..."
    => NEGATIVE (score: 0.998770)

  "Pretty good overall, with some room for improvement...."
    => POSITIVE (score: 0.999488)

### Worker Configuration

Batch prediction workers are configured at job creation:

| Parameter | Description | Default |
|-----------|-------------|---------|
| `starting_replica_count` | Number of workers to spin up. No autoscaling in batch mode — this is the actual count. | 1 |
| `max_replica_count` | Should equal `starting_replica_count` for batch (no autoscaling). | 1 |
| `machine_type` | Machine type for each worker. Larger machines = more memory for bigger models. | `n1-standard-2` |

**Batch size tuning:** Vertex AI also supports `manualBatchTuningParameters.batchSize` (via the REST/gapic API) which controls how many instances are sent per HTTP request to the container. The default is 64. Too large = OOM in the container; too small = underutilized workers. See the [Tuning Reference](#tuning--monitoring-reference) section.

**Cost:** Workers run for the duration of the job. Cost = worker_count x machine_type_rate x job_duration. More workers = faster but more expensive — linear scaling for embarrassingly parallel workloads.

---
## Batch Prediction from BigQuery with `instanceConfig`

Run batch prediction using a BigQuery table as input, with `instanceConfig` to control which columns the model sees. This is the production pattern: your BQ table has many columns but the model only needs one.

`instanceConfig` provides three controls:
- **`included_fields`** — Whitelist of columns to send to the model. Only these fields become the instance.
- **`excluded_fields`** — Blacklist of columns to exclude (mutually exclusive with `included_fields`).
- **`key_field`** — A column that passes through to the output but is **not** sent to the model. Only supported with GCS output format — not with BigQuery output.

We include `id` and `text` in `included_fields` so `id` is available in the output for joining back to the source table. The model container handles the extra field gracefully — it extracts the `text` field from the instance dict.

This section uses the lower-level `aiplatform_v1` gapic API because the high-level `model.batch_predict()` SDK does not expose `instanceConfig`. We use BERT (v2) here so we can compare with DistilBERT (v1) from the GCS section above.

In [30]:
# Create BQ dataset
dataset_ref = bigquery.Dataset(f'{PROJECT_ID}.{BQ_DATASET}')
dataset_ref.location = REGION
try:
    bq_client.get_dataset(dataset_ref)
    print(f'Dataset {BQ_DATASET} already exists')
except Exception:
    bq_client.create_dataset(dataset_ref)
    print(f'Created dataset {BQ_DATASET}')

# Create input table with multiple columns (to demonstrate instanceConfig filtering)
BQ_TABLE = 'input_data'
schema = [
    bigquery.SchemaField('id', 'INTEGER'),
    bigquery.SchemaField('text', 'STRING'),
    bigquery.SchemaField('category', 'STRING'),
    bigquery.SchemaField('created_date', 'DATE'),
]

# Build rows
categories = ['entertainment', 'dining', 'general', 'product', 'product',
              'weather', 'service', 'entertainment', 'product', 'general']
rows = [
    {'id': i + 1, 'text': text, 'category': categories[i], 'created_date': '2026-04-18'}
    for i, text in enumerate(SENTENCES)
]

# Load with WRITE_TRUNCATE to replace any existing data (idempotent across re-runs)
job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition='WRITE_TRUNCATE',
)
bq_client.load_table_from_json(
    rows, f'{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}', job_config=job_config
).result()
print(f'Loaded {len(rows)} rows into {BQ_TABLE} (WRITE_TRUNCATE)')

# Preview
bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}` ORDER BY id LIMIT 3').to_dataframe()

Created dataset mlops_vertex_batch
Loaded 10 rows into input_data (WRITE_TRUNCATE)

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id,text,category,created_date
0,1,This movie is absolutely wonderful and I loved...,entertainment,2026-04-18
1,2,The food was terrible and the service was even...,dining,2026-04-18
2,3,"An average experience, nothing special but not...",general,2026-04-18

In [31]:
# Build batch prediction job with instanceConfig using gapic API
batch_prediction_job = aiplatform_v1.BatchPredictionJob(
    display_name=f'{SERIES}-{EXPERIMENT}-bq-bert-instanceconfig',
    model=vertex_model_v2.resource_name,
    input_config={
        'instances_format': 'bigquery',
        'bigquery_source': {
            'input_uri': f'bq://{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}',
        },
    },
    output_config={
        'predictions_format': 'bigquery',
        'bigquery_destination': {
            'output_uri': f'bq://{PROJECT_ID}.{BQ_DATASET}',
        },
    },
    dedicated_resources={
        'machine_spec': {'machine_type': 'n1-standard-4'},
        'starting_replica_count': 2,
        'max_replica_count': 2,
    },
    # instanceConfig: control which columns the model sees
    # Note: key_field is only supported with GCS output, not BigQuery output.
    # Include 'id' in included_fields so it appears in the output for joining.
    instance_config={
        'included_fields': ['id', 'text'],  # only send these columns to the model
        # 'excluded_fields': ['category', 'created_date'],  # alternative approach
    },
)

print('Submitting batch prediction job (BERT, BQ + instanceConfig) ...')
print(f'  included_fields: [id, text] (only columns sent to model)')
print()

response = jobs_client.create_batch_prediction_job(
    parent=f'projects/{PROJECT_ID}/locations/{REGION}',
    batch_prediction_job=batch_prediction_job,
)
print(f'Job created: {response.name}')

Submitting batch prediction job (BERT, BQ + instanceConfig) ...
  included_fields: [id, text] (only columns sent to model)

Job created: projects/1026793852137/locations/us-central1/batchPredictionJobs/658333532023685120

In [32]:
# Poll for completion
while True:
    job = jobs_client.get_batch_prediction_job(name=response.name)
    state = job.state
    print(f'  State: {state.name}')
    if state in (
        aiplatform_v1.types.JobState.JOB_STATE_SUCCEEDED,
        aiplatform_v1.types.JobState.JOB_STATE_FAILED,
        aiplatform_v1.types.JobState.JOB_STATE_CANCELLED,
    ):
        break
    time.sleep(30)

if job.state == aiplatform_v1.types.JobState.JOB_STATE_SUCCEEDED:
    bq_output_table = job.output_info.bigquery_output_table
    # The gapic API may return just the table name — qualify it with project.dataset
    bq_output_table = bq_output_table.replace('bq://', '').replace(':', '.')
    if bq_output_table.count('.') < 2:
        bq_output_table = f'{PROJECT_ID}.{BQ_DATASET}.{bq_output_table}'
    print(f'\nJob completed! Output table: {bq_output_table}')
else:
    print(f'\nJob failed: {job.error.message}')

  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_RUNNING
  State: JOB_STATE_SUCCEEDED

Job completed! Output table: statmike-mlops-349915.mlops_vertex_batch.predictions_2026_04_20T11_40_09_113Z_889

In [33]:
# Query the predictions — 'id' appears because it was in included_fields
# The model received both 'id' and 'text', but only uses 'text' for inference
bq_results_df = bq_client.query(f'SELECT * FROM `{bq_output_table}`').to_dataframe()
print(f'Output columns: {list(bq_results_df.columns)}')
print(f'Rows: {len(bq_results_df)}')
print()
bq_results_df

Output columns: ['id', 'text', 'category', 'created_date', 'prediction']
Rows: 10

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id,text,category,created_date,prediction
0,2,The food was terrible and the service was even...,dining,2026-04-18,"{""label"": ""LABEL_0"", ""score"": 0.998655}"
1,1,This movie is absolutely wonderful and I loved...,entertainment,2026-04-18,"{""label"": ""LABEL_1"", ""score"": 0.999663}"
2,8,What a fantastic performance by the entire cast!,entertainment,2026-04-18,"{""label"": ""LABEL_1"", ""score"": 0.999662}"
3,3,"An average experience, nothing special but not...",general,2026-04-18,"{""label"": ""LABEL_1"", ""score"": 0.944122}"
4,10,"Pretty good overall, with some room for improv...",general,2026-04-18,"{""label"": ""LABEL_1"", ""score"": 0.984469}"
5,4,"I cannot believe how amazing this product is, ...",product,2026-04-18,"{""label"": ""LABEL_1"", ""score"": 0.999648}"
6,5,Disappointing quality for the price. Would not...,product,2026-04-18,"{""label"": ""LABEL_0"", ""score"": 0.988457}"
7,9,The instructions were confusing and the produc...,product,2026-04-18,"{""label"": ""LABEL_0"", ""score"": 0.997174}"
8,7,I had the worst customer service experience of...,service,2026-04-18,"{""label"": ""LABEL_0"", ""score"": 0.998489}"
9,6,The weather today is mild and partly cloudy.,weather,2026-04-18,"{""label"": ""LABEL_0"", ""score"": 0.863014}"

### `instanceConfig` Reference

| Field | Purpose | Output Format | Example |
|-------|---------|:---:|---------|
| `included_fields` | Whitelist: only these columns are sent as the instance. | GCS, BQ | `['id', 'text']` |
| `excluded_fields` | Blacklist: these columns are excluded from the instance. Mutually exclusive with `included_fields`. | GCS, BQ | `['category', 'created_date']` |
| `key_field` | Column that passes through to output without being sent to the model. Use as a join key. | GCS only | `'id'` |
| `instance_type` | How to format the instance: `'object'` (default for structured), `'array'` (ordered values). | GCS, BQ | `'object'` |

> **`key_field` limitation:** `key_field` is only supported when the output format is GCS (JSONL). With BigQuery output, use `included_fields` to include your ID column — it flows through to the output table naturally. The model container should handle the extra field gracefully (as our container does by extracting only the `text` field).

**Why use `instanceConfig`?**

- **Efficiency:** Your BQ table might have 50 columns but the model only needs 1. Without `instanceConfig`, all 50 columns are serialized and sent to the model container — wasted bandwidth and potential errors.
- **Column filtering:** `included_fields` / `excluded_fields` let you control exactly what the model sees, without creating a view or staging table.
- **No data prep needed:** Configure column filtering directly in the batch job definition.

> **Note:** `instanceConfig` requires the gapic API (`aiplatform_v1.JobServiceClient`). The high-level `model.batch_predict()` SDK does not expose this parameter. For simple batch jobs without column filtering, `model.batch_predict()` is sufficient — as shown in the GCS section above.

---
## Multi-Model Comparison

We now have predictions from two models on the same sentences:
- **DistilBERT (v1)** — from the GCS batch job above (returns `POSITIVE`/`NEGATIVE`)
- **BERT (v2)** — from the BQ batch job with `instanceConfig` (returns `LABEL_0`/`LABEL_1`)

The different label formats confirm which model produced each prediction — the same teaching device used in the [online serving notebooks](../readme.md).

In [34]:
# Build comparison from GCS results (DistilBERT) and BQ results (BERT)

# DistilBERT results are in gcs_results (list of dicts from GCS JSONL)
distilbert_preds = {}
for r in gcs_results:
    text = r['instance'] if isinstance(r['instance'], str) else str(r['instance'])
    distilbert_preds[text] = r['prediction']

# BERT results — query with parsed prediction JSON and deduplicate
bert_df = bq_client.query(f'''
    SELECT DISTINCT
        id, text,
        JSON_VALUE(prediction, '$.label') AS label,
        CAST(JSON_VALUE(prediction, '$.score') AS FLOAT64) AS score
    FROM `{bq_output_table}`
    ORDER BY id
''').to_dataframe()

print('Model Comparison — Same Sentences, Different Models')
print('=' * 70)
print()

for _, row in bert_df.iterrows():
    text = row['text']
    print(f'  "{text[:65]}..."')

    # DistilBERT prediction (from GCS results)
    dp = distilbert_preds.get(text, {})
    if dp:
        print(f'    DistilBERT: {dp["label"]:>10} (score: {dp["score"]:.6f})')

    # BERT prediction (from BQ results, already parsed)
    print(f'    BERT:       {row["label"]:>10} (score: {row["score"]:.6f})')
    print()

Model Comparison — Same Sentences, Different Models
======================================================================

  "This movie is absolutely wonderful and I loved every minute of it..."
    DistilBERT:   POSITIVE (score: 0.999887)
    BERT:          LABEL_1 (score: 0.999663)

  "The food was terrible and the service was even worse...."
    DistilBERT:   NEGATIVE (score: 0.999793)
    BERT:          LABEL_0 (score: 0.998655)

  "An average experience, nothing special but not bad either...."
    DistilBERT:   POSITIVE (score: 0.859379)
    BERT:          LABEL_1 (score: 0.944122)

  "I cannot believe how amazing this product is, truly life-changing..."
    DistilBERT:   POSITIVE (score: 0.999858)
    BERT:          LABEL_1 (score: 0.999648)

  "Disappointing quality for the price. Would not recommend...."
    DistilBERT:   NEGATIVE (score: 0.999712)
    BERT:          LABEL_0 (score: 0.988457)

  "The weather today is mild and partly cloudy...."
    DistilBERT:   NEGATIVE (score: 0.964102)
    BERT:          LABEL_0 (score: 0.863014)

  "I had the worst customer service experience of my life yesterday...."
    DistilBERT:   NEGATIVE (score: 0.999791)
    BERT:          LABEL_0 (score: 0.998489)

  "What a fantastic performance by the entire cast!..."
    DistilBERT:   POSITIVE (score: 0.999882)
    BERT:          LABEL_1 (score: 0.999662)

  "The instructions were confusing and the product broke on day one...."
    DistilBERT:   NEGATIVE (score: 0.998770)
    BERT:          LABEL_0 (score: 0.997174)

  "Pretty good overall, with some room for improvement...."
    DistilBERT:   POSITIVE (score: 0.999488)
    BERT:          LABEL_1 (score: 0.984469)

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

### Multi-Model Batch Prediction Use Cases

| Use Case | Pattern |
|----------|---------|
| **Model comparison** | Run the same data through candidate models, compare accuracy/confidence before promoting |
| **A/B analysis** | Score a dataset with both models, measure business metrics on each |
| **Ensemble voting** | Aggregate predictions from multiple models for higher accuracy |
| **Regression testing** | After retraining, verify new model matches or improves on old model's predictions |
| **Shadow scoring** | Run a new model alongside production model without serving it, compare offline |

For batch prediction, multi-model is straightforward: submit separate jobs per model with the same input data. No endpoint traffic splitting needed — each job runs independently.

---
## Pre/Post Processing with KFP Pipeline

Batch prediction rarely stands alone in production. Typically there's a workflow:
1. **Pre-process:** Clean and filter input data (SQL query, feature engineering)
2. **Predict:** Run batch prediction on the prepared data
3. **Post-process:** Transform predictions (map labels, compute confidence buckets, join to source)

[Kubeflow Pipelines (KFP)](https://www.kubeflow.org/docs/components/pipelines/) on Vertex AI Pipelines orchestrates this as a three-stage pipeline. Each stage runs in its own container, passes outputs to the next, and the full workflow is tracked with lineage and artifacts.

### Define Pipeline Components

Three custom KFP components, each installing only the packages it needs:
- **`preprocess_bq`** — Runs a BQ query to clean and stage data
- **`batch_predict_op`** — Calls `model.batch_predict()` on the staged data
- **`postprocess_bq`** — Transforms predictions with a BQ query (label mapping, confidence buckets, join to source)

In [39]:
from kfp import dsl, compiler

@dsl.component(
    base_image='python:3.10',
    packages_to_install=['google-cloud-bigquery']
)
def preprocess_bq(
    project: str,
    bq_dataset: str,
    source_table: str,
    staging_table: str,
) -> str:
    """Clean and filter data in BigQuery, write to staging table."""
    from google.cloud import bigquery
    client = bigquery.Client(project=project)

    query = f"""
    CREATE OR REPLACE TABLE `{project}.{bq_dataset}.{staging_table}` AS
    SELECT DISTINCT
        id,
        TRIM(text) AS text
    FROM `{project}.{bq_dataset}.{source_table}`
    WHERE text IS NOT NULL
        AND LENGTH(TRIM(text)) > 0
    ORDER BY id
    """
    client.query(query).result()
    count = client.query(f'SELECT COUNT(*) c FROM `{project}.{bq_dataset}.{staging_table}`').result()
    for row in count:
        print(f'Staging table {staging_table}: {row.c} rows')
    return f'bq://{project}.{bq_dataset}.{staging_table}'


@dsl.component(
    base_image='python:3.10',
    packages_to_install=['google-cloud-aiplatform']
)
def batch_predict_op(
    project: str,
    location: str,
    model_resource_name: str,
    bigquery_source: str,
    bigquery_destination_prefix: str,
    bq_dataset: str,
    machine_type: str,
    replica_count: int,
) -> str:
    """Run Vertex AI batch prediction on a BQ table."""
    from google.cloud import aiplatform
    aiplatform.init(project=project, location=location)

    model = aiplatform.Model(model_resource_name)
    job = model.batch_predict(
        job_display_name='pipeline-batch-predict',
        bigquery_source=bigquery_source,
        bigquery_destination_prefix=bigquery_destination_prefix,
        instances_format='bigquery',
        machine_type=machine_type,
        starting_replica_count=replica_count,
        max_replica_count=replica_count,
    )
    output_table = job.output_info.bigquery_output_table
    # Normalize table reference — may be just the table name without project.dataset
    output_table = output_table.replace('bq://', '').replace(':', '.')
    if output_table.count('.') < 2:
        output_table = f'{project}.{bq_dataset}.{output_table}'
    print(f'Batch prediction output: {output_table}')
    return output_table


@dsl.component(
    base_image='python:3.10',
    packages_to_install=['google-cloud-bigquery']
)
def postprocess_bq(
    project: str,
    bq_dataset: str,
    predictions_table: str,
    source_table: str,
    output_table: str,
) -> str:
    """Transform predictions: parse JSON, join to source for enrichment."""
    from google.cloud import bigquery
    client = bigquery.Client(project=project)

    # The predictions table has: id, text, prediction (JSON string)
    # Post-processing: parse prediction JSON, join to source for category
    query = f"""
    CREATE OR REPLACE TABLE `{project}.{bq_dataset}.{output_table}` AS
    SELECT DISTINCT
        p.id,
        p.text,
        JSON_VALUE(p.prediction, '$.label') AS predicted_label,
        CAST(JSON_VALUE(p.prediction, '$.score') AS FLOAT64) AS confidence,
        s.category,
        CURRENT_TIMESTAMP() AS scored_at
    FROM `{predictions_table}` p
    LEFT JOIN (SELECT DISTINCT id, category FROM `{project}.{bq_dataset}.{source_table}`) s USING (id)
    ORDER BY p.id
    """
    client.query(query).result()
    count = client.query(f'SELECT COUNT(*) c FROM `{project}.{bq_dataset}.{output_table}`').result()
    for row in count:
        print(f'Results table {output_table}: {row.c} rows')
    return f'{project}.{bq_dataset}.{output_table}'

print('KFP components defined: preprocess_bq, batch_predict_op, postprocess_bq')

KFP components defined: preprocess_bq, batch_predict_op, postprocess_bq

In [40]:
@dsl.pipeline(
    name='batch-prediction-pipeline',
    description='Pre-process data, run batch prediction, post-process results',
)
def batch_prediction_pipeline(
    project: str,
    location: str,
    model_resource_name: str,
    bq_dataset: str,
    source_table: str,
    machine_type: str = 'n1-standard-4',
    replica_count: int = 2,
):
    # Stage 1: Clean and filter data
    preprocess_task = preprocess_bq(
        project=project,
        bq_dataset=bq_dataset,
        source_table=source_table,
        staging_table=f'{source_table}_staging',
    )

    # Stage 2: Run batch prediction on staged data
    predict_task = batch_predict_op(
        project=project,
        location=location,
        model_resource_name=model_resource_name,
        bigquery_source=preprocess_task.output,
        bigquery_destination_prefix=f'bq://{project}.{bq_dataset}',
        bq_dataset=bq_dataset,
        machine_type=machine_type,
        replica_count=replica_count,
    )

    # Stage 3: Transform predictions — join back to source, add metadata
    postprocess_task = postprocess_bq(
        project=project,
        bq_dataset=bq_dataset,
        predictions_table=predict_task.output,
        source_table=source_table,
        output_table=f'{source_table}_results',
    )

print('Pipeline defined: batch_prediction_pipeline')

Pipeline defined: batch_prediction_pipeline

In [41]:
# Compile the pipeline to JSON
pipeline_json = f'{DIR}/batch_prediction_pipeline.json'
compiler.Compiler().compile(
    pipeline_func=batch_prediction_pipeline,
    package_path=pipeline_json,
)
print(f'Pipeline compiled to {pipeline_json}')

# Submit to Vertex AI Pipelines
pipeline_job = aiplatform.PipelineJob(
    display_name=f'{SERIES}-{EXPERIMENT}-pipeline',
    template_path=pipeline_json,
    parameter_values={
        'project': PROJECT_ID,
        'location': REGION,
        'model_resource_name': vertex_model_v1.resource_name,
        'bq_dataset': BQ_DATASET,
        'source_table': BQ_TABLE,
        'machine_type': 'n1-standard-4',
        'replica_count': 2,
    },
    labels={'series': SERIES, 'experiment': EXPERIMENT},
    enable_caching=False,
)

print('Submitting pipeline ...')
pipeline_job.submit()
print(f'Pipeline job: {pipeline_job.resource_name}')

Pipeline compiled to files/vertex-batch/batch_prediction_pipeline.json
Submitting pipeline ...
Creating PipelineJob
PipelineJob created. Resource name: projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622
To use this PipelineJob in another session:
pipeline_job = aiplatform.PipelineJob.get('projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622')
View Pipeline Job:
https://console.cloud.google.com/vertex-ai/locations/us-central1/pipelines/runs/batch-prediction-pipeline-20260420191622?project=1026793852137
Pipeline job: projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622

In [42]:
# Wait for pipeline completion
pipeline_job.wait()
print(f'Pipeline state: {pipeline_job.state.name}')

PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
2
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622 current state:
3
PipelineJob run completed. Resource name: projects/1026793852137/locations/us-central1/pipelineJobs/batch-prediction-pipeline-20260420191622
Pipeline state: PIPELINE_STATE_SUCCEEDED

In [43]:
# Read the final output table
results_table = f'{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}_results'
try:
    pipeline_results = bq_client.query(f'SELECT * FROM `{results_table}` ORDER BY id').to_dataframe()
    print(f'Pipeline results ({len(pipeline_results)} rows):')
except Exception as e:
    pipeline_results = None
    print(f'Could not read results table: {e}')
    print('Check the pipeline run in the Vertex AI console for details.')

pipeline_results

/home/user/git/vertex-ai-mlops/MLOps/Serving/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

Pipeline results (10 rows):

,id,text,predicted_label,confidence,category,scored_at
0,1,This movie is absolutely wonderful and I loved...,POSITIVE,0.999879,entertainment,2026-04-20 19:40:55.492766+00:00
1,2,The food was terrible and the service was even...,NEGATIVE,0.999796,dining,2026-04-20 19:40:55.492766+00:00
2,3,"An average experience, nothing special but not...",POSITIVE,0.952148,general,2026-04-20 19:40:55.492766+00:00
3,4,"I cannot believe how amazing this product is, ...",POSITIVE,0.999811,product,2026-04-20 19:40:55.492766+00:00
4,5,Disappointing quality for the price. Would not...,NEGATIVE,0.999626,product,2026-04-20 19:40:55.492766+00:00
5,6,The weather today is mild and partly cloudy.,NEGATIVE,0.992905,weather,2026-04-20 19:40:55.492766+00:00
6,7,I had the worst customer service experience of...,NEGATIVE,0.999786,service,2026-04-20 19:40:55.492766+00:00
7,8,What a fantastic performance by the entire cast!,POSITIVE,0.999859,entertainment,2026-04-20 19:40:55.492766+00:00
8,9,The instructions were confusing and the produc...,NEGATIVE,0.998841,product,2026-04-20 19:40:55.492766+00:00
9,10,"Pretty good overall, with some room for improv...",POSITIVE,0.999465,general,2026-04-20 19:40:55.492766+00:00

### Pipeline Parameterization

The pipeline is parameterized — change any of these at submission time without recompiling:

| Parameter | Purpose |
|-----------|---------|
| `model_resource_name` | Swap to a different model version |
| `source_table` | Score a different dataset |
| `machine_type` | Scale up/down worker resources |
| `replica_count` | More workers for larger datasets |

**Scheduling:** Use Vertex AI Pipeline schedules or Airflow (see [Orchestrating Batch Inference With Airflow](./Orchestrating%20Batch%20Inference%20With%20Airflow.ipynb)) to run this pipeline on a recurring basis.

**Lineage:** Each pipeline run tracks which model, data, and parameters produced the predictions — visible in the Vertex AI console under ML Metadata.

---
## Tuning & Monitoring Reference

### Batch Size

The `batchSize` parameter (via `manualBatchTuningParameters` in the REST/gapic API) controls how many instances are sent per HTTP request to the container:

| Batch Size | Effect |
|:---:|--------|
| **Too large** | Container OOMs, failed requests, automatic retries slow the job |
| **Too small** | Underutilized GPU/CPU, more HTTP overhead, slower throughput |
| **Default (64)** | Good starting point for most models |

**Rule of thumb:** Start with the default (64). If the container logs show OOM errors, reduce by half. If container CPU/memory utilization is low, increase. For transformer models like ours, 16-32 is often optimal due to the memory footprint per inference.

### Worker Count

| Factor | Guidance |
|--------|----------|
| **Dataset size** | 10K instances: 1-2 workers. 1M instances: 10-20 workers. |
| **Model complexity** | Large models need more memory per worker → use larger machines, not more workers |
| **Cost vs speed** | Linear scaling: 2x workers ≈ 2x cost, ~0.5x duration |
| **Startup overhead** | Each worker pulls the container image + downloads model from GCS. For small datasets, 1-2 workers avoid spending more time on startup than inference. |

### Monitoring

- **Job state:** Poll via SDK (`job.state`) or check the [Batch Predictions console](https://console.cloud.google.com/vertex-ai/batch-predictions)
- **Container logs:** Available in Cloud Logging under the batch prediction job resource
- **Errors:** Check `job.partial_failures` for per-instance errors (malformed input, model errors)

### Cost

Batch prediction cost = `worker_count` x `machine_type_rate` x `job_duration`. There is no charge for idle time — workers run only for the duration of the job. For cost comparison with online endpoints, batch is typically 3-10x cheaper for large datasets because there's no persistent infrastructure.

---
## Cleanup

Remove all resources created by this notebook.

### Delete Models from Registry

In [44]:
# Delete all models with this experiment's label (catches orphans from previous runs)
models = aiplatform.Model.list(filter=f'labels.experiment={EXPERIMENT}')
for m in models:
    m.delete()
    print(f'Deleted model: {m.display_name} ({m.resource_name.split("/")[-1]})')
if not models:
    print('No models to delete.')

Deleting Model : projects/1026793852137/locations/us-central1/models/5598747293495853056
Model deleted. . Resource name: projects/1026793852137/locations/us-central1/models/5598747293495853056
Deleting Model resource: projects/1026793852137/locations/us-central1/models/5598747293495853056
Delete Model backing LRO: projects/1026793852137/locations/us-central1/models/5598747293495853056/operations/5650897860145709056
Model resource projects/1026793852137/locations/us-central1/models/5598747293495853056 deleted.
Deleted model: vertex-batch-bert (5598747293495853056)
Deleting Model : projects/1026793852137/locations/us-central1/models/3971258978154840064
Model deleted. . Resource name: projects/1026793852137/locations/us-central1/models/3971258978154840064
Deleting Model resource: projects/1026793852137/locations/us-central1/models/3971258978154840064
Delete Model backing LRO: projects/1026793852137/locations/us-central1/models/3971258978154840064/operations/8566978618868105216
Model resource projects/1026793852137/locations/us-central1/models/3971258978154840064 deleted.
Deleted model: vertex-batch-distilbert (3971258978154840064)

### Delete BigQuery Dataset

In [45]:
bq_client.delete_dataset(
    f'{PROJECT_ID}.{BQ_DATASET}',
    delete_contents=True,
    not_found_ok=True,
)
print(f'Deleted BQ dataset {BQ_DATASET}')

Deleted BQ dataset mlops_vertex_batch

### Remove GCS Artifacts (Optional)

Uncomment to remove the model artifacts, container source, and batch output from GCS.

In [46]:
# # Remove all GCS artifacts for this experiment
# for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/'):
#     blob.delete()
# print(f'Removed gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/')