![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_score&file=ai_score.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_score%2Fai_score.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_score/ai_score.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.SCORE — BigQuery AI Functions

`AI.SCORE` is a managed scalar function that rates inputs on a scale you describe and returns a FLOAT64. BigQuery automatically generates a scoring rubric to improve consistency.

**When to use it:**
- You want to rank or rate items using natural language scoring criteria
- You need consistent numeric scores for ordering (ORDER BY) or filtering
- You want BigQuery to auto-generate a scoring rubric

**Alternatives:**
- [`AI.GENERATE_DOUBLE`](../ai_generate_double/) — More control over model and parameters, returns STRUCT
- [`AI.GENERATE`](../ai_generate/) — Full control with output_schema for multiple output fields
- [`AI.CLASSIFY`](../ai_classify/) — Categorical classification instead of numeric scoring

**Featured in:** [Content Analysis Pipeline](../../workflows/content_analysis/) | [Document Intelligence](../../workflows/document_intelligence/) | [Content Moderation](../../workflows/content_moderation/)

**Multimodal:** Supports document, image, and video input via [ObjectRef](../../RESOURCES.md#objectref-and-objectrefruntime-schema-reference). Pass a STRUCT input with ObjectRefRuntime fields to score unstructured data.

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-score) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function doesn't require a connection or model for SQL usage — it uses end-user credentials automatically. BigFrames requires a connection, so we reference the shared one here. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection (used by BigFrames)
BUCKET = PROJECT_ID  # GCS bucket (same name as project)

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes', 'google-cloud-storage')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

### 1. Basic scoring

`AI.SCORE` takes a prompt describing scoring criteria and returns a FLOAT64 directly.

**Important:** There is no fixed default range. Always specify a range in your prompt (e.g., "on a scale of 1 to 10").

In [5]:
query = """
SELECT
  review,
  AI.SCORE(CONCAT('Rate the positivity of this review on a scale of 1 to 10: ', review)) AS positivity_score
FROM UNNEST([
  'Amazing product, exceeded all my expectations!',
  'It was okay, nothing special.',
  'Terrible quality. Completely disappointed.',
  'Good value for the price. Would buy again.'
]) AS review
"""
client.query(query).to_dataframe()

                                           review  positivity_score
0      Terrible quality. Completely disappointed.               1.0
1                   It was okay, nothing special.               5.0
2      Good value for the price. Would buy again.               7.0
3  Amazing product, exceeded all my expectations!              10.0

### 2. Ranking with ORDER BY

Use `AI.SCORE` with `ORDER BY` to rank items.

In [6]:
query = """
SELECT
  resume,
  AI.SCORE(CONCAT(
    'Rate this resume summary for a data engineer role on a scale of 1 to 10, ',
    'where 10 is perfectly qualified: ', resume
  )) AS qualification_score
FROM UNNEST([
  '5 years Python, SQL, Spark. Built data pipelines at scale. AWS certified.',
  'Junior developer, 1 year JavaScript experience. No data engineering.',
  '10 years data engineering. Expert in BigQuery, Dataflow, Airflow. Led team of 8.',
  '3 years analytics, some Python. Interested in transitioning to engineering.'
]) AS resume
ORDER BY qualification_score DESC
"""
client.query(query).to_dataframe()

,resume,qualification_score
0,"10 years data engineering. Expert in BigQuery, Dataflow, Airflow. Led team of 8.",10.0
1,"5 years Python, SQL, Spark. Built data pipelines at scale. AWS certified.",9.0
2,"3 years analytics, some Python. Interested in transitioning to engineering.",5.0
3,"Junior developer, 1 year JavaScript experience. No data engineering.",1.0

### 3. Combining with AI.IF for filter + rank

Filter first, then rank — minimizing Gemini calls.

In [7]:
query = """
WITH scored_reviews AS (
  SELECT
    review,
    AI.SCORE(CONCAT('Rate the urgency of this customer issue on a scale of 1 to 5: ', review)) AS urgency
  FROM UNNEST([
    'My order arrived damaged and I need a replacement ASAP.',
    'Just wondering about your return policy.',
    'Your product caused a safety hazard in my home!',
    'The color is slightly different from the photo.',
    'I was charged twice and need an immediate refund!'
  ]) AS review
)
SELECT review, urgency
FROM scored_reviews
WHERE urgency >= 3
ORDER BY urgency DESC
"""
client.query(query).to_dataframe()

                                                    review  urgency
0          Your product caused a safety hazard in my home!      5.0
1        I was charged twice and need an immediate refund!      5.0
2  My order arrived damaged and I need a replacement ASAP.      4.0

### 4. Specifying an endpoint

Override the auto-selected model with a specific Gemini endpoint.

In [8]:
query = """
SELECT
  text,
  AI.SCORE(
    CONCAT('Rate the reading difficulty of this text on a scale of 1 to 10, where 1 is elementary and 10 is PhD level: ', text),
    endpoint => 'gemini-2.5-flash'
  ) AS reading_level
FROM UNNEST([
  'The cat sat on the mat.',
  'Quantum entanglement demonstrates non-local correlations between particles.',
  'Machine learning models can improve over time with more training data.'
]) AS text
"""
client.query(query).to_dataframe()

,text,reading_level
0,The cat sat on the mat.,1.0
1,Quantum entanglement demonstrates non-local correlations between particles.,9.0
2,Machine learning models can improve over time with more training data.,6.0

---
## Examples — Multimodal with ObjectRef

`AI.SCORE` can score documents, images, and video stored in Cloud Storage. Create an **object table** pointing to your files, then use the tuple syntax to pass both scoring criteria and document content:

```sql
AI.SCORE(('scoring criteria text', OBJ.GET_ACCESS_URL(ref, 'r')))
```

The object table provides a `ref` column that `OBJ.GET_ACCESS_URL` converts to a signed reference. See the [ObjectRef reference](../../RESOURCES.md#objectref-and-objectrefruntime-schema-reference) for details.

In [9]:
import subprocess as _sp, json as _json
from google.cloud import storage as _storage
from pathlib import Path

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant required roles
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
for role in ['roles/aiplatform.user', 'roles/storage.objectViewer']:
    _sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
             f'--member=serviceAccount:{sa}', f'--role={role}', '--quiet'],
            capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

# Upload invoice for the multimodal example
_gcs = _storage.Client(project=PROJECT_ID)
_bucket = _gcs.bucket(BUCKET)
_prefix = 'bq_ai_functions/ai_score'

_data = Path('../../data/documents')
if not _data.exists():
    _data = Path('data/documents')

blob = _bucket.blob(f'{_prefix}/invoice_001.pdf')
if not blob.exists():
    blob.upload_from_filename(str(_data / 'invoices' / 'invoice_001.pdf'))
    print(f'Uploaded invoice_001.pdf → gs://{BUCKET}/{_prefix}/invoice_001.pdf')
else:
    print(f'Already exists: gs://{BUCKET}/{_prefix}/invoice_001.pdf')

# Create object table pointing to the uploaded files
client.query(f"""
CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{DATASET_ID}.ai_score_docs`
WITH CONNECTION `{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}`
OPTIONS (
  object_metadata = 'SIMPLE',
  uris = ['gs://{BUCKET}/{_prefix}/*.pdf']
)
""").result()
print('Object table ai_score_docs ready')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)
Already exists: gs://statmike-mlops-349915/bq_ai_functions/ai_score/invoice_001.pdf
Object table ai_score_docs ready

### 5. Score a document

Use the tuple syntax to pass both scoring criteria and a document reference from the object table.

In [10]:
query = f"""
SELECT
  uri,
  AI.SCORE(
    ('Rate the professionalism and formality of this document on a scale of 0 to 1',
     OBJ.GET_ACCESS_URL(ref, 'r'))
  ) AS professionalism
FROM
  `{PROJECT_ID}.{DATASET_ID}.ai_score_docs`
"""
client.query(query).to_dataframe()

,uri,professionalism
0,gs://statmike-mlops-349915/bq_ai_functions/ai_score/invoice_001.pdf,1.0

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

In [11]:
%%bigquery --project {PROJECT_ID}

SELECT
  review,
  AI.SCORE(CONCAT('Rate positivity on a scale of 1 to 10: ', review)) AS score
FROM UNNEST([
  'Amazing!', 'Terrible.', 'Pretty good.', 'Awful experience.'
]) AS review
ORDER BY score DESC

Query is running:   0%|          |

Downloading:   0%|          |

              review  score
0           Amazing!    9.0
1       Pretty good.    7.0
2  Awful experience.    1.0
3          Terrible.    1.0

---
## Examples — BigFrames

BigFrames wraps `AI.SCORE` via `bbq.ai.score()`. It returns a Series of FLOAT64 directly.

**Key patterns:**
- Returns FLOAT64 directly — use for ranking and filtering
- Tuple prompt pattern: `bbq.ai.score(("Rate: ", df["col"], " on scale 1-10"))`
- No endpoint parameter — BigQuery auto-selects the model

In [12]:
import bigframes.pandas as bpd
import bigframes.bigquery as bbq

bpd.close_session()  # Reset session to apply connection settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION
bpd.options.bigquery.bq_connection = f'{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}'

### Scoring and ranking

In [13]:
df = bpd.DataFrame({'review': [
    'Amazing product!', 'Terrible quality.', 'Pretty good.', 'Best purchase ever!'
]})

df['score'] = bbq.ai.score(('Rate the positivity of this review on a scale of 1 to 10: ', df['review']))
df.sort_values('score', ascending=False).to_pandas()

/usr/local/google/home/statmike/Git/google_projects/projects/bq-ai-functions/.venv/lib/python3.13/site-packages/bigframes/session/__init__.py:384: FutureWarning: You are using the BigFrames session default connection: statmike-
mlops-349915.US.bq_ai_functions,             which can be different
from the BigQuery project default connection.             This default
connection may change in the future.
  warnings.warn(msg, category=FutureWarning)

                review  score
3  Best purchase ever!   10.0
0     Amazing product!    9.0
2         Pretty good.    7.0
1    Terrible quality.    1.0

---
## Cleanup

Remove GCS files uploaded for the multimodal examples. Shared resources (dataset, models, connection) are left for other notebooks.

In [14]:
# Drop object table created for multimodal examples
client.query(f"DROP EXTERNAL TABLE IF EXISTS `{PROJECT_ID}.{DATASET_ID}.ai_score_docs`").result()
print('Dropped ai_score_docs')

# Delete GCS files uploaded for multimodal examples
from google.cloud import storage

gcs_client = storage.Client(project=PROJECT_ID)
bucket = gcs_client.bucket(BUCKET)
prefix = 'bq_ai_functions/ai_score/'

blobs = list(bucket.list_blobs(prefix=prefix))
for blob in blobs:
    blob.delete()
    print(f'Deleted gs://{BUCKET}/{blob.name}')
if not blobs:
    print('No GCS files to clean up')

Dropped ai_score_docs
Deleted gs://statmike-mlops-349915/bq_ai_functions/ai_score/invoice_001.pdf

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [ ]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')