![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_key_drivers&file=ai_key_drivers.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_key_drivers%2Fai_key_drivers.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_key_drivers/ai_key_drivers.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.KEY_DRIVERS — BigQuery AI Functions

`AI.KEY_DRIVERS` is a table-valued function that performs **key driver / contribution analysis**: it compares an interest set against a reference set and surfaces the data segments that most explain the change in a summable metric. No model creation, connection, or endpoint required.

**When to use it:**
- You want to explain *why* a metric moved between two periods (this month vs last)
- You want to compare a test group against a control group and attribute the difference
- You need to find which customer segments, geographies, or product categories drive a KPI change
- You want root-cause analysis without building and managing a contribution analysis model

**Alternatives:**
- Contribution analysis model + [`ML.GET_INSIGHTS`](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ml-get-insights) — use when you need more than 12 dimensions or non-summable metrics. `AI.KEY_DRIVERS` is the simpler, model-free equivalent for summable metrics.

**Featured in:** [Metric Diagnostics](../../workflows/metric_diagnostics/) | [Time Series Intelligence](../../workflows/time_series_intelligence/)

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-key-drivers) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function doesn't require a connection or model — it uses end-user credentials automatically. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

`AI.KEY_DRIVERS` needs a single table containing both the **interest** (test) and **reference** (control) rows, distinguished by a `BOOL` column, plus a summable metric and 1–12 dimension columns.

### Setup: Create sample data from NYC Citi Bike

Materialize a compact slice of the public [NYC Citi Bike](https://console.cloud.google.com/marketplace/details/city-of-new-york/nyc-citi-bike) trips dataset. We compare **April 2017 (interest)** against **April 2016 (reference)** and ask which segments drove the change in total trip duration.

- **Metric:** `tripduration` (seconds) — a summable metric
- **Dimensions:** `usertype` (Customer / Subscriber), `gender`, `start_station_name`
- **Interest label:** `is_interest` — `TRUE` for 2017, `FALSE` for 2016

In [5]:
query = f"""
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips` AS
SELECT
  tripduration,
  usertype,
  gender,
  start_station_name,
  (EXTRACT(YEAR FROM starttime) = 2017) AS is_interest
FROM `bigquery-public-data.new_york_citibike.citibike_trips`
WHERE EXTRACT(MONTH FROM starttime) = 4
  AND EXTRACT(YEAR FROM starttime) IN (2016, 2017)
  AND tripduration IS NOT NULL
"""
client.query(query).result()

# Show the interest/reference balance
client.query(f"""
  SELECT
    is_interest,
    COUNT(*) AS trips,
    SUM(tripduration) AS total_duration
  FROM `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`
  GROUP BY is_interest
  ORDER BY is_interest
""").to_dataframe()

   is_interest    trips  total_duration
0        False  1013149      1088476614
1         True  1315404      1428348828

### 1. Basic key driver analysis

`AI.KEY_DRIVERS` requires `metric_col`, `dimension_cols`, and `interest_label_col`. Here `top_k => 15` returns the 15 highest-support insights and prunes the rest. The `["all"]` row is the whole-population change; the other rows are segments.

In [6]:
query = f"""
SELECT * EXCEPT(usertype, gender, start_station_name)
FROM AI.KEY_DRIVERS(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`,
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender', 'start_station_name'],
  interest_label_col => 'is_interest',
  top_k => 15
)
"""
client.query(query).to_dataframe()

,drivers,metric_interest,metric_reference,difference,relative_difference,unexpected_difference,relative_unexpected_difference,apriori_support,contribution
0,[all],1428348828,1088476614,339872214,0.312246,3.398722e+08,0.312246,1.000000,339872214
1,[usertype=Subscriber],966572815,760845634,205727181,0.270393,-1.057930e+08,-0.098654,0.699000,205727181
2,[gender=male],755328997,558156923,197172074,0.353256,4.698140e+07,0.066325,0.528813,197172074
3,"[usertype=Subscriber, gender=male]",699807744,558156923,141650821,0.253783,-6.697549e+07,-0.087346,0.512787,141650821
4,[usertype=Customer],461776013,327630980,134145033,0.409439,4.555598e+07,0.109452,0.323294,134145033
5,[gender=female],308750284,200906782,107843502,0.536784,5.532240e+07,0.218296,0.216159,107843502
6,"[usertype=Customer, gender=male]",55521253,0,55521253,NaN,5.552125e+07,NaN,0.038871,55521253
7,"[usertype=Subscriber, gender=female]",255095838,200906782,54189056,0.269722,-1.047705e+07,-0.039451,0.184576,54189056
8,"[usertype=Customer, gender=female]",53654446,0,53654446,NaN,5.365445e+07,NaN,0.037564,53654446
9,[gender=unknown],364269547,329412909,34856638,0.105814,-9.751179e+07,-0.211164,0.302637,34856638
10,[start_station_name=Grand Army Plaza & Plaza St West],28466221,0,28466221,NaN,2.846622e+07,NaN,0.019929,28466221
11,"[usertype=Customer, start_station_name=Grand Army Plaza & Plaza St West]",25677464,0,25677464,NaN,2.567746e+07,NaN,0.017977,25677464
12,"[usertype=Customer, gender=unknown]",352600314,327630980,24969334,0.076212,-1.106323e+08,-0.238827,0.301000,24969334
13,[start_station_name=Centre St & Chambers St],18805571,9242983,9562588,1.034578,6.733686e+06,0.557799,0.013166,9562588
14,[start_station_name=Central Park S & 6 Ave],15311227,14196134,1115093,0.078549,-3.361430e+06,-0.180019,0.013042,1115093

### 2. `SUM(metric)` form and sorting by contribution

`metric_col` accepts either the bare column name or `SUM(column_name)` — they are equivalent. Sort by `contribution` (the absolute size of each segment's movement) to rank the biggest drivers.

In [7]:
query = f"""
SELECT
  drivers,
  metric_interest,
  metric_reference,
  difference,
  contribution
FROM AI.KEY_DRIVERS(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`,
  metric_col => 'SUM(tripduration)',
  dimension_cols => ['usertype', 'gender'],
  interest_label_col => 'is_interest',
  top_k => 10
)
ORDER BY contribution DESC
"""
client.query(query).to_dataframe()

,drivers,metric_interest,metric_reference,difference,contribution
0,[all],1428348828,1088476614,339872214,339872214
1,[usertype=Subscriber],966572815,760845634,205727181,205727181
2,[gender=male],755328997,558156923,197172074,197172074
3,"[usertype=Subscriber, gender=male]",699807744,558156923,141650821,141650821
4,[usertype=Customer],461776013,327630980,134145033,134145033
5,[gender=female],308750284,200906782,107843502,107843502
6,"[usertype=Customer, gender=male]",55521253,0,55521253,55521253
7,"[usertype=Subscriber, gender=female]",255095838,200906782,54189056,54189056
8,[gender=unknown],364269547,329412909,34856638,34856638
9,"[usertype=Customer, gender=unknown]",352600314,327630980,24969334,24969334

### 3. Find segments defying the overall trend

`unexpected_difference` compares a segment's actual change to the change you'd *expect* given how every other segment moved. Large absolute values flag segments that behaved differently from the population — often the most actionable insights.

In [8]:
query = f"""
SELECT
  drivers,
  difference,
  unexpected_difference,
  apriori_support
FROM AI.KEY_DRIVERS(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`,
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender', 'start_station_name'],
  interest_label_col => 'is_interest',
  top_k => 25
)
ORDER BY ABS(unexpected_difference) DESC
LIMIT 10
"""
client.query(query).to_dataframe()

,drivers,difference,unexpected_difference,apriori_support
0,[all],339872214,3.398722e+08,1.000000
1,"[usertype=Customer, gender=unknown]",24969334,-1.106323e+08,0.301000
2,[usertype=Subscriber],205727181,-1.057930e+08,0.699000
3,[gender=unknown],34856638,-9.751179e+07,0.302637
4,"[usertype=Subscriber, gender=male]",141650821,-6.697549e+07,0.512787
5,"[usertype=Customer, gender=male]",55521253,5.552125e+07,0.038871
6,[gender=female],107843502,5.532240e+07,0.216159
7,"[usertype=Customer, gender=female]",53654446,5.365445e+07,0.037564
8,[gender=male],197172074,4.698140e+07,0.528813
9,[usertype=Customer],134145033,4.555598e+07,0.323294

### 4. Control segment size with `min_apriori_support`

`apriori_support` measures how large a segment is relative to the population. `min_apriori_support` (default `0.1`) excludes segments below the threshold. Use a smaller value to include more (smaller) segments, or `0` to include every segment.

> `min_apriori_support` and `top_k` are **mutually exclusive** — use one or the other.

In [9]:
query = f"""
SELECT
  drivers,
  difference,
  ROUND(relative_difference, 3) AS pct_change,
  ROUND(apriori_support, 4) AS apriori_support
FROM AI.KEY_DRIVERS(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`,
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender'],
  interest_label_col => 'is_interest',
  min_apriori_support => 0.05
)
ORDER BY contribution DESC
"""
client.query(query).to_dataframe()

,drivers,difference,pct_change,apriori_support
0,[all],339872214,0.312,1.0000
1,[usertype=Subscriber],205727181,0.270,0.6990
2,[gender=male],197172074,0.353,0.5288
3,"[usertype=Subscriber, gender=male]",141650821,0.254,0.5128
4,[usertype=Customer],134145033,0.409,0.3233
5,[gender=female],107843502,0.537,0.2162
6,"[usertype=Subscriber, gender=female]",54189056,0.270,0.1846
7,[gender=unknown],34856638,0.106,0.3026
8,"[usertype=Customer, gender=unknown]",24969334,0.076,0.3010

### 5. See redundant insights with `enable_pruning => FALSE`

By default `AI.KEY_DRIVERS` prunes redundant insights (a segment whose dimensions are a subset of a larger segment with the same metric). Set `enable_pruning => FALSE` to see the full unpruned breakdown — useful when you want every combination.

In [10]:
query = f"""
SELECT
  drivers,
  difference,
  contribution
FROM AI.KEY_DRIVERS(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`,
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender'],
  interest_label_col => 'is_interest',
  min_apriori_support => 0.05,
  enable_pruning => FALSE
)
ORDER BY contribution DESC
"""
client.query(query).to_dataframe()

                                drivers  difference  contribution
0                                 [all]   339872214     339872214
1                 [usertype=Subscriber]   205727181     205727181
2                         [gender=male]   197172074     197172074
3    [usertype=Subscriber, gender=male]   141650821     141650821
4                   [usertype=Customer]   134145033     134145033
5                       [gender=female]   107843502     107843502
6  [usertype=Subscriber, gender=female]    54189056      54189056
7                      [gender=unknown]    34856638      34856638
8   [usertype=Customer, gender=unknown]    24969334      24969334

### 6. Interpreting the output columns

The output columns describe each segment's movement:
- `metric_interest` / `metric_reference` — the metric sum in each group
- `difference` = `metric_interest - metric_reference`
- `relative_difference` = `difference / metric_reference` (percent change; `NULL` when a segment only exists in the interest set)
- `contribution` = `ABS(difference)` (magnitude of the move)
- `apriori_support` — segment size relative to the population

In [11]:
query = f"""
SELECT
  drivers,
  metric_interest,
  metric_reference,
  difference,
  ROUND(relative_difference, 3) AS pct_change,
  contribution
FROM AI.KEY_DRIVERS(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`,
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender', 'start_station_name'],
  interest_label_col => 'is_interest',
  top_k => 15
)
ORDER BY contribution DESC
"""
client.query(query).to_dataframe()

,drivers,metric_interest,metric_reference,difference,pct_change,contribution
0,[all],1428348828,1088476614,339872214,0.312,339872214
1,[usertype=Subscriber],966572815,760845634,205727181,0.270,205727181
2,[gender=male],755328997,558156923,197172074,0.353,197172074
3,"[usertype=Subscriber, gender=male]",699807744,558156923,141650821,0.254,141650821
4,[usertype=Customer],461776013,327630980,134145033,0.409,134145033
5,[gender=female],308750284,200906782,107843502,0.537,107843502
6,"[usertype=Customer, gender=male]",55521253,0,55521253,NaN,55521253
7,"[usertype=Subscriber, gender=female]",255095838,200906782,54189056,0.270,54189056
8,"[usertype=Customer, gender=female]",53654446,0,53654446,NaN,53654446
9,[gender=unknown],364269547,329412909,34856638,0.106,34856638
10,[start_station_name=Grand Army Plaza & Plaza St West],28466221,0,28466221,NaN,28466221
11,"[usertype=Customer, start_station_name=Grand Army Plaza & Plaza St West]",25677464,0,25677464,NaN,25677464
12,"[usertype=Customer, gender=unknown]",352600314,327630980,24969334,0.076,24969334
13,[start_station_name=Centre St & Chambers St],18805571,9242983,9562588,1.035,9562588
14,[start_station_name=Central Park S & 6 Ave],15311227,14196134,1115093,0.079,1115093

### 7. Inline subquery — build the interest/reference split on the fly

You don't need a pre-materialized table. Construct the `BOOL` interest column and the dimensions directly in a subquery over the raw data.

In [12]:
query = f"""
SELECT * EXCEPT(usertype, gender)
FROM AI.KEY_DRIVERS(
  (SELECT
     tripduration,
     usertype,
     gender,
     (EXTRACT(YEAR FROM starttime) = 2017) AS is_interest
   FROM `bigquery-public-data.new_york_citibike.citibike_trips`
   WHERE EXTRACT(MONTH FROM starttime) = 4
     AND EXTRACT(YEAR FROM starttime) IN (2016, 2017)
     AND tripduration IS NOT NULL),
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender'],
  interest_label_col => 'is_interest',
  top_k => 10
)
ORDER BY contribution DESC
"""
client.query(query).to_dataframe()

,drivers,metric_interest,metric_reference,difference,relative_difference,unexpected_difference,relative_unexpected_difference,apriori_support,contribution
0,[all],1428348828,1088476614,339872214,0.312246,3.398722e+08,0.312246,1.000000,339872214
1,[usertype=Subscriber],966572815,760845634,205727181,0.270393,-1.057930e+08,-0.098654,0.699000,205727181
2,[gender=male],755328997,558156923,197172074,0.353256,4.698140e+07,0.066325,0.528813,197172074
3,"[usertype=Subscriber, gender=male]",699807744,558156923,141650821,0.253783,-6.697549e+07,-0.087346,0.512787,141650821
4,[usertype=Customer],461776013,327630980,134145033,0.409439,4.555598e+07,0.109452,0.323294,134145033
5,[gender=female],308750284,200906782,107843502,0.536784,5.532240e+07,0.218296,0.216159,107843502
6,"[usertype=Customer, gender=male]",55521253,0,55521253,NaN,5.552125e+07,NaN,0.038871,55521253
7,"[usertype=Subscriber, gender=female]",255095838,200906782,54189056,0.269722,-1.047705e+07,-0.039451,0.184576,54189056
8,[gender=unknown],364269547,329412909,34856638,0.105814,-9.751179e+07,-0.211164,0.302637,34856638
9,"[usertype=Customer, gender=unknown]",352600314,327630980,24969334,0.076212,-1.106323e+08,-0.238827,0.301000,24969334

---
## Examples — `%%bigquery` Magics

The same analysis using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### Key drivers with `%%bigquery`

In [13]:
%%bigquery --project {PROJECT_ID}

SELECT
  drivers,
  difference,
  contribution
FROM AI.KEY_DRIVERS(
  TABLE `statmike-mlops-349915.bq_ai_functions.ai_key_drivers_trips`,
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender'],
  interest_label_col => 'is_interest',
  top_k => 10
)
ORDER BY contribution DESC

Query is running:   0%|          |

Downloading:   0%|          |

                                drivers  difference  contribution
0                                 [all]   339872214     339872214
1                 [usertype=Subscriber]   205727181     205727181
2                         [gender=male]   197172074     197172074
3    [usertype=Subscriber, gender=male]   141650821     141650821
4                   [usertype=Customer]   134145033     134145033
5                       [gender=female]   107843502     107843502
6      [usertype=Customer, gender=male]    55521253      55521253
7  [usertype=Subscriber, gender=female]    54189056      54189056
8                      [gender=unknown]    34856638      34856638
9   [usertype=Customer, gender=unknown]    24969334      24969334

---
## Examples — BigFrames

There is no native BigFrames API for `AI.KEY_DRIVERS` yet. Use `session.read_gbq_query()` to execute the SQL and return a BigFrames DataFrame.

In [14]:
import bigframes.pandas as bpd

bpd.close_session()  # Reset session to apply project/location settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

### AI.KEY_DRIVERS via `read_gbq_query()`

In [15]:
query = f"""
SELECT
  drivers,
  difference,
  contribution
FROM AI.KEY_DRIVERS(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips`,
  metric_col => 'tripduration',
  dimension_cols => ['usertype', 'gender', 'start_station_name'],
  interest_label_col => 'is_interest',
  top_k => 10
)
ORDER BY contribution DESC
"""
bpd.read_gbq_query(query)

                                   drivers  difference  contribution
0                                  ['all']   339872214     339872214
1                  ['usertype=Subscriber']   205727181     205727181
2                          ['gender=male']   197172074     197172074
3    ['usertype=Subscriber' 'gender=male']   141650821     141650821
4                    ['usertype=Customer']   134145033     134145033
5                        ['gender=female']   107843502     107843502
6      ['usertype=Customer' 'gender=male']    55521253      55521253
7  ['usertype=Subscriber' 'gender=female']    54189056      54189056
8                       ['gender=unknown']    34856638      34856638
9   ['usertype=Customer' 'gender=unknown']    24969334      24969334

[10 rows x 3 columns]

---
## Cleanup

Drop resources created by this notebook. Shared resources (dataset) are left for other notebooks.

In [16]:
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_key_drivers_trips', not_found_ok=True)
print('Table ai_key_drivers_trips deleted')

Table ai_key_drivers_trips deleted

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [17]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')