![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_detect_anomalies&file=ai_detect_anomalies.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_detect_anomalies%2Fai_detect_anomalies.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_detect_anomalies/ai_detect_anomalies.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.DETECT_ANOMALIES — BigQuery AI Functions

`AI.DETECT_ANOMALIES` is a GA table-valued function that detects anomalies in time series data using TimesFM. It forecasts expected values from historical data, then flags data points that deviate significantly.

**When to use it:**
- You want to detect unusual spikes or drops in time series data
- You need anomaly probability scores for each data point
- You want to detect anomalies across multiple time series simultaneously
- You can choose between TimesFM 2.0 (default) and TimesFM 2.5 via the `model` parameter
- You can control how much history the model sees with `context_window` (64–15,360 depending on model)

**Alternatives:**
- [`AI.FORECAST`](../ai_forecast/) — Generate forecasts without anomaly detection
- [`AI.EVALUATE`](../ai_evaluate/) — Evaluate forecast accuracy instead of detecting anomalies

**Featured in:** [Time Series Intelligence](../../workflows/time_series_intelligence/)

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-detect-anomalies) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function doesn't require a connection or model — it uses end-user credentials automatically. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

### Setup: Create historical and target data

Anomaly detection needs two inputs:
1. **Historical data** — used to build a forecast baseline
2. **Target data** — checked for anomalies against the baseline

We create data with a realistic pattern (upward trend + weekly seasonality), then inject two clear anomalies into the target period: a spike on Dec 15 and a drop on Dec 25.

In [5]:
# Create historical data (Jan-Nov 2024): upward trend + weekly seasonality + noise
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history` AS
WITH dates AS (
  SELECT date FROM UNNEST(GENERATE_DATE_ARRAY('2024-01-01', '2024-11-30')) AS date
)
SELECT date,
  GREATEST(0,
    1000
    + EXTRACT(DAYOFYEAR FROM date) * 2  -- upward trend (~2/day)
    + CASE EXTRACT(DAYOFWEEK FROM date)
        WHEN 1 THEN -200  -- Sunday dip
        WHEN 7 THEN 300   -- Saturday peak
        ELSE 0
      END
    + CAST(100 * (RAND() - 0.5) AS INT64)  -- noise
  ) AS daily_sales
FROM dates
'''
client.query(query).result()

# Create target data (Dec 2024): same pattern but with 2 injected anomalies
# IMPORTANT: target must follow the same pattern as history, otherwise
# the model flags every deviation from the learned seasonality.
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target` AS
WITH dates AS (
  SELECT date FROM UNNEST(GENERATE_DATE_ARRAY('2024-12-01', '2024-12-31')) AS date
)
SELECT date,
  CASE
    WHEN date = '2024-12-15' THEN 5000  -- injected spike anomaly (Sunday)
    WHEN date = '2024-12-25' THEN 50    -- injected drop anomaly (Wednesday)
    ELSE GREATEST(0,
      1000
      + EXTRACT(DAYOFYEAR FROM date) * 2  -- same trend
      + CASE EXTRACT(DAYOFWEEK FROM date)
          WHEN 1 THEN -200  -- same weekly seasonality
          WHEN 7 THEN 300
          ELSE 0
        END
      + CAST(100 * (RAND() - 0.5) AS INT64)  -- same noise
    )
  END AS daily_sales
FROM dates
'''
client.query(query).result()
print('Historical and target data created')

Historical and target data created

### 1. Basic anomaly detection

Pass historical and target tables. Returns each target point with `is_anomaly`, bounds, and probability.

In [6]:
query = f'''
SELECT
  time_series_timestamp,
  time_series_data,
  is_anomaly,
  ROUND(anomaly_probability, 4) AS anomaly_prob,
  ROUND(lower_bound, 0) AS lower_bound,
  ROUND(upper_bound, 0) AS upper_bound
FROM AI.DETECT_ANOMALIES(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history`,
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target`,
  data_col => 'daily_sales',
  timestamp_col => 'date'
)
ORDER BY time_series_timestamp
'''
df = client.query(query).to_dataframe()

anomalies = df[df['is_anomaly'] == True]
print(f'Total points: {len(df)}, Anomalies detected: {len(anomalies)}')
print(f'\nAnomalous points:')
print(anomalies[['time_series_timestamp', 'time_series_data', 'anomaly_prob', 'lower_bound', 'upper_bound']].to_string(index=False))

Total points: 31, Anomalies detected: 3

Anomalous points:
    time_series_timestamp  time_series_data  anomaly_prob  lower_bound  upper_bound
2024-12-15 00:00:00+00:00            5000.0        1.0000       1447.0       1555.0
2024-12-25 00:00:00+00:00              50.0        1.0000       1642.0       1750.0
2024-12-28 00:00:00+00:00            2050.0        0.9682       1943.0       2046.0

### 2. Adjusting the anomaly threshold

The `anomaly_prob_threshold` controls sensitivity (default: 0.95). A data point is flagged as anomalous if its anomaly probability exceeds this threshold.

- **Higher threshold** (e.g., 0.99) → fewer, more extreme anomalies only
- **Lower threshold** (e.g., 0.8) → more anomalies, catches subtler deviations

Here we show all points sorted by anomaly probability to see the full distribution.

In [7]:
query = f'''
SELECT
  time_series_timestamp,
  time_series_data,
  is_anomaly,
  ROUND(anomaly_probability, 4) AS anomaly_prob,
  ROUND(lower_bound, 0) AS lower,
  ROUND(upper_bound, 0) AS upper
FROM AI.DETECT_ANOMALIES(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history`,
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  anomaly_prob_threshold => 0.99  -- stricter: only the most extreme anomalies
)
ORDER BY anomaly_prob DESC
'''
df = client.query(query).to_dataframe()

anomalies = df[df['is_anomaly'] == True]
print(f'With threshold=0.99: {len(anomalies)} anomalies (vs default 0.95)')
df.head(10)

With threshold=0.99: 2 anomalies (vs default 0.95)

,time_series_timestamp,time_series_data,is_anomaly,anomaly_prob,lower,upper
0,2024-12-15 00:00:00+00:00,5000.0,True,1.0000,1434.0,1576.0
1,2024-12-25 00:00:00+00:00,50.0,True,1.0000,1626.0,1769.0
2,2024-12-28 00:00:00+00:00,2050.0,False,0.9682,1923.0,2059.0
3,2024-12-30 00:00:00+00:00,1760.0,False,0.9434,1629.0,1776.0
4,2024-12-21 00:00:00+00:00,2014.0,False,0.8956,1904.0,2035.0
5,2024-12-11 00:00:00+00:00,1654.0,False,0.8928,1630.0,1767.0
6,2024-12-31 00:00:00+00:00,1749.0,False,0.8506,1621.0,1782.0
7,2024-12-17 00:00:00+00:00,1708.0,False,0.8003,1618.0,1748.0
8,2024-12-14 00:00:00+00:00,2017.0,False,0.7674,1909.0,2056.0
9,2024-12-19 00:00:00+00:00,1663.0,False,0.7504,1634.0,1747.0

### 3. Using a query for history (subset)

Pass a query instead of a table reference to filter historical data.

In [8]:
query = f'''
SELECT
  time_series_timestamp,
  time_series_data,
  is_anomaly,
  ROUND(anomaly_probability, 4) AS anomaly_prob
FROM AI.DETECT_ANOMALIES(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history`
   WHERE date >= '2024-09-01'),  -- use only recent history
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target`,
  data_col => 'daily_sales',
  timestamp_col => 'date'
)
WHERE is_anomaly = TRUE
ORDER BY anomaly_prob DESC
'''
client.query(query).to_dataframe()

      time_series_timestamp  time_series_data  is_anomaly  anomaly_prob
0 2024-12-15 00:00:00+00:00            5000.0        True        1.0000
1 2024-12-25 00:00:00+00:00              50.0        True        1.0000
2 2024-12-11 00:00:00+00:00            1654.0        True        0.9940
3 2024-12-28 00:00:00+00:00            2050.0        True        0.9902
4 2024-12-14 00:00:00+00:00            2017.0        True        0.9875
5 2024-12-07 00:00:00+00:00            2002.0        True        0.9792
6 2024-12-04 00:00:00+00:00            1654.0        True        0.9635

### 4. Setting the context window

The `context_window` controls how many historical time points the model uses to learn patterns. Supported values depend on the model:
- **TimesFM 2.0:** 64, 128, 256, 512, 1024, 2048
- **TimesFM 2.5:** 64, 128, 256, 512, 1024, 2048, 4096, 8192, 15360

By default, the smallest window covering your input data is auto-selected. A larger window can capture longer-term patterns but uses more resources.

In [9]:
query = f'''
SELECT
  time_series_timestamp,
  time_series_data,
  is_anomaly,
  ROUND(anomaly_probability, 4) AS anomaly_prob
FROM AI.DETECT_ANOMALIES(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history`,
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  context_window => 128
)
WHERE is_anomaly = TRUE
ORDER BY anomaly_prob DESC
'''
client.query(query).to_dataframe()

      time_series_timestamp  time_series_data  is_anomaly  anomaly_prob
0 2024-12-15 00:00:00+00:00            5000.0        True        1.0000
1 2024-12-25 00:00:00+00:00              50.0        True        1.0000
2 2024-12-11 00:00:00+00:00            1654.0        True        0.9993
3 2024-12-07 00:00:00+00:00            2002.0        True        0.9886
4 2024-12-02 00:00:00+00:00            1687.0        True        0.9868
5 2024-12-20 00:00:00+00:00            1688.0        True        0.9864
6 2024-12-28 00:00:00+00:00            2050.0        True        0.9849
7 2024-12-30 00:00:00+00:00            1760.0        True        0.9813
8 2024-12-16 00:00:00+00:00            1670.0        True        0.9774

### 5. Using TimesFM 2.5

The `model` parameter selects which TimesFM version to use. TimesFM 2.5 supports larger context windows (up to 15,360) and may produce different anomaly probabilities.

In [10]:
query = f'''
SELECT
  time_series_timestamp,
  time_series_data,
  is_anomaly,
  ROUND(anomaly_probability, 4) AS anomaly_prob
FROM AI.DETECT_ANOMALIES(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history`,
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target`,
  data_col => 'daily_sales',
  timestamp_col => 'date',
  model => 'TimesFM 2.5'
)
WHERE is_anomaly = TRUE
ORDER BY anomaly_prob DESC
'''
client.query(query).to_dataframe()

      time_series_timestamp  time_series_data  is_anomaly  anomaly_prob
0 2024-12-15 00:00:00+00:00            5000.0        True           1.0
1 2024-12-25 00:00:00+00:00              50.0        True           1.0

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### Anomaly detection with `%%bigquery`

In [11]:
%%bigquery --project {PROJECT_ID}

SELECT time_series_timestamp, time_series_data, is_anomaly,
  ROUND(anomaly_probability, 4) AS anomaly_prob
FROM AI.DETECT_ANOMALIES(
  TABLE `statmike-mlops-349915.bq_ai_functions.ai_detect_anomalies_history`,
  TABLE `statmike-mlops-349915.bq_ai_functions.ai_detect_anomalies_target`,
  data_col => 'daily_sales',
  timestamp_col => 'date'
)
WHERE is_anomaly = TRUE
ORDER BY anomaly_probability DESC

Query is running:   0%|          |

Downloading:   0%|          |

      time_series_timestamp  time_series_data  is_anomaly  anomaly_prob
0 2024-12-15 00:00:00+00:00            5000.0        True        1.0000
1 2024-12-25 00:00:00+00:00              50.0        True        1.0000
2 2024-12-28 00:00:00+00:00            2050.0        True        0.9682

---
## Examples — BigFrames

`AI.DETECT_ANOMALIES` has no direct BigFrames equivalent for TimesFM. Use `session.read_gbq_query()` to execute the SQL from BigFrames.

**Note:** `bigframes.ml.forecasting.ARIMAPlus.detect_anomalies()` exists but uses ARIMA_PLUS, not TimesFM.

In [12]:
import bigframes.pandas as bpd

bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

### Running AI.DETECT_ANOMALIES via read_gbq_query

In [13]:
query = f"""
SELECT time_series_timestamp, time_series_data, is_anomaly, anomaly_probability
FROM AI.DETECT_ANOMALIES(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history`,
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target`,
  data_col => 'daily_sales',
  timestamp_col => 'date'
)
ORDER BY time_series_timestamp
"""
df = bpd.read_gbq_query(query)
df.to_pandas()

,time_series_timestamp,time_series_data,is_anomaly,anomaly_probability
0,2024-12-01 00:00:00+00:00,1464.0,False,0.268381
1,2024-12-02 00:00:00+00:00,1687.0,False,0.714765
2,2024-12-03 00:00:00+00:00,1690.0,False,0.666009
3,2024-12-04 00:00:00+00:00,1654.0,False,0.621016
4,2024-12-05 00:00:00+00:00,1642.0,False,0.602793
5,2024-12-06 00:00:00+00:00,1720.0,False,0.712633
6,2024-12-07 00:00:00+00:00,2002.0,False,0.743485
7,2024-12-08 00:00:00+00:00,1463.0,False,0.518391
8,2024-12-09 00:00:00+00:00,1709.0,False,0.632777
9,2024-12-10 00:00:00+00:00,1685.0,False,0.0806
10,2024-12-11 00:00:00+00:00,1654.0,False,0.892812
11,2024-12-12 00:00:00+00:00,1668.0,False,0.719453
12,2024-12-13 00:00:00+00:00,1716.0,False,0.158341
13,2024-12-14 00:00:00+00:00,2017.0,False,0.767411
14,2024-12-15 00:00:00+00:00,5000.0,True,1.0
15,2024-12-16 00:00:00+00:00,1670.0,False,0.315044
16,2024-12-17 00:00:00+00:00,1708.0,False,0.800274
17,2024-12-18 00:00:00+00:00,1717.0,False,0.6782
18,2024-12-19 00:00:00+00:00,1663.0,False,0.750449
19,2024-12-20 00:00:00+00:00,1688.0,False,0.366443
20,2024-12-21 00:00:00+00:00,2014.0,False,0.895576
21,2024-12-22 00:00:00+00:00,1523.0,False,0.617624
22,2024-12-23 00:00:00+00:00,1682.0,False,0.32101
23,2024-12-24 00:00:00+00:00,1692.0,False,0.143971
24,2024-12-25 00:00:00+00:00,50.0,True,1.0
25,2024-12-26 00:00:00+00:00,1735.0,False,0.668764
26,2024-12-27 00:00:00+00:00,1737.0,False,0.492688
27,2024-12-28 00:00:00+00:00,2050.0,True,0.968169
28,2024-12-29 00:00:00+00:00,1496.0,False,0.25425
29,2024-12-30 00:00:00+00:00,1760.0,False,0.943423
30,2024-12-31 00:00:00+00:00,1749.0,False,0.850598

---
## Cleanup

Drop resources created by this notebook. Shared resources (dataset, models, connection) are left for other notebooks.

In [14]:
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_history', not_found_ok=True)
print('Table ai_detect_anomalies_history deleted')
client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.ai_detect_anomalies_target', not_found_ok=True)
print('Table ai_detect_anomalies_target deleted')

Table ai_detect_anomalies_history deleted
Table ai_detect_anomalies_target deleted

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [15]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')