![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_parse_document&file=ai_parse_document.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_parse_document%2Fai_parse_document.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_parse_document/ai_parse_document.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.PARSE_DOCUMENT — BigQuery AI Functions

`AI.PARSE_DOCUMENT` is a table-valued function that parses documents using the Document AI Layout Parser. It combines OCR, layout parsing, and chunking into a single SQL function call — no `CREATE MODEL` step required.

**When to use it:**
- You need to extract text from PDFs, images, or Office documents stored in Cloud Storage
- You're building a RAG (Retrieval-Augmented Generation) pipeline and need document chunks
- You want a simpler alternative to `ML.PROCESS_DOCUMENT` that skips the remote model creation step

**Alternatives:**
- [`ML.PROCESS_DOCUMENT`](../ml_process_document/) — Requires `CREATE MODEL` with a Document AI remote service, but supports all processor types (invoice parser, form parser, OCR, custom extractors). Use when you need specialized extraction beyond layout parsing.

**Key differences from ML.PROCESS_DOCUMENT:**
- `AI.PARSE_DOCUMENT` uses the `endpoint` parameter to point directly to a Document AI processor — **no `CREATE MODEL` needed**
- `ML.PROCESS_DOCUMENT` requires creating a remote model with `REMOTE_SERVICE_TYPE = 'CLOUD_AI_DOCUMENT_V1'`
- `AI.PARSE_DOCUMENT` is **Layout Parser only** — it returns chunks (`chunk_id`, `start_page`, `end_page`, `content`)
- `ML.PROCESS_DOCUMENT` supports **all Document AI processor types** (invoice, receipt, form, OCR, custom)

**Featured in:** [Document RAG Pipeline](../../workflows/document_rag/)

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-parse-document) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create shared resources.

> This function requires: (1) a **Cloud resource connection** with Document AI and Storage roles, (2) a **Document AI Layout Parser processor**, and (3) an **object table** pointing to documents in Cloud Storage. No `CREATE MODEL` step is needed. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection
BUCKET = PROJECT_ID  # GCS bucket for document storage

### Environment

> **Already set up the project environment?** Skip to [Examples](#examples--sql).  
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? Run the cells below to install packages, authenticate, and create the shared dataset. See the [Setup Reference](../../setup/) for details.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes',
        'google-cloud-storage', 'google-cloud-documentai')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

In [5]:
import subprocess as _sp, json as _json

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant required roles
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
for role in ['roles/aiplatform.user', 'roles/storage.objectViewer', 'roles/documentai.apiUser']:
    _sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
             f'--member=serviceAccount:{sa}', f'--role={role}', '--quiet'],
            capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

In [6]:
from google.cloud import documentai_v1 as documentai

docai_client = documentai.DocumentProcessorServiceClient()
parent = docai_client.common_location_path(PROJECT_ID, 'us')

# Check for existing layout parser processor (idempotent)
PROCESSOR_DISPLAY_NAME = 'bq_ai_functions_layout_parser'
processor = None
for p in docai_client.list_processors(parent=parent):
    if p.display_name == PROCESSOR_DISPLAY_NAME:
        processor = p
        break

if processor is None:
    processor = docai_client.create_processor(
        parent=parent,
        processor=documentai.Processor(
            display_name=PROCESSOR_DISPLAY_NAME,
            type_='LAYOUT_PARSER_PROCESSOR',
        ),
    )

PROCESSOR_ID = processor.name
print(f'Layout Parser processor ready: {PROCESSOR_ID}')

Layout Parser processor ready: projects/1026793852137/locations/us/processors/54637c0f25399e5b

### Upload documents and create object table

Upload 10 sample invoices to Cloud Storage and create an object table to reference them from BigQuery.

In [7]:
from google.cloud import storage
from pathlib import Path
from tqdm import tqdm

gcs = storage.Client(project=PROJECT_ID)
bucket = gcs.bucket(BUCKET)
prefix = 'bq_ai_functions/ai_parse_document'

data_dir = Path('../../data/documents/invoices')
if not data_dir.exists():
    data_dir = Path('data/documents/invoices')

files = sorted(data_dir.glob('*.pdf'))[:10]
uploaded, skipped = 0, 0
for f in tqdm(files, desc='Uploading'):
    blob = bucket.blob(f'{prefix}/{f.name}')
    if blob.exists():
        skipped += 1
    else:
        blob.upload_from_filename(str(f))
        uploaded += 1
print(f'Uploaded {uploaded} documents, skipped {skipped} (already exist)')
print(f'Location: gs://{BUCKET}/{prefix}/')

Uploading: 100%|██████████| 10/10 [00:01<00:00,  7.11it/s]

Uploaded 10 documents, skipped 0 (already exist)
Location: gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/

In [8]:
client.query(f"""
CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices`
WITH CONNECTION `{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}`
OPTIONS (
  object_metadata = 'SIMPLE',
  uris = ['gs://{BUCKET}/{prefix}/*.pdf']
)
""").result()

df = client.query(f"""
  SELECT uri, content_type, size
  FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices`
  ORDER BY uri
""").to_dataframe()
print(f'Object table ai_parse_document_invoices ready — {len(df)} documents')
df.head()

Object table ai_parse_document_invoices ready — 10 documents

,uri,content_type,size
0,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,application/pdf,17240
1,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_002.pdf,application/pdf,16264
2,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_003.pdf,application/pdf,15007
3,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_004.pdf,application/pdf,21071
4,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_005.pdf,application/pdf,17012

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

`AI.PARSE_DOCUMENT` is a **table-valued function** — it returns a table of chunks. Use it in `FROM` clauses, like `VECTOR_SEARCH` or `AI.GENERATE_TABLE`.

### 1. Parse a single document — discover output columns

Use `SELECT *` with a `LIMIT` subquery to see all columns `AI.PARSE_DOCUMENT` returns: the chunking columns (`chunk_id`, `start_page`, `end_page`, `content`) plus all columns from the input object table.

In [9]:
query = f"""
SELECT *
FROM AI.PARSE_DOCUMENT(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices` ORDER BY uri LIMIT 1),
  endpoint => '{PROCESSOR_ID}'
)
"""
df = client.query(query).to_dataframe()
print(f'Columns: {list(df.columns)}')
print(f'Chunks: {len(df)}')
df.head()

Columns: ['chunk_id', 'start_page', 'end_page', 'content', 'status', 'uri', 'generation', 'content_type', 'size', 'md5_hash', 'updated', 'metadata', 'ref']
Chunks: 1

,chunk_id,start_page,end_page,content,status,uri,generation,content_type,size,md5_hash,updated,metadata,ref
0,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Marketing LLC Attn: Samantha Chen 789 Market Street, 10th Floor San Francisco, CA 94103\n\n|-|-|-|-|-|\n| DESCRIPTION | QTY | UNIT | UNIT PRICE | AMOUNT |\n| Website Redesign & Development (Phase 1) | 1 | ea | $4500.00 | $4500.00 |\n| Strategic Consulting - Q3 2024 | 20 | hrs | $180.00 | $3600.00 |\n| Social Media Management - July 2024 | 1 | mo | $1200.00 | $1200.00 |\n\nINVOICE DETAILS INV-2024-0013 Issued: 2024-07-15 Due: 2024-08-14 Terms: Net 30 Payment Terms: Net 30 Thank you for your business. We appreciate the opportunity to support your marketing efforts.\n\n|-|-|\n| Subtotal | $9300.00 |\n| Tax (8.2%) | $767.25 |\n| Total Due | $10067.25 |\n\nNexus Innovations Group",,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,1779541966974873,application/pdf,17240,7f6627d7b274f0ae1c46bc6d62c2b70c,2026-05-23 13:12:47.014000+00:00,[],"{'uri': 'gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf', 'version': '1779541966974873', 'authorizer': 'statmike-mlops-349915.us.bq_ai_functions', 'details': '{""gcs_metadata"":{""content_type"":""application/pdf"",""md5_hash"":""7f6627d7b274f0ae1c46bc6d62c2b70c"",""size"":17240,""updated"":1779541967014000}}'}"

### 2. Select specific output fields

The key output columns are `chunk_id`, `start_page`, `end_page`, and `content`. Select just the fields you need.

In [10]:
query = f"""
SELECT
  uri,
  chunk_id,
  start_page,
  end_page,
  LEFT(content, 200) AS content_preview
FROM AI.PARSE_DOCUMENT(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices` ORDER BY uri LIMIT 3),
  endpoint => '{PROCESSOR_ID}'
)
ORDER BY uri, chunk_id
"""
client.query(query).to_dataframe()

,uri,chunk_id,start_page,end_page,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Marketing LLC Attn: Samantha Chen 789 Market Street,"
1,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_002.pdf,1,1,1,"# Harmony Event Solutions LLC\n\n123 Event Horizon Blvd Nashville, TN 37203(615) 555-0100 billing@harmonyevents.com INVOICE BILL TO Summit Conference Center Eleanor Vance 789 Mountain View Rd Knoxville,"
2,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_003.pdf,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 Austin, TX 78759 (512) 555-0123 billing@nexusinnovations.com INVOICE\n\n|-|\n| Invoice #: INV-2023-0110 |\n| Date: 2023-10-26 |\n| Due Date: 2023-11-"

### 3. Custom chunk_size — smaller chunks for RAG

The `chunk_size` parameter controls how the Layout Parser splits document text into chunks. Smaller chunks (e.g., 250) improve retrieval precision in RAG pipelines. The default is approximately 1000 characters.

In [11]:
query = f"""
SELECT
  uri,
  chunk_id,
  start_page,
  end_page,
  LENGTH(content) AS chunk_length,
  LEFT(content, 100) AS content_preview
FROM AI.PARSE_DOCUMENT(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices` ORDER BY uri LIMIT 3),
  endpoint => '{PROCESSOR_ID}',
  chunk_size => 250
)
ORDER BY uri, chunk_id
"""
df = client.query(query).to_dataframe()
print(f'Total chunks with chunk_size=250: {len(df)} (vs fewer with default ~1000)')
df

Total chunks with chunk_size=250: 3 (vs fewer with default ~1000)

,uri,chunk_id,start_page,end_page,chunk_length,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,1,1,1,816,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts"
1,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_002.pdf,1,1,1,913,"# Harmony Event Solutions LLC\n\n123 Event Horizon Blvd Nashville, TN 37203(615) 555-0100 billing@harm"
2,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_003.pdf,1,1,1,790,"Nexus Innovations Group 450 Technology Drive, Suite 200 Austin, TX 78759 (512) 555-0123 billing@nexu"

### 4. Subquery filtering — parse specific documents

Use a subquery to filter which documents to process, avoiding unnecessary parsing of the entire object table.

In [12]:
query = f"""
SELECT
  uri,
  chunk_id,
  LEFT(content, 200) AS content_preview
FROM AI.PARSE_DOCUMENT(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices`
   WHERE uri LIKE '%invoice_001%' OR uri LIKE '%invoice_005%'),
  endpoint => '{PROCESSOR_ID}'
)
ORDER BY uri, chunk_id
"""
client.query(query).to_dataframe()

,uri,chunk_id,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Marketing LLC Attn: Samantha Chen 789 Market Street,"
1,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_005.pdf,1,"Apex Digital Solutions LLC 789 Tech Drive | Innovation City, CA 90012 | (555) 789-0123 | billing@apexds.com INVOICE BILL TO Quantum Enterprises Inc. Attn: Eleanor Vance 101 Corporate Way Metropolis, N"

### 5. Persist results — avoid re-parsing

Save parsed output to a regular BigQuery table. This avoids re-processing documents on every query and lets you build indexes for search.

In [13]:
query = f"""
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_results` AS
SELECT
  uri,
  chunk_id,
  start_page,
  end_page,
  content
FROM AI.PARSE_DOCUMENT(
  TABLE `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices`,
  endpoint => '{PROCESSOR_ID}'
)
"""
client.query(query).result()

df = client.query(f"""
  SELECT COUNT(*) AS total_chunks, COUNT(DISTINCT uri) AS documents
  FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_results`
""").to_dataframe()
print(f'Persisted {df.iloc[0]["total_chunks"]} chunks from {df.iloc[0]["documents"]} documents')

Persisted 10 chunks from 10 documents

### 6. Using connection_id — service account credentials

Use the `connection_id` parameter to authenticate with a service account instead of end-user credentials — useful for shared environments and production pipelines.

In [14]:
query = f"""
SELECT
  uri,
  chunk_id,
  LEFT(content, 200) AS content_preview
FROM AI.PARSE_DOCUMENT(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices` ORDER BY uri LIMIT 2),
  endpoint => '{PROCESSOR_ID}',
  connection_id => '{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}'
)
ORDER BY uri, chunk_id
"""
client.query(query).to_dataframe()

,uri,chunk_id,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Marketing LLC Attn: Samantha Chen 789 Market Street,"
1,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_002.pdf,1,"# Harmony Event Solutions LLC\n\n123 Event Horizon Blvd Nashville, TN 37203(615) 555-0100 billing@harmonyevents.com INVOICE BILL TO Summit Conference Center Eleanor Vance 789 Mountain View Rd Knoxville,"

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

**Note:** The `endpoint` parameter requires a processor ID that varies per environment, so the magics example below queries the persisted results table from Example 5. To use `AI.PARSE_DOCUMENT` directly in magics, hardcode the processor endpoint in the SQL.

### Parse and preview chunks

In [15]:
%%bigquery --project {PROJECT_ID}

SELECT
  uri,
  chunk_id,
  start_page,
  end_page,
  LEFT(content, 150) AS content_preview
FROM `statmike-mlops-349915.bq_ai_functions.ai_parse_document_results`
ORDER BY uri, chunk_id
LIMIT 10

Query is running:   0%|          |

Downloading:   0%|          |

,uri,chunk_id,start_page,end_page,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Ma"
1,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_002.pdf,1,1,1,"# Harmony Event Solutions LLC\n\n123 Event Horizon Blvd Nashville, TN 37203(615) 555-0100 billing@harmonyevents.com INVOICE BILL TO Summit Conference Ce"
2,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_003.pdf,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 Austin, TX 78759 (512) 555-0123 billing@nexusinnovations.com INVOICE\n\n|-|\n| Invoice #: INV-202"
3,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_004.pdf,1,1,1,"123 Creative Way Austin, TX 78701 (512) 555-1234 info@digitalascent.com INVOICE BILL TO GreenLeaf Organics Inc. Sarah Chen 456 Market St Dallas, TX 75"
4,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_005.pdf,1,1,1,"Apex Digital Solutions LLC 789 Tech Drive | Innovation City, CA 90012 | (555) 789-0123 | billing@apexds.com INVOICE BILL TO Quantum Enterprises Inc. A"
5,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_006.pdf,1,1,1,"Innovate Digital Solutions 450 Tech Plaza | Austin, TX 78701 | (512) 555-0187 | billing@innovatedigitalsolutions.com INVOICE BILL TO Quantum Leap Mark"
6,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_007.pdf,1,1,1,"PixelForge Innovations 123 Creative Way Austin, TX 78704 512-555-0199 billing@pixelforge.com INVOICE\n\n|-|-|-|\n| Invoice | | #: INV-2024-0039 |\n| | D"
7,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_008.pdf,1,1,1,"Quantum Innovations Corp. 123 Tech Drive San Jose, CA 95113 (408) 555-1234 billing@quantuminnovations.com INVOICE\n\n|-|-|\n| Invoice | #: INV-2023-0006"
8,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_009.pdf,1,1,1,"Quantum Solutions LLC 1400 Innovation Drive | Austin, TX 78701 | 512-555-0100 | info@quantumsolutions.com INVOICE BILL TO Horizon Global Corp. Attn: S"
9,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_010.pdf,1,1,1,"# InnovateX Solutions LLC\n\n456 Market St, Suite 200 San Francisco, CA 94103 415-555-0123 billing@innovatexsolutions.com INVOICE BILL TO Global Dynamic"

---
## Examples — BigFrames

There is no native BigFrames API for `AI.PARSE_DOCUMENT` yet. Use `session.read_gbq_query()` to execute AI.PARSE_DOCUMENT queries and get results as a BigFrames DataFrame.

In [16]:
import bigframes.pandas as bpd

bpd.close_session()  # Reset session to apply connection settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION

### AI.PARSE_DOCUMENT via `read_gbq_query()`

In [17]:
query = f"""
SELECT
  uri,
  chunk_id,
  start_page,
  end_page,
  LEFT(content, 150) AS content_preview
FROM AI.PARSE_DOCUMENT(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.ai_parse_document_invoices` ORDER BY uri LIMIT 2),
  endpoint => '{PROCESSOR_ID}'
)
ORDER BY uri, chunk_id
"""
bf_df = bpd.read_gbq_query(query)
bf_df.to_pandas()

,uri,chunk_id,start_page,end_page,content_preview
0,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_001.pdf,1,1,1,"Nexus Innovations Group 450 Technology Drive, Suite 200 | Austin, TX 78701 | 512-555-0199 | accounts@nexinovations.com INVOICE BILL TO Global Reach Ma"
1,gs://statmike-mlops-349915/bq_ai_functions/ai_parse_document/invoice_002.pdf,1,1,1,"# Harmony Event Solutions LLC\n\n123 Event Horizon Blvd Nashville, TN 37203(615) 555-0100 billing@harmonyevents.com INVOICE BILL TO Summit Conference Ce"

---
## Cleanup

Drop tables and GCS files created by this notebook. Shared resources (dataset, connection) are left for other notebooks.

In [18]:
# Drop notebook-specific tables
for table in ['ai_parse_document_results', 'ai_parse_document_invoices']:
    client.query(f'DROP TABLE IF EXISTS `{PROJECT_ID}.{DATASET_ID}.{table}`').result()
    print(f'Dropped {table}')

# Clean up GCS files
blobs = list(bucket.list_blobs(prefix=prefix))
for blob in blobs:
    blob.delete()
print(f'Deleted {len(blobs)} GCS files')

# Uncomment to delete the Document AI processor:
# docai_client.delete_processor(name=PROCESSOR_ID)
# print(f'Deleted processor {PROCESSOR_ID}')

Dropped ai_parse_document_results
Dropped ai_parse_document_invoices
Deleted 10 GCS files

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [19]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')