![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Fworkflows%2Flog_analysis&file=log_analysis.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Fworkflows%2Flog_analysis%2Flog_analysis.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/log_analysis/log_analysis.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Log Analysis — BigQuery AI Functions

An end-to-end log analysis pipeline that composes six functions to analyze application support tickets:

1. **Generate** sample support tickets with `AI.GENERATE_TABLE`
2. **Classify** each ticket by category with `AI.CLASSIFY`
3. **Score** each ticket for priority with `AI.SCORE`
4. **Summarize** patterns by category with `AI.AGG` (the star of this workflow)
5. **Retrieve** similar past incidents with `AI.EMBED` + hybrid `VECTOR_SEARCH`

**What this demonstrates:**
- `AI.AGG` as the natural aggregation function — summarize groups of tickets without manual batching
- Composing classify → score → aggregate in a single analytical pipeline
- Using `TO_JSON_STRING` to pass structured data to `AI.AGG`
- Where `AI.AGG` stops being trustworthy — it batches hierarchically, so the counts and totals it states are reconstructions rather than aggregates
- Hybrid retrieval — pairing semantic similarity with an exact lexical match on an error code, and measuring what fusion actually buys: the rows it adds, and how far up the ranking it can lift them

**Functions used:** [`AI.GENERATE_TABLE`](../../functions/ai_generate_table/) | [`AI.CLASSIFY`](../../functions/ai_classify/) | [`AI.SCORE`](../../functions/ai_score/) | [`AI.AGG`](../../functions/ai_agg/) | [`AI.EMBED`](../../functions/ai_embed/) | [`VECTOR_SEARCH`](../../functions/vector_search/) (hybrid)

**Prerequisites:** [Setup guide](../../setup/) | [Function reference](../../RESOURCES.md)

---
## Setup

Set your project and location, authenticate, and create shared resources.

> This workflow uses `AI.GENERATE_TABLE` (requires a connection and remote model) and `AI.CLASSIFY`, `AI.SCORE`, `AI.AGG` (no model needed). See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

In [5]:
import subprocess as _sp, json as _json

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant Vertex AI User role
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
_sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
         f'--member=serviceAccount:{sa}', '--role=roles/aiplatform.user', '--quiet'],
        capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

In [6]:
# Create remote Gemini model for AI.GENERATE_TABLE (idempotent)
client.query(f'''
CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`
  REMOTE WITH CONNECTION `{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}`
  OPTIONS (endpoint = 'gemini-2.5-flash')
''').result()
print('Model gemini_flash ready')

Model gemini_flash ready

---
## Step 1 — Generate sample support tickets with AI.GENERATE_TABLE

Generate 30 realistic IT support tickets from seed categories. Each ticket has a user, description, resolution, and resolution time — mimicking real helpdesk data.

Every seed also carries an **error code**. The codes are written by hand in the SQL below rather than invented by the model, for two reasons: they stay identical on every run, and the prompt can require the model to quote the code verbatim inside the description. That gives Step 5 a stable token that appears both in a dedicated column and in free text.

Two codes repeat across seeds on purpose: `VPN-4033` covers a provisioning request and a disconnect complaint, and `AUTH-0142` covers two access tickets. A third code, `IDP-7761`, appears exactly once — on a data ticket about a quarterly archive job. That single ticket is what Step 5 has to find. The same identity-provider fault that locks users out also breaks the archive job's service credential, but nothing in the way the ticket is written resembles a login problem, so the code is the only thread connecting the two.

In [7]:
output_schema = """user_name STRING OPTIONS(description = "The employee who submitted the ticket"),
       ticket_description STRING OPTIONS(description = "Detailed description of the issue"),
       resolution STRING OPTIONS(description = "How the issue was resolved, or current status if unresolved"),
       resolution_hours FLOAT64 OPTIONS(description = "Hours from ticket creation to resolution, or NULL if unresolved")"""

query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_tickets` AS
SELECT ticket_id, error_code, user_name, ticket_description, resolution, resolution_hours
FROM AI.GENERATE_TABLE(
  MODEL `{PROJECT_ID}.{DATASET_ID}.gemini_flash`,
  (SELECT
    ticket_id,
    error_code,
    CONCAT(
      'Generate one realistic IT support ticket. Category: ', category,
      '. Scenario: ', scenario,
      '. The user saw error code ', error_code,
      '. Mention this code verbatim in the description. ',
      'Write a detailed description (2-3 sentences) and a resolution. ',
      'Create a believable employee name. ',
      'Set resolution_hours between 0.5 and 48, or null if unresolved.'
    ) AS prompt
   FROM UNNEST([
     STRUCT(1 AS ticket_id, 'access' AS category, 'new employee needs VPN access' AS scenario, 'VPN-4033' AS error_code),
     STRUCT(2, 'access', 'password reset for locked account', 'AUTH-0142'),
     STRUCT(3, 'access', 'MFA token not working after phone upgrade', 'MFA-2210'),
     STRUCT(4, 'access', 'shared drive permissions denied', 'PERM-0307'),
     STRUCT(5, 'access', 'SSO login loop on new laptop', 'AUTH-0142'),
     STRUCT(6, 'hardware', 'laptop screen flickering intermittently', 'HW-1180'),
     STRUCT(7, 'hardware', 'keyboard keys sticking after coffee spill', 'HW-1204'),
     STRUCT(8, 'hardware', 'docking station not detecting external monitors', 'DOCK-0521'),
     STRUCT(9, 'hardware', 'battery draining in under 2 hours', 'PWR-0918'),
     STRUCT(10, 'hardware', 'trackpad unresponsive after OS update', 'DRV-3312'),
     STRUCT(11, 'software', 'Slack keeps crashing on startup', 'APP-5007'),
     STRUCT(12, 'software', 'Excel macro broken after Office update', 'APP-5119'),
     STRUCT(13, 'software', 'VPN disconnects every 30 minutes', 'VPN-4033'),
     STRUCT(14, 'software', 'Docker containers failing to build', 'BLD-7742'),
     STRUCT(15, 'software', 'IDE license expired and blocking work', 'LIC-6301'),
     STRUCT(16, 'network', 'Wi-Fi drops in conference room B', 'NET-2048'),
     STRUCT(17, 'network', 'cannot reach internal wiki from remote', 'NET-2065'),
     STRUCT(18, 'network', 'latency spikes during video calls', 'NET-2103'),
     STRUCT(19, 'network', 'DNS resolution failing for staging servers', 'DNS-0553'),
     STRUCT(20, 'network', 'printer not found on office network', 'NET-2211'),
     STRUCT(21, 'security', 'suspicious login from unknown location', 'SEC-9001'),
     STRUCT(22, 'security', 'phishing email reported by multiple users', 'SEC-9014'),
     STRUCT(23, 'security', 'unauthorized app installed on work laptop', 'SEC-9027'),
     STRUCT(24, 'security', 'sensitive file shared externally by accident', 'DLP-8802'),
     STRUCT(25, 'security', 'antivirus flagging a development tool', 'SEC-9033'),
     STRUCT(26, 'data', 'accidental deletion of production database rows', 'DB-3401'),
     STRUCT(27, 'data', 'ETL pipeline failing with schema mismatch', 'ETL-7120'),
     STRUCT(28, 'data', 'quarterly archive job writing zero-byte files to cold storage', 'IDP-7761'),
     STRUCT(29, 'data', 'backup restoration needed for corrupted file', 'BKP-4409'),
     STRUCT(30, 'data', 'BigQuery query hitting quota limits', 'QUOTA-0429')
   ])),
  STRUCT(
    """{output_schema}""" AS output_schema
  )
)
'''
client.query(query).result()

tickets = client.query(
    f'SELECT ticket_id, error_code, user_name, LEFT(ticket_description, 80) AS description_preview, resolution_hours FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_tickets` ORDER BY ticket_id'
).to_dataframe()
print(f'{len(tickets)} tickets generated')
tickets.head(10)

30 tickets generated

,ticket_id,error_code,user_name,description_preview,resolution_hours
0,1,VPN-4033,Sarah Chen,"New employee, Sarah Chen, is unable to connect to the company VPN. She is receiv",1.50
1,2,AUTH-0142,Alex Chen,User Alex Chen reported their account is locked. They mentioned seeing error cod,0.75
2,3,MFA-2210,Alex Chen,User Alex Chen is unable to log in due to their MFA token not working after upgr,0.75
3,4,PERM-0307,Alex Chen,User Alex Chen reported that they are unable to access the 'Marketing Shared Dri,0.75
4,5,AUTH-0142,Sarah Jenkins,User Sarah Jenkins is experiencing a continuous login loop when trying to access,1.50
5,6,HW-1180,Sarah Chen,"My laptop screen has been flickering intermittently throughout the day, making i",3.75
6,7,HW-1204,Eleanor Vance,User reports that several keys on their laptop keyboard are sticking after a cof,2.50
7,8,DOCK-0521,Eleanor Vance,User reports that their external monitors are not being detected when connected,1.50
8,9,PWR-0918,Alex Chen,"User Alex Chen reports that their laptop battery is draining significantly, last",3.50
9,10,DRV-3312,Eleanor Vance,User reports that their laptop trackpad stopped responding immediately after com,2.50

---
## Step 2 — Classify tickets by category with AI.CLASSIFY

Use `AI.CLASSIFY` to categorize each ticket. The generated data has known categories, but in a real scenario you'd classify unstructured ticket text into operational categories.

In [8]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_classified` AS
SELECT
  ticket_id,
  error_code,
  user_name,
  ticket_description,
  resolution,
  resolution_hours,
  AI.CLASSIFY(
    ticket_description,
    [('access', 'Account access, permissions, authentication, SSO, VPN credentials'),
     ('hardware', 'Physical device issues: laptops, monitors, keyboards, docking stations'),
     ('software', 'Application bugs, crashes, license issues, build failures'),
     ('network', 'Connectivity, Wi-Fi, DNS, latency, printer discovery'),
     ('security', 'Suspicious activity, phishing, unauthorized access, data leaks'),
     ('data', 'Database issues, ETL failures, backups, query performance')]
  ) AS category
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_tickets`
'''
client.query(query).result()

classified = client.query(f'''
  SELECT category, COUNT(*) AS count,
    ROUND(AVG(IFNULL(resolution_hours, 0)), 1) AS avg_hours
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_classified`
  GROUP BY category
  ORDER BY count DESC
''').to_dataframe()
print('Ticket distribution by category:')
classified

Ticket distribution by category:

   category  count  avg_hours
0   network      6        2.0
1    access      5        1.1
2      data      5        3.1
3  hardware      5        2.8
4  security      5        3.3
5  software      4        2.5

---
## Step 3 — Score tickets for priority with AI.SCORE

Use `AI.SCORE` to rate each ticket's business impact on a 1–10 scale. This helps triage which issues affect the most people or business operations.

In [9]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored` AS
SELECT
  ticket_id,
  error_code,
  user_name,
  ticket_description,
  resolution,
  resolution_hours,
  category,
  AI.SCORE(CONCAT(
    'Rate the business impact of this IT support ticket on a scale of 1 to 10, ',
    'where 1 is minor inconvenience and 10 is critical business disruption ',
    '(e.g. data loss, security breach, entire team blocked): ',
    ticket_description,
    ' Resolution: ', IFNULL(resolution, 'UNRESOLVED')
  )) AS priority
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_classified`
'''
client.query(query).result()

scored = client.query(f'''
  SELECT category,
    ROUND(AVG(priority), 1) AS avg_priority,
    ROUND(MAX(priority), 1) AS max_priority,
    COUNT(*) AS count
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored`
  GROUP BY category
  ORDER BY avg_priority DESC
''').to_dataframe()
print('Priority scores by category:')
scored

Priority scores by category:

   category  avg_priority  max_priority  count
0      data           7.6           9.0      5
1  security           6.2           9.0      5
2  software           4.8           5.0      4
3   network           4.7           7.0      6
4  hardware           4.0           4.0      5
5    access           3.6           4.0      5

### High-priority tickets

Tickets scoring 7+ that need immediate attention.

In [10]:
high_priority = client.query(f'''
  SELECT ticket_id, user_name, category, priority,
    LEFT(ticket_description, 120) AS description
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored`
  WHERE priority >= 7
  ORDER BY priority DESC
''').to_dataframe()

if len(high_priority) == 0:
    print('No high-priority tickets — operations are running smoothly!')
else:
    print(f'{len(high_priority)} high-priority tickets:')
    display(high_priority)

8 high-priority tickets:

,ticket_id,user_name,category,priority,description
0,28,Eleanor Vance,data,9.0,"Our quarterly data archive job to cold storage completed, but upon inspection, all archived files are zero bytes. The jo"
1,24,Alex Chen,security,9.0,User Alex Chen reported receiving an error code DLP-8802 when attempting to share a document titled 'Q4_Financial_Report
2,26,Alex Chen,data,9.0,"User, Alex Chen, accidentally deleted a significant number of rows from the 'customer_accounts' table in the production"
3,27,Eleanor Vance,data,8.0,"Our daily ETL pipeline for sales data failed last night. I'm seeing error code ETL-7120 in the job logs, which indicates"
4,30,Eleanor Vance,data,8.0,"I'm encountering an issue with my BigQuery queries failing. I am consistently receiving the error code QUOTA-0429, indic"
5,22,Sarah Jenkins,security,8.0,"Multiple users, including Sarah Jenkins, have reported receiving a suspicious email with a link to a fake login page. Sa"
6,23,Eleanor Vance,security,8.0,"I noticed an application running on my work laptop that I did not install. When trying to close it, I received an error"
7,19,Maria Rodriguez,network,7.0,Our staging servers are currently inaccessible due to DNS resolution failures. When attempting to ping or access any sta

---
## Step 4 — Summarize patterns with AI.AGG

This is where `AI.AGG` shines. Instead of manually concatenating tickets into a prompt with `STRING_AGG`, we let `AI.AGG` handle the batching and aggregation automatically. It returns one summary per category — identifying common patterns, root causes, and recommended actions.

In [11]:
query = f'''
SELECT
  category,
  AI.AGG(
    TO_JSON_STRING(STRUCT(
      ticket_id, user_name, ticket_description,
      resolution, resolution_hours, priority
    )),
    'You are an IT operations analyst. Analyze these support tickets for this category. '
    'Identify: (1) common patterns or root causes, (2) average resolution effectiveness, '
    '(3) any systemic issues that need proactive fixes, (4) one actionable recommendation. '
    'Be concise.'
  ) AS category_analysis
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored`
GROUP BY category
'''
df_analysis = client.query(query).to_dataframe()
for _, row in df_analysis.iterrows():
    print(f'=== {row["category"].upper()} ===')
    print(row['category_analysis'])
    print()

=== ACCESS ===
As an IT operations analyst, I've reviewed the recent support tickets for this category.

1.  **Common Patterns/Root Causes:** We're seeing a mix of issues, including MFA token problems after phone upgrades, account lockouts/password resets, permissions denials, VPN connection issues for new employees, and SSO login loops/stale tokens on new devices.
2.  **Resolution Effectiveness:** The average resolution time for these 5 tickets was approximately 1 hour and 3 minutes per ticket.
3.  **Systemic Issues:** There's a recurring theme of new employees encountering VPN access problems and users with new devices experiencing SSO/MFA issues.
4.  **Actionable Recommendation:** Implement a pre-onboarding checklist for new employees to ensure VPN access is provisioned and tested before their start date.

=== DATA ===
As an IT operations analyst, I've reviewed the support tickets for this category and identified the following:

**Common Patterns/Root Causes:**
*   **Data Integrity Issues:** The most frequent cause, appearing in 3 out of 5 tickets, involves corrupted files, zero-byte archives, and accidental data deletion.
*   **Configuration/Credential Issues:** One ticket was due to expired credentials.
*   **Schema Mismatch:** One ticket highlighted an ETL pipeline failure due to a schema mismatch.
*   **Quota Limits:** One ticket was related to hitting a BigQuery quota.

**Resolution Effectiveness:**
All 5 tickets were successfully resolved, with an average resolution time of 3.1 hours per ticket.

**Systemic Issues for Proactive Fixes:**
*   **Data Backup/Restore:** The recurring data integrity issues suggest a need to review backup strategies, user access controls for critical data, and implement more robust post-backup data validation.
*   **Credential Management:** Expired credentials causing job failures indicate a need for automated credential rotation or improved expiry monitoring.
*   **Schema Management:** ETL failures due to schema mismatches point to a lack of automated schema evolution or better communication between development and data engineering teams.
*   **Quota Management:** Repeated quota issues suggest a need for proactive quota monitoring and a review of default quotas or user training on efficient resource usage.

**Actionable Recommendation:**
Implement automated monitoring and alerting for critical data integrity checks (e.g., file size validation post-archive, database row counts, schema drift detection) to proactively identify and address issues before they impact users.

=== HARDWARE ===
Here's an analysis of the support tickets:

1.  **Common Patterns/Root Causes:** We're seeing a mix of driver/software conflicts (especially after OS updates), and recurring hardware failures (batteries, display cables, keyboards). The consistent use of specific error codes (e.g., DOCK-0521, DRV-3312, HW-1204) indicates a structured diagnostic system.

2.  **Average Resolution Effectiveness:** The average resolution time for these tickets is approximately 2.75 hours.

3.  **Systemic Issues:** A significant systemic issue is the potential for OS updates to introduce driver conflicts, particularly with peripherals like trackpads. There's also a pattern of recurring hardware component failures. The existing error code system could be better utilized for proactive monitoring and trend analysis.

4.  **Actionable Recommendation:** Establish a pre-deployment testing protocol for all OS updates, using a diverse set of hardware configurations, to proactively identify and resolve potential driver conflicts before broad rollout.

=== NETWORK ===
As an IT operations analyst, my review of these support tickets reveals the following:

1.  **Common Patterns/Root Causes:** The most frequent issues are network connectivity problems, often stemming from VPN client/connection issues, and hardware/infrastructure problems like overloaded access points or loose cabling. DNS resolution failures also appeared.
2.  **Average Resolution Effectiveness:** All 6 tickets were resolved successfully, with an average resolution time of approximately 2 hours per ticket.
3.  **Systemic Issues:** There's a potential for outdated VPN client versions or unclear setup instructions. Network infrastructure bottlenecks, such as overloaded access points and intermittent power, are also recurring. Proactive monitoring of network device health and capacity appears to be lacking.
4.  **Actionable Recommendation:** Implement a proactive network health monitoring system to identify and address overloaded access points, intermittent power issues, and potential DNS misconfigurations before they impact users.

=== SECURITY ===
As an IT operations analyst, I've reviewed the support tickets for this category and identified the following:

**Common Patterns/Root Causes:**
*   **Security Alerts:** Three tickets (SEC-90xx) involved security-related error codes, including a false positive, a suspicious application, and a legitimate user login flagged.
*   **Phishing/Social Engineering:** One ticket directly addressed a phishing attempt.
*   **Data Loss Prevention (DLP):** One ticket concerned a DLP violation.
*   **User Education:** Two tickets highlighted a need for improved user understanding of security protocols and data handling.

**Average Resolution Effectiveness:**
The average resolution time for these tickets was 3.25 hours.

**Systemic Issues:**
*   **User Security Awareness:** There's a recurring need for user education on identifying legitimate activities versus suspicious ones, proper data sharing, and software installation policies.
*   **False Positives in Security Tools:** An instance of a critical tool being incorrectly flagged suggests a need to fine-tune security configurations to prevent productivity impacts.
*   **Phishing Vulnerability:** A company-wide phishing attempt indicates a need for continuous and robust phishing awareness training and enhanced email gateway protection.

**Actionable Recommendation:**
Implement mandatory, recurring security awareness training modules focusing on phishing identification, secure data handling, and authorized software installation, coupled with regular simulated phishing campaigns.

=== SOFTWARE ===
As an IT operations analyst, I've reviewed the support tickets for this category.

**Common Patterns/Root Causes:**
*   Application crashes/errors (APP-5007, APP-5119)
*   License expiration (LIC-6301)
*   Build/deployment failures (BLD-7742)

**Average Resolution Effectiveness:**
The average resolution time for these tickets is 2.5 hours.

**Systemic Issues Needing Proactive Fixes:**
*   Office 365 updates are causing macro incompatibilities (APP-5119).
*   There's a version mismatch in Docker base images (BLD-7742).

**Actionable Recommendation:**
Implement a pre-deployment testing phase for Office 365 updates to identify and mitigate macro incompatibilities before they impact users.

### Overall incident summary with AI.AGG

Without `GROUP BY`, `AI.AGG` aggregates all tickets into a single cross-category summary — an operational overview for leadership.

In [12]:
query = f'''
SELECT
  AI.AGG(
    TO_JSON_STRING(STRUCT(ticket_id, category, ticket_description, priority, resolution_hours)),
    'You are a VP of IT writing a weekly operations report. Summarize all support tickets into a '
    'brief executive report (3-4 paragraphs). Cover: overall volume and category breakdown, '
    'most critical issues, resolution performance, and top 2 recommendations for the coming week.'
  ) AS weekly_report
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored`
'''
df = client.query(query).to_dataframe()
print(df.iloc[0]['weekly_report'])

Here is a summary of our IT operations for the past week. We processed a total of 30 support tickets, with the volume fairly evenly distributed across several categories. Hardware, network, and security issues each accounted for 6 tickets, while access and data-related problems each generated 5 tickets. Software issues were the least frequent, with 4 tickets.

We addressed several critical issues this week, with a notable concentration in data and security. Key incidents included a critical data archive failure impacting compliance, an accidental deletion of customer data from our production database, and a data leakage incident involving a sensitive financial report. Additionally, we responded to a significant network outage affecting staging servers and multiple security concerns, including a phishing attempt and an unauthorized application installation.

Our team demonstrated strong resolution performance, with an average resolution time of 2.34 hours across all tickets. The total resolution time for the week was 70.25 hours. This efficiency is particularly commendable given the severity and complexity of some of the critical issues handled.

Looking ahead, I recommend two key areas of focus for the coming week. First, we need to implement enhanced data governance and access controls, particularly around sensitive financial data and production databases, to prevent accidental deletions and unauthorized sharing. Second, given the recurring data pipeline and quota issues, we should conduct a thorough review of our ETL processes and BigQuery resource allocation to ensure stability and prevent future disruptions to critical reporting.

### Checking AI.AGG's arithmetic

`AI.AGG` never sees all 30 tickets in one model call. It batches them hierarchically and summarizes the summaries, so every count, total, and average in the report above is a figure the model reassembled from partial views — not an aggregate BigQuery computed. Volume numbers are both the first thing a reader checks and the easiest thing for this to get wrong.

The rule that follows: **reach for `GROUP BY` when the number has to be right, and for `AI.AGG` when the prose has to be good.** The cell below computes the same figures the report tries to state, prints them next to it for comparison, and then feeds them back into `AI.AGG` so the model spends its call on synthesis instead of counting.

In [13]:
truth = client.query(f'''
  SELECT category,
    COUNT(*) AS tickets,
    ROUND(SUM(IFNULL(resolution_hours, 0)), 1) AS total_hours,
    ROUND(AVG(IFNULL(resolution_hours, 0)), 2) AS avg_hours
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored`
  GROUP BY category
  ORDER BY tickets DESC
''').to_dataframe()

print(f'Ground truth from GROUP BY — {int(truth["tickets"].sum())} tickets, '
      f'{truth["total_hours"].sum():.1f} total hours. '
      f'Compare against the report above:')
display(truth)

facts = '; '.join(
    f'{row.category}: {row.tickets} tickets, {row.total_hours} hours'
    for row in truth.itertuples()
)

query = f'''
SELECT
  AI.AGG(
    TO_JSON_STRING(STRUCT(ticket_id, category, ticket_description, priority, resolution_hours)),
    'You are a VP of IT writing a weekly operations report. The verified totals, computed in SQL, '
    'are: {facts}. Use those figures verbatim and do not recount anything. '
    'Write a brief executive report (3-4 paragraphs) covering the most critical issues, '
    'resolution performance, and the top 2 recommendations for the coming week.'
  ) AS weekly_report
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored`
'''
print('\n=== Grounded report — counting done by GROUP BY, prose by AI.AGG ===')
print(client.query(query).to_dataframe().iloc[0]['weekly_report'])

Ground truth from GROUP BY — 30 tickets, 73.2 total hours. Compare against the report above:

   category  tickets  total_hours  avg_hours
0   network        6         12.3       2.04
1    access        5          5.3       1.05
2      data        5         15.5       3.10
3  hardware        5         13.8       2.75
4  security        5         16.3       3.25
5  software        4         10.0       2.50

=== Grounded report — counting done by GROUP BY, prose by AI.AGG ===
Here's a summary of IT operations for the past week:

This week, IT operations addressed a total of 30 tickets across six categories, accumulating 73.2 hours of resolution time. The most critical issues revolved around data integrity and security, with several high-priority incidents requiring immediate attention. Specifically, a significant data deletion in the production database (DB-3401) and a data leakage attempt (DLP-8802) were among the highest priority tickets, underscoring the need for robust preventative measures and rapid response protocols.

Resolution performance varied by category. While Access and Network issues saw a moderate number of tickets with reasonable resolution times, Data and Security categories, despite having fewer tickets, consumed the most resolution hours due to the severity and complexity of the incidents. Hardware issues also contributed significantly to the total hours. The team demonstrated agility in addressing critical security threats and data anomalies, preventing potentially larger impacts.

For the coming week, our top two recommendations are:
1. **Enhance Data Protection and Recovery Protocols:** Given the critical data deletion and data leakage incidents, we recommend a comprehensive review and enhancement of our data backup, recovery, and data loss prevention (DLP) systems. This includes reinforcing user training on data handling best practices and exploring automated solutions for anomaly detection in database operations.
2. **Proactive Network Infrastructure Health Checks:** The recurring network issues, including VPN disconnections and latency spikes, suggest a need for more proactive monitoring and maintenance of our network infrastructure. We recommend scheduling a thorough audit of network devices and configurations, particularly focusing on remote access and Wi-Fi stability in key areas.

---
## Step 5 — Find similar past incidents with hybrid retrieval

Triage gets faster when whoever picks up a new ticket can see how the same problem was handled before. That is a retrieval problem, and it needs two different kinds of matching at the same time:

- **Semantic** — *users cannot authenticate after switching to a new device* should surface the MFA-after-phone-upgrade ticket even though the two share almost no words. Embeddings are good at this.
- **Lexical** — the same incident's log carries `IDP-7761`. An embedding model has no notion of what that token stands for, so the one earlier ticket carrying it can sit near the bottom of the semantic ranking simply because it is written about something else — a scheduled archive job, not a login.

`VECTOR_SEARCH` can run both at once. Its single-query syntax accepts `lexical_search_columns` and `lexical_search_query_value` alongside `query_value`, then fuses the two result lists into a single ranking. That is **hybrid search**.

Whether fusion actually changes *which rows come back* is a measurable question, not an assumption. The cells below run both searches over the same corpus and print the difference between the two result sets.

The tickets need embeddings first. `AI.EMBED` turns each description into an `ARRAY<FLOAT64>` stored in a new table, alongside the columns the search should return — including `resolution`, so every hit arrives with its fix attached.

In [14]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_embedded` AS
SELECT
  ticket_id,
  error_code,
  category,
  priority,
  ticket_description,
  resolution,
  (AI.EMBED(
    content => ticket_description,
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_DOCUMENT'
  )).result AS embedding
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_scored`
'''
client.query(query).result()

embedded = client.query(f'''
  SELECT ticket_id, error_code, category, ARRAY_LENGTH(embedding) AS embedding_dims
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_log_embedded`
  ORDER BY ticket_id
''').to_dataframe()
print(f'{len(embedded)} tickets embedded')
embedded.head()

30 tickets embedded

   ticket_id error_code category  embedding_dims
0          1   VPN-4033   access             768
1          2  AUTH-0142   access             768
2          3   MFA-2210   access             768
3          4  PERM-0307   access             768
4          5  AUTH-0142   access             768

### Semantic search alone

The incident being triaged is *users cannot authenticate after switching to a new device*, and its log carries error code `IDP-7761`. Called with only `query_value`, `VECTOR_SEARCH` ranks tickets by embedding distance, so access tickets about logins and new devices dominate.

`AI.EMBED` builds the query vector inline, with `task_type => 'RETRIEVAL_QUERY'` to pair correctly with the `RETRIEVAL_DOCUMENT` vectors already stored.

A second call with `top_k => 30` ranks the entire corpus, so the cell can print exactly where the one ticket carrying the code lands. That position is the number the rest of this section turns on.

In [15]:
INCIDENT_TEXT = 'users cannot authenticate after switching to a new device'
ERROR_CODE = 'IDP-7761'  # seeded onto exactly one ticket in Step 1 — a data ticket, not an access one
TOP_K = 12               # out of 30 tickets

QUERY_VECTOR = f'''(AI.EMBED(
    content => '{INCIDENT_TEXT}',
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_QUERY'
  )).result'''

query = f'''
SELECT
  base.ticket_id,
  base.error_code,
  base.category,
  base.priority,
  LEFT(base.ticket_description, 100) AS description,
  distance
FROM VECTOR_SEARCH(
  TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_embedded`,
  'embedding',
  query_value => {QUERY_VECTOR},
  top_k => {TOP_K},
  distance_type => 'COSINE'
)
ORDER BY distance
'''
semantic_only = client.query(query).to_dataframe()

# Rank the whole corpus so the code-carrying ticket's true position is visible
ranked = client.query(f'''
SELECT
  base.ticket_id,
  base.error_code,
  ROW_NUMBER() OVER (ORDER BY distance) AS semantic_rank
FROM VECTOR_SEARCH(
  TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_embedded`,
  'embedding',
  query_value => {QUERY_VECTOR},
  top_k => 30,
  distance_type => 'COSINE'
)
QUALIFY base.error_code = '{ERROR_CODE}'
''').to_dataframe()

TARGET = int(ranked['ticket_id'].iloc[0])
TARGET_SEMANTIC_RANK = int(ranked['semantic_rank'].iloc[0])
print(f'Ticket carrying {ERROR_CODE}: {TARGET} — semantic rank {TARGET_SEMANTIC_RANK} of 30')
print(f'Returned by semantic-only top {TOP_K}: {TARGET in set(semantic_only["ticket_id"])}')
print(f'Categories returned: {sorted(semantic_only["category"].unique().tolist())}')
semantic_only

Ticket carrying IDP-7761: 28 — semantic rank 28 of 30
Returned by semantic-only top 12: False
Categories returned: ['access', 'hardware', 'network', 'security', 'software']

,ticket_id,error_code,category,priority,description,distance
0,3,MFA-2210,access,2.0,User Alex Chen is unable to log in due to their MFA token not working after upgrading their phone. T,0.301167
1,5,AUTH-0142,access,4.0,User Sarah Jenkins is experiencing a continuous login loop when trying to access internal applicatio,0.374078
2,2,AUTH-0142,access,4.0,User Alex Chen reported their account is locked. They mentioned seeing error code AUTH-0142 when att,0.419694
3,21,SEC-9001,security,1.0,User Alex Chen reported a suspicious login attempt from an unknown location. They received an email,0.441662
4,1,VPN-4033,access,4.0,"New employee, Sarah Chen, is unable to connect to the company VPN. She is receiving an error code VP",0.442149
5,22,SEC-9014,security,8.0,"Multiple users, including Sarah Jenkins, have reported receiving a suspicious email with a link to a",0.481919
6,13,VPN-4033,network,5.0,"User, Sarah Jenkins, reports that her VPN connection consistently disconnects every 30 minutes, inte",0.484061
7,12,APP-5119,software,5.0,User is reporting that a critical Excel macro is no longer functioning after a recent Office 365 upd,0.497209
8,10,DRV-3312,hardware,4.0,User reports that their laptop trackpad stopped responding immediately after completing a recent ope,0.498080
9,25,SEC-9033,security,5.0,"User reported that their antivirus software is flagging a critical development tool as malicious, pr",0.508264
10,4,PERM-0307,access,4.0,User Alex Chen reported that they are unable to access the 'Marketing Shared Drive'. When attempting,0.514325
11,17,NET-2065,network,4.0,User reports being unable to access the internal company wiki while working remotely. They are encou,0.515854

### Hybrid — semantic similarity plus the exact code

Same query vector and the same `top_k`, now with a lexical query alongside it, so the two result sets are directly comparable.

- `lexical_search_columns` names the `STRING` columns to keyword-match. They do **not** have to be the column the embeddings came from, so the search can match the code in its own dedicated column *and* wherever the model quoted it in the description.
- `lexical_search_query_value` is the text to keyword-match, and it is independent of `query_value`. Here it is the error code, not the incident sentence — two different questions asked in one call.

Hybrid is single-query only: `lexical_search_columns` is rejected when `VECTOR_SEARCH` is called in its batch (query-table) form. A vector index is not required — without one, both sides run brute force, which is fine at this scale.

The cell prints the set difference in both directions. Fusion re-ranks everything, so a row it adds arrives at the expense of a row the semantic search would have returned.

In [16]:
def hybrid_search(k):
    """Same query vector, plus a lexical query on the error code, fused into one top-k ranking."""
    return client.query(f'''
    SELECT
      base.ticket_id,
      base.error_code,
      base.category,
      base.priority,
      LEFT(base.ticket_description, 100) AS description,
      distance
    FROM VECTOR_SEARCH(
      TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_embedded`,
      'embedding',
      query_value => {QUERY_VECTOR},
      top_k => {k},
      distance_type => 'COSINE',
      lexical_search_columns => ['error_code', 'ticket_description'],
      lexical_search_query_value => '{ERROR_CODE}'
    )
    ORDER BY distance
    ''').to_dataframe()


hybrid = hybrid_search(TOP_K)

gained = sorted(int(t) for t in set(hybrid['ticket_id']) - set(semantic_only['ticket_id']))
dropped = sorted(int(t) for t in set(semantic_only['ticket_id']) - set(hybrid['ticket_id']))
print(f'Tickets hybrid added that semantic-only missed: {gained or "none"}')
print(f'Tickets hybrid dropped to make room: {dropped or "none"}')
print(f'Ticket {TARGET}, the only one carrying {ERROR_CODE}, in the hybrid top {TOP_K}: '
      f'{TARGET in set(hybrid["ticket_id"])}')
hybrid

Tickets hybrid added that semantic-only missed: [28]
Tickets hybrid dropped to make room: [17]
Ticket 28, the only one carrying IDP-7761, in the hybrid top 12: True

,ticket_id,error_code,category,priority,description,distance
0,3,MFA-2210,access,2.0,User Alex Chen is unable to log in due to their MFA token not working after upgrading their phone. T,0.967734
1,5,AUTH-0142,access,4.0,User Sarah Jenkins is experiencing a continuous login loop when trying to access internal applicatio,0.968246
2,2,AUTH-0142,access,4.0,User Alex Chen reported their account is locked. They mentioned seeing error code AUTH-0142 when att,0.968742
3,21,SEC-9001,security,1.0,User Alex Chen reported a suspicious login attempt from an unknown location. They received an email,0.969223
4,1,VPN-4033,access,4.0,"New employee, Sarah Chen, is unable to connect to the company VPN. She is receiving an error code VP",0.969690
5,22,SEC-9014,security,8.0,"Multiple users, including Sarah Jenkins, have reported receiving a suspicious email with a link to a",0.970143
6,13,VPN-4033,network,5.0,"User, Sarah Jenkins, reports that her VPN connection consistently disconnects every 30 minutes, inte",0.970582
7,12,APP-5119,software,5.0,User is reporting that a critical Excel macro is no longer functioning after a recent Office 365 upd,0.971008
8,10,DRV-3312,hardware,4.0,User reports that their laptop trackpad stopped responding immediately after completing a recent ope,0.971423
9,25,SEC-9033,security,5.0,"User reported that their antivirus software is flagging a critical development tool as malicious, pr",0.971825
10,4,PERM-0307,access,4.0,User Alex Chen reported that they are unable to access the 'Marketing Shared Drive'. When attempting,0.972217
11,28,IDP-7761,data,9.0,"Our quarterly data archive job to cold storage completed, but upon inspection, all archived files ar",0.972507

### How far up can fusion lift a row?

Fusion does not put the exact-token match on top, and how deep in the ranking it can reach is decided by `top_k` — twice over, through two separate gates.

**Gate 1 — the candidate pool.** The lexical leg never sees the whole table. BigQuery hands it the top `10 * top_k` rows by semantic rank and BM25 scores only those. A row deeper than `10 * top_k` receives no lexical rank at all, so no token match, however exact, can reach it. At `top_k => 12` the pool is 120 rows, which covers this 30-ticket corpus several times over; on a 7,275-ticket archive the same `top_k` would leave 7,155 rows invisible to the keyword search.

**Gate 2 — the fused score.** Inside the pool both legs rank every candidate. BM25 matches take lexical ranks 1..m, and every pooled row the keyword search does not match falls in behind them in semantic order, so no pooled row is ever missing from a list. What a lexical match buys a row is promotion to lexical rank 1, worth `1/62 ≈ 0.0161` — a fixed amount of lift, competing against a page whose last slot is held by a row that also carries both terms. A matched row at semantic rank `R` scores `1/(60 + R) + 1/62`. It has to displace the row at semantic rank `top_k`, which the match itself pushes down to lexical rank `top_k + 1` and which therefore scores `1/(60 + top_k) + 1/(61 + top_k + 1)`.

A row has to clear both gates, so the reach is whichever one is tighter — `min(score reach, 10 * top_k)`:

| `top_k` | 2 | 3 | 5 | 10 | 20 | 30 | 40 | 50 | 51 | 64 | 100 | 208 | 300 |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| deepest semantic rank retrievable | 3 | 6 | 10 | 23 | 56 | 110 | 212 | 468 | 510 | 640 | 1,000 | 2,080 | 3,000 |

The score gate binds below `top_k = 51`; from 51 up the pool is the limit and reach grows strictly in proportion to `top_k`. There is no threshold past which it stops being a limit: at `top_k => 64` a matched row surfaces from semantic rank 640 at best.

That fixes the sizing rule for error-code lookup. **To surface a code buried at semantic rank `R`, `top_k` has to be at least `R/10`** — necessary, but not on its own sufficient. The two gates cross at `top_k = 51`, so for `R` under a few hundred it is the score gate that binds and `R/10` falls short: a code at semantic rank 100 needs `top_k => 29`, not 10, and one at rank 200 needs 40, not 20. Read the number to use off the reach table above rather than dividing. A code sitting at rank 2,072 in a 7,275-ticket archive needs `top_k => 208`; asking for it at `top_k => 64` returns nothing, because the pool stopped at 640. And when the code *is* the whole question, skip the arithmetic: `WHERE error_code = @code` has no pool and cannot be outranked by a fusion score.

The cell below prints where the code-carrying ticket lands in the full 30-row fused ranking, how many positions that is worth, and whether the *identical* hybrid query returns it at `top_k => 5`. The table above says what to expect. At `top_k => 30` the pool is 300 and the score reach is 110, so 110 is the binding number — far past anything a 30-ticket corpus can hide, and the ticket makes the page and climbs well up it. At `top_k => 5` the reach is 10; the lexical search still runs and still finds the row, but the row cannot buy its way onto a five-row page, and the result collapses back onto what semantic search alone would have returned.

In [17]:
full_hybrid = hybrid_search(30)
fused_position = int(full_hybrid.index[full_hybrid['ticket_id'] == TARGET][0]) + 1
narrow = hybrid_search(5)

print(f'Ticket {TARGET} — vector rank {TARGET_SEMANTIC_RANK} of 30, '
      f'fused position {fused_position} of 30')
print(f'Positions gained by adding the lexical leg: {TARGET_SEMANTIC_RANK - fused_position}')
print(f'Returned by the same hybrid query at top_k => 5:  {TARGET in set(narrow["ticket_id"])}')
print(f'Returned by the same hybrid query at top_k => {TOP_K}: {TARGET in set(hybrid["ticket_id"])}')

narrow_gain = sorted(int(t) for t in set(narrow['ticket_id']) - set(semantic_only['ticket_id'].head(5)))
print(f'Rows the top_k => 5 hybrid adds over the semantic-only top 5: {narrow_gain or "none"}')

Ticket 28 — vector rank 28 of 30, fused position 12 of 30
Positions gained by adding the lexical leg: 16
Returned by the same hybrid query at top_k => 5:  False
Returned by the same hybrid query at top_k => 12: True
Rows the top_k => 5 hybrid adds over the semantic-only top 5: none

### What the hybrid `distance` column actually is

Under hybrid search, `distance` stops being a distance. Two things give it away: values land in a narrow band just under 1 instead of spreading across the COSINE range seen in the semantic-only result, and a row that matches perfectly does not score 0.

It is a **fused rank score**. Each of the two searches produces its own ranking, and the rankings are combined with Reciprocal Rank Fusion:

```
distance = 1 - ( 1/(60 + rank_vector) + 1/(61 + rank_lexical) )
```

with 1-based ranks. The two legs do not share a rank base: 60 for the vector leg, 61 for the lexical leg. That asymmetry is determined, not cosmetic. A row ranked 1st by the vector search and 2nd by the lexical search scores:

```
1 - (1/61 + 1/63)
  = 1 - (0.01639344262295082 + 0.015873015873015872)
  = 0.9677335415040333
```

Neither shared base reproduces that value. For the same row — vector rank 1, lexical rank 2 — 60 on both legs gives `1 - (1/61 + 1/62) = 0.9674775251189847` and 61 on both legs gives `1 - (1/62 + 1/63) = 0.9679979518689196`. What BigQuery returns falls *between* the two, which is the signature of two different bases rather than one.

`0.9674775251189847` appears again below as the best attainable score. That is the same arithmetic, `1/61 + 1/62`, reached from different ranks: under the measured law it is a row at rank 1 on *both* legs. Here it is the shared-base-60 reading of a rank-1 / rank-2 row, and it is the wrong prediction for that row.

What that means when reading the column:

- **Lower is still better** — the reciprocal ranks are subtracted from 1, so a strong row on both signals subtracts the most.
- **The values are not comparable to VECTOR-mode distances.** A hybrid 0.967 and a cosine 0.967 have nothing to do with each other.
- **The magnitude carries no similarity information**, only the ordering does. Rank 1 on both signals gives `1 - (1/61 + 1/62) = 0.9674775251189847`, the best attainable score no matter how good the match is.
- **Each reciprocal term is small and decays fast.** The vector term tops out at `1/61 ≈ 0.0164` and the lexical term at `1/62 ≈ 0.0161`; by rank 10 a term is worth 0.0143 and by rank 25, 0.0118. The whole score lives inside a range narrower than 0.02, which is why one signal can never dominate the other.
- **No pooled row forfeits a term.** The lexical leg ranks the entire candidate pool — the top `10 * top_k` rows by vector rank — not just the keyword matches: BM25 hits take lexical ranks 1..m and every remaining pooled row falls in behind them in vector order. A row whose text contains nothing like the token still carries a lexical rank — its vector rank, pushed down one place for each matching row below it. Only where nothing matches at all does the page reduce to `1 - ( 1/(60 + r) + 1/(61 + r) )` at vector rank `r`. What an exact-token match changes is that rank, promoting the row to lexical rank 1. Rows outside the pool are never scored by BM25 at all, and a result set where every row's lexical rank equals its vector rank is the signature that nothing in the pool matched.
- **`distance_type` is still accepted in hybrid mode**, and it still governs how the vector leg orders its candidates — but the value returned in `distance` is the fused rank score, never a COSINE distance, whatever is passed.

> **This decomposition is reverse-engineered from observed behavior; Google does not document it.** The reference pages describe `distance` only as the distance "for the semantic search portion of a vector search" and say nothing about fusion, the constants, or the scale change. The formula here was recovered by matching returned values to all 16 significant digits. Treat it as an explanation of what the function does today, not a contract — it can change without notice.

The cell below rebuilds the arithmetic from live results rather than asserting it: it re-runs the semantic search across all 30 tickets to recover each row's vector rank, solves the formula for the lexical rank, and then reconstructs the fused score from those two integers. At `top_k => 12` the pool is 120 rows, so all 30 tickets sit inside it and every returned row has a lexical rank to recover. Every one of them comes back as an exact integer — that is the evidence the formula is right, including the 61 on the lexical leg.

In [18]:
query = f'''
WITH incident AS (
  SELECT (AI.EMBED(
    content => '{INCIDENT_TEXT}',
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_QUERY'
  )).result AS query_vector
),
semantic AS (
  SELECT
    base.ticket_id AS ticket_id,
    ROW_NUMBER() OVER (ORDER BY distance) AS vector_rank,
    distance AS vector_distance
  FROM VECTOR_SEARCH(
    TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_embedded`,
    'embedding',
    query_value => (SELECT query_vector FROM incident),
    top_k => 30,
    distance_type => 'COSINE')
),
fused AS (
  SELECT
    base.ticket_id AS ticket_id,
    base.error_code AS error_code,
    distance AS fused_distance
  FROM VECTOR_SEARCH(
    TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_log_embedded`,
    'embedding',
    query_value => (SELECT query_vector FROM incident),
    top_k => {TOP_K},
    distance_type => 'COSINE',
    lexical_search_columns => ['error_code', 'ticket_description'],
    lexical_search_query_value => '{ERROR_CODE}')
),
terms AS (
  SELECT
    f.ticket_id,
    f.error_code,
    s.vector_rank,
    ROUND(s.vector_distance, 4) AS vector_distance,
    f.fused_distance,
    1 / (60 + s.vector_rank) AS vector_term,
    (1 - f.fused_distance) - 1 / (60 + s.vector_rank) AS lexical_term
  FROM fused f
  JOIN semantic s USING (ticket_id)
),
solved AS (
  -- The lexical leg ranks the whole candidate pool — the top 10 * top_k rows by vector
  -- rank — with BM25 matches taking ranks 1..m and every other pooled row following in
  -- vector order, so every returned row has a lexical rank to recover.
  SELECT
    *,
    CAST(ROUND(SAFE_DIVIDE(1, lexical_term) - 61) AS INT64) AS lexical_rank
  FROM terms
)
SELECT
  ticket_id,
  error_code,
  vector_rank,
  vector_distance,
  lexical_rank,
  fused_distance,
  1 - (vector_term + 1 / (61 + lexical_rank)) AS rebuilt_from_ranks
FROM solved
ORDER BY fused_distance
'''
rrf = client.query(query).to_dataframe()

gap = (rrf['rebuilt_from_ranks'] - rrf['fused_distance']).abs()
print(f'Rows whose fused score rebuilds exactly from the two integer ranks: '
      f'{int(gap.lt(1e-12).sum())} of {len(rrf)}')
print(f'Rows with a solved lexical rank: {int(rrf["lexical_rank"].notna().sum())} of {len(rrf)}')
print(f'Best solved lexical rank among the returned rows: {rrf["lexical_rank"].min()}')
rrf

Rows whose fused score rebuilds exactly from the two integer ranks: 12 of 12
Rows with a solved lexical rank: 12 of 12
Best solved lexical rank among the returned rows: 1

,ticket_id,error_code,vector_rank,vector_distance,lexical_rank,fused_distance,rebuilt_from_ranks
0,3,MFA-2210,1,0.3012,2,0.967734,0.967734
1,5,AUTH-0142,2,0.3741,3,0.968246,0.968246
2,2,AUTH-0142,3,0.4197,4,0.968742,0.968742
3,21,SEC-9001,4,0.4417,5,0.969223,0.969223
4,1,VPN-4033,5,0.4421,6,0.969690,0.969690
5,22,SEC-9014,6,0.4819,7,0.970143,0.970143
6,13,VPN-4033,7,0.4841,8,0.970582,0.970582
7,12,APP-5119,8,0.4972,9,0.971008,0.971008
8,10,DRV-3312,9,0.4981,10,0.971423,0.971423
9,25,SEC-9033,10,0.5083,11,0.971825,0.971825
10,4,PERM-0307,11,0.5143,12,0.972217,0.972217
11,28,IDP-7761,28,0.5613,1,0.972507,0.972507

Both halves of the workflow serve triage. The `AI.AGG` narratives in Step 4 answer the queue-level question — what is going wrong across all tickets this week — provided the numbers in them are checked against `GROUP BY`. Hybrid retrieval answers the ticket-level one: *has anyone seen this exact error before, and what fixed it?* Because `resolution` travels with every hit, the answer comes back with the remedy already attached.

Two things about hybrid retrieval are worth carrying out of Step 5:

- **It is a re-ranking that also widens.** The lexical leg changes the fused score of every row, so a row it adds arrives at the expense of a row the semantic search would have returned. Step 5 prints both sides of that trade rather than claiming only the upside.
- **`top_k` decides how far the widening reaches, through two gates.** BM25 only ever sees the top `10 * top_k` rows by semantic rank, and inside that pool a match is worth `1/62 ≈ 0.0161` of lift against the row holding the last slot. The tighter of the two fixes the deepest rank a matched row can climb from: 10 at `top_k => 5`, 110 at `top_k => 30`, 640 at `top_k => 64`. Size `top_k` short of that reach and the lexical leg does its work while the row it found never appears. For a code expected at semantic rank `R`, `R/10` is the floor and not the recipe — under a few hundred ranks deep the score gate binds first, so take the value from the reach table in Step 5. When an identifier is the whole question and the answer has to be certain, `WHERE error_code = @code` is the right tool — a predicate has no pool and cannot be outranked by a fusion score.

---
## Cleanup

Drop tables created by this workflow. Shared resources (dataset, models, connection) are left for other notebooks.

In [19]:
for table in ['workflow_log_tickets', 'workflow_log_classified', 'workflow_log_scored', 'workflow_log_embedded']:
    client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.{table}', not_found_ok=True)
    print(f'Dropped {table}')

Dropped workflow_log_tickets
Dropped workflow_log_classified
Dropped workflow_log_scored
Dropped workflow_log_embedded

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [20]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')