![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FApplied+GenAI%2FSolutions%2Fmulti-type-parsing-and-vector-search-2&file=grounded_generation.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FApplied%2520GenAI%2FSolutions%2Fmulti-type-parsing-and-vector-search-2%2Fgrounded_generation.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/grounded_generation.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
</table>

# Grounded Generation with Gemini

The retrieval layer (steps 0–10) is mature — 10+ search methods, hybrid RRF, crowding, sparse BM25 — but the system doesn't produce answers. Users must read raw search results themselves.

This notebook adds **grounded generation**: take search results from any method, format them as numbered source context, send to Gemini with a grounding instruction, and produce a cited response. This closes the RAG loop and turns the search pipeline into a full Retrieval-Augmented Generation system.

**What this notebook covers:**
1. Context formatting — numbered sources with chunk_id and source_type
2. System instruction — grounding constraints, citation rules
3. Structured output — Pydantic schema for per-claim citations
4. Generation — Gemini produces structured responses with per-claim source attribution
5. Search method impact — how SemanticSearch, Hybrid RRF, and Crowded search produce different responses
6. Context window management — truncation strategies for large result sets

---
# Setup

In [20]:
import string
from collections import Counter

import asyncio
import nltk
import pandas as pd
from pydantic import BaseModel
from google.cloud import bigquery, vectorsearch_v1beta
from google import genai
from google.genai.types import GenerateContentConfig
from config import (
    PROJECT_ID, REGION, GEMINI_MODEL, EMBEDDING_MODEL, EMBEDDING_DIMENSIONS,
    BQ_PROJECT, BQ_DATASET, BQ_TABLE_PREFIX,
    VS_COLLECTION_COMBINED,
    BM25_K1, BM25_B, BM25_EPSILON, BM25_NGRAMS,
)

# NLTK resources for BM25 preprocessing
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('wordnet', quiet=True)
lemmatizer = nltk.stem.WordNetLemmatizer()
stop_words = set(nltk.corpus.stopwords.words('english'))

# Search clients
search_client = vectorsearch_v1beta.DataObjectSearchServiceClient()
async_search_client = vectorsearch_v1beta.DataObjectSearchServiceAsyncClient()

# BigQuery + Gemini clients
bq = bigquery.Client(project=BQ_PROJECT)
genai_client = genai.Client(vertexai=True, project=PROJECT_ID, location=REGION)

# Collection parent path
COMBINED = f'projects/{PROJECT_ID}/locations/{REGION}/collections/{VS_COLLECTION_COMBINED}'

# Load BM25 vocabulary and model metadata from BigQuery
vocab_table = f'{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE_PREFIX}_bm25_vocabulary'
model_table = f'{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE_PREFIX}_bm25_model'

vocab_rows = list(bq.query(f'SELECT term, term_index, idf FROM `{vocab_table}`').result())
vocab_map = {row.term: row.term_index for row in vocab_rows}
idf_map = {row.term: row.idf for row in vocab_rows}

model_meta = list(bq.query(f'SELECT * FROM `{model_table}` ORDER BY model_version DESC LIMIT 1').result())[0]

print(f'BM25 model v{model_meta.model_version}: vocab={model_meta.vocab_size}, corpus={model_meta.corpus_size}, avgdl={model_meta.avgdl:.1f}')
print(f'  k1={model_meta.k1}, b={model_meta.b}, epsilon={model_meta.epsilon}, ngrams={model_meta.ngrams}')
print(f'Generation model: {GEMINI_MODEL}')

BM25 model v1: vocab=13506, corpus=117, avgdl=407.8
  k1=1.2, b=0.6, epsilon=0.25, ngrams=2
Generation model: gemini-2.5-pro

---
# Search Helpers

Minimal search helpers reused from [search_and_query.ipynb](search_and_query.ipynb) — enough to demonstrate SemanticSearch, Hybrid RRF, and Crowded search as retrieval inputs to generation.

In [21]:
def search_df(results, fields, max_text=150):
    """Format search results as a ranked DataFrame."""
    rows = []
    for r in results:
        data = r.data_object.data
        row = {}
        for f in fields:
            val = data.get(f, '')
            if isinstance(val, str) and len(val) > max_text:
                val = val[:max_text] + '...'
            elif hasattr(val, '__iter__') and not isinstance(val, str):
                val = ', '.join(str(v) for v in val)
            row[f] = val
        rows.append(row)
    df = pd.DataFrame(rows)
    df.index = range(1, len(df) + 1)
    df.index.name = 'rank'
    return df


def hybrid_search(parent, query, weights, top_k=10, fields=None):
    """Run hybrid semantic + text search with RRF reranking."""
    if fields is None:
        fields = ['chunk_id', 'text_content']
    output = vectorsearch_v1beta.OutputFields(data_fields=fields)
    request = vectorsearch_v1beta.BatchSearchDataObjectsRequest(
        parent=parent,
        searches=[
            vectorsearch_v1beta.Search(
                semantic_search=vectorsearch_v1beta.SemanticSearch(
                    search_text=query,
                    search_field='text_content_embedding',
                    task_type='QUESTION_ANSWERING',
                    top_k=top_k,
                    output_fields=output,
                )
            ),
            vectorsearch_v1beta.Search(
                text_search=vectorsearch_v1beta.TextSearch(
                    search_text=query,
                    data_field_names=['text_content'],
                    top_k=top_k,
                    output_fields=output,
                )
            ),
        ],
        combine=vectorsearch_v1beta.BatchSearchDataObjectsRequest.CombineResultsOptions(
            ranker=vectorsearch_v1beta.Ranker(
                rrf=vectorsearch_v1beta.ReciprocalRankFusion(weights=weights)
            )
        ),
    )
    response = search_client.batch_search_data_objects(request)
    if response.results:
        return list(response.results[0].results)
    return []


async def crowded_search(parent, query, crowd_field, crowd_values, top_k_per_value=2, fields=None):
    """Diversity search: top_k results per unique value of a metadata field, run in parallel."""
    if fields is None:
        fields = ['chunk_id', 'source_type', 'text_content']
    output = vectorsearch_v1beta.OutputFields(data_fields=fields)

    async def _search_one(value):
        response = await async_search_client.search_data_objects(
            vectorsearch_v1beta.SearchDataObjectsRequest(
                parent=parent,
                semantic_search=vectorsearch_v1beta.SemanticSearch(
                    search_text=query,
                    search_field='text_content_embedding',
                    task_type='QUESTION_ANSWERING',
                    top_k=top_k_per_value,
                    output_fields=output,
                    filter={crowd_field: {'$eq': value}},
                ),
            )
        )
        return value, list(response.results)

    return dict(await asyncio.gather(*[_search_one(v) for v in crowd_values]))


def chunk_prep(text, ngrams=BM25_NGRAMS):
    """Preprocess text for BM25: lowercase, remove punctuation, tokenize,
    lemmatize, remove stopwords, generate n-grams."""
    text = text.lower().translate(str.maketrans('', '', string.punctuation))
    tokens = nltk.tokenize.word_tokenize(text)
    unigrams = [lemmatizer.lemmatize(t) for t in tokens
                if len(t) > 1 and t not in stop_words]
    if ngrams >= 2:
        all_grams = unigrams.copy()
        for n in range(2, ngrams + 1):
            all_grams.extend(' '.join(g) for g in zip(*[unigrams[i:] for i in range(n)]))
        return all_grams
    return unigrams


def create_bm25_sparse_embedding(text):
    """Compute BM25 sparse embedding for query text using stored vocabulary."""
    tokens = chunk_prep(text)
    term_freqs = Counter(tokens)
    doc_len = len(tokens)
    k1, b, avgdl = model_meta.k1, model_meta.b, model_meta.avgdl

    indices, values = [], []
    for term, freq in term_freqs.items():
        if term not in vocab_map:
            continue
        idf = idf_map[term]
        score = idf * (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * doc_len / avgdl))
        indices.append(vocab_map[term])
        values.append(score)
    return indices, values

---
# Context Formatting

Search results need to be formatted as numbered sources before being sent to Gemini. The format includes chunk_id and source_type metadata so the model can reference specific sources, and so we can trace citations back to their origin.

The function works with results from both `search_data_objects` (flat list) and `batch_search_data_objects` (combined results from RRF) — both produce the same result object structure. For crowded search (dict of grouped results), flatten the groups before calling `format_context`.

An optional `max_chars` parameter truncates individual chunks for context window management (demonstrated in the final section).

In [22]:
def format_context(results, text_field='text_content', max_chars=None):
    """Format search results as numbered source context for grounded generation.

    Args:
        results: List of search result objects (from search_data_objects or batch_search_data_objects).
        text_field: Name of the data field containing the chunk text.
        max_chars: Optional max characters per chunk (truncates with '...' if exceeded).

    Returns:
        Formatted string with numbered sources.
    """
    blocks = []
    for i, r in enumerate(results, 1):
        data = r.data_object.data
        chunk_id = data.get('chunk_id', 'unknown')
        source_type = data.get('source_type', 'unknown')
        text = data.get(text_field, '')
        if max_chars and len(text) > max_chars:
            text = text[:max_chars] + '...'
        blocks.append(f'[Source {i}] (chunk_id: {chunk_id}, type: {source_type})\n{text}')
    return '\n\n'.join(blocks)

---
# System Instruction

The system instruction constrains the model to answer only from the provided sources. This is the core grounding mechanism — without it, the model may use its own knowledge rather than the retrieved context.

The default instruction enforces:
- **Source-only answers** — no external knowledge
- **Per-claim citations** — every claim carries its source numbers
- **Synthesis** — combine information across sources rather than summarizing each one
- **Disagreement handling** — present both perspectives as separate claims

Customize the instruction to change response style (e.g., more detailed, more conversational, domain-specific terminology).

In [23]:
DEFAULT_INSTRUCTION = """You are a technical assistant. Answer the user's question based ONLY on
the provided source documents. If the sources don't contain enough
information, say so — do not make up information.

Rules:
- Break your answer into individual claims, each with its supporting source numbers
- Every claim must cite at least one source
- If multiple sources support a claim, include all source numbers
- Synthesize across sources rather than summarizing each one separately
- If sources disagree, present both perspectives as separate claims
- Keep claims concise and technical"""

print(DEFAULT_INSTRUCTION)

You are a technical assistant. Answer the user's question based ONLY on
the provided source documents. If the sources don't contain enough
information, say so — do not make up information.

Rules:
- Break your answer into individual claims, each with its supporting source numbers
- Every claim must cite at least one source
- If multiple sources support a claim, include all source numbers
- Synthesize across sources rather than summarizing each one separately
- If sources disagree, present both perspectives as separate claims
- Keep claims concise and technical

---
# Response Schema

Using Gemini's [structured output](https://cloud.google.com/vertex-ai/generative-ai/docs/structured-output) with a Pydantic schema to get per-claim citations as structured data. Each `Claim` carries its statement text and the source numbers that support it. This eliminates regex-based citation parsing and gives direct access to which sources support each claim.

The schema is passed to `GenerateContentConfig(response_schema=...)` which constrains Gemini to return JSON matching this structure.

In [24]:
class Claim(BaseModel):
    """A single claim with its supporting source numbers."""
    statement: str
    source_numbers: list[int]


class GroundedResponse(BaseModel):
    """Structured response with per-claim citations."""
    claims: list[Claim]

---
# Generate Function

The generation function takes a query and pre-formatted context string, sends them to Gemini with the system instruction and response schema, and returns a `GroundedResponse` with structured per-claim citations. The prompt structure places sources first, then the question — this gives the model full context before it sees what to answer.

In [25]:
def generate_grounded(query, context, system_instruction=DEFAULT_INSTRUCTION, model=None):
    """Generate a grounded response using Gemini with retrieved context.

    Args:
        query: The user's question.
        context: Formatted source context string (from format_context).
        system_instruction: System instruction for grounding constraints.
        model: Gemini model name (defaults to GEMINI_MODEL from config).

    Returns:
        GroundedResponse with per-claim citations.
    """
    response = genai_client.models.generate_content(
        model=model or GEMINI_MODEL,
        contents=f'Sources:\n\n{context}\n\nQuestion: {query}',
        config=GenerateContentConfig(
            system_instruction=system_instruction,
            response_mime_type='application/json',
            response_schema=GroundedResponse,
        ),
    )
    return GroundedResponse.model_validate_json(response.text)

---
# Response Helpers

Helpers for working with the structured `GroundedResponse`. `render_response` produces readable text with inline citations from the structured claims. `extract_citations` collects all unique source numbers. `citation_summary` cross-references cited sources against the search results to show which chunks were used and which were available but not cited.

In [26]:
def render_response(grounded):
    """Render structured response as readable text with inline citations."""
    lines = []
    for claim in grounded.claims:
        citations = ''.join(f'[Source {n}]' for n in claim.source_numbers)
        lines.append(f'{claim.statement} {citations}')
    return '\n\n'.join(lines)


def extract_citations(grounded):
    """Extract unique source numbers from structured response."""
    return sorted({n for claim in grounded.claims for n in claim.source_numbers})


def citation_summary(grounded, results, text_field='text_content'):
    """Show which sources were cited vs available.

    Args:
        grounded: GroundedResponse object.
        results: List of search result objects used as context.
        text_field: Name of the data field containing chunk text.

    Returns:
        DataFrame with source number, cited status, chunk_id, source_type, and text preview.
    """
    cited = set(extract_citations(grounded))
    rows = []
    for i, r in enumerate(results, 1):
        data = r.data_object.data
        text = data.get(text_field, '')
        rows.append({
            'source': i,
            'cited': 'yes' if i in cited else '',
            'chunk_id': data.get('chunk_id', ''),
            'source_type': data.get('source_type', ''),
            'text_preview': text[:80] + '...' if len(text) > 80 else text,
        })
    return pd.DataFrame(rows)


def claims_df(grounded):
    """Format structured response as a DataFrame of claims."""
    rows = []
    for claim in grounded.claims:
        rows.append({
            'statement': claim.statement,
            'sources': claim.source_numbers,
        })
    df = pd.DataFrame(rows)
    df.index = range(1, len(df) + 1)
    df.index.name = 'claim'
    return df

---
# Demo 1: SemanticSearch → Generate

SemanticSearch auto-embeds the query and finds the most semantically similar chunks. For a natural language question like this, it tends to surface conversational content (Reddit threads) over structured documentation (PDFs).

In [27]:
query = 'What machine learning methods work best for demand forecasting?'
fields = ['chunk_id', 'source_type', 'text_content']

# Retrieve
semantic_results = list(search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=COMBINED,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(data_fields=fields),
        ),
    )
).results)

print(f'SemanticSearch: "{query}"')
print(f'Results: {len(semantic_results)} chunks\n')
search_df(semantic_results, fields)

SemanticSearch: "What machine learning methods work best for demand forecasting?"
Results: 5 chunks

,chunk_id,source_type,text_content
rank,,,
1,red_thread_deep_015,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,red_thread_shallow_003,reddit,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
3,red_thread_medium_000,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
4,red_thread_deep_016,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_medium_001,reddit,THREAD: Beyond ARIMA and Prophet: What are you...

In [28]:
# Format context and generate
context = format_context(semantic_results)
response = generate_grounded(query, context)

print(f'Query: {query}\n')
print(render_response(response))

Query: What machine learning methods work best for demand forecasting?

Gradient boosting models, such as LightGBM and XGBoost, are described as a "workhorse" for demand forecasting. [Source 2][Source 3]

The success of gradient boosting models in forecasting is highly dependent on proper feature engineering, which includes creating lag features, rolling window statistics, and calendar-based features. [Source 2][Source 3][Source 5]

Gradient boosting models are flexible and can incorporate numerous external regressors or exogenous variables, like promotions and weather. [Source 1][Source 2]

For many business problems, a well-tuned gradient boosting model can achieve 95% of the performance of a deep learning model for about 10% of the effort, complexity, and training cost. [Source 4][Source 5]

A potential weakness of gradient boosting is that it does not perform well when extrapolating far into the future unless a good trend feature is engineered. [Source 2]

Deep learning models like N-BEATS and Temporal Fusion Transformers (TFT) are considered state-of-the-art (SOTA) on many forecasting benchmarks. [Source 1][Source 3]

Deep learning models are recommended for use with very large datasets, such as thousands of parallel time series. [Source 3][Source 4]

Both N-BEATS and TFT architectures are noted for their interpretability. [Source 1][Source 3]

The high data requirements, training time, and computational costs of deep learning models can be prohibitive for standard business applications. [Source 4][Source 5]

LSTM models are considered somewhat dated in comparison to newer architectures like N-BEATS and TFT. [Source 3]

The PyTorch Forecasting library is a recommended starting point for implementing TFT and N-BEATS models. [Source 5]

In [29]:
# Structured claims
claims_df(response)

                                               statement    sources
claim
1      Gradient boosting models, such as LightGBM and...     [2, 3]
2      The success of gradient boosting models in for...  [2, 3, 5]
3      Gradient boosting models are flexible and can ...     [1, 2]
4      For many business problems, a well-tuned gradi...     [4, 5]
5      A potential weakness of gradient boosting is t...        [2]
6      Deep learning models like N-BEATS and Temporal...     [1, 3]
7      Deep learning models are recommended for use w...     [3, 4]
8      Both N-BEATS and TFT architectures are noted f...     [1, 3]
9      The high data requirements, training time, and...     [4, 5]
10     LSTM models are considered somewhat dated in c...        [3]
11     The PyTorch Forecasting library is a recommend...        [5]

In [30]:
# Citation summary
cited = extract_citations(response)
print(f'Citations used: {cited}\n')
citation_summary(response, semantic_results)

Citations used: [1, 2, 3, 4, 5]

,source,cited,chunk_id,source_type,text_preview
0,1,yes,red_thread_deep_015,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
1,2,yes,red_thread_shallow_003,reddit,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,3,yes,red_thread_medium_000,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
3,4,yes,red_thread_deep_016,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
4,5,yes,red_thread_medium_001,reddit,THREAD: Beyond ARIMA and Prophet: What are you...

---
# Demo 2: Hybrid RRF → Generate

Hybrid search combines SemanticSearch and TextSearch with RRF reranking. This brings in keyword-matched content (typically PDF documentation) alongside semantically similar content (typically Reddit discussion). The generated response should include more technical detail from documentation sources.

In [31]:
fields = ['chunk_id', 'source_type', 'text_content']

# Retrieve with hybrid RRF
hybrid_results = hybrid_search(COMBINED, query, weights=[1.0, 1.0], top_k=5, fields=fields)

print(f'Hybrid RRF [1.0, 1.0]: "{query}"')
print(f'Results: {len(hybrid_results)} chunks\n')
search_df(hybrid_results, fields)

Hybrid RRF [1.0, 1.0]: "What machine learning methods work best for demand forecasting?"
Results: 5 chunks

,chunk_id,source_type,text_content
rank,,,
1,red_thread_deep_015,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,red_thread_shallow_003,reddit,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
3,red_thread_medium_000,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
4,red_thread_deep_016,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_medium_001,reddit,THREAD: Beyond ARIMA and Prophet: What are you...

In [32]:
# Format context and generate
context = format_context(hybrid_results)
response_hybrid = generate_grounded(query, context)

print(f'Query: {query}\n')
print(render_response(response_hybrid))

Query: What machine learning methods work best for demand forecasting?

Gradient boosting models like LightGBM and XGBoost are considered a go-to "workhorse" for demand forecasting. [Source 1][Source 2][Source 3][Source 5]

The effectiveness of gradient boosting relies on proper feature engineering, such as creating lag features, rolling window statistics, and calendar features. [Source 2][Source 3]

Gradient boosting models can incorporate a large number of external variables like promotions and weather. [Source 1][Source 2]

A well-tuned gradient boosting model can achieve 95% of the performance of a deep learning model with only 10% of the effort and cost. [Source 4][Source 5]

A drawback of gradient boosting is that it is not well-suited for extrapolating far into the future without a strong trend feature. [Source 2]

Deep learning models such as N-BEATS and Temporal Fusion Transformers (TFT) are considered state-of-the-art for many forecasting benchmarks. [Source 1][Source 3]

Deep learning models are most suitable for very large datasets, such as thousands of parallel time series. [Source 3][Source 4]

The data requirements, training time, and computational costs of deep learning models can be prohibitive for standard business applications. [Source 4][Source 5]

The N-BEATS and TFT architectures are noted for their interpretability. [Source 1][Source 3]

Long Short-Term Memory (LSTM) models are considered a somewhat dated deep learning architecture for forecasting. [Source 3]

Dynamic Linear Models (DLMs), or State-Space Models, are a flexible and interpretable framework for modeling trend, seasonality, and external variables. [Source 3]

The PyTorch Forecasting library is a recommended resource for implementing TFT and N-BEATS models. [Source 5]

In [33]:
# Structured claims
claims_df(response_hybrid)

                                               statement       sources
claim
1      Gradient boosting models like LightGBM and XGB...  [1, 2, 3, 5]
2      The effectiveness of gradient boosting relies ...        [2, 3]
3      Gradient boosting models can incorporate a lar...        [1, 2]
4      A well-tuned gradient boosting model can achie...        [4, 5]
5      A drawback of gradient boosting is that it is ...           [2]
6      Deep learning models such as N-BEATS and Tempo...        [1, 3]
7      Deep learning models are most suitable for ver...        [3, 4]
8      The data requirements, training time, and comp...        [4, 5]
9      The N-BEATS and TFT architectures are noted fo...        [1, 3]
10     Long Short-Term Memory (LSTM) models are consi...           [3]
11     Dynamic Linear Models (DLMs), or State-Space M...           [3]
12     The PyTorch Forecasting library is a recommend...           [5]

In [34]:
# Citation summary
cited_hybrid = extract_citations(response_hybrid)
print(f'Citations used: {cited_hybrid}\n')
citation_summary(response_hybrid, hybrid_results)

Citations used: [1, 2, 3, 4, 5]

,source,cited,chunk_id,source_type,text_preview
0,1,yes,red_thread_deep_015,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
1,2,yes,red_thread_shallow_003,reddit,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,3,yes,red_thread_medium_000,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
3,4,yes,red_thread_deep_016,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
4,5,yes,red_thread_medium_001,reddit,THREAD: Beyond ARIMA and Prophet: What are you...

---
# Demo 3: Crowded Search → Generate

Crowded search retrieves top results per source type (reddit, zoom, pdf), ensuring all three perspectives are represented in the context. This produces the most balanced response — no single source type dominates.

In [35]:
fields = ['chunk_id', 'source_type', 'text_content']

# Retrieve with crowded search
crowded_results = await crowded_search(
    COMBINED, query,
    crowd_field='source_type',
    crowd_values=['reddit', 'zoom', 'pdf'],
    top_k_per_value=2,
    fields=fields,
)

for source_type, hits in crowded_results.items():
    print(f'{source_type}: {len(hits)} results')

# Flatten grouped results into a single list for context formatting
crowded_flat = [r for hits in crowded_results.values() for r in hits]
print(f'\nTotal: {len(crowded_flat)} chunks')

reddit: 2 results
zoom: 2 results
pdf: 2 results

Total: 6 chunks

In [36]:
# Format context and generate
context = format_context(crowded_flat)
response_crowded = generate_grounded(query, context)

print(f'Query: {query}\n')
print(render_response(response_crowded))

Query: What machine learning methods work best for demand forecasting?

Gradient boosting models like LightGBM and XGBoost are often favored for their flexibility and accuracy, especially when enough data is available. [Source 1][Source 2]

The primary advantage of gradient boosting models is their ability to incorporate a vast number of external regressors, such as promotions, weather, or holidays. [Source 1][Source 2]

To use gradient boosting models effectively, one must perform feature engineering, creating features like lags, rolling window statistics, and calendar attributes. [Source 2][Source 4]

A drawback of gradient boosting models is that they are not ideal for long-term extrapolation unless a good trend feature is engineered. [Source 2]

While sometimes considered a 'black box', LightGBM forecasts can be interpreted using SHAP values, which show the contribution of each feature to a specific prediction. [Source 3][Source 4]

The extensive feature engineering required for gradient boosting can be a significant upfront effort and may lead to a higher risk of overfitting the model to noise. [Source 4]

Prophet is considered an intuitive and fast model to implement, making it a strong choice for a scalable baseline, especially for analysts familiar with business calendars. [Source 3][Source 4]

Prophet automatically decomposes a time series into trend, weekly seasonality, and yearly seasonality, and is resilient to missing data and trend shifts. [Source 3]

A key limitation of Prophet is that, as a generalized additive model, it struggles to capture complex interactions between features, like a promotion's effect during a holiday. [Source 3]

SARIMA is a classical statistical model considered a 'gold standard' that explicitly models trend, seasonality, and autocorrelation, providing interpretable parameters and confidence intervals. [Source 3]

The main challenge with SARIMA is its difficulty in scaling, as manually tuning its parameters for thousands of individual time series is a 'daunting' task. [Source 3][Source 4]

Despite scaling challenges, BigQuery ML offers tools to perform scalable forecasting with ARIMA on millions of time series. [Source 5]

Deep learning models such as N-BEATS and Temporal Fusion Transformers (TFT) are considered state-of-the-art on many forecasting benchmarks. [Source 1]

The Temporal Fusion Transformer (TFT) is a deep learning architecture noted for being interpretable, offering insights comparable to traditional models. [Source 1]

A common strategy for model selection is to run a 'bake-off', comparing models like Prophet, LightGBM, and SARIMA on a representative dataset using metrics like MAPE and RMSE. [Source 4]

BigQuery ML offers an `AI.FORECAST` function that uses a `TimesFM` model for time series forecasting. [Source 6]

In [37]:
# Structured claims
claims_df(response_crowded)

                                               statement sources
claim
1      Gradient boosting models like LightGBM and XGB...  [1, 2]
2      The primary advantage of gradient boosting mod...  [1, 2]
3      To use gradient boosting models effectively, o...  [2, 4]
4      A drawback of gradient boosting models is that...     [2]
5      While sometimes considered a 'black box', Ligh...  [3, 4]
6      The extensive feature engineering required for...     [4]
7      Prophet is considered an intuitive and fast mo...  [3, 4]
8      Prophet automatically decomposes a time series...     [3]
9      A key limitation of Prophet is that, as a gene...     [3]
10     SARIMA is a classical statistical model consid...     [3]
11     The main challenge with SARIMA is its difficul...  [3, 4]
12     Despite scaling challenges, BigQuery ML offers...     [5]
13     Deep learning models such as N-BEATS and Tempo...     [1]
14     The Temporal Fusion Transformer (TFT) is a dee...     [1]
15     A common strategy for model selection is to ru...     [4]
16     BigQuery ML offers an `AI.FORECAST` function t...     [6]

In [38]:
# Citation summary
cited_crowded = extract_citations(response_crowded)
print(f'Citations used: {cited_crowded}\n')
citation_summary(response_crowded, crowded_flat)

Citations used: [1, 2, 3, 4, 5, 6]

,source,cited,chunk_id,source_type,text_preview
0,1,yes,red_thread_deep_015,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
1,2,yes,red_thread_shallow_003,reddit,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,3,yes,zoom_meeting_model_planning_000,zoom,"Sarah (Lead): Alright everyone, thanks for joi..."
3,4,yes,zoom_meeting_model_planning_002,zoom,[Summary: The team weighs the pros and cons of...
4,5,yes,pdf_90bbc35dad_c19,pdf,# What's next\n\n• Try the following tutorials...
5,6,yes,pdf_1fa007c733_c4,pdf,# The Al.FORECAST function\n\n## Examples\n\nT...

---
# Comparison

Same query, three retrieval methods. Compare the source types in context, source types cited, number of claims, and a preview of each response.

In [39]:
def source_types(results):
    """Count source types in a result list."""
    types = [r.data_object.data.get('source_type', 'unknown') for r in results]
    return dict(Counter(types))


def cited_source_types(grounded, results):
    """Count source types of cited sources only."""
    cited_nums = set(extract_citations(grounded))
    types = []
    for i, r in enumerate(results, 1):
        if i in cited_nums:
            types.append(r.data_object.data.get('source_type', 'unknown'))
    return dict(Counter(types))


comparison = pd.DataFrame([
    {
        'method': 'SemanticSearch',
        'sources_in_context': source_types(semantic_results),
        'sources_cited': cited_source_types(response, semantic_results),
        'num_claims': len(response.claims),
        'citations_used': len(extract_citations(response)),
        'response_preview': render_response(response)[:150] + '...',
    },
    {
        'method': 'Hybrid RRF',
        'sources_in_context': source_types(hybrid_results),
        'sources_cited': cited_source_types(response_hybrid, hybrid_results),
        'num_claims': len(response_hybrid.claims),
        'citations_used': len(extract_citations(response_hybrid)),
        'response_preview': render_response(response_hybrid)[:150] + '...',
    },
    {
        'method': 'Crowded',
        'sources_in_context': source_types(crowded_flat),
        'sources_cited': cited_source_types(response_crowded, crowded_flat),
        'num_claims': len(response_crowded.claims),
        'citations_used': len(extract_citations(response_crowded)),
        'response_preview': render_response(response_crowded)[:150] + '...',
    },
])

comparison

,method,sources_in_context,sources_cited,num_claims,citations_used,response_preview
0,SemanticSearch,{'reddit': 5},{'reddit': 5},11,5,"Gradient boosting models, such as LightGBM and..."
1,Hybrid RRF,{'reddit': 5},{'reddit': 5},12,5,Gradient boosting models like LightGBM and XGB...
2,Crowded,"{'reddit': 2, 'zoom': 2, 'pdf': 2}","{'reddit': 2, 'zoom': 2, 'pdf': 2}",16,6,Gradient boosting models like LightGBM and XGB...

---
# Context Window Management

As `top_k` increases or chunks get longer, the combined context can approach Gemini's context window limit. Three strategies to manage this:

1. **Reduce `top_k`** — fewer chunks, less context
2. **Truncate chunks** — use `max_chars` in `format_context` to limit individual chunk length
3. **Summarize before generation** — pre-summarize long chunks (adds latency and cost)

The simplest approach is to combine `top_k` and `max_chars`. Below we demonstrate with `top_k=10` and `max_chars=500` to show the effect on context size and response quality.

In [40]:
# Full context (no truncation)
full_results = hybrid_search(COMBINED, query, weights=[1.0, 1.0], top_k=10, fields=fields)
full_context = format_context(full_results)
approx_tokens_full = len(full_context.split())

# Truncated context
truncated_context = format_context(full_results, max_chars=500)
approx_tokens_truncated = len(truncated_context.split())

print(f'top_k=10, no truncation:     ~{approx_tokens_full:,} words')
print(f'top_k=10, max_chars=500:     ~{approx_tokens_truncated:,} words')
print(f'Reduction:                   {(1 - approx_tokens_truncated / approx_tokens_full) * 100:.0f}%')

top_k=10, no truncation:     ~1,541 words
top_k=10, max_chars=500:     ~828 words
Reduction:                   46%

In [41]:
# Generate with truncated context
response_truncated = generate_grounded(query, truncated_context)

print(f'Query: {query}')
print(f'Context: top_k=10, max_chars=500\n')
print(render_response(response_truncated))

Query: What machine learning methods work best for demand forecasting?
Context: top_k=10, max_chars=500

Gradient boosting models, such as LightGBM and XGBoost, are frequently recommended for demand forecasting problems, often as a more flexible alternative to statistical models. [Source 1][Source 2][Source 5][Source 8][Source 9]

A primary advantage of gradient boosting models is the ability to incorporate numerous exogenous variables, such as marketing spend, competitor pricing, and weather data. [Source 1][Source 2][Source 8]

Effective use of gradient boosting models for forecasting requires feature engineering, including the creation of lag features, rolling window statistics (e.g., mean, standard deviation), and calendar features (e.g., day of week, holiday). [Source 2][Source 5][Source 7][Source 8]

LightGBM is noted for its ability to scale, with one source mentioning its use for forecasting across hundreds of thousands of SKUs. [Source 9]

Deep learning models like N-BEATS and Temporal Fusion Transformers (TFT) are considered state-of-the-art on many forecasting benchmarks. [Source 1]

Despite being state-of-the-art, deep learning models can have prohibitive data requirements and training costs for standard business problems when compared to LightGBM. [Source 4][Source 9]

Dynamic Linear Models (DLMs), also known as State-Space Models, are a flexible framework for forecasting series with multiple seasonalities and external variables, with the benefit of high interpretability. [Source 3]

In [42]:
# Structured claims
claims_df(response_truncated)

                                               statement          sources
claim
1      Gradient boosting models, such as LightGBM and...  [1, 2, 5, 8, 9]
2      A primary advantage of gradient boosting model...        [1, 2, 8]
3      Effective use of gradient boosting models for ...     [2, 5, 7, 8]
4      LightGBM is noted for its ability to scale, wi...              [9]
5      Deep learning models like N-BEATS and Temporal...              [1]
6      Despite being state-of-the-art, deep learning ...           [4, 9]
7      Dynamic Linear Models (DLMs), also known as St...              [3]

In [43]:
# Citation summary for truncated context
cited_truncated = extract_citations(response_truncated)
print(f'Citations used: {cited_truncated} (out of {len(full_results)} sources)\n')
citation_summary(response_truncated, full_results)

Citations used: [1, 2, 3, 4, 5, 7, 8, 9] (out of 10 sources)

,source,cited,chunk_id,source_type,text_preview
0,1,yes,red_thread_deep_015,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
1,2,yes,red_thread_shallow_003,reddit,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,3,yes,red_thread_medium_000,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
3,4,yes,red_thread_deep_016,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
4,5,yes,red_thread_medium_001,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
5,6,,zoom_meeting_model_planning_000,zoom,"Sarah (Lead): Alright everyone, thanks for joi..."
6,7,yes,red_thread_shallow_004,reddit,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
7,8,yes,red_thread_deep_001,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
8,9,yes,red_thread_medium_002,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
9,10,,red_thread_deep_009,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

---
# Observations

**Structured output:**
- Per-claim citations via Pydantic schema eliminate regex parsing and provide direct access to which sources support each claim
- Each claim is independently traceable — downstream evaluation can check whether a claim is actually supported by its cited source(s)
- The `claims_df` view makes it easy to inspect the response structure and spot uncited or weakly-cited claims
- `render_response` reconstructs readable text with inline `[Source N]` notation from the structured data

**Search method impact on generation:**
- **SemanticSearch** context is dominated by conversational content (Reddit), producing opinion-heavy claims with community-sourced recommendations
- **Hybrid RRF** brings in PDF documentation alongside Reddit discussion, producing claims that include both practical experience and technical reference details
- **Crowded search** forces representation from all source types (reddit, zoom, pdf), producing the most balanced multi-perspective claims

**Citation behavior:**
- The model generally cites the most relevant sources and may skip less relevant ones, even when they're available in context
- Multi-source citations on a single claim appear when multiple sources independently support the same point
- The number of claims varies by response — more diverse context (crowded search) tends to produce more claims

**Context window management:**
- `max_chars` truncation reduces context size while preserving the beginning of each chunk (where the most important structural context usually appears)
- At 10+ sources, truncation becomes important for staying within token limits and keeping generation focused
- The model can still produce good responses from truncated context because the `[Source N]` headers and leading text provide enough signal

**For production use:**
- Crowded or hybrid RRF provides the most reliable grounding — single-method retrieval can produce biased responses
- The system instruction is critical: without it, the model freely mixes retrieved context with its own knowledge
- Structured output enables programmatic quality checks — claims with empty `source_numbers`, source numbers outside the valid range, or zero total claims all indicate grounding failures