![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FApplied+GenAI%2FSolutions%2Fmulti-type-parsing-and-vector-search-2&file=search_and_query.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FApplied%2520GenAI%2FSolutions%2Fmulti-type-parsing-and-vector-search-2%2Fsearch_and_query.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
</table>

# Search & Query: Vector Search 2.0 Collections

This notebook demonstrates querying and searching all four collections — Reddit, Zoom, PDF, and Combined. Covers:

- **Query**: Filter DataObjects by field values (analogous to SQL `WHERE`)
- **Semantic Search**: Natural language queries using auto-generated embeddings
- **Text Search**: Keyword-based full-text search
- **Hybrid Search**: Combine semantic + text with [Reciprocal Rank Fusion (RRF)](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf)
- **RRF Weight Tuning**: How adjusting weights shifts result ranking
- **Crowding/Diversity Search**: Retrieve top-k results per unique value of a metadata field using parallel async searches

**Embedding task types:** The collections were indexed with `task_type="RETRIEVAL_DOCUMENT"` (see step 4). At search time, we use `task_type="QUESTION_ANSWERING"` — the asymmetric counterpart that tells the embedding model the search text is a question looking for answers in the indexed documents. This document/query pairing produces embeddings optimized for matching questions to relevant reference material. Other asymmetric query types include `RETRIEVAL_QUERY` (general search), `FACT_VERIFICATION`, and `CODE_RETRIEVAL_QUERY`. See [embedding task types](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/task-types) for the full reference.

In [1]:
import pandas as pd
import asyncio
from google.cloud import vectorsearch_v1beta
from config import (
    PROJECT_ID, REGION,
    VS_COLLECTION_REDDIT, VS_COLLECTION_ZOOM, VS_COLLECTION_PDF, VS_COLLECTION_COMBINED,
)

# Sync clients
vs_client = vectorsearch_v1beta.VectorSearchServiceClient()
do_client = vectorsearch_v1beta.DataObjectServiceClient()
search_client = vectorsearch_v1beta.DataObjectSearchServiceClient()

# Async client for parallel searches (used in crowding/diversity queries)
async_search_client = vectorsearch_v1beta.DataObjectSearchServiceAsyncClient()

# Collection parent paths
REDDIT = f'projects/{PROJECT_ID}/locations/{REGION}/collections/{VS_COLLECTION_REDDIT}'
ZOOM = f'projects/{PROJECT_ID}/locations/{REGION}/collections/{VS_COLLECTION_ZOOM}'
PDF = f'projects/{PROJECT_ID}/locations/{REGION}/collections/{VS_COLLECTION_PDF}'
COMBINED = f'projects/{PROJECT_ID}/locations/{REGION}/collections/{VS_COLLECTION_COMBINED}'

print(f'Reddit:   {VS_COLLECTION_REDDIT}')
print(f'Zoom:     {VS_COLLECTION_ZOOM}')
print(f'PDF:      {VS_COLLECTION_PDF}')
print(f'Combined: {VS_COLLECTION_COMBINED}')

Reddit:   applied-genai-solutions-multi-type-parsing-reddit
Zoom:     applied-genai-solutions-multi-type-parsing-zoom
PDF:      applied-genai-solutions-multi-type-parsing-pdf
Combined: applied-genai-solutions-multi-type-parsing-combined

In [2]:
def search_df(results, fields, max_text=150):
    """Format search results as a ranked DataFrame."""
    rows = []
    for r in results:
        data = r.data_object.data
        row = {}
        for f in fields:
            val = data.get(f, '')
            if isinstance(val, str) and len(val) > max_text:
                val = val[:max_text] + '...'
            elif hasattr(val, '__iter__') and not isinstance(val, str):
                val = ', '.join(str(v) for v in val)
            row[f] = val
        rows.append(row)
    df = pd.DataFrame(rows)
    df.index = range(1, len(df) + 1)
    df.index.name = 'rank'
    return df


def query_df(results, fields, max_text=150):
    """Format query results as a DataFrame."""
    rows = []
    for r in results:
        row = {}
        for f in fields:
            val = r.data.get(f, '')
            if isinstance(val, str) and len(val) > max_text:
                val = val[:max_text] + '...'
            elif hasattr(val, '__iter__') and not isinstance(val, str):
                val = ', '.join(str(v) for v in val)
            row[f] = val
        rows.append(row)
    return pd.DataFrame(rows)


def hybrid_search(parent, query, weights, top_k=10, fields=None):
    """Run hybrid semantic + text search with RRF reranking."""
    if fields is None:
        fields = ['chunk_id', 'text_content']
    output = vectorsearch_v1beta.OutputFields(data_fields=fields)
    request = vectorsearch_v1beta.BatchSearchDataObjectsRequest(
        parent=parent,
        searches=[
            vectorsearch_v1beta.Search(
                semantic_search=vectorsearch_v1beta.SemanticSearch(
                    search_text=query,
                    search_field='text_content_embedding',
                    task_type='QUESTION_ANSWERING',
                    top_k=top_k,
                    output_fields=output,
                )
            ),
            vectorsearch_v1beta.Search(
                text_search=vectorsearch_v1beta.TextSearch(
                    search_text=query,
                    data_field_names=['text_content'],
                    top_k=top_k,
                    output_fields=output,
                )
            ),
        ],
        combine=vectorsearch_v1beta.BatchSearchDataObjectsRequest.CombineResultsOptions(
            ranker=vectorsearch_v1beta.Ranker(
                rrf=vectorsearch_v1beta.ReciprocalRankFusion(weights=weights)
            )
        ),
    )
    response = search_client.batch_search_data_objects(request)
    if response.results:
        return list(response.results[0].results)
    return []


async def crowded_search(parent, query, crowd_field, crowd_values, top_k_per_value=2, fields=None):
    """Diversity search: top_k results per unique value of a metadata field, run in parallel.

    Uses the async client to run filtered semantic searches concurrently — one per
    crowd_field value. Returns a dict mapping each value to its ranked search results.
    """
    if fields is None:
        fields = ['chunk_id', 'source_type', 'text_content']
    output = vectorsearch_v1beta.OutputFields(data_fields=fields)

    async def _search_one(value):
        response = await async_search_client.search_data_objects(
            vectorsearch_v1beta.SearchDataObjectsRequest(
                parent=parent,
                semantic_search=vectorsearch_v1beta.SemanticSearch(
                    search_text=query,
                    search_field='text_content_embedding',
                    task_type='QUESTION_ANSWERING',
                    top_k=top_k_per_value,
                    output_fields=output,
                    filter={crowd_field: {'$eq': value}},
                ),
            )
        )
        return value, list(response.results)

    return dict(await asyncio.gather(*[_search_one(v) for v in crowd_values]))


def crowded_df(grouped_results, fields, max_text=150):
    """Format crowded search results as a DataFrame with group labels."""
    rows = []
    for group, results in grouped_results.items():
        for rank, r in enumerate(results, 1):
            data = r.data_object.data
            row = {'group': group, 'group_rank': rank}
            for f in fields:
                val = data.get(f, '')
                if isinstance(val, str) and len(val) > max_text:
                    val = val[:max_text] + '...'
                elif hasattr(val, '__iter__') and not isinstance(val, str):
                    val = ', '.join(str(v) for v in val)
                row[f] = val
            rows.append(row)
    return pd.DataFrame(rows)

---
# Reddit Collection

The Reddit collection contains flattened thread chunks with conversational context (`THREAD: title | PARENT: context | COMMENT: body`). Each chunk includes metadata: `subreddit`, `karma`, and `is_image_description`.

In [3]:
# Count DataObjects in the Reddit collection
search_client.aggregate_data_objects(
    vectorsearch_v1beta.AggregateDataObjectsRequest(parent=REDDIT, aggregate='COUNT')
)

aggregate_results {
  fields {
    key: "count"
    value {
      number_value: 34
    }
  }
}

## Query: Filtering by Field Values

Query lets you filter DataObjects by their data fields — similar to a SQL `WHERE` clause. Supports comparison operators (`$eq`, `$gt`, `$lt`, `$gte`, `$lte`), logical operators (`$and`, `$or`), and array operators (`$in`, `$nin`).

In [4]:
# Find high-karma Reddit chunks (quality signal)
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=REDDIT,
        filter={'karma': {'$gt': 50}},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'subreddit', 'karma', 'text_content']
        ),
    )
))
print(f'{len(results)} chunks with karma > 50')
query_df(results, ['chunk_id', 'subreddit', 'karma', 'text_content'])

7 chunks with karma > 50

,chunk_id,subreddit,karma,text_content
0,red_thread_shallow_003,r/datascience,52.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
1,red_thread_shallow_000,r/datascience,89.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,red_thread_medium_004,r/datascience,52.0,THREAD: Beyond ARIMA and Prophet: What are you...
3,red_thread_medium_000,r/datascience,98.0,THREAD: Beyond ARIMA and Prophet: What are you...
4,red_thread_deep_001,r/datascience,121.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_deep_000,r/datascience,82.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
6,red_thread_deep_007,r/datascience,53.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

In [5]:
# Combined filter: high karma AND image-enriched chunks
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=REDDIT,
        filter={'$and': [{'karma': {'$gte': 20}}, {'is_image_description': {'$eq': True}}]},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'karma', 'is_image_description', 'text_content']
        ),
    )
))
print(f'{len(results)} image-enriched chunks with karma >= 20')
query_df(results, ['chunk_id', 'karma', 'is_image_description', 'text_content'])

3 image-enriched chunks with karma >= 20

,chunk_id,karma,is_image_description,text_content
0,red_thread_medium_006,31.0,True,THREAD: Beyond ARIMA and Prophet: What are you...
1,red_thread_medium_004,52.0,True,THREAD: Beyond ARIMA and Prophet: What are you...
2,red_thread_deep_001,121.0,True,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

## Semantic Search

Semantic search converts your natural language query into an embedding and finds DataObjects with the most similar `text_content_embedding` vectors. The query uses `task_type='QUESTION_ANSWERING'` to pair with the documents indexed as `RETRIEVAL_DOCUMENT` — this asymmetric pairing helps the model understand that queries and documents have different intents.

In [6]:
query = 'What machine learning methods work best for demand forecasting?'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=REDDIT,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'subreddit', 'karma', 'text_content']
            ),
        ),
    )
)

print(f'Semantic search: "{query}"\n')
search_df(results, ['chunk_id', 'subreddit', 'karma', 'text_content'])

Semantic search: "What machine learning methods work best for demand forecasting?"

,chunk_id,subreddit,karma,text_content
rank,,,,
1,red_thread_deep_015,r/datascience,9.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,red_thread_shallow_003,r/datascience,52.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
3,red_thread_medium_000,r/datascience,98.0,THREAD: Beyond ARIMA and Prophet: What are you...
4,red_thread_deep_016,r/datascience,15.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_medium_001,r/datascience,45.0,THREAD: Beyond ARIMA and Prophet: What are you...

## Text Search

Text search provides keyword-based full-text matching. Useful for finding specific method names, acronyms, or terms that may not have strong semantic representation in the embedding model.

In [7]:
query = 'ARIMA'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=REDDIT,
        text_search=vectorsearch_v1beta.TextSearch(
            search_text=query,
            data_field_names=['text_content'],
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'subreddit', 'karma', 'text_content']
            ),
        ),
    )
)

print(f'Text search: "{query}"\n')
search_df(results, ['chunk_id', 'subreddit', 'karma', 'text_content'])

Text search: "ARIMA"

,chunk_id,subreddit,karma,text_content
rank,,,,
1,red_thread_shallow_000,r/datascience,89.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,red_thread_shallow_006,r/datascience,33.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
3,red_thread_shallow_002,r/datascience,25.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
4,red_thread_shallow_001,r/datascience,-12.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
5,red_thread_deep_014,r/datascience,31.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

## Hybrid Search with Reciprocal Rank Fusion (RRF)

Hybrid search runs both semantic and text searches in parallel, then combines results using [RRF](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf). RRF merges ranked lists by assigning each result a score based on its rank position in each list, then sorting by combined score.

The `weights` parameter controls the relative importance of each search:
- `[1.0, 1.0]` — equal balance between semantic and text
- `[3.0, 1.0]` — favor semantic understanding (better for intent-based queries)
- `[1.0, 3.0]` — favor keyword matching (better for exact-term queries)

In [8]:
query = 'seasonal ARIMA forecasting methods'
fields = ['chunk_id', 'subreddit', 'karma', 'text_content']

results = hybrid_search(REDDIT, query, weights=[1.0, 1.0], top_k=5, fields=fields)

print(f'Hybrid search (equal weights [1, 1]): "{query}"\n')
search_df(results, fields)

Hybrid search (equal weights [1, 1]): "seasonal ARIMA forecasting methods"

,chunk_id,subreddit,karma,text_content
rank,,,,
1,red_thread_deep_000,r/datascience,82.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,red_thread_medium_004,r/datascience,52.0,THREAD: Beyond ARIMA and Prophet: What are you...
3,red_thread_medium_007,r/datascience,41.0,THREAD: Beyond ARIMA and Prophet: What are you...
4,red_thread_deep_003,r/datascience,18.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_deep_004,r/datascience,25.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
6,red_thread_medium_000,r/datascience,98.0,THREAD: Beyond ARIMA and Prophet: What are you...
7,red_thread_deep_011,r/datascience,22.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
8,red_thread_shallow_000,r/datascience,89.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...

### RRF Weight Comparison

The table below shows how the same query produces different rankings under three weight configurations. A lower rank number means higher relevance. Watch how chunks shift position as the balance changes between semantic understanding and keyword matching.

In [9]:
query = 'seasonal ARIMA forecasting methods'
fields = ['chunk_id', 'text_content']

configs = {
    'Equal [1, 1]': [1.0, 1.0],
    'Semantic [3, 1]': [3.0, 1.0],
    'Text [1, 3]': [1.0, 3.0],
}

rankings = {}
for label, weights in configs.items():
    results = hybrid_search(REDDIT, query, weights, top_k=10, fields=fields)
    for rank, r in enumerate(results, 1):
        cid = r.data_object.data['chunk_id']
        if cid not in rankings:
            text = r.data_object.data['text_content']
            rankings[cid] = {'chunk_id': cid, 'text_preview': text[:100] + '...'}
        rankings[cid][label] = rank

comparison = pd.DataFrame(rankings.values()).sort_values('Equal [1, 1]')
print(f'RRF weight comparison: "{query}"')
print('Lower rank = higher relevance. Watch how chunks shift position.\n')
comparison

RRF weight comparison: "seasonal ARIMA forecasting methods"
Lower rank = higher relevance. Watch how chunks shift position.

,chunk_id,text_preview,"Equal [1, 1]","Semantic [3, 1]","Text [1, 3]"
0,red_thread_medium_004,THREAD: Beyond ARIMA and Prophet: What are you...,1,1,1
1,red_thread_medium_000,THREAD: Beyond ARIMA and Prophet: What are you...,2,2,2
2,red_thread_deep_000,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,3,3,4
3,red_thread_medium_007,THREAD: Beyond ARIMA and Prophet: What are you...,4,11,3
4,red_thread_deep_003,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,5,4,5
5,red_thread_deep_004,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,6,5,6
6,red_thread_deep_011,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,7,6,7
7,red_thread_shallow_000,THREAD: ARIMA vs. Prophet for Retail Demand Fo...,8,7,8
8,red_thread_deep_013,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,9,8,9
9,red_thread_deep_012,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,10,9,10
10,red_thread_deep_014,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,11,10,11

---
# Zoom Collection

The Zoom collection contains sliding-window transcript chunks with speaker labels and timestamp ranges. Each chunk covers ~15 cues with 5-cue overlap between neighbors. Non-first windows include a Gemini-generated rolling summary prefix.

In [10]:
# Count DataObjects in the Zoom collection
search_client.aggregate_data_objects(
    vectorsearch_v1beta.AggregateDataObjectsRequest(parent=ZOOM, aggregate='COUNT')
)

aggregate_results {
  fields {
    key: "count"
    value {
      number_value: 12
    }
  }
}

## Query: Browsing Transcript Chunks

Filter by timestamp to find chunks from later in meetings, or browse all chunks to see the speaker distribution.

In [11]:
# Find transcript chunks from later in meetings (past 5 minutes)
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=ZOOM,
        filter={'timestamp_start': {'$gt': 300}},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'speaker_list', 'timestamp_start', 'timestamp_end', 'text_content']
        ),
    )
))
print(f'{len(results)} chunks starting after 5:00')
query_df(results, ['chunk_id', 'speaker_list', 'timestamp_start', 'timestamp_end', 'text_content'])

1 chunks starting after 5:00

,chunk_id,speaker_list,timestamp_start,timestamp_end,text_content
0,zoom_meeting_business_readout_003,"Dr. Anya Sharma, Maria Rodriguez, Sarah Jenkin...",318.06,341.36,[Summary: The team agreed to provide cleaner d...

## Semantic Search

In [12]:
query = 'How should we evaluate forecast model accuracy and performance?'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=ZOOM,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'speaker_list', 'text_content']
            ),
        ),
    )
)

print(f'Semantic search: "{query}"\n')
search_df(results, ['chunk_id', 'speaker_list', 'text_content'])

Semantic search: "How should we evaluate forecast model accuracy and performance?"

,chunk_id,speaker_list,text_content
rank,,,
1,zoom_meeting_business_readout_001,"Dr. Anya Sharma, Maria Rodriguez, Sarah Jenkin...",[Summary: Stakeholders question the model's gr...
2,zoom_meeting_model_planning_002,"Chloe (ML Engineer), David (Statistician), Ben...",[Summary: The team weighs the pros and cons of...
3,zoom_meeting_business_readout_000,"Tom Davis, Dr. Anya Sharma, Maria Rodriguez, D...","Tom Davis: Alright everyone, thanks for joinin..."
4,zoom_meeting_model_planning_003,"Chloe (ML Engineer), Sarah (Lead), David (Stat...",[Summary: The team finalized a plan to benchma...
5,zoom_meeting_model_planning_000,"Sarah (Lead), David (Statistician), Ben (Analy...","Sarah (Lead): Alright everyone, thanks for joi..."

## Text Search

In [13]:
query = 'Prophet'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=ZOOM,
        text_search=vectorsearch_v1beta.TextSearch(
            search_text=query,
            data_field_names=['text_content'],
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'speaker_list', 'text_content']
            ),
        ),
    )
)

print(f'Text search: "{query}"\n')
search_df(results, ['chunk_id', 'speaker_list', 'text_content'])

Text search: "Prophet"

,chunk_id,speaker_list,text_content
rank,,,
1,zoom_meeting_model_planning_001,"Ben (Analyst), Sarah (Lead), Chloe (ML Enginee...",[Summary: The team debates Prophet versus a gr...
2,zoom_meeting_model_planning_000,"Sarah (Lead), David (Statistician), Ben (Analy...","Sarah (Lead): Alright everyone, thanks for joi..."
3,zoom_meeting_model_planning_002,"Chloe (ML Engineer), David (Statistician), Ben...",[Summary: The team weighs the pros and cons of...
4,zoom_meeting_data_review_002,"Dr. Anya Sharma, Leo Chen",[Summary: Leo recaps data cleaning tasks while...
5,zoom_meeting_data_review_001,"Leo Chen, Dr. Anya Sharma",[Summary: They will handle a sales spike by cr...

## Hybrid Search with RRF Weight Comparison

In [14]:
query = 'seasonal patterns and Prophet model'
fields = ['chunk_id', 'text_content']

configs = {
    'Equal [1, 1]': [1.0, 1.0],
    'Semantic [3, 1]': [3.0, 1.0],
    'Text [1, 3]': [1.0, 3.0],
}

rankings = {}
for label, weights in configs.items():
    results = hybrid_search(ZOOM, query, weights, top_k=10, fields=fields)
    for rank, r in enumerate(results, 1):
        cid = r.data_object.data['chunk_id']
        if cid not in rankings:
            text = r.data_object.data['text_content']
            rankings[cid] = {'chunk_id': cid, 'text_preview': text[:100] + '...'}
        rankings[cid][label] = rank

comparison = pd.DataFrame(rankings.values()).sort_values('Equal [1, 1]')
print(f'RRF weight comparison: "{query}"')
print('Lower rank = higher relevance.\n')
comparison

RRF weight comparison: "seasonal patterns and Prophet model"
Lower rank = higher relevance.

,chunk_id,text_preview,"Equal [1, 1]","Semantic [3, 1]","Text [1, 3]"
0,zoom_meeting_model_planning_001,[Summary: The team debates Prophet versus a gr...,1,1,1
1,zoom_meeting_model_planning_000,"Sarah (Lead): Alright everyone, thanks for joi...",2,2,2
2,zoom_meeting_data_review_000,"Leo Chen: Hey Anya, thanks for joining. I want...",3,3,3
3,zoom_meeting_data_review_001,[Summary: They will handle a sales spike by cr...,4,4,4
4,zoom_meeting_model_planning_002,[Summary: The team weighs the pros and cons of...,5,5,5
5,zoom_meeting_business_readout_000,"Tom Davis: Alright everyone, thanks for joinin...",6,6,6
6,zoom_meeting_data_review_002,[Summary: Leo recaps data cleaning tasks while...,7,7,7
7,zoom_meeting_business_readout_001,[Summary: Stakeholders question the model's gr...,8,8,8
8,zoom_meeting_model_planning_003,[Summary: The team finalized a plan to benchma...,9,9,9
9,zoom_meeting_business_readout_002,[Summary: The team agrees on a consensus forec...,10,10,10

---
# PDF Collection

The PDF collection contains Document AI Layout Parser v1.5 chunks from batch-processed PDFs. Each chunk has `page_start` and `page_end` metadata for page-level filtering.

In [15]:
# Count DataObjects in the PDF collection
search_client.aggregate_data_objects(
    vectorsearch_v1beta.AggregateDataObjectsRequest(parent=PDF, aggregate='COUNT')
)

aggregate_results {
  fields {
    key: "count"
    value {
      number_value: 71
    }
  }
}

## Query: Filtering by Page Range

PDF chunks carry `page_start` and `page_end` fields from the Layout Parser. Filter to find content from specific page ranges — useful for targeting introductions (early pages) or appendices (later pages).

In [16]:
# Find chunks from the first few pages (introductory content)
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=PDF,
        filter={'page_start': {'$lte': 2}},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'source_uri', 'page_start', 'page_end', 'text_content']
        ),
    )
))
print(f'{len(results)} chunks from pages 0-2')
query_df(results, ['chunk_id', 'source_uri', 'page_start', 'page_end', 'text_content'])

18 chunks from pages 0-2

,chunk_id,source_uri,page_start,page_end,text_content
0,pdf_1fa007c733_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,7.0,# The Al.FORECAST function\n\nThis document de...
1,pdf_5fa7c6b197_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,6.0,# The CREATE MODEL statement for ARIMA PLUS XR...
2,pdf_765aeabdb0_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,3.0,# The ML.ARIMA_COEFFICIENTS function\n\nThis d...
3,pdf_5e3c207262_c2,gs://statmike-mlops-349915/applied-genai-solut...,2.0,4.0,# The AI.DETECT_ANOMALIES function\n\n## Argum...
4,pdf_5e3c207262_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,7.0,# The AI.DETECT_ANOMALIES function\n\nPreview ...
5,pdf_944a4f7390_c3,gs://statmike-mlops-349915/applied-genai-solut...,1.0,4.0,# Automatic feature preprocessing\n\n## Missin...
6,pdf_944a4f7390_c2,gs://statmike-mlops-349915/applied-genai-solut...,1.0,4.0,# Automatic feature preprocessing\n\n## Missin...
7,pdf_944a4f7390_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,6.0,# Automatic feature preprocessing\n\nBigQuery ...
8,pdf_1affd50072_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,6.0,# The ML.DETECT_ANOMALIES function\n\nThis doc...
9,pdf_2f59757db2_c2,gs://statmike-mlops-349915/applied-genai-solut...,2.0,4.0,# The ML.ARIMA EVALUATE function\n\n## Output\...
10,pdf_2f59757db2_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,2.0,# The ML.ARIMA EVALUATE function\n\nThis docum...
11,pdf_984db4d064_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,3.0,# The AI.EVALUATE function\n\nThis document de...
12,pdf_0712f4777d_c2,gs://statmike-mlops-349915/applied-genai-solut...,2.0,5.0,# The ML.EXPLAIN_FORECAST function\n\n## Outpu...
13,pdf_0712f4777d_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,7.0,# The ML.EXPLAIN_FORECAST function\n\nThis doc...
14,pdf_2179554f75_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,3.0,# The ML.HOLIDAY INFO function\n\nThis documen...
15,pdf_90bbc35dad_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,6.0,# The CREATE MODEL statement for ARIMA PLUS mo...
16,pdf_90bbc35dad_c2,gs://statmike-mlops-349915/applied-genai-solut...,1.0,3.0,# The CREATE MODEL statement for ARIMA PLUS mo...
17,pdf_f1d30bd3e8_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,3.0,# The ML.FORECAST function\n\nThis document de...

## Semantic Search

In [17]:
query = 'How do you create a time series forecasting model in SQL?'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=PDF,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'source_uri', 'page_start', 'text_content']
            ),
        ),
    )
)

print(f'Semantic search: "{query}"\n')
search_df(results, ['chunk_id', 'source_uri', 'page_start', 'text_content'])

Semantic search: "How do you create a time series forecasting model in SQL?"

,chunk_id,source_uri,page_start,text_content
rank,,,,
1,pdf_1fa007c733_c4,gs://statmike-mlops-349915/applied-genai-solut...,5.0,# The Al.FORECAST function\n\n## Examples\n\nT...
2,pdf_1fa007c733_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,# The Al.FORECAST function\n\nThis document de...
3,pdf_90bbc35dad_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,# The CREATE MODEL statement for ARIMA PLUS mo...
4,pdf_90bbc35dad_c3,gs://statmike-mlops-349915/applied-genai-solut...,3.0,# The CREATE MODEL statement for ARIMA PLUS mo...
5,pdf_90bbc35dad_c2,gs://statmike-mlops-349915/applied-genai-solut...,1.0,# The CREATE MODEL statement for ARIMA PLUS mo...

## Text Search

In [18]:
query = 'CREATE MODEL'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=PDF,
        text_search=vectorsearch_v1beta.TextSearch(
            search_text=query,
            data_field_names=['text_content'],
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'source_uri', 'page_start', 'text_content']
            ),
        ),
    )
)

print(f'Text search: "{query}"\n')
search_df(results, ['chunk_id', 'source_uri', 'page_start', 'text_content'])

Text search: "CREATE MODEL"

,chunk_id,source_uri,page_start,text_content
rank,,,,
1,pdf_5fa7c6b197_c4,gs://statmike-mlops-349915/applied-genai-solut...,5.0,# The CREATE MODEL statement for ARIMA PLUS XR...
2,pdf_90bbc35dad_c4,gs://statmike-mlops-349915/applied-genai-solut...,4.0,# The CREATE MODEL statement for ARIMA PLUS mo...
3,pdf_5fa7c6b197_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,# The CREATE MODEL statement for ARIMA PLUS XR...
4,pdf_0712f4777d_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,# The ML.EXPLAIN_FORECAST function\n\nThis doc...
5,pdf_f1d30bd3e8_c1,gs://statmike-mlops-349915/applied-genai-solut...,1.0,# The ML.FORECAST function\n\nThis document de...

## Hybrid Search with RRF Weight Comparison

In [19]:
query = 'ARIMA time series model training'
fields = ['chunk_id', 'text_content']

configs = {
    'Equal [1, 1]': [1.0, 1.0],
    'Semantic [3, 1]': [3.0, 1.0],
    'Text [1, 3]': [1.0, 3.0],
}

rankings = {}
for label, weights in configs.items():
    results = hybrid_search(PDF, query, weights, top_k=10, fields=fields)
    for rank, r in enumerate(results, 1):
        cid = r.data_object.data['chunk_id']
        if cid not in rankings:
            text = r.data_object.data['text_content']
            rankings[cid] = {'chunk_id': cid, 'text_preview': text[:100] + '...'}
        rankings[cid][label] = rank

comparison = pd.DataFrame(rankings.values()).sort_values('Equal [1, 1]')
print(f'RRF weight comparison: "{query}"')
print('Lower rank = higher relevance.\n')
comparison

RRF weight comparison: "ARIMA time series model training"
Lower rank = higher relevance.

,chunk_id,text_preview,"Equal [1, 1]","Semantic [3, 1]","Text [1, 3]"
0,pdf_90bbc35dad_c3,# The CREATE MODEL statement for ARIMA PLUS mo...,1,1,2
1,pdf_90bbc35dad_c5,# model_name\n\nThe name of the model you're c...,2,4,1
2,pdf_5fa7c6b197_c3,# The CREATE MODEL statement for ARIMA PLUS XR...,3,3,3
3,pdf_90bbc35dad_c18,# Limitations\n\nARIMA_PLUS models have the fo...,4,2,4
4,pdf_5fa7c6b197_c16,# Limitations\n\nARIMA_PLUS_XREG models have t...,5,5,5
5,pdf_90bbc35dad_c6,# AUTO_ARIMA_MAX_ORDER\n\n## Syntax\n\nAUTO_AR...,6,6,6
6,pdf_90bbc35dad_c2,# The CREATE MODEL statement for ARIMA PLUS mo...,7,7,11
7,pdf_90bbc35dad_c19,# What's next\n\n• Try the following tutorials...,8,8,12
8,pdf_90bbc35dad_c4,# The CREATE MODEL statement for ARIMA PLUS mo...,9,11,7
9,pdf_5fa7c6b197_c5,# model_name\n\nThe name of the model you're c...,10,9,13
10,pdf_2f59757db2_c1,# The ML.ARIMA EVALUATE function\n\nThis docum...,11,12,8
11,pdf_5fa7c6b197_c4,# The CREATE MODEL statement for ARIMA PLUS XR...,12,13,9
12,pdf_5fa7c6b197_c6,"# Arguments\n\nAn INT64 value between 1 and 5,...",13,10,14
13,pdf_0712f4777d_c2,# The ML.EXPLAIN_FORECAST function\n\n## Outpu...,14,14,10

---
# Combined Collection

The Combined collection merges all three source types (Reddit, Zoom, PDF) into a single searchable index with a `source_type` discriminator and the union of all metadata fields. This enables:

- **Cross-type search**: Find relevant content regardless of source format
- **Filtered search**: Restrict to a single source type using pre-filters on `SemanticSearch`
- **Crowding/diversity**: Retrieve top-k results per source type using parallel async queries

In [21]:
# Count DataObjects by source type
total = search_client.aggregate_data_objects(
    vectorsearch_v1beta.AggregateDataObjectsRequest(parent=COMBINED, aggregate='COUNT')
)
print(f'Total: {int(total.aggregate_results[0]["count"])} DataObjects')

# Count per source type
for stype in ['reddit', 'zoom', 'pdf']:
    count = search_client.aggregate_data_objects(
        vectorsearch_v1beta.AggregateDataObjectsRequest(
            parent=COMBINED,
            aggregate='COUNT',
            filter={'source_type': {'$eq': stype}},
        )
    )
    n = int(count.aggregate_results[0]['count'])
    print(f'  {stype}: {n}')

Total: 117 DataObjects
  reddit: 34
  zoom: 12
  pdf: 71

## Query: Filtering by Source Type

Use the `source_type` field to browse content from a specific source.

In [22]:
# Browse Zoom-only content in the combined collection
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=COMBINED,
        filter={'source_type': {'$eq': 'zoom'}},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'source_type', 'source_uri', 'text_content']
        ),
    )
))
print(f'{len(results)} zoom chunks')
query_df(results, ['chunk_id', 'source_type', 'source_uri', 'text_content'])

12 zoom chunks

,chunk_id,source_type,source_uri,text_content
0,zoom_meeting_data_review_003,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: They finalized action items for data...
1,zoom_meeting_data_review_002,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: Leo recaps data cleaning tasks while...
2,zoom_meeting_data_review_001,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: They will handle a sales spike by cr...
3,zoom_meeting_data_review_000,zoom,gs://statmike-mlops-349915/applied-genai-solut...,"Leo Chen: Hey Anya, thanks for joining. I want..."
4,zoom_meeting_model_planning_003,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: The team finalized a plan to benchma...
5,zoom_meeting_model_planning_002,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: The team weighs the pros and cons of...
6,zoom_meeting_model_planning_001,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: The team debates Prophet versus a gr...
7,zoom_meeting_model_planning_000,zoom,gs://statmike-mlops-349915/applied-genai-solut...,"Sarah (Lead): Alright everyone, thanks for joi..."
8,zoom_meeting_business_readout_003,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: The team agreed to provide cleaner d...
9,zoom_meeting_business_readout_002,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: The team agrees on a consensus forec...
10,zoom_meeting_business_readout_001,zoom,gs://statmike-mlops-349915/applied-genai-solut...,[Summary: Stakeholders question the model's gr...
11,zoom_meeting_business_readout_000,zoom,gs://statmike-mlops-349915/applied-genai-solut...,"Tom Davis: Alright everyone, thanks for joinin..."

## Cross-Type Semantic Search

An unfiltered semantic search on the combined collection returns results from all source types, ranked purely by embedding similarity.

In [23]:
query = 'What methods handle seasonal patterns in demand forecasting?'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=COMBINED,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=6,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'source_type', 'text_content']
            ),
        ),
    )
)

print(f'Cross-type semantic search: "{query}"\n')
search_df(results, ['chunk_id', 'source_type', 'text_content'])

Cross-type semantic search: "What methods handle seasonal patterns in demand forecasting?"

,chunk_id,source_type,text_content
rank,,,
1,red_thread_deep_000,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,red_thread_deep_011,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
3,red_thread_deep_004,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
4,red_thread_deep_003,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_medium_004,reddit,THREAD: Beyond ARIMA and Prophet: What are you...
6,red_thread_deep_012,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

## Filtered Semantic Search

The `filter` parameter on `SemanticSearch` applies a pre-filter before vector similarity ranking. This restricts results to a subset without affecting embedding comparison quality.

In [24]:
query = 'What methods handle seasonal patterns in demand forecasting?'

# Same query, filtered to PDF-only results
results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=COMBINED,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'source_type', 'source_uri', 'text_content']
            ),
            filter={'source_type': {'$eq': 'pdf'}},
        ),
    )
)

print(f'Filtered semantic search (pdf only): "{query}"\n')
search_df(results, ['chunk_id', 'source_type', 'source_uri', 'text_content'])

Filtered semantic search (pdf only): "What methods handle seasonal patterns in demand forecasting?"

,chunk_id,source_type,source_uri,text_content
rank,,,,
1,pdf_90bbc35dad_c19,pdf,gs://statmike-mlops-349915/applied-genai-solut...,# What's next\n\n• Try the following tutorials...
2,pdf_90bbc35dad_c16,pdf,gs://statmike-mlops-349915/applied-genai-solut...,# Custom holiday limitations\n\n• Custom holid...
3,pdf_90bbc35dad_c17,pdf,gs://statmike-mlops-349915/applied-genai-solut...,# Hierarchical reconciliation\n\nYou can break...
4,pdf_1fa007c733_c4,pdf,gs://statmike-mlops-349915/applied-genai-solut...,# The Al.FORECAST function\n\n## Examples\n\nT...
5,pdf_5fa7c6b197_c13,pdf,gs://statmike-mlops-349915/applied-genai-solut...,# Holiday data\n\n|-|-|-|-|-|\n| region | holi...

## Crowding: Diversity Search with Async Parallel Queries

Unfiltered semantic search often returns results dominated by one source type (whichever has the most relevant embeddings). **Crowding** ensures diversity by retrieving top-k results per group.

The `crowded_search` helper (defined above) uses the `DataObjectSearchServiceAsyncClient` to run one filtered semantic search per group value **concurrently** via `asyncio.gather`. Each search independently retrieves the best matches for its group, and results are combined for a balanced view across all source types.

This is the async counterpart pattern:
- **Sync**: `DataObjectSearchServiceClient` → sequential, one search at a time
- **Async**: `DataObjectSearchServiceAsyncClient` → concurrent, all searches in parallel

In [25]:
query = 'What methods handle seasonal patterns in demand forecasting?'
fields = ['chunk_id', 'source_type', 'source_uri', 'text_content']

# Top 2 results per source type, searched in parallel
results = await crowded_search(
    COMBINED, query,
    crowd_field='source_type',
    crowd_values=['reddit', 'zoom', 'pdf'],
    top_k_per_value=2,
    fields=fields,
)

for source_type, hits in results.items():
    print(f'{source_type}: {len(hits)} results')

print(f'\nCrowded search: "{query}"\n')
crowded_df(results, ['chunk_id', 'source_type', 'text_content'])

reddit: 2 results
zoom: 2 results
pdf: 2 results

Crowded search: "What methods handle seasonal patterns in demand forecasting?"

,group,group_rank,chunk_id,source_type,text_content
0,reddit,1,red_thread_deep_000,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
1,reddit,2,red_thread_deep_011,reddit,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,zoom,1,zoom_meeting_model_planning_000,zoom,"Sarah (Lead): Alright everyone, thanks for joi..."
3,zoom,2,zoom_meeting_model_planning_001,zoom,[Summary: The team debates Prophet versus a gr...
4,pdf,1,pdf_90bbc35dad_c19,pdf,# What's next\n\n• Try the following tutorials...
5,pdf,2,pdf_90bbc35dad_c16,pdf,# Custom holiday limitations\n\n• Custom holid...

### Crowding on Other Metadata Fields

The `crowded_search` function works with **any** metadata field, not just `source_type`. For example, crowd by `source_uri` to ensure diversity across individual documents, or by `subreddit` for Reddit-specific analysis.

In [26]:
query = 'How accurate is ARIMA for retail forecasting?'
fields = ['chunk_id', 'source_type', 'source_uri', 'text_content']

# Get unique source URIs from the combined collection
reddit_results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=COMBINED,
        filter={'source_type': {'$eq': 'reddit'}},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['source_uri']
        ),
    )
))
uris = list(set(r.data['source_uri'] for r in reddit_results))
print(f'Crowding across {len(uris)} Reddit source URIs\n')

# Top 1 result per Reddit thread
results = await crowded_search(
    COMBINED, query,
    crowd_field='source_uri',
    crowd_values=uris,
    top_k_per_value=1,
    fields=fields,
)

for uri, hits in results.items():
    short = uri.split('/')[-1]
    print(f'{short}: {len(hits)} result')

print(f'\nCrowded by source_uri: "{query}"\n')
crowded_df(results, ['chunk_id', 'source_type', 'source_uri', 'text_content'])

Crowding across 3 Reddit source URIs

thread_shallow.json: 1 result
thread_medium.json: 1 result
thread_deep.json: 1 result

Crowded by source_uri: "How accurate is ARIMA for retail forecasting?"

,group,group_rank,chunk_id,source_type,source_uri,text_content
0,gs://statmike-mlops-349915/applied-genai-solut...,1,red_thread_shallow_000,reddit,gs://statmike-mlops-349915/applied-genai-solut...,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
1,gs://statmike-mlops-349915/applied-genai-solut...,1,red_thread_medium_004,reddit,gs://statmike-mlops-349915/applied-genai-solut...,THREAD: Beyond ARIMA and Prophet: What are you...
2,gs://statmike-mlops-349915/applied-genai-solut...,1,red_thread_deep_000,reddit,gs://statmike-mlops-349915/applied-genai-solut...,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

---
# Key Takeaways

| Search Type | Strengths | Weaknesses | Best For |
|-------------|-----------|------------|----------|
| **Semantic** | Understands intent, finds synonyms | May miss exact keywords | Natural language questions |
| **Text** | Precise keyword matching | No semantic understanding | Specific terms, acronyms, names |
| **Hybrid (RRF)** | Best of both | Requires weight tuning | Production search systems |
| **Filtered** | Scoped to metadata values | Reduces recall pool | Source-type or field-specific queries |
| **Crowded** | Ensures diversity across groups | More API calls (mitigated by async) | Multi-source RAG pipelines |

**RRF weight tuning tips:**
- Start with equal weights `[1, 1]` as a baseline
- Increase semantic weight when users ask natural language questions
- Increase text weight when users search for specific terms or codes
- The comparison tables above show how the same query can surface different chunks depending on the weight balance — chunks containing exact keyword matches rise when text weight increases, while chunks with conceptually related content rise when semantic weight increases

**Crowding tips:**
- Use `crowded_search` with `source_type` to ensure each source type is represented in RAG context
- Crowd by `source_uri` for per-document diversity
- The async client runs all filtered searches concurrently, so latency scales with the slowest single search, not the sum
- Adjust `top_k_per_value` to control the balance between diversity and relevance depth