![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2FApplied+GenAI%2FSolutions%2Fmulti-type-parsing-and-vector-search-2&file=search_and_query.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2FApplied%2520GenAI%2FSolutions%2Fmulti-type-parsing-and-vector-search-2%2Fsearch_and_query.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/Applied%20GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/Applied%2520GenAI/Solutions/multi-type-parsing-and-vector-search-2/search_and_query.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
</table>

# Search & Query: Vector Search 2.0 Collections

This notebook demonstrates querying and searching the Reddit and Zoom collections created in steps 4–5. Covers:

- **Query**: Filter DataObjects by field values (analogous to SQL `WHERE`)
- **Semantic Search**: Natural language queries using auto-generated embeddings
- **Text Search**: Keyword-based full-text search
- **Hybrid Search**: Combine semantic + text with [Reciprocal Rank Fusion (RRF)](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf)
- **RRF Weight Tuning**: How adjusting weights shifts result ranking

In [1]:
import pandas as pd
from google.cloud import vectorsearch_v1beta
from config import PROJECT_ID, REGION, VS_COLLECTION_REDDIT, VS_COLLECTION_ZOOM

# Three specialized SDK clients
vs_client = vectorsearch_v1beta.VectorSearchServiceClient()
do_client = vectorsearch_v1beta.DataObjectServiceClient()
search_client = vectorsearch_v1beta.DataObjectSearchServiceClient()

# Collection parent paths
REDDIT = f'projects/{PROJECT_ID}/locations/{REGION}/collections/{VS_COLLECTION_REDDIT}'
ZOOM = f'projects/{PROJECT_ID}/locations/{REGION}/collections/{VS_COLLECTION_ZOOM}'

print(f'Reddit: {VS_COLLECTION_REDDIT}')
print(f'Zoom:   {VS_COLLECTION_ZOOM}')

Reddit: applied-genai-solutions-multi-type-parsing-reddit
Zoom:   applied-genai-solutions-multi-type-parsing-zoom

In [2]:
def search_df(results, fields, max_text=150):
    """Format search results as a ranked DataFrame."""
    rows = []
    for r in results:
        data = r.data_object.data
        row = {}
        for f in fields:
            val = data.get(f, '')
            if isinstance(val, str) and len(val) > max_text:
                val = val[:max_text] + '...'
            elif hasattr(val, '__iter__') and not isinstance(val, str):
                val = ', '.join(str(v) for v in val)
            row[f] = val
        rows.append(row)
    df = pd.DataFrame(rows)
    df.index = range(1, len(df) + 1)
    df.index.name = 'rank'
    return df


def query_df(results, fields, max_text=150):
    """Format query results as a DataFrame."""
    rows = []
    for r in results:
        row = {}
        for f in fields:
            val = r.data.get(f, '')
            if isinstance(val, str) and len(val) > max_text:
                val = val[:max_text] + '...'
            elif hasattr(val, '__iter__') and not isinstance(val, str):
                val = ', '.join(str(v) for v in val)
            row[f] = val
        rows.append(row)
    return pd.DataFrame(rows)


def hybrid_search(parent, query, weights, top_k=10, fields=None):
    """Run hybrid semantic + text search with RRF reranking."""
    if fields is None:
        fields = ['chunk_id', 'text_content']
    output = vectorsearch_v1beta.OutputFields(data_fields=fields)
    request = vectorsearch_v1beta.BatchSearchDataObjectsRequest(
        parent=parent,
        searches=[
            vectorsearch_v1beta.Search(
                semantic_search=vectorsearch_v1beta.SemanticSearch(
                    search_text=query,
                    search_field='text_content_embedding',
                    task_type='QUESTION_ANSWERING',
                    top_k=top_k,
                    output_fields=output,
                )
            ),
            vectorsearch_v1beta.Search(
                text_search=vectorsearch_v1beta.TextSearch(
                    search_text=query,
                    data_field_names=['text_content'],
                    top_k=top_k,
                    output_fields=output,
                )
            ),
        ],
        combine=vectorsearch_v1beta.BatchSearchDataObjectsRequest.CombineResultsOptions(
            ranker=vectorsearch_v1beta.Ranker(
                rrf=vectorsearch_v1beta.ReciprocalRankFusion(weights=weights)
            )
        ),
    )
    response = search_client.batch_search_data_objects(request)
    if response.results:
        return list(response.results[0].results)
    return []

---
# Reddit Collection

The Reddit collection contains flattened thread chunks with conversational context (`THREAD: title | PARENT: context | COMMENT: body`). Each chunk includes metadata: `subreddit`, `karma`, and `is_image_description`.

In [3]:
# Count DataObjects in the Reddit collection
search_client.aggregate_data_objects(
    vectorsearch_v1beta.AggregateDataObjectsRequest(parent=REDDIT, aggregate='COUNT')
)

aggregate_results {
  fields {
    key: "count"
    value {
      number_value: 34
    }
  }
}

## Query: Filtering by Field Values

Query lets you filter DataObjects by their data fields — similar to a SQL `WHERE` clause. Supports comparison operators (`$eq`, `$gt`, `$lt`, `$gte`, `$lte`), logical operators (`$and`, `$or`), and array operators (`$in`, `$nin`).

In [4]:
# Find high-karma Reddit chunks (quality signal)
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=REDDIT,
        filter={'karma': {'$gt': 50}},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'subreddit', 'karma', 'text_content']
        ),
    )
))
print(f'{len(results)} chunks with karma > 50')
query_df(results, ['chunk_id', 'subreddit', 'karma', 'text_content'])

7 chunks with karma > 50

,chunk_id,subreddit,karma,text_content
0,red_thread_shallow_003,r/datascience,52.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
1,red_thread_shallow_000,r/datascience,89.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,red_thread_medium_004,r/datascience,52.0,THREAD: Beyond ARIMA and Prophet: What are you...
3,red_thread_medium_000,r/datascience,98.0,THREAD: Beyond ARIMA and Prophet: What are you...
4,red_thread_deep_001,r/datascience,121.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_deep_000,r/datascience,82.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
6,red_thread_deep_007,r/datascience,53.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

In [5]:
# Combined filter: high karma AND image-enriched chunks
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=REDDIT,
        filter={'$and': [{'karma': {'$gte': 20}}, {'is_image_description': {'$eq': True}}]},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'karma', 'is_image_description', 'text_content']
        ),
    )
))
print(f'{len(results)} image-enriched chunks with karma >= 20')
query_df(results, ['chunk_id', 'karma', 'is_image_description', 'text_content'])

3 image-enriched chunks with karma >= 20

,chunk_id,karma,is_image_description,text_content
0,red_thread_medium_006,31.0,True,THREAD: Beyond ARIMA and Prophet: What are you...
1,red_thread_medium_004,52.0,True,THREAD: Beyond ARIMA and Prophet: What are you...
2,red_thread_deep_001,121.0,True,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

## Semantic Search

Semantic search converts your natural language query into an embedding and finds DataObjects with the most similar `text_content_embedding` vectors. The query uses `task_type='QUESTION_ANSWERING'` to pair with the documents indexed as `RETRIEVAL_DOCUMENT` — this asymmetric pairing helps the model understand that queries and documents have different intents.

In [6]:
query = 'What machine learning methods work best for demand forecasting?'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=REDDIT,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'subreddit', 'karma', 'text_content']
            ),
        ),
    )
)

print(f'Semantic search: "{query}"\n')
search_df(results, ['chunk_id', 'subreddit', 'karma', 'text_content'])

Semantic search: "What machine learning methods work best for demand forecasting?"

,chunk_id,subreddit,karma,text_content
rank,,,,
1,red_thread_deep_015,r/datascience,9.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,red_thread_shallow_003,r/datascience,52.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
3,red_thread_medium_000,r/datascience,98.0,THREAD: Beyond ARIMA and Prophet: What are you...
4,red_thread_deep_016,r/datascience,15.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
5,red_thread_medium_001,r/datascience,45.0,THREAD: Beyond ARIMA and Prophet: What are you...

## Text Search

Text search provides keyword-based full-text matching. Useful for finding specific method names, acronyms, or terms that may not have strong semantic representation in the embedding model.

In [7]:
query = 'ARIMA'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=REDDIT,
        text_search=vectorsearch_v1beta.TextSearch(
            search_text=query,
            data_field_names=['text_content'],
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'subreddit', 'karma', 'text_content']
            ),
        ),
    )
)

print(f'Text search: "{query}"\n')
search_df(results, ['chunk_id', 'subreddit', 'karma', 'text_content'])

Text search: "ARIMA"

,chunk_id,subreddit,karma,text_content
rank,,,,
1,red_thread_shallow_000,r/datascience,89.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
2,red_thread_shallow_006,r/datascience,33.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
3,red_thread_shallow_002,r/datascience,25.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
4,red_thread_shallow_001,r/datascience,-12.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...
5,red_thread_deep_014,r/datascience,31.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...

## Hybrid Search with Reciprocal Rank Fusion (RRF)

Hybrid search runs both semantic and text searches in parallel, then combines results using [RRF](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf). RRF merges ranked lists by assigning each result a score based on its rank position in each list, then sorting by combined score.

The `weights` parameter controls the relative importance of each search:
- `[1.0, 1.0]` — equal balance between semantic and text
- `[3.0, 1.0]` — favor semantic understanding (better for intent-based queries)
- `[1.0, 3.0]` — favor keyword matching (better for exact-term queries)

In [8]:
query = 'seasonal ARIMA forecasting methods'
fields = ['chunk_id', 'subreddit', 'karma', 'text_content']

results = hybrid_search(REDDIT, query, weights=[1.0, 1.0], top_k=5, fields=fields)

print(f'Hybrid search (equal weights [1, 1]): "{query}"\n')
search_df(results, fields)

Hybrid search (equal weights [1, 1]): "seasonal ARIMA forecasting methods"

,chunk_id,subreddit,karma,text_content
rank,,,,
1,red_thread_deep_000,r/datascience,82.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
2,red_thread_medium_004,r/datascience,52.0,THREAD: Beyond ARIMA and Prophet: What are you...
3,red_thread_deep_003,r/datascience,18.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
4,red_thread_medium_007,r/datascience,41.0,THREAD: Beyond ARIMA and Prophet: What are you...
5,red_thread_medium_000,r/datascience,98.0,THREAD: Beyond ARIMA and Prophet: What are you...
6,red_thread_deep_004,r/datascience,25.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
7,red_thread_deep_011,r/datascience,22.0,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...
8,red_thread_shallow_000,r/datascience,89.0,THREAD: ARIMA vs. Prophet for Retail Demand Fo...

### RRF Weight Comparison

The table below shows how the same query produces different rankings under three weight configurations. A lower rank number means higher relevance. Watch how chunks shift position as the balance changes between semantic understanding and keyword matching.

In [9]:
query = 'seasonal ARIMA forecasting methods'
fields = ['chunk_id', 'text_content']

configs = {
    'Equal [1, 1]': [1.0, 1.0],
    'Semantic [3, 1]': [3.0, 1.0],
    'Text [1, 3]': [1.0, 3.0],
}

rankings = {}
for label, weights in configs.items():
    results = hybrid_search(REDDIT, query, weights, top_k=10, fields=fields)
    for rank, r in enumerate(results, 1):
        cid = r.data_object.data['chunk_id']
        if cid not in rankings:
            text = r.data_object.data['text_content']
            rankings[cid] = {'chunk_id': cid, 'text_preview': text[:100] + '...'}
        rankings[cid][label] = rank

comparison = pd.DataFrame(rankings.values()).sort_values('Equal [1, 1]')
print(f'RRF weight comparison: "{query}"')
print('Lower rank = higher relevance. Watch how chunks shift position.\n')
comparison

RRF weight comparison: "seasonal ARIMA forecasting methods"
Lower rank = higher relevance. Watch how chunks shift position.

,chunk_id,text_preview,"Equal [1, 1]","Semantic [3, 1]","Text [1, 3]"
0,red_thread_medium_004,THREAD: Beyond ARIMA and Prophet: What are you...,1,1,1
1,red_thread_medium_000,THREAD: Beyond ARIMA and Prophet: What are you...,2,2,2
2,red_thread_deep_000,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,3,3,4
3,red_thread_deep_003,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,4,4,5
4,red_thread_medium_007,THREAD: Beyond ARIMA and Prophet: What are you...,5,11,3
5,red_thread_deep_004,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,6,5,6
6,red_thread_deep_011,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,7,6,7
7,red_thread_shallow_000,THREAD: ARIMA vs. Prophet for Retail Demand Fo...,8,7,8
8,red_thread_deep_013,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,9,8,9
9,red_thread_deep_012,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,10,9,10
10,red_thread_deep_014,THREAD: ARIMA vs. Prophet vs. LightGBM for Dem...,11,10,11

---
# Zoom Collection

The Zoom collection contains sliding-window transcript chunks with speaker labels and timestamp ranges. Each chunk covers ~15 cues with 5-cue overlap between neighbors. Non-first windows include a Gemini-generated rolling summary prefix.

In [10]:
# Count DataObjects in the Zoom collection
search_client.aggregate_data_objects(
    vectorsearch_v1beta.AggregateDataObjectsRequest(parent=ZOOM, aggregate='COUNT')
)

aggregate_results {
  fields {
    key: "count"
    value {
      number_value: 12
    }
  }
}

## Query: Browsing Transcript Chunks

Filter by timestamp to find chunks from later in meetings, or browse all chunks to see the speaker distribution.

In [11]:
# Find transcript chunks from later in meetings (past 5 minutes)
results = list(search_client.query_data_objects(
    vectorsearch_v1beta.QueryDataObjectsRequest(
        parent=ZOOM,
        filter={'timestamp_start': {'$gt': 300}},
        output_fields=vectorsearch_v1beta.OutputFields(
            data_fields=['chunk_id', 'speaker_list', 'timestamp_start', 'timestamp_end', 'text_content']
        ),
    )
))
print(f'{len(results)} chunks starting after 5:00')
query_df(results, ['chunk_id', 'speaker_list', 'timestamp_start', 'timestamp_end', 'text_content'])

1 chunks starting after 5:00

,chunk_id,speaker_list,timestamp_start,timestamp_end,text_content
0,zoom_meeting_business_readout_003,"Dr. Anya Sharma, Maria Rodriguez, Sarah Jenkin...",318.06,341.36,[Summary: The team agreed to provide cleaner d...

## Semantic Search

In [12]:
query = 'How should we evaluate forecast model accuracy and performance?'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=ZOOM,
        semantic_search=vectorsearch_v1beta.SemanticSearch(
            search_text=query,
            search_field='text_content_embedding',
            task_type='QUESTION_ANSWERING',
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'speaker_list', 'text_content']
            ),
        ),
    )
)

print(f'Semantic search: "{query}"\n')
search_df(results, ['chunk_id', 'speaker_list', 'text_content'])

Semantic search: "How should we evaluate forecast model accuracy and performance?"

,chunk_id,speaker_list,text_content
rank,,,
1,zoom_meeting_business_readout_001,"Dr. Anya Sharma, Maria Rodriguez, Sarah Jenkin...",[Summary: Stakeholders question the model's gr...
2,zoom_meeting_model_planning_002,"Chloe (ML Engineer), David (Statistician), Ben...",[Summary: The team weighs the pros and cons of...
3,zoom_meeting_business_readout_000,"Tom Davis, Dr. Anya Sharma, Maria Rodriguez, D...","Tom Davis: Alright everyone, thanks for joinin..."
4,zoom_meeting_model_planning_003,"Chloe (ML Engineer), Sarah (Lead), David (Stat...",[Summary: The team finalized a plan to benchma...
5,zoom_meeting_model_planning_000,"Sarah (Lead), David (Statistician), Ben (Analy...","Sarah (Lead): Alright everyone, thanks for joi..."

## Text Search

In [13]:
query = 'Prophet'

results = search_client.search_data_objects(
    vectorsearch_v1beta.SearchDataObjectsRequest(
        parent=ZOOM,
        text_search=vectorsearch_v1beta.TextSearch(
            search_text=query,
            data_field_names=['text_content'],
            top_k=5,
            output_fields=vectorsearch_v1beta.OutputFields(
                data_fields=['chunk_id', 'speaker_list', 'text_content']
            ),
        ),
    )
)

print(f'Text search: "{query}"\n')
search_df(results, ['chunk_id', 'speaker_list', 'text_content'])

Text search: "Prophet"

,chunk_id,speaker_list,text_content
rank,,,
1,zoom_meeting_model_planning_001,"Ben (Analyst), Sarah (Lead), Chloe (ML Enginee...",[Summary: The team debates Prophet versus a gr...
2,zoom_meeting_model_planning_000,"Sarah (Lead), David (Statistician), Ben (Analy...","Sarah (Lead): Alright everyone, thanks for joi..."
3,zoom_meeting_model_planning_002,"Chloe (ML Engineer), David (Statistician), Ben...",[Summary: The team weighs the pros and cons of...
4,zoom_meeting_data_review_002,"Dr. Anya Sharma, Leo Chen",[Summary: Leo recaps data cleaning tasks while...
5,zoom_meeting_data_review_001,"Leo Chen, Dr. Anya Sharma",[Summary: They will handle a sales spike by cr...

## Hybrid Search with RRF Weight Comparison

In [14]:
query = 'seasonal patterns and Prophet model'
fields = ['chunk_id', 'text_content']

configs = {
    'Equal [1, 1]': [1.0, 1.0],
    'Semantic [3, 1]': [3.0, 1.0],
    'Text [1, 3]': [1.0, 3.0],
}

rankings = {}
for label, weights in configs.items():
    results = hybrid_search(ZOOM, query, weights, top_k=10, fields=fields)
    for rank, r in enumerate(results, 1):
        cid = r.data_object.data['chunk_id']
        if cid not in rankings:
            text = r.data_object.data['text_content']
            rankings[cid] = {'chunk_id': cid, 'text_preview': text[:100] + '...'}
        rankings[cid][label] = rank

comparison = pd.DataFrame(rankings.values()).sort_values('Equal [1, 1]')
print(f'RRF weight comparison: "{query}"')
print('Lower rank = higher relevance.\n')
comparison

RRF weight comparison: "seasonal patterns and Prophet model"
Lower rank = higher relevance.

,chunk_id,text_preview,"Equal [1, 1]","Semantic [3, 1]","Text [1, 3]"
0,zoom_meeting_model_planning_001,[Summary: The team debates Prophet versus a gr...,1,1,1
1,zoom_meeting_model_planning_000,"Sarah (Lead): Alright everyone, thanks for joi...",2,2,2
2,zoom_meeting_data_review_000,"Leo Chen: Hey Anya, thanks for joining. I want...",3,3,3
3,zoom_meeting_data_review_001,[Summary: They will handle a sales spike by cr...,4,4,4
4,zoom_meeting_model_planning_002,[Summary: The team weighs the pros and cons of...,5,5,5
5,zoom_meeting_business_readout_000,"Tom Davis: Alright everyone, thanks for joinin...",6,6,6
6,zoom_meeting_data_review_002,[Summary: Leo recaps data cleaning tasks while...,7,7,7
7,zoom_meeting_business_readout_001,[Summary: Stakeholders question the model's gr...,8,8,8
8,zoom_meeting_model_planning_003,[Summary: The team finalized a plan to benchma...,9,9,9
9,zoom_meeting_business_readout_002,[Summary: The team agrees on a consensus forec...,10,10,10

---
# Key Takeaways

| Search Type | Strengths | Weaknesses | Best For |
|-------------|-----------|------------|----------|
| **Semantic** | Understands intent, finds synonyms | May miss exact keywords | Natural language questions |
| **Text** | Precise keyword matching | No semantic understanding | Specific terms, acronyms, names |
| **Hybrid (RRF)** | Best of both | Requires weight tuning | Production search systems |

**RRF weight tuning tips:**
- Start with equal weights `[1, 1]` as a baseline
- Increase semantic weight when users ask natural language questions
- Increase text weight when users search for specific terms or codes
- The comparison tables above show how the same query can surface different chunks depending on the weight balance — chunks containing exact keyword matches rise when text weight increases, while chunks with conceptually related content rise when semantic weight increases