![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Fworkflows%2Fsemantic_search&file=semantic_search.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Fworkflows%2Fsemantic_search%2Fsemantic_search.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/workflows/semantic_search/semantic_search.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Semantic Search System — BigQuery AI Functions

Build a semantic search system in BigQuery, comparing two approaches:

1. **Manual approach**: `AI.EMBED` to create embeddings + `VECTOR_SEARCH` to query them
2. **Simplified approach**: `AI.SEARCH` with autonomous embedding generation

**What this demonstrates:**
- Creating and storing embeddings with `AI.EMBED`
- Searching with `VECTOR_SEARCH` (single query, batch, filtered)
- Setting up autonomous embeddings for `AI.SEARCH`
- Comparing the two approaches: flexibility vs simplicity

**Functions used:** [`AI.EMBED`](../../functions/ai_embed/) | [`VECTOR_SEARCH`](../../functions/vector_search/) | [`AI.SEARCH`](../../functions/ai_search/)

**Prerequisites:** [Setup guide](../../setup/) | [Function reference](../../RESOURCES.md)

---
## Setup

Set your project and location, authenticate, and create shared resources.

> `AI.EMBED` and `VECTOR_SEARCH` use end-user credentials — no connection needed. `AI.SEARCH` requires a connection for autonomous embedding generation. See the [Setup Reference](../../setup/) for details.

In [13]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection (needed for AI.SEARCH)

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [14]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm')

In [15]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [16]:
from google.cloud import bigquery
import pandas as pd
import time

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready
The bigquery_magics extension is already loaded. To reload it, use:
  %reload_ext bigquery_magics

In [17]:
import subprocess as _sp, json as _json

# Create connection (idempotent) — needed for AI.SEARCH autonomous embeddings
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant Vertex AI User role
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
_sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
         f'--member=serviceAccount:{sa}', '--role=roles/aiplatform.user', '--quiet'],
        capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)

---
## Step 1 — Create a knowledge base

Create a sample knowledge base of technical documentation articles. We'll use this same data for both search approaches.

In [18]:
# Source data — technical documentation articles
articles_query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_search_articles` AS
SELECT * FROM UNNEST([
  STRUCT(1 AS id, 'BigQuery' AS product, 'Querying Data' AS title,
    'BigQuery supports standard SQL for querying data. Use SELECT statements to retrieve data from tables. BigQuery processes queries using a distributed architecture that can scan terabytes in seconds.' AS content),
  STRUCT(2, 'BigQuery', 'Loading Data',
    'Load data into BigQuery from Cloud Storage, local files, or streaming inserts. Supported formats include CSV, JSON, Avro, Parquet, and ORC. Use batch loading for large datasets and streaming for real-time data.'),
  STRUCT(3, 'BigQuery', 'Access Control',
    'BigQuery uses IAM for access control. Grant roles at the project, dataset, or table level. Key roles include BigQuery Data Viewer, Data Editor, and Admin. Use authorized views for row-level security.'),
  STRUCT(4, 'Cloud Storage', 'Creating Buckets',
    'Create Cloud Storage buckets to store objects. Choose a storage class based on access frequency: Standard for hot data, Nearline for monthly, Coldline for quarterly, and Archive for yearly access.'),
  STRUCT(5, 'Cloud Storage', 'Object Lifecycle',
    'Configure lifecycle rules to automatically manage objects. Rules can delete objects after a specified age, transition to cheaper storage classes, or abort incomplete multipart uploads.'),
  STRUCT(6, 'Cloud Functions', 'Writing Functions',
    'Cloud Functions lets you write single-purpose functions that respond to events. Supported runtimes include Python, Node.js, Go, Java, and .NET. Functions automatically scale based on incoming request volume.'),
  STRUCT(7, 'Cloud Functions', 'Triggers',
    'Functions can be triggered by HTTP requests, Pub/Sub messages, Cloud Storage events, Firestore changes, or scheduled by Cloud Scheduler. Each trigger type provides different event data to your function.'),
  STRUCT(8, 'Cloud Run', 'Deploying Services',
    'Deploy containerized applications to Cloud Run. Build your container image, push to Artifact Registry, and deploy. Cloud Run automatically scales from zero to handle traffic and scales back down when idle.'),
  STRUCT(9, 'Cloud Run', 'Custom Domains',
    'Map custom domains to Cloud Run services. Verify domain ownership, create a DNS mapping, and update your DNS records. Cloud Run automatically provisions and renews TLS certificates.'),
  STRUCT(10, 'Pub/Sub', 'Publishing Messages',
    'Publish messages to Pub/Sub topics for asynchronous communication. Messages can be up to 10MB. Use batch publishing for higher throughput. Messages are stored for up to 31 days until acknowledged.')
])
'''
client.query(articles_query).result()

articles = client.query(
    f'SELECT id, product, title FROM `{PROJECT_ID}.{DATASET_ID}.workflow_search_articles` ORDER BY id'
).to_dataframe()
print(f'{len(articles)} articles created')
articles

10 articles created

   id          product                title
0   1         BigQuery        Querying Data
1   2         BigQuery         Loading Data
2   3         BigQuery       Access Control
3   4    Cloud Storage     Creating Buckets
4   5    Cloud Storage     Object Lifecycle
5   6  Cloud Functions    Writing Functions
6   7  Cloud Functions             Triggers
7   8        Cloud Run   Deploying Services
8   9        Cloud Run       Custom Domains
9  10          Pub/Sub  Publishing Messages

---
## Approach 1: Manual — AI.EMBED + VECTOR_SEARCH

The manual approach gives you full control: you choose the embedding model, task type, distance metric, and can pre-filter the search space.

### Step 2a — Embed the knowledge base

Create embeddings for all articles using `AI.EMBED` with `RETRIEVAL_DOCUMENT` task type (the document side of asymmetric retrieval).

In [19]:
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_search_embedded` AS
SELECT
  id, product, title, content,
  (AI.EMBED(
    content => content,
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_DOCUMENT'
  )).result AS embedding
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_search_articles`
'''
client.query(query).result()

# Verify embeddings
verify = client.query(f'''
  SELECT id, title, ARRAY_LENGTH(embedding) AS dims
  FROM `{PROJECT_ID}.{DATASET_ID}.workflow_search_embedded`
  ORDER BY id
''').to_dataframe()
print(f'All {len(verify)} articles embedded ({verify.iloc[0]["dims"]} dimensions)')
verify

All 10 articles embedded (768 dimensions)

   id                title  dims
0   1        Querying Data   768
1   2         Loading Data   768
2   3       Access Control   768
3   4     Creating Buckets   768
4   5     Object Lifecycle   768
5   6    Writing Functions   768
6   7             Triggers   768
7   8   Deploying Services   768
8   9       Custom Domains   768
9  10  Publishing Messages   768

### Step 3a — Search with VECTOR_SEARCH

Search the embedded knowledge base. Note the asymmetric pattern: queries use `RETRIEVAL_QUERY` task type to match the `RETRIEVAL_DOCUMENT` embeddings.

In [20]:
# Single query search
query = f'''
SELECT base.product, base.title, base.content, distance
FROM VECTOR_SEARCH(
  TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_search_embedded`,
  'embedding',
  query_value => (AI.EMBED(
    content => 'How do I load CSV files into a data warehouse?',
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_QUERY'
  )).result,
  top_k => 3,
  distance_type => 'COSINE'
)
'''
client.query(query).to_dataframe()

,product,title,content,distance
0,BigQuery,Loading Data,"Load data into BigQuery from Cloud Storage, local files, or streaming inserts. Supported formats include CSV, JSON, Avro, Parquet, and ORC. Use batch loading for large datasets and streaming for real-time data.",0.347335
1,BigQuery,Querying Data,BigQuery supports standard SQL for querying data. Use SELECT statements to retrieve data from tables. BigQuery processes queries using a distributed architecture that can scan terabytes in seconds.,0.450654
2,Cloud Storage,Creating Buckets,"Create Cloud Storage buckets to store objects. Choose a storage class based on access frequency: Standard for hot data, Nearline for monthly, Coldline for quarterly, and Archive for yearly access.",0.452092

### Step 4a — Filtered search

One advantage of the manual approach: you can pre-filter the search space. Here we restrict search to only BigQuery articles.

In [21]:
query = f'''
SELECT base.product, base.title, base.content, distance
FROM VECTOR_SEARCH(
  (SELECT * FROM `{PROJECT_ID}.{DATASET_ID}.workflow_search_embedded` WHERE product = 'BigQuery'),
  'embedding',
  query_value => (AI.EMBED(
    content => 'security and permissions',
    endpoint => 'text-embedding-005',
    task_type => 'RETRIEVAL_QUERY'
  )).result,
  top_k => 3,
  distance_type => 'COSINE'
)
'''
client.query(query).to_dataframe()

,product,title,content,distance
0,BigQuery,Access Control,"BigQuery uses IAM for access control. Grant roles at the project, dataset, or table level. Key roles include BigQuery Data Viewer, Data Editor, and Admin. Use authorized views for row-level security.",0.331078
1,BigQuery,Querying Data,BigQuery supports standard SQL for querying data. Use SELECT statements to retrieve data from tables. BigQuery processes queries using a distributed architecture that can scan terabytes in seconds.,0.547338
2,BigQuery,Loading Data,"Load data into BigQuery from Cloud Storage, local files, or streaming inserts. Supported formats include CSV, JSON, Avro, Parquet, and ORC. Use batch loading for large datasets and streaming for real-time data.",0.566600

### Step 5a — Batch search

Search for multiple queries at once — efficient for processing many questions in a single pass.

In [22]:
query = f'''
SELECT
  query.question,
  base.product,
  base.title,
  distance
FROM VECTOR_SEARCH(
  TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_search_embedded`,
  'embedding',
  (SELECT
     question,
     (AI.EMBED(content => question, endpoint => 'text-embedding-005',
               task_type => 'RETRIEVAL_QUERY')).result AS embedding
   FROM UNNEST([
     'How do I set up event-driven processing?',
     'What are the storage tiers available?',
     'How do I deploy a container?'
   ]) AS question),
  top_k => 2,
  distance_type => 'COSINE'
)
ORDER BY question, distance
'''
client.query(query).to_dataframe()

,question,product,title,distance
0,How do I deploy a container?,Cloud Run,Deploying Services,0.333112
1,How do I deploy a container?,Cloud Run,Custom Domains,0.480912
2,How do I set up event-driven processing?,Cloud Functions,Triggers,0.420273
3,How do I set up event-driven processing?,Cloud Functions,Writing Functions,0.426756
4,What are the storage tiers available?,Cloud Storage,Creating Buckets,0.341791
5,What are the storage tiers available?,Cloud Storage,Object Lifecycle,0.424782

---
## Approach 2: Simplified — AI.SEARCH

`AI.SEARCH` handles embedding generation automatically. You create a table with a `GENERATED ALWAYS AS` column that uses `AI.EMBED`, and BigQuery generates embeddings in the background.

### Step 2b — Create table with autonomous embeddings

The key syntax: define an embedding column as `GENERATED ALWAYS AS (AI.EMBED(...)) STORED OPTIONS (asynchronous = TRUE)`. BigQuery populates embeddings automatically after data is inserted.

In [23]:
# Create table with autonomous embedding column
query = f'''
CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_search_auto` (
  id INT64,
  product STRING,
  title STRING,
  content STRING,
  content_embedding STRUCT<result ARRAY<FLOAT64>, status STRING>
    GENERATED ALWAYS AS (
      AI.EMBED(content,
        connection_id => '{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}',
        endpoint => 'text-embedding-005')
    ) STORED OPTIONS (asynchronous = TRUE)
)
'''
client.query(query).result()

# Insert the same articles
query = f'''
INSERT INTO `{PROJECT_ID}.{DATASET_ID}.workflow_search_auto` (id, product, title, content)
SELECT id, product, title, content
FROM `{PROJECT_ID}.{DATASET_ID}.workflow_search_articles`
'''
client.query(query).result()
print('Data inserted — embeddings generating in background...')

# Wait for embeddings to be ready
# Successful embeddings have status = '' (empty string) and a non-null embedding
for i in range(30):
    result = client.query(f'''
        SELECT
          COUNT(*) AS total,
          COUNTIF(content_embedding IS NOT NULL AND content_embedding.status = '') AS ready
        FROM `{PROJECT_ID}.{DATASET_ID}.workflow_search_auto`
    ''').to_dataframe()
    total = int(result.iloc[0]['total'])
    ready = int(result.iloc[0]['ready'])
    if ready == total:
        print(f'All {total} embeddings ready!')
        break
    print(f'  Waiting... {ready}/{total} embeddings ready')
    time.sleep(10)
else:
    print(f'Warning: only {ready}/{total} embeddings ready after 5 minutes')

Data inserted — embeddings generating in background...
  Waiting... 0/10 embeddings ready
  Waiting... 0/10 embeddings ready
  Waiting... 0/10 embeddings ready
  Waiting... 0/10 embeddings ready
  Waiting... 0/10 embeddings ready
All 10 embeddings ready!

### Step 3b — Search with AI.SEARCH

`AI.SEARCH` is much simpler — just pass the table, column, and search text. No manual embedding of queries, no distance type selection.

In [24]:
query = f'''
SELECT base.product, base.title, base.content, distance
FROM AI.SEARCH(
  TABLE `{PROJECT_ID}.{DATASET_ID}.workflow_search_auto`,
  'content',
  'How do I load CSV files into a data warehouse?',
  top_k => 3
)
'''
client.query(query).to_dataframe()

,product,title,content,distance
0,BigQuery,Loading Data,"Load data into BigQuery from Cloud Storage, local files, or streaming inserts. Supported formats include CSV, JSON, Avro, Parquet, and ORC. Use batch loading for large datasets and streaming for real-time data.",0.782421
1,BigQuery,Querying Data,BigQuery supports standard SQL for querying data. Use SELECT statements to retrieve data from tables. BigQuery processes queries using a distributed architecture that can scan terabytes in seconds.,0.975333
2,Cloud Storage,Creating Buckets,"Create Cloud Storage buckets to store objects. Choose a storage class based on access frequency: Standard for hot data, Nearline for monthly, Coldline for quarterly, and Archive for yearly access.",1.018026

---
## Comparison: Manual vs Simplified

| Feature | Manual (EMBED + VECTOR_SEARCH) | Simplified (AI.SEARCH) |
|---------|-------------------------------|------------------------|
| **Setup** | Create embeddings yourself | Autonomous — BigQuery handles it |
| **Query embedding** | You call AI.EMBED on queries | Automatic |
| **Task types** | Full control (RETRIEVAL_DOCUMENT / RETRIEVAL_QUERY) | Managed by BigQuery |
| **Distance metrics** | Choose COSINE, EUCLIDEAN, DOT_PRODUCT | Managed |
| **Filtering** | Pre-filter base table with subquery | Not supported |
| **Batch queries** | Multiple queries in one call | One query at a time |
| **Vector indexes** | Supports IVF and TreeAH indexes | Managed |
| **Best for** | Production systems needing control | Quick prototyping, simple search |

---
## Cleanup

Drop tables created by this workflow. Shared resources (dataset, connection) are left for other notebooks.

In [ ]:
for table in ['workflow_search_articles', 'workflow_search_embedded', 'workflow_search_auto']:
    client.delete_table(f'{PROJECT_ID}.{DATASET_ID}.{table}', not_found_ok=True)
    print(f'Table {table} deleted')

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [ ]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')