![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fbq-ai-functions%2Ffunctions%2Fai_if&file=ai_if.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fbq-ai-functions%2Ffunctions%2Fai_if%2Fai_if.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/bq-ai-functions/functions/ai_if/ai_if.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# AI.IF — BigQuery AI Functions

`AI.IF` is a managed scalar function that evaluates a natural language condition and returns a BOOL. BigQuery automatically optimizes prompts and minimizes Gemini calls.

**When to use it:**
- You want boolean filtering in WHERE clauses with natural language conditions
- You need simple true/false classification without managing prompts
- You want BigQuery to auto-optimize your AI calls (query plan optimization)

**Alternatives:**
- [`AI.GENERATE_BOOL`](../ai_generate_bool/) — More control over model and parameters, returns STRUCT
- [`AI.GENERATE`](../ai_generate/) — Full control with output_schema for custom structured output
- [`AI.CLASSIFY`](../ai_classify/) — Multi-category classification instead of boolean

**Multimodal:** Supports document, image, and video input via [ObjectRef](../../RESOURCES.md#objectref-and-objectrefruntime-schema-reference). Pass a STRUCT condition with ObjectRefRuntime fields to evaluate conditions on unstructured data.

**Featured in:** [Content Moderation](../../workflows/content_moderation/)

**References:** [Full syntax reference](../../RESOURCES.md) | [Official documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-if) | [Setup guide](../../setup/)

---
## Setup

Set your project and location, authenticate, and create a temporary dataset for this notebook.

> This function doesn't require a connection or model for SQL usage — it uses end-user credentials automatically. BigFrames requires a connection, so we reference the shared one here. See the [Setup Reference](../../setup/) for details.

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # <-- Replace with your project ID
LOCATION = 'US'  # BigQuery dataset location
DATASET_ID = 'bq_ai_functions'  # Shared dataset across all notebooks
CONNECTION_ID = 'bq_ai_functions'  # Shared connection (used by BigFrames)
BUCKET = PROJECT_ID  # GCS bucket (same name as project)

### Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [Setup Reference](../../setup/) for details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [2]:
import subprocess, sys, shutil

def install(*packages):
    """Install packages using uv (fast) with pip fallback."""
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install('google-cloud-bigquery', 'db-dtypes', 'bigquery-magics', 'tqdm', 'bigframes', 'google-cloud-storage')

In [3]:
# Authenticate (Colab only — other environments use Application Default Credentials)
try:
    from google.colab import auth
    auth.authenticate_user()
except ImportError:
    pass  # Not in Colab — ADC is used automatically

In [4]:
from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project=PROJECT_ID)
pd.set_option('display.max_colwidth', None)

# Create the shared dataset (idempotent)
dataset_ref = bigquery.DatasetReference(PROJECT_ID, DATASET_ID)
dataset = bigquery.Dataset(dataset_ref)
dataset.location = LOCATION
client.create_dataset(dataset, exists_ok=True)
print(f'Dataset {PROJECT_ID}.{DATASET_ID} ready')

# Register %%bigquery cell magic (auto-loaded in Colab, needed elsewhere)
%load_ext bigquery_magics

Dataset statmike-mlops-349915.bq_ai_functions ready

---
## Examples — SQL

Progressive examples from simplest to most advanced. Each cell adds one new concept.

### 1. Simplest call — boolean evaluation

`AI.IF` takes a prompt and returns TRUE or FALSE directly (not a struct).

In [5]:
query = """
SELECT
  city,
  AI.IF(CONCAT(city, ' is in Asia')) AS is_in_asia
FROM UNNEST(['Tokyo', 'Paris', 'Nairobi', 'Bangkok', 'Sydney']) AS city
"""
client.query(query).to_dataframe()

      city  is_in_asia
0   Sydney       False
1    Tokyo        True
2  Bangkok        True
3    Paris       False
4  Nairobi       False

### 2. Filtering with WHERE

Use `AI.IF` in WHERE clauses for semantic filtering. BigQuery evaluates non-AI filters first to reduce Gemini calls.

In [6]:
query = """
SELECT review
FROM UNNEST([
  'Amazing product, fast delivery!',
  'Terrible quality. Broke after one day.',
  'Average, nothing special.',
  'Great value for the price!',
  'Worst purchase ever.'
]) AS review
WHERE AI.IF(CONCAT(review, ' is a positive review'))
"""
client.query(query).to_dataframe()

                            review
0  Amazing product, fast delivery!
1       Great value for the price!

### 3. Combining with non-AI filters

**Best practice:** Place non-AI filters alongside `AI.IF` — BigQuery evaluates non-AI conditions first, reducing the number of Gemini calls.

In [7]:
query = """
WITH articles AS (
  SELECT *
  FROM UNNEST([
    STRUCT('tech' AS category, 'New AI chip sets speed record' AS title),
    STRUCT('tech', 'Best smartphones of the year'),
    STRUCT('sports', 'Olympic records broken in swimming'),
    STRUCT('tech', 'Cloud computing market grows 30%'),
    STRUCT('sports', 'Local team wins championship')
  ])
)
SELECT category, title
FROM articles
WHERE category = 'tech'  -- evaluated first (no AI call)
  AND AI.IF(CONCAT(title, ' is about artificial intelligence'))  -- only called for tech articles
"""
client.query(query).to_dataframe()

  category                          title
0     tech  New AI chip sets speed record

### 4. Content moderation

Use `AI.IF` to flag content that may need review.

In [8]:
query = """
SELECT
  comment,
  AI.IF(CONCAT(comment, ' contains inappropriate language or personal attacks')) AS needs_review
FROM UNNEST([
  'Great article, very informative!',
  'This is completely wrong and the author is incompetent.',
  'I disagree with the conclusion but appreciate the research.',
  'What a waste of time reading this garbage.'
]) AS comment
"""
client.query(query).to_dataframe()

                                                       comment  needs_review
0  I disagree with the conclusion but appreciate the research.         False
1      This is completely wrong and the author is incompetent.          True
2                             Great article, very informative!         False
3                   What a waste of time reading this garbage.          True

### 5. Specifying an endpoint

Override the auto-selected model with a specific Gemini model.

In [9]:
query = """
SELECT
  statement,
  AI.IF(CONCAT(statement, ' is a factually accurate statement'), endpoint => 'gemini-2.5-flash') AS is_accurate
FROM UNNEST([
  'The Earth orbits the Sun.',
  'Water boils at 50 degrees Celsius.',
  'Python is a programming language.'
]) AS statement
"""
client.query(query).to_dataframe()

                            statement  is_accurate
0           The Earth orbits the Sun.         True
1  Water boils at 50 degrees Celsius.        False
2   Python is a programming language.         True

---
## Examples — Multimodal with ObjectRef

`AI.IF` can analyze documents, images, and video stored in Cloud Storage. Use the **ObjectRef pipeline** to create a STRUCT prompt with signed references:

```
OBJ.MAKE_REF(uri, connection)        → ObjectRef
  → OBJ.FETCH_METADATA(objectref)    → adds content type and size
    → OBJ.GET_ACCESS_URL(ref, 'r')   → ObjectRefRuntime (signed URL)
```

The STRUCT replaces the STRING prompt. See the [ObjectRef reference](../../RESOURCES.md#objectref-and-objectrefruntime-schema-reference) for details.

In [10]:
import subprocess as _sp, json as _json
from google.cloud import storage as _storage
from pathlib import Path

# Create connection (idempotent)
_sp.run(['bq', 'mk', '--connection', '--location', LOCATION,
         '--connection_type', 'CLOUD_RESOURCE',
         '--project_id', PROJECT_ID, CONNECTION_ID],
        capture_output=True, text=True)

# Get service account and grant required roles
r = _sp.run(['bq', 'show', '--connection', '--format=json',
             '--project_id', PROJECT_ID, '--location', LOCATION, CONNECTION_ID],
            capture_output=True, text=True, check=True)
sa = _json.loads(r.stdout)['cloudResource']['serviceAccountId']
for role in ['roles/aiplatform.user', 'roles/storage.objectViewer']:
    _sp.run(['gcloud', 'projects', 'add-iam-policy-binding', PROJECT_ID,
             f'--member=serviceAccount:{sa}', f'--role={role}', '--quiet'],
            capture_output=True, text=True)
print(f'Connection {CONNECTION_ID} ready (SA: {sa})')

# Upload invoice for the multimodal example
_gcs = _storage.Client(project=PROJECT_ID)
_bucket = _gcs.bucket(BUCKET)
_prefix = 'bq_ai_functions/ai_if'

_data = Path('../../data/documents')
if not _data.exists():
    _data = Path('data/documents')

blob = _bucket.blob(f'{_prefix}/invoice_001.pdf')
if not blob.exists():
    blob.upload_from_filename(str(_data / 'invoices' / 'invoice_001.pdf'))
    print(f'Uploaded invoice_001.pdf → gs://{BUCKET}/{_prefix}/invoice_001.pdf')
else:
    print(f'Already exists: gs://{BUCKET}/{_prefix}/invoice_001.pdf')

Connection bq_ai_functions ready (SA: bqcx-1026793852137-hx0g@gcp-sa-bigquery-condel.iam.gserviceaccount.com)
Uploaded invoice_001.pdf → gs://statmike-mlops-349915/bq_ai_functions/ai_if/invoice_001.pdf

### 6. Evaluate a condition on a document

Pass a document via ObjectRef in a STRUCT prompt to evaluate a boolean condition.

In [11]:
query = f"""
SELECT
  AI.IF(
    STRUCT(
      'This document is a financial invoice' AS prompt,
      [OBJ.GET_ACCESS_URL(
        OBJ.FETCH_METADATA(
          OBJ.MAKE_REF(
            'gs://{BUCKET}/bq_ai_functions/ai_if/invoice_001.pdf',
            '{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}'
          )
        ), 'r'
      )] AS object_ref_runtime
    )
  ) AS is_invoice
"""
client.query(query).to_dataframe()

   is_invoice
0        True

---
## Examples — `%%bigquery` Magics

The same examples using IPython magic commands. Magics let you write SQL directly in notebook cells without Python string wrapping.

Key patterns:
- `%%bigquery` — run SQL, display results inline
- `%%bigquery df` — run SQL, capture results into a pandas DataFrame

### Filtering with `%%bigquery`

In [12]:
%%bigquery --project {PROJECT_ID}

SELECT
  city,
  AI.IF(CONCAT(city, ' is in Europe')) AS is_in_europe
FROM UNNEST(['London', 'Tokyo', 'Berlin', 'Sydney', 'Rome']) AS city

Query is running:   0%|          |

Downloading:   0%|          |

     city  is_in_europe
0   Tokyo         False
1  Berlin          True
2    Rome          True
3  London          True
4  Sydney         False

### Using in WHERE clause

In [13]:
%%bigquery df_positive --project {PROJECT_ID}

SELECT review
FROM UNNEST([
  'Love it!', 'Terrible.', 'Pretty good.', 'Awful experience.'
]) AS review
WHERE AI.IF(CONCAT(review, ' is a positive review'))

Query is running:   0%|          |

Downloading:   0%|          |

In [14]:
df_positive

         review
0      Love it!
1  Pretty good.

---
## Examples — BigFrames

BigFrames wraps `AI.IF` via `bbq.ai.if_()`. It returns a Series of BOOL directly (not a struct, unlike `generate_bool`).

**Key patterns:**
- Returns BOOL directly — use for boolean indexing
- Tuple prompt pattern: `bbq.ai.if_((df["col"], " condition"))`
- No endpoint parameter — BigQuery auto-selects the model

In [15]:
import bigframes.pandas as bpd
import bigframes.bigquery as bbq

bpd.close_session()  # Reset session to apply connection settings
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION
bpd.options.bigquery.bq_connection = f'{PROJECT_ID}.{LOCATION}.{CONNECTION_ID}'

### Boolean evaluation

In [16]:
df = bpd.DataFrame({'city': ['Tokyo', 'Paris', 'Nairobi', 'Bangkok', 'Sydney']})

df['is_in_asia'] = bbq.ai.if_((df['city'], ' is in Asia'))
df.to_pandas()

/usr/local/google/home/statmike/Git/google_projects/projects/bq-ai-functions/.venv/lib/python3.13/site-packages/bigframes/session/__init__.py:384: FutureWarning: You are using the BigFrames session default connection: statmike-
mlops-349915.US.bq_ai_functions,             which can be different
from the BigQuery project default connection.             This default
connection may change in the future.
  warnings.warn(msg, category=FutureWarning)

      city  is_in_asia
0    Tokyo        True
1    Paris       False
2  Nairobi       False
3  Bangkok        True
4   Sydney       False

### Boolean indexing (filtering)

In [17]:
reviews = bpd.DataFrame({'review': [
    'Amazing product!', 'Terrible quality.', 'Pretty good.', 'Worst ever.'
]})

# Filter to only positive reviews
positive = reviews[bbq.ai.if_((reviews['review'], ' is a positive review'))]
positive.to_pandas()

/usr/local/google/home/statmike/Git/google_projects/projects/bq-ai-functions/.venv/lib/python3.13/site-packages/bigframes/session/__init__.py:384: FutureWarning: You are using the BigFrames session default connection: statmike-
mlops-349915.US.bq_ai_functions,             which can be different
from the BigQuery project default connection.             This default
connection may change in the future.
  warnings.warn(msg, category=FutureWarning)

             review
0  Amazing product!
2      Pretty good.

---
## Cleanup

Remove GCS files uploaded for the multimodal examples. Shared resources (dataset, models, connection) are left for other notebooks.

In [18]:
# Delete GCS files uploaded for multimodal examples
from google.cloud import storage

gcs_client = storage.Client(project=PROJECT_ID)
bucket = gcs_client.bucket(BUCKET)
prefix = 'bq_ai_functions/ai_if/'

blobs = list(bucket.list_blobs(prefix=prefix))
for blob in blobs:
    blob.delete()
    print(f'Deleted gs://{BUCKET}/{blob.name}')
if not blobs:
    print('No GCS files to clean up')

Deleted gs://statmike-mlops-349915/bq_ai_functions/ai_if/invoice_001.pdf

### Remove all shared resources

When finished with **all** notebooks, uncomment and run the cell below to delete the shared dataset and all tables, models, and other resources within it.

In [ ]:
# client.delete_dataset(
#     f'{PROJECT_ID}.{DATASET_ID}',
#     delete_contents=True,
#     not_found_ok=True
# )
# print(f'Dataset {PROJECT_ID}.{DATASET_ID} deleted')