![tracker](https://us-central1-vertex-ai-mlops-369716.cloudfunctions.net/pixel-tracking?path=statmike%2Fvertex-ai-mlops%2Fdata%2Bai%2Fdataproc%2Fexamples&file=dataproc-batch-inference.ipynb)
<!--- header table --->
<table align="left">
<tr>
  <td style="text-align: center">
    <a href="https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/dataproc/examples/dataproc-batch-inference.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo">
      <br>View on<br>GitHub
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/statmike/vertex-ai-mlops/blob/main/data%2Bai/dataproc/examples/dataproc-batch-inference.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo">
      <br>Run in<br>Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fstatmike%2Fvertex-ai-mlops%2Fmain%2Fdata%252Bai%2Fdataproc%2Fexamples%2Fdataproc-batch-inference.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo">
      <br>Run in<br>Colab Enterprise
    </a>
  </td>      
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%2Bai/dataproc/examples/dataproc-batch-inference.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery logo">
      <br>Open in<br>BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/dataproc/examples/dataproc-batch-inference.ipynb">
      <img width="32px" src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo">
      <br>Open in<br>Vertex AI Workbench
    </a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Share This On: </b> 
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/dataproc/examples/dataproc-batch-inference.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a> 
    <a href="https://reddit.com/submit?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/dataproc/examples/dataproc-batch-inference.ipynb"><img src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit Logo" width="20px"></a> 
    <a href="https://bsky.app/intent/compose?text=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/dataproc/examples/dataproc-batch-inference.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://twitter.com/intent/tweet?url=https://github.com/statmike/vertex-ai-mlops/blob/main/data%252Bai/dataproc/examples/dataproc-batch-inference.ipynb"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a> 
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <b>Connect With Author On: </b> 
    <a href="https://www.linkedin.com/in/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="Linkedin Logo" width="20px"></a>
    <a href="https://www.github.com/statmike"><img src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub Logo" width="20px"></a> 
    <a href="https://www.youtube.com/@statmike-channel"><img src="https://upload.wikimedia.org/wikipedia/commons/f/fd/YouTube_full-color_icon_%282024%29.svg" alt="YouTube Logo" width="20px"></a>
    <a href="https://bsky.app/profile/statmike.bsky.social"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="BlueSky Logo" width="20px"></a> 
    <a href="https://x.com/statmike"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X (Twitter) Logo" width="20px"></a>
  </td>
</tr>
<tr>
  <td colspan="5" style="text-align: right">
    <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/dataproc/examples/dataproc-batch-inference.ipynb"><img src="https://www.svgrepo.com/download/5445/download-button.svg" alt="Download icon" width="20px"></a> <a href="https://raw.githubusercontent.com/statmike/vertex-ai-mlops/main/data%2Bai/dataproc/examples/dataproc-batch-inference.ipynb">Download Notebook</a> <i>(right-click and "Save As")</i>
  </td>
</tr>
</table>

# Spark Batch Inference on Dataproc (Managed Service for Apache Spark) — Serverless

Batch ML inference using [PySpark](https://spark.apache.org/docs/latest/api/python/) Pandas UDFs on [Dataproc](https://cloud.google.com/dataproc/docs) (Managed Service for Apache Spark) Serverless. This notebook explores two inference patterns — **Pandas UDF** and **mapPartitions** — then compares both side by side.

**How is this different from [MLOps/Serving/Batch/Batch Inference With Dataproc](../../../MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb)?**

That notebook covers Dataproc as one of four batch inference platforms and orchestrates jobs with Vertex AI Pipelines. *This* notebook focuses on the Spark-specific patterns themselves — Pandas UDF vs mapPartitions, module-level caching, multi-model comparison, and performance tuning.

**Story arc:**
1. Download models to GCS
2. Write and run a Pandas UDF inference script
3. Write and run a mapPartitions alternative
4. Compare patterns
5. Multi-model inference
6. Performance tuning

**Models:**

| Version | Model | Params | Labels |
|---------|-------|--------|--------|
| v1 | [`distilbert-base-uncased-finetuned-sst-2-english`](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english) | 67M | POSITIVE / NEGATIVE |
| v2 | [`textattack/bert-base-uncased-SST-2`](https://huggingface.co/textattack/bert-base-uncased-SST-2) | 110M | LABEL_0 / LABEL_1 |

---
## Colab Setup

To run this notebook in Colab run the cells in this section. Otherwise, skip this section.

This cell will authenticate to GCP (follow prompts in the popup).

In [1]:
PROJECT_ID = 'statmike-mlops-349915'  # replace with your project ID

In [2]:
try:
    import google.colab
    from google.colab import auth
    auth.authenticate_user()
    !gcloud config set project {PROJECT_ID}
except Exception:
    pass

---
## Environment

> **Already set up the project environment?** The cell below is a no-op — packages are already in your kernel. See the [README](../readme.md) for uv setup details.
>
> **Running standalone** (Colab, Colab Enterprise, Vertex AI Workbench)? The cell below installs required packages into your current kernel.

In [3]:
import subprocess, sys, shutil

def install(*packages):
    uv = shutil.which('uv')
    if uv:
        subprocess.check_call([uv, 'pip', 'install', '-q', '--python', sys.executable, *packages])
    else:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *packages])

install(
    'google-cloud-dataproc', 'google-cloud-bigquery', 'google-cloud-storage',
    'transformers', 'torch', 'sentencepiece',
    'pandas', 'db-dtypes',
)

### API Enablement

In [4]:
!gcloud services enable dataproc.googleapis.com
!gcloud services enable bigquery.googleapis.com

---
## Setup

inputs:

In [5]:
project = !gcloud config get-value project
PROJECT_ID = project[-1]
PROJECT_ID

'statmike-mlops-349915'

In [6]:
REGION = 'us-central1'
SERIES = 'data-ai'
EXPERIMENT = 'dataproc-batch-inference'

GCS_BUCKET = PROJECT_ID
BQ_DATASET = f'{SERIES}_{EXPERIMENT}'.replace('-', '_')

packages:

In [7]:
import json, os, time, tempfile
from datetime import datetime

from google.cloud import storage
from google.cloud import bigquery
from google.cloud import dataproc_v1
import pandas as pd

clients:

In [8]:
gcs = storage.Client(project=PROJECT_ID)
bucket = gcs.bucket(GCS_BUCKET)

bq_client = bigquery.Client(project=PROJECT_ID)

# Dataproc Serverless requires a regional endpoint
dataproc_client = dataproc_v1.BatchControllerClient(
    client_options={'api_endpoint': f'{REGION}-dataproc.googleapis.com:443'}
)

parameters:

In [9]:
DIR = f'files/{EXPERIMENT}'
os.makedirs(DIR, exist_ok=True)

### Network Configuration

Dataproc Serverless requires [Private Google Access](https://cloud.google.com/vpc/docs/configure-private-google-access) on the subnet to reach Google APIs (BigQuery, GCS). The cell below checks and enables it on the default subnet.

In [10]:
status = !gcloud compute networks subnets describe default --region={REGION} --format="get(privateIpGoogleAccess)"
if status[0] == 'False':
    !gcloud compute networks subnets update default --region={REGION} --enable-private-ip-google-access
    status = !gcloud compute networks subnets describe default --region={REGION} --format="get(privateIpGoogleAccess)"
print(f'Private Google Access enabled: {status[0]}')

Private Google Access enabled: True

In [11]:
# Test sentences used throughout the notebook
SENTENCES = [
    "This movie is absolutely wonderful and I loved every minute of it!",
    "The food was terrible and the service was even worse.",
    "An average experience, nothing special but not bad either.",
    "I cannot believe how amazing this product is, truly life-changing.",
    "Disappointing quality for the price. Would not recommend.",
    "The weather today is mild and partly cloudy.",
    "I had the worst customer service experience of my life yesterday.",
    "What a fantastic performance by the entire cast!",
    "The instructions were confusing and the product broke on day one.",
    "Pretty good overall, with some room for improvement.",
]

---
## Download Models to GCS

Download two HuggingFace sentiment models and upload them to GCS. Dataproc executors will download these model files from GCS at job startup.

- **v1 (DistilBERT):** Smaller, faster — primary model
- **v2 (BERT):** Larger — second model for multi-model comparison

In [12]:
MODELS = {
    'v1': {
        'hub_name': 'distilbert-base-uncased-finetuned-sst-2-english',
        'display_name': 'distilbert-sst2',
    },
    'v2': {
        'hub_name': 'textattack/bert-base-uncased-SST-2',
        'display_name': 'bert-sst2',
    },
}

In [13]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

for version, info in MODELS.items():
    gcs_prefix = f'{SERIES}/{EXPERIMENT}/models/{version}'

    # check if already uploaded
    existing = list(bucket.list_blobs(prefix=gcs_prefix, max_results=1))
    if existing:
        print(f'{version} ({info["hub_name"]}) already in GCS at gs://{GCS_BUCKET}/{gcs_prefix}')
        continue

    print(f'Downloading {version}: {info["hub_name"]} ...')
    with tempfile.TemporaryDirectory() as tmpdir:
        model = AutoModelForSequenceClassification.from_pretrained(info['hub_name'])
        tokenizer = AutoTokenizer.from_pretrained(info['hub_name'])
        model.save_pretrained(tmpdir)
        tokenizer.save_pretrained(tmpdir)

        for root, dirs, files in os.walk(tmpdir):
            for fname in files:
                local_path = os.path.join(root, fname)
                blob_name = f'{gcs_prefix}/{os.path.relpath(local_path, tmpdir)}'
                bucket.blob(blob_name).upload_from_filename(local_path)
        print(f'  Uploaded to gs://{GCS_BUCKET}/{gcs_prefix}')

    info['artifact_uri'] = f'gs://{GCS_BUCKET}/{gcs_prefix}'

# set artifact_uri for any that were already uploaded
for version, info in MODELS.items():
    if 'artifact_uri' not in info:
        info['artifact_uri'] = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/models/{version}'

/home/user/git/vertex-ai-mlops/data+ai/dataproc/examples/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Downloading v1: distilbert-base-uncased-finetuned-sst-2-english ...

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 1124.87it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.71s/it]

  Uploaded to gs://statmike-mlops-349915/data-ai/dataproc-batch-inference/models/v1
Downloading v2: textattack/bert-base-uncased-SST-2 ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13669.76it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]

  Uploaded to gs://statmike-mlops-349915/data-ai/dataproc-batch-inference/models/v2

---
## Create BigQuery Input Data

Create the input table used across the batch inference series. The `category` and `created_date` columns exist for post-processing enrichment — the model only uses `text`.

In [14]:
# Create BQ dataset
dataset_ref = bigquery.Dataset(f'{PROJECT_ID}.{BQ_DATASET}')
dataset_ref.location = REGION
try:
    bq_client.get_dataset(dataset_ref)
    print(f'Dataset {BQ_DATASET} already exists')
except Exception:
    bq_client.create_dataset(dataset_ref)
    print(f'Created dataset {BQ_DATASET}')

# Create input table
BQ_TABLE = 'input_data'
schema = [
    bigquery.SchemaField('id', 'INTEGER'),
    bigquery.SchemaField('text', 'STRING'),
    bigquery.SchemaField('category', 'STRING'),
    bigquery.SchemaField('created_date', 'DATE'),
]

categories = ['entertainment', 'dining', 'general', 'product', 'product',
              'weather', 'service', 'entertainment', 'product', 'general']
rows = [
    {'id': i + 1, 'text': text, 'category': categories[i], 'created_date': '2026-04-18'}
    for i, text in enumerate(SENTENCES)
]

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition='WRITE_TRUNCATE',
)
bq_client.load_table_from_json(
    rows, f'{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}', job_config=job_config
).result()
print(f'Loaded {len(rows)} rows into {BQ_TABLE} (WRITE_TRUNCATE)')

Created dataset data_ai_dataproc_batch_inference
Loaded 10 rows into input_data (WRITE_TRUNCATE)

In [15]:
bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}` ORDER BY id').to_dataframe()

/home/user/git/vertex-ai-mlops/data+ai/dataproc/examples/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id,text,category,created_date
0,1,This movie is absolutely wonderful and I loved...,entertainment,2026-04-18
1,2,The food was terrible and the service was even...,dining,2026-04-18
2,3,"An average experience, nothing special but not...",general,2026-04-18
3,4,"I cannot believe how amazing this product is, ...",product,2026-04-18
4,5,Disappointing quality for the price. Would not...,product,2026-04-18
5,6,The weather today is mild and partly cloudy.,weather,2026-04-18
6,7,I had the worst customer service experience of...,service,2026-04-18
7,8,What a fantastic performance by the entire cast!,entertainment,2026-04-18
8,9,The instructions were confusing and the produc...,product,2026-04-18
9,10,"Pretty good overall, with some room for improv...",general,2026-04-18

---
## Pattern 1: Pandas UDF (Recommended)

A [Pandas UDF](https://spark.apache.org/docs/latest/api/python/user_guide/sql/arrow_pandas.html) is Spark's vectorized user-defined function. It receives and returns Pandas objects, with Arrow-optimized data transfer between JVM and Python.

**Why this is the recommended pattern for ML inference:**

- **Arrow-optimized:** Data transfers between Spark and Python use Apache Arrow columnar format — no row-by-row serialization overhead
- **Automatic batching:** Spark automatically groups rows into batches for the UDF, matching the batch-oriented nature of ML models
- **SQL integration:** Works with `withColumn`, `select`, and other DataFrame operations — the result is a struct column you can unpack
- **Structured output:** Returns a DataFrame with typed columns (`label: string`, `score: float`), not opaque tuples

**Module-level model caching:**

The key optimization is a module-level `_model_cache` dictionary. When Spark calls the UDF on a batch of rows, the model is loaded from GCS on the first call and cached. Subsequent UDF calls on the same executor reuse the cached model — no repeated downloads.

```python
_model_cache = {}

def get_model(model_gcs_uri):
    if model_gcs_uri not in _model_cache:
        # download from GCS, load model
        _model_cache[model_gcs_uri] = pipeline(...)
    return _model_cache[model_gcs_uri]
```

Without caching, every batch of rows would trigger a full model download from GCS — the model load time would dominate inference time.

In [16]:
%%writefile {DIR}/inference_pandas_udf.py
"""Batch inference with Pandas UDF — the recommended pattern."""
import argparse
import os
import tempfile

from pyspark.sql import SparkSession
from pyspark.sql.functions import pandas_udf, col, lit, round as spark_round
from pyspark.sql.types import StructType, StructField, StringType, FloatType
import pandas as pd

# Module-level model cache — persists across UDF calls within the same executor
_model_cache = {}


def get_model(model_gcs_uri):
    """Load model from GCS, caching after first load per executor."""
    if model_gcs_uri not in _model_cache:
        from transformers import pipeline as hf_pipeline, AutoTokenizer
        from google.cloud import storage

        client = storage.Client()
        parts = model_gcs_uri.replace('gs://', '').split('/', 1)
        bkt = client.bucket(parts[0])
        prefix = parts[1]
        model_dir = tempfile.mkdtemp()
        for blob in bkt.list_blobs(prefix=prefix):
            rel = blob.name[len(prefix):].lstrip('/')
            if rel:
                local = os.path.join(model_dir, rel)
                os.makedirs(os.path.dirname(local), exist_ok=True)
                blob.download_to_filename(local)
        # Load tokenizer explicitly — DistilBERT doesn't accept token_type_ids
        # but some transformers versions (e.g. runtime 2.2) generate them
        tokenizer = AutoTokenizer.from_pretrained(model_dir)
        if 'token_type_ids' in tokenizer.model_input_names:
            tokenizer.model_input_names.remove('token_type_ids')
        _model_cache[model_gcs_uri] = hf_pipeline(
            'sentiment-analysis', model=model_dir, tokenizer=tokenizer
        )
    return _model_cache[model_gcs_uri]


def run():
    parser = argparse.ArgumentParser()
    parser.add_argument('--project', required=True)
    parser.add_argument('--bq_dataset', required=True)
    parser.add_argument('--source_table', required=True)
    parser.add_argument('--output_table', required=True)
    parser.add_argument('--model_gcs_uri', required=True)
    parser.add_argument('--model_name', default='distilbert')
    parser.add_argument('--temp_bucket', required=True)
    args = parser.parse_args()

    spark = SparkSession.builder.appName('pandas-udf-inference').getOrCreate()
    spark.conf.set('temporaryGcsBucket', args.temp_bucket)

    # Read from BigQuery
    df = spark.read.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.source_table}') \
        .load() \
        .select('id', 'text', 'category')

    # Define sentiment UDF with struct return type
    model_uri = args.model_gcs_uri

    schema = StructType([
        StructField('label', StringType()),
        StructField('score', FloatType()),
    ])

    @pandas_udf(schema)
    def sentiment_udf(texts: pd.Series) -> pd.DataFrame:
        pipe = get_model(model_uri)
        results = pipe(texts.tolist(), batch_size=32)
        return pd.DataFrame(results)

    # Apply inference and format output
    result_df = df.withColumn('prediction', sentiment_udf(col('text')))
    output_df = result_df.select(
        col('id'),
        col('text'),
        col('category'),
        col('prediction.label').alias('label'),
        spark_round(col('prediction.score'), 6).alias('score'),
        lit(args.model_name).alias('model'),
    )

    # Write to BigQuery
    output_df.write.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.output_table}') \
        .mode('overwrite') \
        .save()

    print(f'Results written to {args.project}.{args.bq_dataset}.{args.output_table}')


if __name__ == '__main__':
    run()

Writing files/dataproc-batch-inference/inference_pandas_udf.py

### Submit Pandas UDF Job

Upload the inference script to GCS and submit it as a Dataproc Serverless batch job.

In [17]:
bucket.blob(f'{SERIES}/{EXPERIMENT}/scripts/inference_pandas_udf.py').upload_from_filename(
    f'{DIR}/inference_pandas_udf.py'
)
pandas_udf_script = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/scripts/inference_pandas_udf.py'
print(f'Script uploaded: {pandas_udf_script}')

Script uploaded: gs://statmike-mlops-349915/data-ai/dataproc-batch-inference/scripts/inference_pandas_udf.py

In [18]:
BQ_PANDAS_UDF_TABLE = 'pandas_udf_predictions'
batch_id_udf = f'{EXPERIMENT}-pandas-udf-{datetime.now().strftime("%Y%m%d-%H%M%S")}'

batch_udf = dataproc_v1.Batch(
    pyspark_batch=dataproc_v1.PySparkBatch(
        main_python_file_uri=pandas_udf_script,
        args=[
            '--project', PROJECT_ID,
            '--bq_dataset', BQ_DATASET,
            '--source_table', BQ_TABLE,
            '--output_table', BQ_PANDAS_UDF_TABLE,
            '--model_gcs_uri', MODELS['v1']['artifact_uri'],
            '--model_name', 'distilbert',
            '--temp_bucket', GCS_BUCKET,
        ],
    ),
    runtime_config=dataproc_v1.RuntimeConfig(version='2.2'),
)

print(f'Submitting Pandas UDF batch job: {batch_id_udf}')
operation_udf = dataproc_client.create_batch(
    request={
        'parent': f'projects/{PROJECT_ID}/locations/{REGION}',
        'batch': batch_udf,
        'batch_id': batch_id_udf,
    }
)
print(f'Console: https://console.cloud.google.com/dataproc/batches/{REGION}/{batch_id_udf}?project={PROJECT_ID}')

Submitting Pandas UDF batch job: dataproc-batch-inference-pandas-udf-20260430-201335
Console: https://console.cloud.google.com/dataproc/batches/us-central1/dataproc-batch-inference-pandas-udf-20260430-201335?project=statmike-mlops-349915

In [19]:
response_udf = operation_udf.result()
print(f'Batch state: {dataproc_v1.Batch.State(response_udf.state).name}')

Batch state: SUCCEEDED

In [20]:
df_udf = bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_PANDAS_UDF_TABLE}` ORDER BY id').to_dataframe()
print(f'Pandas UDF predictions ({len(df_udf)} rows):')
df_udf

Pandas UDF predictions (10 rows):

/home/user/git/vertex-ai-mlops/data+ai/dataproc/examples/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id,text,category,label,score,model
0,1,This movie is absolutely wonderful and I loved...,entertainment,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,dining,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",general,POSITIVE,0.859377,distilbert
3,4,"I cannot believe how amazing this product is, ...",product,POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,product,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,weather,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,service,NEGATIVE,0.999791,distilbert
7,8,What a fantastic performance by the entire cast!,entertainment,POSITIVE,0.999882,distilbert
8,9,The instructions were confusing and the produc...,product,NEGATIVE,0.998770,distilbert
9,10,"Pretty good overall, with some room for improv...",general,POSITIVE,0.999488,distilbert

---
## Pattern 2: mapPartitions (Alternative)

[`mapPartitions`](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.mapPartitions.html) is Spark's RDD-level transformation that gives you explicit control over how data is processed within each partition.

**How it differs from Pandas UDF:**

- **RDD-level:** Operates on the RDD API, not DataFrames — you iterate over rows manually
- **Per-partition model loading:** The model is loaded once per partition call (not via module-level caching, though you can combine both)
- **Row-by-row iteration:** You receive an iterator of Row objects and yield tuples
- **Returns tuples:** Output is an RDD of tuples that you convert back to a DataFrame with an explicit schema

**When to use mapPartitions instead of Pandas UDF:**

- You need explicit control over the model lifecycle (e.g., GPU allocation per partition)
- You want to implement custom batching logic within a partition
- Your output doesn't fit the struct-column pattern of Pandas UDFs
- You're working with an existing RDD-based codebase

In [21]:
%%writefile {DIR}/inference_map_partitions.py
"""Batch inference with mapPartitions — lower-level alternative."""
import argparse
import os
import tempfile

from pyspark.sql import SparkSession
from pyspark.sql.functions import col
from pyspark.sql.types import StructType, StructField, StringType, FloatType, IntegerType

# Module-level model cache — same pattern as Pandas UDF version
_model_cache = {}


def get_model(model_gcs_uri):
    """Load model from GCS, caching after first load per executor."""
    if model_gcs_uri not in _model_cache:
        from transformers import pipeline as hf_pipeline, AutoTokenizer
        from google.cloud import storage

        client = storage.Client()
        parts = model_gcs_uri.replace('gs://', '').split('/', 1)
        bkt = client.bucket(parts[0])
        prefix = parts[1]
        model_dir = tempfile.mkdtemp()
        for blob in bkt.list_blobs(prefix=prefix):
            rel = blob.name[len(prefix):].lstrip('/')
            if rel:
                local = os.path.join(model_dir, rel)
                os.makedirs(os.path.dirname(local), exist_ok=True)
                blob.download_to_filename(local)
        tokenizer = AutoTokenizer.from_pretrained(model_dir)
        if 'token_type_ids' in tokenizer.model_input_names:
            tokenizer.model_input_names.remove('token_type_ids')
        _model_cache[model_gcs_uri] = hf_pipeline(
            'sentiment-analysis', model=model_dir, tokenizer=tokenizer
        )
    return _model_cache[model_gcs_uri]


def run():
    parser = argparse.ArgumentParser()
    parser.add_argument('--project', required=True)
    parser.add_argument('--bq_dataset', required=True)
    parser.add_argument('--source_table', required=True)
    parser.add_argument('--output_table', required=True)
    parser.add_argument('--model_gcs_uri', required=True)
    parser.add_argument('--model_name', default='distilbert')
    parser.add_argument('--temp_bucket', required=True)
    args = parser.parse_args()

    spark = SparkSession.builder.appName('map-partitions-inference').getOrCreate()
    spark.conf.set('temporaryGcsBucket', args.temp_bucket)

    # Read from BigQuery
    df = spark.read.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.source_table}') \
        .load() \
        .select('id', 'text', 'category')

    model_uri = args.model_gcs_uri
    model_name = args.model_name

    def predict_partition(iterator):
        """Process each partition: load model once, predict row by row."""
        pipe = get_model(model_uri)
        for row in iterator:
            result = pipe(row.text)[0]
            yield (
                row.id,
                row.text,
                row.category,
                result['label'],
                round(result['score'], 6),
                model_name,
            )

    output_schema = StructType([
        StructField('id', IntegerType()),
        StructField('text', StringType()),
        StructField('category', StringType()),
        StructField('label', StringType()),
        StructField('score', FloatType()),
        StructField('model', StringType()),
    ])

    # mapPartitions operates on the RDD, returns tuples
    results_rdd = df.rdd.mapPartitions(predict_partition)
    output_df = spark.createDataFrame(results_rdd, schema=output_schema)

    # Write to BigQuery
    output_df.write.format('bigquery') \
        .option('table', f'{args.project}.{args.bq_dataset}.{args.output_table}') \
        .mode('overwrite') \
        .save()

    print(f'Results written to {args.project}.{args.bq_dataset}.{args.output_table}')


if __name__ == '__main__':
    run()

Writing files/dataproc-batch-inference/inference_map_partitions.py

### Submit mapPartitions Job

Upload the mapPartitions script and submit it as a separate batch job.

In [22]:
bucket.blob(f'{SERIES}/{EXPERIMENT}/scripts/inference_map_partitions.py').upload_from_filename(
    f'{DIR}/inference_map_partitions.py'
)
map_partitions_script = f'gs://{GCS_BUCKET}/{SERIES}/{EXPERIMENT}/scripts/inference_map_partitions.py'
print(f'Script uploaded: {map_partitions_script}')

Script uploaded: gs://statmike-mlops-349915/data-ai/dataproc-batch-inference/scripts/inference_map_partitions.py

In [23]:
BQ_MAP_PARTITIONS_TABLE = 'map_partitions_predictions'
batch_id_mp = f'{EXPERIMENT}-map-partitions-{datetime.now().strftime("%Y%m%d-%H%M%S")}'

batch_mp = dataproc_v1.Batch(
    pyspark_batch=dataproc_v1.PySparkBatch(
        main_python_file_uri=map_partitions_script,
        args=[
            '--project', PROJECT_ID,
            '--bq_dataset', BQ_DATASET,
            '--source_table', BQ_TABLE,
            '--output_table', BQ_MAP_PARTITIONS_TABLE,
            '--model_gcs_uri', MODELS['v1']['artifact_uri'],
            '--model_name', 'distilbert',
            '--temp_bucket', GCS_BUCKET,
        ],
    ),
    runtime_config=dataproc_v1.RuntimeConfig(version='2.2'),
)

print(f'Submitting mapPartitions batch job: {batch_id_mp}')
operation_mp = dataproc_client.create_batch(
    request={
        'parent': f'projects/{PROJECT_ID}/locations/{REGION}',
        'batch': batch_mp,
        'batch_id': batch_id_mp,
    }
)
print(f'Console: https://console.cloud.google.com/dataproc/batches/{REGION}/{batch_id_mp}?project={PROJECT_ID}')

Submitting mapPartitions batch job: dataproc-batch-inference-map-partitions-20260430-201800
Console: https://console.cloud.google.com/dataproc/batches/us-central1/dataproc-batch-inference-map-partitions-20260430-201800?project=statmike-mlops-349915

In [24]:
response_mp = operation_mp.result()
print(f'Batch state: {dataproc_v1.Batch.State(response_mp.state).name}')

Batch state: SUCCEEDED

In [25]:
df_mp = bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_MAP_PARTITIONS_TABLE}` ORDER BY id').to_dataframe()
print(f'mapPartitions predictions ({len(df_mp)} rows):')
df_mp

mapPartitions predictions (10 rows):

/home/user/git/vertex-ai-mlops/data+ai/dataproc/examples/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id,text,category,label,score,model
0,1,This movie is absolutely wonderful and I loved...,entertainment,POSITIVE,0.999887,distilbert
1,2,The food was terrible and the service was even...,dining,NEGATIVE,0.999793,distilbert
2,3,"An average experience, nothing special but not...",general,POSITIVE,0.859377,distilbert
3,4,"I cannot believe how amazing this product is, ...",product,POSITIVE,0.999858,distilbert
4,5,Disappointing quality for the price. Would not...,product,NEGATIVE,0.999712,distilbert
5,6,The weather today is mild and partly cloudy.,weather,NEGATIVE,0.964102,distilbert
6,7,I had the worst customer service experience of...,service,NEGATIVE,0.999791,distilbert
7,8,What a fantastic performance by the entire cast!,entertainment,POSITIVE,0.999882,distilbert
8,9,The instructions were confusing and the produc...,product,NEGATIVE,0.998770,distilbert
9,10,"Pretty good overall, with some room for improv...",general,POSITIVE,0.999488,distilbert

---
## Pattern Comparison

Both patterns produce the same results — the choice is about API level and control.

| Aspect | Pandas UDF | mapPartitions |
|--------|-----------|---------------|
| **API level** | DataFrame | RDD |
| **Batching** | Arrow-optimized, automatic | Row-by-row (manual batching possible) |
| **Return type** | Structured DataFrame (struct column) | Tuples → DataFrame |
| **SQL integration** | Yes (`withColumn`, `select`) | No (RDD-level) |
| **Model lifecycle** | Module-level cache (shared across UDF calls) | Per-partition explicit (one load per partition) |
| **Best for** | Most use cases — structured output, SQL-friendly | Full control over model lifecycle, custom batching |

**Recommendation:** Use Pandas UDF for most workloads. It's higher-level, Arrow-optimized, and integrates with DataFrame operations. Use mapPartitions only when you need explicit control over model loading or custom batching logic.

---
## Multi-Model Inference

Run both DistilBERT (v1) and BERT (v2) on the same data via separate Dataproc Serverless batch jobs. Each job uses the same Pandas UDF script with different `--model_gcs_uri` and `--output_table` args.

Unlike Dataflow (which can branch within a single pipeline), Dataproc Serverless runs one PySpark script per batch job. Sequential jobs are the simplest pattern — each job is independent.

In [26]:
# Submit v2 (BERT) job using the same Pandas UDF script
BQ_PANDAS_UDF_TABLE_V2 = 'pandas_udf_predictions_v2'
batch_id_v2 = f'{EXPERIMENT}-inference-v2-{datetime.now().strftime("%Y%m%d-%H%M%S")}'

batch_v2 = dataproc_v1.Batch(
    pyspark_batch=dataproc_v1.PySparkBatch(
        main_python_file_uri=pandas_udf_script,
        args=[
            '--project', PROJECT_ID,
            '--bq_dataset', BQ_DATASET,
            '--source_table', BQ_TABLE,
            '--output_table', BQ_PANDAS_UDF_TABLE_V2,
            '--model_gcs_uri', MODELS['v2']['artifact_uri'],
            '--model_name', 'bert',
            '--temp_bucket', GCS_BUCKET,
        ],
    ),
    runtime_config=dataproc_v1.RuntimeConfig(version='2.2'),
)

print(f'Submitting v2 (BERT) batch job: {batch_id_v2}')
operation_v2 = dataproc_client.create_batch(
    request={
        'parent': f'projects/{PROJECT_ID}/locations/{REGION}',
        'batch': batch_v2,
        'batch_id': batch_id_v2,
    }
)
print(f'Console: https://console.cloud.google.com/dataproc/batches/{REGION}/{batch_id_v2}?project={PROJECT_ID}')

Submitting v2 (BERT) batch job: dataproc-batch-inference-inference-v2-20260430-202238
Console: https://console.cloud.google.com/dataproc/batches/us-central1/dataproc-batch-inference-inference-v2-20260430-202238?project=statmike-mlops-349915

In [27]:
response_v2 = operation_v2.result()
print(f'Batch state: {dataproc_v1.Batch.State(response_v2.state).name}')

Batch state: SUCCEEDED

In [28]:
# Compare predictions from both models
v1_df = bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_PANDAS_UDF_TABLE}` ORDER BY id').to_dataframe()
v2_df = bq_client.query(f'SELECT * FROM `{PROJECT_ID}.{BQ_DATASET}.{BQ_PANDAS_UDF_TABLE_V2}` ORDER BY id').to_dataframe()

print('Model Comparison')
print('=' * 70)
print()

for _, (r1, r2) in enumerate(zip(v1_df.itertuples(), v2_df.itertuples())):
    print(f'  "{r1.text[:65]}..."')
    print(f'    DistilBERT: {r1.label:>10} (score: {r1.score:.6f})')
    print(f'    BERT:       {r2.label:>10} (score: {r2.score:.6f})')
    print()

/home/user/git/vertex-ai-mlops/data+ai/dataproc/examples/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

Model Comparison
======================================================================

  "This movie is absolutely wonderful and I loved every minute of it..."
    DistilBERT:   POSITIVE (score: 0.999887)
    BERT:          LABEL_1 (score: 0.999614)

  "The food was terrible and the service was even worse...."
    DistilBERT:   NEGATIVE (score: 0.999793)
    BERT:          LABEL_0 (score: 0.999059)

  "An average experience, nothing special but not bad either...."
    DistilBERT:   POSITIVE (score: 0.859377)
    BERT:          LABEL_1 (score: 0.898916)

  "I cannot believe how amazing this product is, truly life-changing..."
    DistilBERT:   POSITIVE (score: 0.999858)
    BERT:          LABEL_1 (score: 0.999475)

  "Disappointing quality for the price. Would not recommend...."
    DistilBERT:   NEGATIVE (score: 0.999712)
    BERT:          LABEL_0 (score: 0.997783)

  "The weather today is mild and partly cloudy...."
    DistilBERT:   NEGATIVE (score: 0.964102)
    BERT:          LABEL_0 (score: 0.818888)

  "I had the worst customer service experience of my life yesterday...."
    DistilBERT:   NEGATIVE (score: 0.999791)
    BERT:          LABEL_0 (score: 0.998323)

  "What a fantastic performance by the entire cast!..."
    DistilBERT:   POSITIVE (score: 0.999882)
    BERT:          LABEL_1 (score: 0.999615)

  "The instructions were confusing and the product broke on day one...."
    DistilBERT:   NEGATIVE (score: 0.998770)
    BERT:          LABEL_0 (score: 0.997837)

  "Pretty good overall, with some room for improvement...."
    DistilBERT:   POSITIVE (score: 0.999488)
    BERT:          LABEL_1 (score: 0.997235)

---
## Performance Tuning

Tuning Dataproc Serverless for ML inference involves balancing executor count against model memory. Each executor loads a separate copy of the model, so more executors means more parallelism but also more total memory.

### Key Configuration

| Config | Effect | Recommendation |
|--------|--------|----------------|
| `spark.executor.instances` | More executors = more parallel model copies | 2-4 for small models |
| `spark.executor.memory` | Must fit model + tokenizer + batch | 4g for DistilBERT, 8g for BERT |
| `batch_size` in UDF | Larger = more efficient inference | 32-64 for CPU |
| `spark.sql.execution.arrow.pyspark.enabled` | Arrow transfer for Pandas UDFs | true (default in 2.2) |

### Executor Count vs Model Memory

Each executor loads a full copy of the model into memory. For a 67M-parameter DistilBERT (~500MB in memory), 4 executors need ~2GB just for models. For BERT (~1GB), the same 4 executors need ~4GB.

```python
# Example: tuned batch for larger models
batch.runtime_config.properties.update({
    'spark.executor.instances': '4',
    'spark.executor.memory': '8g',
    'spark.driver.memory': '4g',
})
```

> **Driver memory constraint:** Dataproc Serverless enforces a minimum of 1024 MB/core for total memory (memory + 40% overhead). With the default 4 driver cores, `spark.driver.memory` must be at least 4g. Setting it lower (e.g., 2g) will cause the batch to fail at submission. The same constraint applies to executor memory and cores.

### Batch Size in the UDF

The `batch_size` parameter in the HuggingFace pipeline controls how many texts are tokenized and forwarded through the model at once. Larger batches use CPU/GPU more efficiently but require more memory.

```python
@pandas_udf(schema)
def sentiment_udf(texts: pd.Series) -> pd.DataFrame:
    pipe = get_model(model_uri)
    results = pipe(texts.tolist(), batch_size=64)  # increase for larger datasets
    return pd.DataFrame(results)
```

### Dynamic Allocation

Dataproc Serverless enables dynamic allocation by default — Spark adds or removes executors based on workload. For ML inference, this means:
- Small datasets may only use 1-2 executors (model loads on each)
- Large datasets will scale up, with each new executor loading its own model copy
- Set `spark.executor.instances` as a starting point; dynamic allocation adjusts from there

### Data Partitioning

The number of Spark partitions affects parallelism. With Pandas UDF, Spark processes one partition per UDF call. For small datasets (like our 10 rows), repartitioning is unnecessary. For large datasets:

```python
# Repartition to match executor count for even distribution
df = df.repartition(4)  # match spark.executor.instances
```

---
## Cleanup

Remove all resources created by this notebook.

In [29]:
# Delete BigQuery dataset
bq_client.delete_dataset(
    f'{PROJECT_ID}.{BQ_DATASET}',
    delete_contents=True,
    not_found_ok=True,
)
print(f'Deleted BQ dataset {BQ_DATASET}')

# Remove GCS scripts
for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/scripts/'):
    blob.delete()
print(f'Removed GCS scripts')

Deleted BQ dataset data_ai_dataproc_batch_inference
Removed GCS scripts
Removed GCS scripts

In [30]:
# # Uncomment to remove all GCS artifacts (including models) for this experiment
# for blob in bucket.list_blobs(prefix=f'{SERIES}/{EXPERIMENT}/'):
#     blob.delete()
# print(f'Removed all GCS artifacts for {EXPERIMENT}')

---
## Summary

This notebook covered two PySpark inference patterns on Dataproc Serverless:

1. **Pandas UDF (recommended)** — Arrow-optimized, DataFrame-level, returns structured output. Module-level `_model_cache` avoids repeated model downloads.
2. **mapPartitions (alternative)** — RDD-level, explicit model loading per partition, row-by-row iteration. Use when you need full control over the model lifecycle.
3. **Multi-model inference** — Submit separate batch jobs with different `--model_gcs_uri` args. Same script, different models.
4. **Performance tuning** — Balance executor count against model memory. Use `batch_size` in the UDF for efficient inference.

### Key Takeaways

- Pandas UDF is the recommended pattern for ML batch inference on Spark
- Module-level `_model_cache` avoids repeated model downloads per executor
- mapPartitions gives more control but is lower-level and row-oriented
- Multi-model inference via separate batch jobs, each with its own model URI
- Size executor memory to accommodate your model (~4g for DistilBERT, ~8g for BERT)

### Series Navigation

- **[Notebook 1: Dataproc Serverless Fundamentals](./dataproc-serverless-fundamentals.ipynb)** — Platform basics, job submission, Spark properties
- **Notebook 2: Batch Inference (this notebook)** — Pandas UDF vs mapPartitions, multi-model, tuning
- **[Notebook 3: Structured Streaming](./dataproc-structured-streaming.ipynb)** — Provisioned Dataproc cluster, foreachBatch, GCS file stream
- **[Notebook 4: Dataproc to Vertex AI Endpoint](./dataproc-vertex-ai-endpoint.ipynb)** — Call a Vertex AI endpoint from Spark

### Cross-References

- [MLOps/Serving/Batch/Batch Inference With Dataproc](../../../MLOps/Serving/Batch/Batch%20Inference%20With%20Dataproc.ipynb) — Same models, same Pandas UDF pattern, but with Vertex AI Pipelines orchestration and side-by-side comparison with other batch platforms